In [1]:
import pandas as pd
import numpy as np
import camelot
from functools import reduce
from pathlib import Path

# Abay oblast and East-Kazakhstan oblast

Since these two oblasts were divided in 2022, we will need to recombine rayon level data for both.

## Investments

### 2022-2024

In [2]:
abay_all_2022 = pd.read_excel(Path("../Data/Investments/Abay/2022_Investments.xlsx"), sheet_name='13', header=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
abay_all_2023 = pd.read_excel(Path("../Data/Investments/Abay/2023_Investments.xlsx"), sheet_name='19', header=3, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
abay_all_2024 = pd.read_excel(Path("../Data/Investments/Abay/2024_Investments.xlsx"), sheet_name='14', header=3, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [3]:
abay_non_2022 = pd.read_excel(Path("../Data/Investments/Abay/2022_Investments.xlsx"), sheet_name='14', header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
abay_non_2023 = pd.read_excel(Path("../Data/Investments/Abay/2023_Investments.xlsx"), sheet_name='20', header=3, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
abay_non_2024 = pd.read_excel(Path("../Data/Investments/Abay/2024_Investments.xlsx"), sheet_name='15', header=3, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [4]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [abay_all_2022, abay_all_2023, abay_all_2024]:
    df.columns = all_columns

for df in [abay_non_2022, abay_non_2023, abay_non_2024]:
    df.columns = non_columns
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

In [5]:
abay_all_2024.loc[0, ['l_all_inv', 'f_all_inv']] = abay_all_2024.loc[0, ['l_all_inv', 'f_all_inv']] + abay_all_2024.loc[7, ['l_all_inv', 'f_all_inv']]
abay_all_2024.loc[11, ['l_all_inv', 'f_all_inv']] = abay_all_2024.loc[10, ['l_all_inv', 'f_all_inv']] + abay_all_2024.loc[11, ['l_all_inv', 'f_all_inv']]
abay_all_2024 = abay_all_2024.drop([7, 10]).reset_index(drop=True)

abay_non_2024.loc[0, ['l_nonextr_inv', 'f_nonextr_inv']] = abay_non_2024.loc[0, ['l_nonextr_inv', 'f_nonextr_inv']] + abay_non_2024.loc[7, ['l_nonextr_inv', 'f_nonextr_inv']]
abay_non_2024.loc[11, ['l_nonextr_inv', 'f_nonextr_inv']] = abay_non_2024.loc[10, ['l_nonextr_inv', 'f_nonextr_inv']] + abay_non_2024.loc[11, ['l_nonextr_inv', 'f_nonextr_inv']]
abay_non_2024 = abay_non_2024.drop([7, 10]).reset_index(drop=True)

In [6]:
rayon_names = ['Semey_city', 'Kurchatov_city', 'Abay', 'Aksuat', 'Ayagoz', 'Beskaragay', 'Boroduliha', 'Zharma', 'Kokpekti', 'Urzhar']

for df in [abay_all_2022, abay_all_2023, abay_all_2024, abay_non_2022, abay_non_2023, abay_non_2024]:
    df['rayon'] = rayon_names

In [7]:
abay_2022 = abay_all_2022.merge(abay_non_2022, on='rayon')
abay_2023 = abay_all_2023.merge(abay_non_2023, on='rayon')
abay_2024 = abay_all_2024.merge(abay_non_2024, on='rayon')

In [8]:
dfs = [abay_2022, abay_2023, abay_2024]

for i in range(3):
    df = dfs[i]
    df['oblast'] = 'East-Kazakhstan'
    if i == 0:
        df['year'] = 2022
    elif i == 1:
        df['year'] = 2023
    else:
        df['year'] = 2024

In [9]:
ek_all_2022 = pd.read_excel(Path("../Data/Investments/East-Kazakhstan/2022_Investments.xlsx"), sheet_name='13', header=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
ek_all_2023 = pd.read_excel(Path("../Data/Investments/East-Kazakhstan/2023_Investments.xlsx"), sheet_name='19', header=4, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
ek_all_2024 = pd.read_excel(Path("../Data/Investments/East-Kazakhstan/2024_Investments.xlsx"), sheet_name='14', header=4, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [10]:
ek_non_2022 = pd.read_excel(Path("../Data/Investments/East-Kazakhstan/2022_Investments.xlsx"), sheet_name='14', header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
ek_non_2023 = pd.read_excel(Path("../Data/Investments/East-Kazakhstan/2023_Investments.xlsx"), sheet_name='20', header=4, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
ek_non_2024 = pd.read_excel(Path("../Data/Investments/East-Kazakhstan/2024_Investments.xlsx"), sheet_name='15', header=4, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [11]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [ek_all_2022, ek_all_2023, ek_all_2024]:
    df.columns = all_columns

for df in [ek_non_2022, ek_non_2023, ek_non_2024]:
    df.columns = non_columns
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

In [12]:
ek_all_2024.loc[5, ['l_all_inv', 'f_all_inv']] = ek_all_2024.loc[5, ['l_all_inv', 'f_all_inv']] + ek_all_2024.loc[7, ['l_all_inv', 'f_all_inv']]
ek_all_2024.loc[6, ['l_all_inv', 'f_all_inv']] = ek_all_2024.loc[6, ['l_all_inv', 'f_all_inv']] + ek_all_2024.loc[11, ['l_all_inv', 'f_all_inv']]
ek_all_2024 = ek_all_2024.drop([7, 11]).reset_index(drop=True)

ek_non_2024.loc[5, ['l_nonextr_inv', 'f_nonextr_inv']] = ek_non_2024.loc[5, ['l_nonextr_inv', 'f_nonextr_inv']] + ek_non_2024.loc[7, ['l_nonextr_inv', 'f_nonextr_inv']]
ek_non_2024.loc[6, ['l_nonextr_inv', 'f_nonextr_inv']] = ek_non_2024.loc[6, ['l_nonextr_inv', 'f_nonextr_inv']] + ek_non_2024.loc[11, ['l_nonextr_inv', 'f_nonextr_inv']]
ek_non_2024 = ek_non_2024.drop([7, 11]).reset_index(drop=True)

In [13]:
rayon_names = ['Oskemen_city', 'Ridder_city', 'Glubokoe', 'Zaysan', 'Altay', 'Kurshim', 'Katonkaragay', 'Samar', 'Tarbagatay', 'Ulan', 'Shemonaiha']

for df in [ek_all_2022, ek_all_2023, ek_all_2024, ek_non_2022, ek_non_2023, ek_non_2024]:
    df['rayon'] = rayon_names

In [14]:
ek_2022 = ek_all_2022.merge(ek_non_2022, on='rayon')
ek_2023 = ek_all_2023.merge(ek_non_2023, on='rayon')
ek_2024 = ek_all_2024.merge(ek_non_2024, on='rayon')

In [15]:
dfs = [ek_2022, ek_2023, ek_2024]

for i in range(3):
    df = dfs[i]
    df['oblast'] = 'East-Kazakhstan'
    if i == 0:
        df['year'] = 2022
    elif i == 1:
        df['year'] = 2023
    else:
        df['year'] = 2024

In [16]:
east_2022 = pd.concat([abay_2022, ek_2022], ignore_index=True)
east_2023 = pd.concat([abay_2023, ek_2023], ignore_index=True)
east_2024 = pd.concat([abay_2024, ek_2024], ignore_index=True)

In [17]:
east_2022.loc[18, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] = east_2022.loc[18, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] + east_2022.loc[3, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']]
east_2022.loc[8, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] = east_2022.loc[8, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] + east_2022.loc[17, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']]
east_2022 = east_2022.drop([3, 17]).reset_index(drop=True)

east_2023.loc[18, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] = east_2023.loc[18, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] + east_2023.loc[3, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']]
east_2023.loc[8, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] = east_2023.loc[8, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] + east_2023.loc[17, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']]
east_2023 = east_2023.drop([3, 17]).reset_index(drop=True)

east_2024.loc[18, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] = east_2024.loc[18, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] + east_2024.loc[3, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']]
east_2024.loc[8, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] = east_2024.loc[8, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] + east_2024.loc[17, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']]
east_2024 = east_2024.drop([3, 17]).reset_index(drop=True)

### 2018-2021

In [18]:
east_all_2018 = camelot.read_pdf(Path("../Data/Investments/East-Kazakhstan/2018_Investments.pdf"), pages='28', flavor='stream')[0].df
east_nonextr_2018 = camelot.read_pdf(Path("../Data/Investments/East-Kazakhstan/2018_Investments.pdf"), pages='29', flavor='stream')[0].df

In [19]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

rayons = ['Oskemen_city', 'Kurchatov_city', 'Ridder_city', 'Semey_city', 'Abay', 'Ayagoz', 'Beskaragay', 'Boroduliha', 'Glubokoe', 'Zharma', 'Zaysan', 'Altay', 'Kokpekti', 'Kurshim', 'Katonkaragay', 'Tarbagatay', 'Ulan', 'Urzhar', 'Shemonaiha']

east_all_2018 = east_all_2018[[0, 2, 5]]
east_all_2018 = east_all_2018.drop([0, 1, 2, 3, 4]).reset_index(drop=True)
east_all_2018.columns = all_columns
east_all_2018['rayon'] = rayons
east_all_2018['l_all_inv'] = east_all_2018['l_all_inv'].str.replace(' ', '').astype(int)
east_all_2018['f_all_inv'] = east_all_2018['f_all_inv'].str.replace(' ', '').astype(int)

east_nonextr_2018 = east_nonextr_2018[[0, 2, 5]]
east_nonextr_2018 = east_nonextr_2018.drop([0, 1, 2, 3, 4]).reset_index(drop=True)
east_nonextr_2018.columns = non_columns
east_nonextr_2018['all_nonextr_inv'] = east_nonextr_2018['all_nonextr_inv'].str.replace(' ', '').astype(int)
east_nonextr_2018['f_nonextr_inv'] = east_nonextr_2018['f_nonextr_inv'].str.replace(' ', '').astype(int)
east_nonextr_2018['l_nonextr_inv'] = east_nonextr_2018['all_nonextr_inv'] - east_nonextr_2018['f_nonextr_inv']
east_nonextr_2018 = east_nonextr_2018.drop('all_nonextr_inv', axis=1)
east_nonextr_2018['rayon'] = rayons

In [20]:
east_2018 = east_all_2018.merge(east_nonextr_2018, on='rayon')
east_2018['oblast'] = 'East-Kazakhstan'
east_2018['year'] = 2018

In [21]:
east_all_2019 = pd.read_excel(Path("../Data/Investments/East-Kazakhstan/2019_Investments.xls"), sheet_name='14', header=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
east_nonextr_2019 = pd.read_excel(Path("../Data/Investments/East-Kazakhstan/2019_Investments.xls"), sheet_name='15', header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop([0, 20, 21, 22]).reset_index(drop=True)

east_all_2020 = pd.read_excel(Path("../Data/Investments/East-Kazakhstan/2020_Investments.xlsx"), sheet_name='13', header=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
east_nonextr_2020 = pd.read_excel(Path("../Data/Investments/East-Kazakhstan/2020_Investments.xlsx"), sheet_name='14', header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

east_all_2021 = pd.read_excel(Path("../Data/Investments/East-Kazakhstan/2021_Investments.xlsx"), sheet_name='13', header=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
east_nonextr_2021 = pd.read_excel(Path("../Data/Investments/East-Kazakhstan/2021_Investments.xlsx"), sheet_name='14', header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [22]:
rayons = ['Oskemen_city', 'Kurchatov_city', 'Ridder_city', 'Semey_city', 'Abay', 'Ayagoz', 'Beskaragay', 'Boroduliha', 'Glubokoe', 'Zharma', 'Zaysan', 'Altay', 'Kokpekti', 'Kurshim', 'Katonkaragay', 'Tarbagatay', 'Ulan', 'Urzhar', 'Shemonaiha']

all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [east_all_2019, east_all_2020, east_all_2021]:
    df.columns = all_columns
    df['rayon'] = rayons

for df in [east_nonextr_2019, east_nonextr_2020, east_nonextr_2021]:
    df.columns = non_columns
    df['rayon'] = rayons
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

In [23]:
east_2019 = east_all_2019.merge(east_nonextr_2019, on='rayon')
east_2020 = east_all_2020.merge(east_nonextr_2020, on='rayon')
east_2021 = east_all_2021.merge(east_nonextr_2021, on='rayon')

In [24]:
dfs = [east_2019, east_2020, east_2021]

for i in range(3):
    df = dfs[i]
    df['oblast'] = 'East-Kazakhstan'
    if i == 0:
        df['year'] = 2019
    elif i == 1:
        df['year'] = 2020
    else:
        df['year'] = 2021

In [25]:
east_inv = pd.concat([east_2018, east_2019, east_2020, east_2021, east_2022, east_2023, east_2024], ignore_index=True)
east_inv

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year
0,Oskemen_city,118861638,8712430.0,8139851.0,85817952.0,East-Kazakhstan,2018
1,Kurchatov_city,5246007,149907.0,136764.0,2343776.0,East-Kazakhstan,2018
2,Ridder_city,24795133,413071.0,413071.0,5428607.0,East-Kazakhstan,2018
3,Semey_city,59960428,7947330.0,7823433.0,30683044.0,East-Kazakhstan,2018
4,Abay,2868180,3092.0,3092.0,981955.0,East-Kazakhstan,2018
...,...,...,...,...,...,...,...
128,Kurshim,35094458,177293.0,177293.0,5181927.0,East-Kazakhstan,2024
129,Katonkaragay,24393822,513.0,513.0,11539800.0,East-Kazakhstan,2024
130,Tarbagatay,32015111,8251464.0,8178190.0,11248329.0,East-Kazakhstan,2024
131,Ulan,17831632,3100990.0,2650866.0,3644444.0,East-Kazakhstan,2024
132,Shemonaiha,35546797,436488.0,398723.0,1846726.0,East-Kazakhstan,2024

## Employment

### 2022-2024

In [26]:
abay_empl = pd.read_excel(Path("../Data/Employment/Abay.xlsx"), skiprows=22, nrows=10, header=None, usecols=[0, 1, 2, 3])

In [27]:
abay_empl.columns = ['rayon', 2022, 2023, 2024]

rayons = ['Semey_city', 'Kurchatov_city', 'Abay', 'Aksuat', 'Ayagoz', 'Beskaragay', 'Boroduliha', 'Zharma', 'Kokpekti', 'Urzhar']

abay_empl['rayon'] = rayons

abay_empl[2022] = abay_empl[2022].str.replace(',', '.').astype(float)
abay_empl[2023] = abay_empl[2023].astype(float)
abay_empl[2024] = abay_empl[2024].astype(float)

In [28]:
ek_empl = pd.read_excel(Path("../Data/Employment/East-Kazakhstan.xlsx"), skiprows=30, nrows=20, header=None, usecols='A, J, K, L', na_values=['x', 'х', '-', '', ' ']).dropna().reset_index(drop=True)

In [29]:
ek_empl.columns = ['rayon', 2022, 2023, 2024]

rayons = ['Oskemen_city', 'Ridder_city', 'Glubokoe', 'Zaysan', 'Altay', 'Samar', 'Kurshim', 'Katonkaragay', 'Tarbagatay', 'Ulan', 'Shemonaiha']

ek_empl['rayon'] = rayons

ek_empl[2022] = ek_empl[2022].astype(float)
ek_empl[2023] = ek_empl[2023].astype(float)
ek_empl[2024] = ek_empl[2024].astype(float)

In [30]:
east_empl = pd.concat([abay_empl, ek_empl], ignore_index=True)

In [31]:
east_empl.loc[8, [2022, 2023, 2024]] = east_empl.loc[8, [2022, 2023, 2024]] + east_empl.loc[15, [2022, 2023, 2024]]
east_empl.loc[18, [2022, 2023, 2024]] = east_empl.loc[18, [2022, 2023, 2024]] + east_empl.loc[3, [2022, 2023, 2024]]
east_empl = east_empl.drop([3, 15]).reset_index(drop=True)

In [32]:
east_empl_22_24 = east_empl.melt(id_vars='rayon', value_vars=[2022, 2023, 2024], var_name='year', value_name='employment')

### 2014-2021

In [33]:
ek_empl = pd.read_excel(Path("../Data/Employment/East-Kazakhstan.xlsx"), skiprows=30, nrows=20, header=None, usecols='A, F:I', na_values=['x', 'х', '-', '', ' ']).dropna().reset_index(drop=True)

In [34]:
ek_empl.columns = ['rayon', 2018, 2019, 2020, 2021]

rayons = ['Oskemen_city', 'Kurchatov_city', 'Ridder_city', 'Semey_city', 'Abay', 'Ayagoz', 'Beskaragay', 'Boroduliha', 'Glubokoe', 'Zharma', 'Zaysan', 'Altay', 'Kokpekti', 'Kurshim', 'Katonkaragay', 'Tarbagatay', 'Ulan', 'Urzhar', 'Shemonaiha']

ek_empl['rayon'] = rayons

for i in [2018, 2019, 2020, 2021]:
    ek_empl[i] = ek_empl[i].astype(float)

In [35]:
east_empl_18_21 = ek_empl.melt(id_vars='rayon', value_vars=[2018, 2019, 2020, 2021], var_name='year', value_name='employment')

In [36]:
east_empl = pd.concat([east_empl_18_21, east_empl_22_24], ignore_index=True)
east_empl

              rayon  year  employment
0      Oskemen_city  2018       168.7
1    Kurchatov_city  2018         7.0
2       Ridder_city  2018        29.7
3        Semey_city  2018       165.3
4              Abay  2018         6.8
..              ...   ...         ...
128         Kurshim  2024        10.5
129    Katonkaragay  2024        10.3
130      Tarbagatay  2024        18.1
131            Ulan  2024        17.2
132      Shemonaiha  2024        20.8

[133 rows x 3 columns]

## Other controls

In [37]:
kurchatov = pd.read_excel(Path("../Data/Controls/Abay_All.xls"), sheet_name="моног.Курчатов", header=2, usecols='B, AD:AJ', nrows=272, na_values=['x', 'х', '-', '', ' ', '...'])

In [38]:
kurchatov.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023, 2024]
kurchatov = kurchatov.loc[[134, 167, 257]].reset_index(drop=True)

In [39]:
kurchatov['Indicator'] = ['production', 'agriculture', 'retail']
kurchatov[2024] = kurchatov[2024].str.replace(',', '.')
kurchatov[2024] = kurchatov[2024].str.replace(')', '')
kurchatov[2024] = kurchatov[2024].str.replace(' ', '')
kurchatov[2024] = kurchatov[2024].astype(float)

In [40]:
kurchatov = pd.melt(kurchatov, id_vars=['Indicator'], var_name='year', value_name='value')
kurchatov = kurchatov.pivot(index='year', columns='Indicator', values='value').reset_index()
kurchatov.insert(0, 'rayon', 'Kurchatov_city')
kurchatov.columns.name = None

In [41]:
semey = pd.read_excel(Path("../Data/Controls/Abay_All.xls"), sheet_name="Семей", header=2, usecols='A, AC:AI', nrows=229, na_values=['x', 'х', '-', '', ' ', '...'])

In [42]:
semey.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023, 2024]
semey = semey.loc[[117, 149, 218]].reset_index(drop=True)

In [43]:
semey['Indicator'] = ['production', 'agriculture', 'retail']
semey[2024] = semey[2024].str.replace(',', '.')
semey[2024] = semey[2024].str.replace(')', '')
semey[2024] = semey[2024].str.replace(' ', '')
semey[2024] = semey[2024].astype(float)

In [44]:
zh_semey = pd.read_excel(Path("../Data/Controls/Abay_All.xls"), sheet_name="Жаңасемей", header=4, usecols='A:B', nrows=229, na_values=['x', 'х', '-', '', ' ', '...'])

In [45]:
zh_semey.columns = ['Indicator', 2024]
zh_semey = zh_semey.loc[[117, 149, 218]].reset_index(drop=True)

In [46]:
zh_semey['Indicator'] = ['production', 'agriculture', 'retail']
zh_semey[2024] = zh_semey[2024].replace(zh_semey[2024].iloc[2], '1.8')
zh_semey[2024] = zh_semey[2024].str.replace(' ', '')
zh_semey[2024] = zh_semey[2024].str.replace(',', '.')
zh_semey[2024] = zh_semey[2024].str.replace(')', '')
zh_semey[2024] = zh_semey[2024].astype(float)

In [47]:
semey[2024] = semey[2024] + zh_semey[2024]

In [48]:
semey = pd.melt(semey, id_vars=['Indicator'], var_name='year', value_name='value')
semey = semey.pivot(index='year', columns='Indicator', values='value').reset_index()
semey.insert(0, 'rayon', 'Semey_city')
semey.columns.name = None

In [49]:
abay = pd.read_excel(Path("../Data/Controls/Abay_All.xls"), sheet_name="Абай", header=3, usecols='A, AC:AI', nrows=230, na_values=['x', 'х', '-', '', ' ', '...'])

In [50]:
abay.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023, 2024]
abay = abay.loc[[117, 149, 218]].reset_index(drop=True)

In [51]:
abay['Indicator'] = ['production', 'agriculture', 'retail']
abay[2024] = abay[2024].str.replace(',', '.')
abay[2024] = abay[2024].str.replace(')', '')
abay[2024] = abay[2024].str.replace(' ', '')
abay[2024] = abay[2024].astype(float)

In [52]:
abay = pd.melt(abay, id_vars=['Indicator'], var_name='year', value_name='value')
abay = abay.pivot(index='year', columns='Indicator', values='value').reset_index()
abay.insert(0, 'rayon', 'Abay')
abay.columns.name = None

In [53]:
ayagoz = pd.read_excel(Path("../Data/Controls/Abay_All.xls"), sheet_name="Аягоз", header=2, usecols='A, AC:AI', nrows=230, na_values=['x', 'х', '-', '', ' ', '...'])

In [54]:
ayagoz.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023, 2024]
ayagoz = ayagoz.loc[[117, 149, 218]].reset_index(drop=True)

In [55]:
ayagoz['Indicator'] = ['production', 'agriculture', 'retail']
ayagoz[2024] = ayagoz[2024].str.replace(',', '.')
ayagoz[2024] = ayagoz[2024].str.replace(')', '')
ayagoz[2024] = ayagoz[2024].str.replace(' ', '')
ayagoz[2024] = ayagoz[2024].astype(float)

In [56]:
ayagoz = pd.melt(ayagoz, id_vars=['Indicator'], var_name='year', value_name='value')
ayagoz = ayagoz.pivot(index='year', columns='Indicator', values='value').reset_index()
ayagoz.insert(0, 'rayon', 'Ayagoz')
ayagoz.columns.name = None

In [57]:
beskaragay = pd.read_excel(Path("../Data/Controls/Abay_All.xls"), sheet_name="Бескарагай", header=4, usecols='A, AC:AI', nrows=232, na_values=['x', 'х', '-', '', ' ', '...'])

In [58]:
beskaragay.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023, 2024]
beskaragay = beskaragay.loc[[119, 151, 220]].reset_index(drop=True)

In [59]:
beskaragay['Indicator'] = ['production', 'agriculture', 'retail']
beskaragay[2024] = beskaragay[2024].str.replace(',', '.')
beskaragay[2024] = beskaragay[2024].str.replace(')', '')
beskaragay[2024] = beskaragay[2024].str.replace(' ', '')
beskaragay[2024] = beskaragay[2024].astype(float)

In [60]:
beskaragay = pd.melt(beskaragay, id_vars=['Indicator'], var_name='year', value_name='value')
beskaragay = beskaragay.pivot(index='year', columns='Indicator', values='value').reset_index()
beskaragay.insert(0, 'rayon', 'Beskaragay')
beskaragay.columns.name = None

In [61]:
boroduliha = pd.read_excel(Path("../Data/Controls/Abay_All.xls"), sheet_name="Бородулиха", header=4, usecols='A, AC:AI', nrows=230, na_values=['x', 'х', '-', '', ' ', '...'])

In [62]:
boroduliha.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023, 2024]
boroduliha = boroduliha.loc[[117, 149, 218]].reset_index(drop=True)

In [63]:
boroduliha['Indicator'] = ['production', 'agriculture', 'retail']
boroduliha[2024] = boroduliha[2024].str.replace(',', '.')
boroduliha[2024] = boroduliha[2024].str.replace(')', '')
boroduliha[2024] = boroduliha[2024].str.replace(' ', '')
boroduliha[2024] = boroduliha[2024].astype(float)

In [64]:
boroduliha = pd.melt(boroduliha, id_vars=['Indicator'], var_name='year', value_name='value')
boroduliha = boroduliha.pivot(index='year', columns='Indicator', values='value').reset_index()
boroduliha.insert(0, 'rayon', 'Boroduliha')
boroduliha.columns.name = None

In [65]:
zharma = pd.read_excel(Path("../Data/Controls/Abay_All.xls"), sheet_name="Жарма", header=4, usecols='A, AC:AI', nrows=230, na_values=['x', 'х', '-', '', ' ', '...'])

In [66]:
zharma.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023, 2024]
zharma = zharma.loc[[117, 149, 218]].reset_index(drop=True)

In [67]:
zharma['Indicator'] = ['production', 'agriculture', 'retail']
zharma[2024] = zharma[2024].str.replace(',', '.')
zharma[2024] = zharma[2024].str.replace(')', '')
zharma[2024] = zharma[2024].str.replace(' ', '')
zharma[2024] = zharma[2024].astype(float)

In [68]:
zharma = pd.melt(zharma, id_vars=['Indicator'], var_name='year', value_name='value')
zharma = zharma.pivot(index='year', columns='Indicator', values='value').reset_index()
zharma.insert(0, 'rayon', 'Zharma')
zharma.columns.name = None

In [69]:
kokpekti = pd.read_excel(Path("../Data/Controls/Abay_All.xls"), sheet_name="Кокпекты", header=4, usecols='A, AC:AI', nrows=232, na_values=['x', 'х', '-', '', ' ', '...'])

In [70]:
kokpekti.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023, 2024]
kokpekti = kokpekti.loc[[119, 151, 220]].reset_index(drop=True)

In [71]:
kokpekti['Indicator'] = ['production', 'agriculture', 'retail']
kokpekti[2024] = kokpekti[2024].str.replace(',', '.')
kokpekti[2024] = kokpekti[2024].str.replace(')', '')
kokpekti[2024] = kokpekti[2024].str.replace(' ', '')
kokpekti[2024] = kokpekti[2024].astype(float)

In [72]:
aksuat = pd.read_excel(Path("../Data/Controls/Abay_All.xls"), sheet_name="Аксуат", header=4, usecols='A, AC:AI', nrows=230, na_values=['x', 'х', '-', '', ' ', '...'])

In [73]:
aksuat.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023, 2024]
aksuat = aksuat.loc[[117, 149, 218]].reset_index(drop=True)

In [74]:
aksuat['Indicator'] = ['production', 'agriculture', 'retail']
aksuat[2024] = aksuat[2024].str.replace(',', '.')
aksuat[2024] = aksuat[2024].str.replace(')', '')
aksuat[2024] = aksuat[2024].str.replace(' ', '')
aksuat[2024] = aksuat[2024].astype(float)

In [75]:
urzhar = pd.read_excel(Path("../Data/Controls/Abay_All.xls"), sheet_name="Урджар", header=4, usecols='A, AC:AI', nrows=230, na_values=['x', 'х', '-', '', ' ', '...'])

In [76]:
urzhar.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023, 2024]
urzhar = urzhar.loc[[117, 149, 218]].reset_index(drop=True)

In [77]:
urzhar['Indicator'] = ['production', 'agriculture', 'retail']
urzhar[2024] = urzhar[2024].str.replace(',', '.')
urzhar[2024] = urzhar[2024].str.replace(')', '')
urzhar[2024] = urzhar[2024].str.replace(' ', '')
urzhar[2024] = urzhar[2024].astype(float)

In [78]:
makanshi = pd.read_excel(Path("../Data/Controls/Abay_All.xls"), sheet_name="Мақаншы", header=4, usecols='A:B', nrows=230, na_values=['x', 'х', '-', '', ' ', '...'])

In [79]:
makanshi.columns = ['Indicator', 2024]
makanshi = makanshi.loc[[117, 149, 218]].reset_index(drop=True)

In [80]:
makanshi['Indicator'] = ['production', 'agriculture', 'retail']
makanshi[2024] = makanshi[2024].str.replace(',', '.')
makanshi[2024] = makanshi[2024].str.replace(')', '')
makanshi[2024] = makanshi[2024].str.replace(' ', '')
makanshi[2024] = makanshi[2024].astype(float)

In [81]:
urzhar[2024] = urzhar[2024] + makanshi[2024]

In [82]:
urzhar = pd.melt(urzhar, id_vars=['Indicator'], var_name='year', value_name='value')
urzhar = urzhar.pivot(index='year', columns='Indicator', values='value').reset_index()
urzhar.insert(0, 'rayon', 'Urzhar')
urzhar.columns.name = None

In [83]:
oskemen = pd.read_excel(Path("../Data/Controls/East-Kazakhstan_All.xls"), sheet_name="У-ка", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [84]:
oskemen.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
oskemen = oskemen.loc[[125, 157, 226]].reset_index(drop=True)
oskemen['Indicator'] = ['production', 'agriculture', 'retail']

In [85]:
oskemen = pd.melt(oskemen, id_vars=['Indicator'], var_name='year', value_name='value')
oskemen = oskemen.pivot(index='year', columns='Indicator', values='value').reset_index()
oskemen.insert(0, 'rayon', 'Oskemen_city')
oskemen.columns.name = None

In [86]:
ridder = pd.read_excel(Path("../Data/Controls/East-Kazakhstan_All.xls"), sheet_name="Риддер", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [87]:
ridder.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
ridder = ridder.loc[[125, 157, 226]].reset_index(drop=True)
ridder['Indicator'] = ['production', 'agriculture', 'retail']

In [88]:
ridder_city = pd.read_excel(Path("../Data/Controls/East-Kazakhstan_All.xls"), sheet_name="Моногорода Риддер", header=1, usecols='B, K:P', nrows=279, na_values=['x', 'х', '-', '', ' ', '...'])

In [89]:
ridder_city.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
ridder_city = ridder_city.loc[[137, 172, 263]].reset_index(drop=True)
ridder_city['Indicator'] = ['production', 'agriculture', 'retail']

In [90]:
ridder_city[[2018, 2019, 2020, 2021, 2022, 2023]] = ridder_city[[2018, 2019, 2020, 2021, 2022, 2023]] + ridder[[2018, 2019, 2020, 2021, 2022, 2023]]

In [91]:
ridder_city = pd.melt(ridder_city, id_vars=['Indicator'], var_name='year', value_name='value')
ridder_city = ridder_city.pivot(index='year', columns='Indicator', values='value').reset_index()
ridder_city.insert(0, 'rayon', 'Ridder_city')
ridder_city.columns.name = None

In [92]:
glubokoe = pd.read_excel(Path("../Data/Controls/East-Kazakhstan_All.xls"), sheet_name="Глубокое", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [93]:
glubokoe.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
glubokoe = glubokoe.loc[[125, 157, 226]].reset_index(drop=True)
glubokoe['Indicator'] = ['production', 'agriculture', 'retail']

In [94]:
glubokoe = pd.melt(glubokoe, id_vars=['Indicator'], var_name='year', value_name='value')
glubokoe = glubokoe.pivot(index='year', columns='Indicator', values='value').reset_index()
glubokoe.insert(0, 'rayon', 'Glubokoe')
glubokoe.columns.name = None

In [95]:
zaysan = pd.read_excel(Path("../Data/Controls/East-Kazakhstan_All.xls"), sheet_name="Зайсан", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [96]:
zaysan.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
zaysan = zaysan.loc[[125, 157, 226]].reset_index(drop=True)
zaysan['Indicator'] = ['production', 'agriculture', 'retail']

In [97]:
zaysan = pd.melt(zaysan, id_vars=['Indicator'], var_name='year', value_name='value')
zaysan = zaysan.pivot(index='year', columns='Indicator', values='value').reset_index()
zaysan.insert(0, 'rayon', 'Zaysan')
zaysan.columns.name = None

In [98]:
altay = pd.read_excel(Path("../Data/Controls/East-Kazakhstan_All.xls"), sheet_name="Алтай", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [99]:
altay.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
altay = altay.loc[[125, 157, 226]].reset_index(drop=True)
altay['Indicator'] = ['production', 'agriculture', 'retail']

In [100]:
altay_city = pd.read_excel(Path("../Data/Controls/East-Kazakhstan_All.xls"), sheet_name="Моногорода Алтай", header=1, usecols='B, K:P', nrows=278, na_values=['x', 'х', '-', '', ' ', '...', '…'])

In [101]:
altay_city.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
altay_city = altay_city.loc[[137, 172, 263]].reset_index(drop=True)
altay_city['Indicator'] = ['production', 'agriculture', 'retail']

In [102]:
altay[[2018, 2019, 2020, 2021, 2022, 2023]] = altay[[2018, 2019, 2020, 2021, 2022, 2023]] + altay_city[[2018, 2019, 2020, 2021, 2022, 2023]].fillna(0)

/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/2740354433.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  altay[[2018, 2019, 2020, 2021, 2022, 2023]] = altay[[2018, 2019, 2020, 2021, 2022, 2023]] + altay_city[[2018, 2019, 2020, 2021, 2022, 2023]].fillna(0)

In [103]:
altay = pd.melt(altay, id_vars=['Indicator'], var_name='year', value_name='value')
altay = altay.pivot(index='year', columns='Indicator', values='value').reset_index()
altay.insert(0, 'rayon', 'Altay')
altay.columns.name = None

In [104]:
kurshim = pd.read_excel(Path("../Data/Controls/East-Kazakhstan_All.xls"), sheet_name="Курчум", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [105]:
kurshim.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
kurshim = kurshim.loc[[125, 157, 226]].reset_index(drop=True)
kurshim['Indicator'] = ['production', 'agriculture', 'retail']

In [106]:
kurshim = pd.melt(kurshim, id_vars=['Indicator'], var_name='year', value_name='value')
kurshim = kurshim.pivot(index='year', columns='Indicator', values='value').reset_index()
kurshim.insert(0, 'rayon', 'Kurshim')
kurshim.columns.name = None

In [107]:
katon = pd.read_excel(Path("../Data/Controls/East-Kazakhstan_All.xls"), sheet_name="Катон-Карагай", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [108]:
katon.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
katon = katon.loc[[125, 157, 226]].reset_index(drop=True)
katon['Indicator'] = ['production', 'agriculture', 'retail']

In [109]:
katon = pd.melt(katon, id_vars=['Indicator'], var_name='year', value_name='value')
katon = katon.pivot(index='year', columns='Indicator', values='value').reset_index()
katon.insert(0, 'rayon', 'Katonkaragay')
katon.columns.name = None

In [110]:
samar = pd.read_excel(Path("../Data/Controls/East-Kazakhstan_All.xls"), sheet_name="Самар", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [111]:
samar.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
samar = samar.loc[[125, 157, 226]].reset_index(drop=True)
samar['Indicator'] = ['production', 'agriculture', 'retail']

In [112]:
kokpekti[[2018, 2019, 2020, 2021, 2022, 2023]] = kokpekti[[2018, 2019, 2020, 2021, 2022, 2023]] + samar[[2018, 2019, 2020, 2021, 2022, 2023]].fillna(0)

/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/3062827892.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  kokpekti[[2018, 2019, 2020, 2021, 2022, 2023]] = kokpekti[[2018, 2019, 2020, 2021, 2022, 2023]] + samar[[2018, 2019, 2020, 2021, 2022, 2023]].fillna(0)

In [113]:
kokpekti = pd.melt(kokpekti, id_vars=['Indicator'], var_name='year', value_name='value')
kokpekti = kokpekti.pivot(index='year', columns='Indicator', values='value').reset_index()
kokpekti.insert(0, 'rayon', 'Kokpekti')
kokpekti.columns.name = None

In [114]:
tarbagatay = pd.read_excel(Path("../Data/Controls/East-Kazakhstan_All.xls"), sheet_name="Тарбагатай", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [115]:
tarbagatay.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
tarbagatay = tarbagatay.loc[[125, 157, 226]].reset_index(drop=True)
tarbagatay['Indicator'] = ['production', 'agriculture', 'retail']

In [116]:
tarbagatay[[2018, 2019, 2020, 2021, 2022, 2023]] = tarbagatay[[2018, 2019, 2020, 2021, 2022, 2023]] + aksuat[[2018, 2019, 2020, 2021, 2022, 2023]].fillna(0)

/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/3275713407.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  tarbagatay[[2018, 2019, 2020, 2021, 2022, 2023]] = tarbagatay[[2018, 2019, 2020, 2021, 2022, 2023]] + aksuat[[2018, 2019, 2020, 2021, 2022, 2023]].fillna(0)

In [117]:
tarbagatay = pd.melt(tarbagatay, id_vars=['Indicator'], var_name='year', value_name='value')
tarbagatay = tarbagatay.pivot(index='year', columns='Indicator', values='value').reset_index()
tarbagatay.insert(0, 'rayon', 'Tarbagatay')
tarbagatay.columns.name = None

In [118]:
ulan = pd.read_excel(Path("../Data/Controls/East-Kazakhstan_All.xls"), sheet_name="Улан", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [119]:
ulan.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
ulan = ulan.loc[[125, 157, 226]].reset_index(drop=True)
ulan['Indicator'] = ['production', 'agriculture', 'retail']

In [120]:
ulan = pd.melt(ulan, id_vars=['Indicator'], var_name='year', value_name='value')
ulan = ulan.pivot(index='year', columns='Indicator', values='value').reset_index()
ulan.insert(0, 'rayon', 'Ulan')
ulan.columns.name = None

In [121]:
shemonaiha = pd.read_excel(Path("../Data/Controls/East-Kazakhstan_All.xls"), sheet_name="Шемонаиха", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [122]:
shemonaiha.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
shemonaiha = shemonaiha.loc[[125, 157, 226]].reset_index(drop=True)
shemonaiha['Indicator'] = ['production', 'agriculture', 'retail']

In [123]:
shemonaiha = pd.melt(shemonaiha, id_vars=['Indicator'], var_name='year', value_name='value')
shemonaiha = shemonaiha.pivot(index='year', columns='Indicator', values='value').reset_index()
shemonaiha.insert(0, 'rayon', 'Shemonaiha')
shemonaiha.columns.name = None

In [124]:
east_controls = pd.concat([oskemen, kurchatov, ridder_city, semey, abay, ayagoz, beskaragay, boroduliha, glubokoe, zharma, zaysan, altay, kokpekti, kurshim, katon, tarbagatay, ulan, urzhar, shemonaiha], ignore_index=True)

In [125]:
east_controls

            rayon  year agriculture   production    retail
0    Oskemen_city  2018     18710.2    1089708.7    505623
1    Oskemen_city  2019     20500.4      1188598  575488.1
2    Oskemen_city  2020     26403.4    1267686.2  614110.3
3    Oskemen_city  2021       33072    1432273.9  710753.9
4    Oskemen_city  2022     29324.4  1680829.586  856099.9
..            ...   ...         ...          ...       ...
118    Shemonaiha  2019     33198.3      64098.8   10808.9
119    Shemonaiha  2020     35344.6      74754.4   11599.3
120    Shemonaiha  2021     54787.5      92854.4   13944.5
121    Shemonaiha  2022     60296.4   118102.441   17349.8
122    Shemonaiha  2023     51963.6    122014.43   19931.9

[123 rows x 5 columns]

## PPI

In [126]:
east_ppi = pd.read_excel(Path("../Data/PPI/East-Kazakhstan.xls"), header=4, usecols='AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [127]:
east_ppi.columns = [2018, 2019, 2020, 2021, 2022, 2023]
east_ppi = east_ppi.loc[80].reset_index(drop=True)
east_ppi.loc[[0, 1, 2, 3, 5]] = ['100.7', '103.4', '121.1', '116.6', '101.5']
east_ppi = east_ppi.str.replace(',', '.').astype(float)

In [128]:
rayons = list(east_inv['rayon'].unique())

In [129]:
dfs = []

for rayon in rayons:
    df_temp = pd.DataFrame({
        'rayon': rayon,
        'year': range(2018, 2024),
        'ppi': east_ppi.values
    })
    dfs.append(df_temp)

east_ppi = pd.concat(dfs, ignore_index=True)

In [130]:
east_ppi

            rayon  year    ppi
0    Oskemen_city  2018  100.7
1    Oskemen_city  2019  103.4
2    Oskemen_city  2020  121.1
3    Oskemen_city  2021  116.6
4    Oskemen_city  2022  101.9
..            ...   ...    ...
109    Shemonaiha  2019  103.4
110    Shemonaiha  2020  121.1
111    Shemonaiha  2021  116.6
112    Shemonaiha  2022  101.9
113    Shemonaiha  2023  101.5

[114 rows x 3 columns]

## Combine together

In [131]:
dfs = [east_inv, east_empl, east_controls, east_ppi]

east_merged = reduce(lambda left, right: pd.merge(left, right, on=['rayon', 'year'], how='outer'), dfs)

east_merged

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year,employment,agriculture,production,retail,ppi
0,Abay,2868180,3092.0,3092.0,981955.0,East-Kazakhstan,2018,6.8,22795.4,1593.9,1869.4,100.7
1,Abay,2514048,405350.0,67923.0,529073.0,East-Kazakhstan,2019,6.8,25865.6,2352.1,2470.9,103.4
2,Abay,7040473,5593.0,5593.0,784053.0,East-Kazakhstan,2020,6.7,29614.9,3201.9,2720.2,121.1
3,Abay,3671620,1643.0,1643.0,1125547.0,East-Kazakhstan,2021,6.8,34162.9,5753.1,3228.1,116.6
4,Abay,6258213,0.0,0.0,1723622.0,East-Kazakhstan,2022,7.0,40779.1,7437.8,4868.6,101.9
...,...,...,...,...,...,...,...,...,...,...,...,...
128,Zharma,8965750,30650877.0,22714979.0,2663341.0,East-Kazakhstan,2020,16.9,29248.6,319768.5,14468.2,121.1
129,Zharma,11089448,16530654.0,5231374.0,7488723.0,East-Kazakhstan,2021,16.9,34225.4,294781.8,16452.7,116.6
130,Zharma,22694539,28933370.0,17497704.0,17646057.0,East-Kazakhstan,2022,18.8,42371.9,282815.6,21264.1,101.9
131,Zharma,57603107,17378503.0,5777877.0,23491273.0,East-Kazakhstan,2023,17.8,41639.4,315236,31105.3,101.5
132,Zharma,25006215,44066611.0,31108924.0,11218226.0,East-Kazakhstan,2024,17.0,NaN,398951.97,34366.87,NaN

# Almaty oblast and Zhetisu oblast

## Investments

### 2022-2024

In [132]:
zhetisu_all_2022 = pd.read_excel(Path("../Data/Investments/Zhetisu/2022_Investments.xls"), sheet_name='13.', header=5, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhetisu_all_2023 = pd.read_excel(Path("../Data/Investments/Zhetisu/2023_Investments.xlsx"), sheet_name='19', header=3, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhetisu_all_2024 = pd.read_excel(Path("../Data/Investments/Zhetisu/2024_Investments.xls"), sheet_name='14', header=3, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

zhetisu_non_2022 = pd.read_excel(Path("../Data/Investments/Zhetisu/2022_Investments.xls"), sheet_name='14.', header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhetisu_non_2023 = pd.read_excel(Path("../Data/Investments/Zhetisu/2023_Investments.xlsx"), sheet_name='20', header=3, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhetisu_non_2024 = pd.read_excel(Path("../Data/Investments/Zhetisu/2024_Investments.xls"), sheet_name='15', header=3, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [133]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [zhetisu_all_2022, zhetisu_all_2023, zhetisu_all_2024]:
    df.columns = all_columns

for df in [zhetisu_non_2022, zhetisu_non_2023, zhetisu_non_2024]:
    df.columns = non_columns
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

rayon_names = ['Taldykorgan_city', 'Tekeli_city', 'Aksu', 'Alakol', 'Yeskeldi', 'Kerbulak', 'Koksu', 'Karatal', 'Panfilov', 'Sarkan']

for df in [zhetisu_all_2022, zhetisu_all_2023, zhetisu_all_2024, zhetisu_non_2022, zhetisu_non_2023, zhetisu_non_2024]:
    df['rayon'] = rayon_names

zhetisu_2022 = zhetisu_all_2022.merge(zhetisu_non_2022, on='rayon')
zhetisu_2023 = zhetisu_all_2023.merge(zhetisu_non_2023, on='rayon')
zhetisu_2024 = zhetisu_all_2024.merge(zhetisu_non_2024, on='rayon')

dfs = [zhetisu_2022, zhetisu_2023, zhetisu_2024]

for i in range(3):
    df = dfs[i]
    df['oblast'] = 'Almaty'
    if i == 0:
        df['year'] = 2022
    elif i == 1:
        df['year'] = 2023
    else:
        df['year'] = 2024

In [134]:
almaty_all_2022 = pd.read_excel(Path("../Data/Investments/Almaty/2022_Investments.xls"), sheet_name='13', header=5, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
almaty_all_2023 = pd.read_excel(Path("../Data/Investments/Almaty/2023_Investments.xlsx"), sheet_name='14', header=3, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
almaty_all_2024 = pd.read_excel(Path("../Data/Investments/Almaty/2024_Investments.xls"), sheet_name='14', header=3, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

almaty_non_2022 = pd.read_excel(Path("../Data/Investments/Almaty/2022_Investments.xls"), sheet_name='14.', header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
almaty_non_2023 = pd.read_excel(Path("../Data/Investments/Almaty/2023_Investments.xlsx"), sheet_name='15', header=3, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
almaty_non_2024 = pd.read_excel(Path("../Data/Investments/Almaty/2024_Investments.xls"), sheet_name='15', header=3, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [135]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [almaty_all_2022, almaty_all_2023, almaty_all_2024]:
    df.columns = all_columns

for df in [almaty_non_2022, almaty_non_2023, almaty_non_2024]:
    df.columns = non_columns
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

almaty_non_2022 = almaty_non_2022.loc[:9]

rayon_names = ['Konayev_city', 'Balkhash', 'Enbekshikazak', 'Zhambyl', 'Kegen', 'Karasay', 'Rayimbek', 'Talgar', 'Uyghur', 'Ile']
rayon_names_2024 = ['Konayev_city', 'Alatau_city', 'Balkhash', 'Enbekshikazak', 'Zhambyl', 'Kegen', 'Karasay', 'Rayimbek', 'Talgar', 'Uyghur', 'Ile']

dfs = [almaty_all_2022, almaty_all_2023, almaty_all_2024, almaty_non_2022, almaty_non_2023, almaty_non_2024]

for i in range(6):
    df = dfs[i]
    if (i == 2) | (i == 5):
        df['rayon'] = rayon_names_2024
    else:
        df['rayon'] = rayon_names

alm_2022 = almaty_all_2022.merge(almaty_non_2022, on='rayon')
alm_2023 = almaty_all_2023.merge(almaty_non_2023, on='rayon')
alm_2024 = almaty_all_2024.merge(almaty_non_2024, on='rayon')

alm_2022.loc[6, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] = alm_2022.loc[6, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] + alm_2022.loc[4, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']]
alm_2023.loc[6, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] = alm_2023.loc[6, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] + alm_2023.loc[4, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']]
alm_2024.loc[7, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] = alm_2024.loc[7, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] + alm_2024.loc[5, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']]

alm_2022 = alm_2022.drop(4).reset_index(drop=True)
alm_2023 = alm_2023.drop(4).reset_index(drop=True)
alm_2024 = alm_2024.drop(5).reset_index(drop=True)

dfs = [alm_2022, alm_2023, alm_2024]

for i in range(3):
    df = dfs[i]
    df['oblast'] = 'Almaty'
    if i == 0:
        df['year'] = 2022
    elif i == 1:
        df['year'] = 2023
    else:
        df['year'] = 2024

almaty_2022 = pd.concat([zhetisu_2022, alm_2022], ignore_index=True)
almaty_2023 = pd.concat([zhetisu_2023, alm_2023], ignore_index=True)
almaty_2024 = pd.concat([zhetisu_2024, alm_2024], ignore_index=True)

### 2016 - 2021

In [136]:
almaty_all_2016 = pd.read_excel(Path("../Data/Investments/Almaty/2016_Investments/Internal_vs_external.xls"), header=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
almaty_nonextr_2016 = pd.read_excel(Path("../Data/Investments/Almaty/2016_Investments/Greenfield_investments.xls"), header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True).loc[:18]

almaty_all_2017 = pd.read_excel(Path("../Data/Investments/Almaty/2017_Investments/Internal_vs_external.xls"), header=5, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
almaty_nonextr_2017 = pd.read_excel(Path("../Data/Investments/Almaty/2017_Investments/Greenfield_investments.xls"), header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True).loc[:18]

almaty_all_2018 = pd.read_excel(Path("../Data/Investments/Almaty/2018_Investments/Internal_vs_external.xls"), header=5, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
almaty_nonextr_2018 = pd.read_excel(Path("../Data/Investments/Almaty/2018_Investments/Greenfield_investments.xlsx"), header=5, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True).loc[:19]

almaty_all_2019 = pd.read_excel(Path("../Data/Investments/Almaty/2019_Investments.xls"), sheet_name='14.', header=5, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
almaty_nonextr_2019 = pd.read_excel(Path("../Data/Investments/Almaty/2019_Investments.xls"), sheet_name='15.', header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True).loc[:19]

almaty_all_2020 = pd.read_excel(Path("../Data/Investments/Almaty/2020_Investments.xls"), sheet_name='13.', header=5, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
almaty_nonextr_2020 = pd.read_excel(Path("../Data/Investments/Almaty/2020_Investments.xls"), sheet_name='14.', header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True).loc[:19]

almaty_all_2021 = pd.read_excel(Path("../Data/Investments/Almaty/2021_Investments.xls"), sheet_name='13.', header=5, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
almaty_nonextr_2021 = pd.read_excel(Path("../Data/Investments/Almaty/2021_Investments.xls"), sheet_name='14.', header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [137]:
rayons_2016 = ['Aksu', 'Alakol', 'Balkhash', 'Enbekshikazak', 'Yeskeldi', 'Zhambyl', 'Ile', 'Karasay', 'Karatal', 'Kerbulak', 'Koksu', 'Panfilov', 'Rayimbek', 'Sarkan', 'Talgar', 'Uyghur', 'Konayev_city', 'Taldykorgan_city', 'Tekeli_city']
rayons_2017 = ['Taldykorgan_city', 'Konayev_city', 'Tekeli_city', 'Aksu', 'Alakol', 'Balkhash', 'Enbekshikazak', 'Zhambyl', 'Kerbulak', 'Koksu', 'Karatal', 'Karasay', 'Panfilov', 'Rayimbek', 'Sarkan', 'Talgar', 'Yeskeldi', 'Uyghur', 'Ile']
rayons = ['Taldykorgan_city', 'Konayev_city', 'Tekeli_city', 'Aksu', 'Alakol', 'Balkhash', 'Enbekshikazak', 'Zhambyl', 'Kegen', 'Kerbulak', 'Koksu', 'Karatal', 'Karasay', 'Panfilov', 'Rayimbek', 'Sarkan', 'Talgar', 'Yeskeldi', 'Uyghur', 'Ile']

all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']


dfs = [almaty_all_2016, almaty_all_2017, almaty_all_2018, almaty_all_2019, almaty_all_2020, almaty_all_2021]
for i in range(6):
    df = dfs[i]
    df.columns = all_columns
    if i == 0:
        df['rayon'] = rayons_2016
    elif i == 1:
        df['rayon'] = rayons_2017
    else:
        df['rayon'] = rayons

dfs = [almaty_nonextr_2016, almaty_nonextr_2017, almaty_nonextr_2018, almaty_nonextr_2019, almaty_nonextr_2020, almaty_nonextr_2021]
for i in range(6):
    df = dfs[i]
    df.columns = non_columns
    if i == 0:
        df['rayon'] = rayons_2016
    elif i == 1:
        df['rayon'] = rayons_2017
    else:
        df['rayon'] = rayons
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

almaty_2016 = almaty_all_2016.merge(almaty_nonextr_2016, on='rayon')
almaty_2017 = almaty_all_2017.merge(almaty_nonextr_2017, on='rayon')
almaty_2018 = almaty_all_2018.merge(almaty_nonextr_2018, on='rayon')
almaty_2019 = almaty_all_2019.merge(almaty_nonextr_2019, on='rayon')
almaty_2020 = almaty_all_2020.merge(almaty_nonextr_2020, on='rayon')
almaty_2021 = almaty_all_2021.merge(almaty_nonextr_2021, on='rayon')


dfs = [almaty_2018, almaty_2019, almaty_2020, almaty_2021]
for i in range(4):
    df = dfs[i]
    df.loc[14, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] = df.loc[14, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] + df.loc[8, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']]
    df.drop(8, inplace=True)
    df.reset_index(drop=True, inplace=True)


dfs = [almaty_2016, almaty_2017, almaty_2018, almaty_2019, almaty_2020, almaty_2021]

for i in range(6):
    df = dfs[i]
    df['oblast'] = 'Almaty'
    if i == 0:
        df['year'] = 2016
    elif i == 1:
        df['year'] = 2017
    elif i == 2:
        df['year'] = 2018
    elif i == 3:
        df['year'] = 2019
    elif i == 4:
        df['year'] = 2020
    else:
        df['year'] = 2021


almaty_inv = pd.concat([almaty_2016, almaty_2017, almaty_2018, almaty_2019, almaty_2020, almaty_2021, almaty_2022, almaty_2023, almaty_2024], ignore_index=True)
almaty_inv

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year
0,Aksu,1960440.0,21135.0,21135,338507.0,Almaty,2016
1,Alakol,18247465.0,639604.0,639604,12909596.0,Almaty,2016
2,Balkhash,1641387.0,210000.0,210000,1029359.0,Almaty,2016
3,Enbekshikazak,39068086.0,10628382.0,10620166,27886775.0,Almaty,2016
4,Yeskeldi,4026292.0,360630.0,360630,2245158.0,Almaty,2016
...,...,...,...,...,...,...,...
167,Karasay,172344338.0,51895433.0,51895433.0,111379415.0,Almaty,2024
168,Rayimbek,22816202.0,0.0,0.0,8753487.0,Almaty,2024
169,Talgar,105091760.0,19530203.0,19530203.0,79502676.0,Almaty,2024
170,Uyghur,14859311.0,10419128.0,2744199.0,4466472.0,Almaty,2024
171,Ile,145558420.0,59945415.0,59945415.0,121898606.0,Almaty,2024

## Employment

### 2022-2023

In [138]:
zhetisu_empl = pd.read_excel(Path("../Data/Employment/Zhetisu.xlsx"), skiprows=21, nrows=10, header=None, usecols='A:C')
alm_empl = pd.read_excel(Path("../Data/Employment/Almaty.xlsx"), skiprows=31, nrows=20, header=None, usecols='A, J:K', na_values=['x', 'х', '-', '', ' ']).dropna().reset_index(drop=True)

In [139]:
zhetisu_empl.columns = ['rayon', 2022, 2023]

rayons = ['Taldykorgan_city', 'Tekeli_city', 'Aksu', 'Alakol', 'Yeskeldi', 'Kerbulak', 'Koksu', 'Karatal', 'Panfilov', 'Sarkan']

zhetisu_empl['rayon'] = rayons

zhetisu_empl[2022] = zhetisu_empl[2022].astype(float)
zhetisu_empl[2023] = zhetisu_empl[2023].astype(float)

alm_empl.columns = ['rayon', 2022, 2023]

rayons = ['Konayev_city', 'Balkhash', 'Enbekshikazak', 'Zhambyl', 'Kegen', 'Karasay', 'Rayimbek', 'Talgar', 'Uyghur', 'Ile']

alm_empl['rayon'] = rayons

alm_empl[2022] = alm_empl[2022].astype(float)
alm_empl[2023] = alm_empl[2023].astype(float)

almaty_empl = pd.concat([zhetisu_empl, alm_empl], ignore_index=True)

almaty_empl.loc[16, [2022, 2023]] = almaty_empl.loc[16, [2022, 2023]] + almaty_empl.loc[14, [2022, 2023]]
almaty_empl = almaty_empl.drop(14).reset_index(drop=True)

almaty_empl_22_23 = almaty_empl.melt(id_vars='rayon', value_vars=[2022, 2023], var_name='year', value_name='employment')

### 2016-2021

In [140]:
alm_empl = pd.read_excel(Path("../Data/Employment/Almaty.xlsx"), skiprows=31, nrows=20, header=None, usecols='A, D:I', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
alm_empl

                   0      3      4      5      6      7      8
0   г.а. Талдыкорган   85.3   86.3   86.8   88.5   86.3   88.5
1        г.а. Конаев   31.6   31.1   31.7   31.1   29.3   28.5
2        г.а. Текели   16.6   17.6   17.7   17.5   17.2   17.2
3          Аксуский    18.9   18.9   18.1   18.1   17.4   17.2
4       Алакольский    35.1   35.1   35.0   34.2   33.3   31.9
5         Балхашский   14.7   14.6   14.4   14.5   14.1   13.9
6   Енбекшиказахский  157.9  156.3  157.9  152.2  147.9  147.2
7         Жамбылский   75.0   78.4   79.9   81.9   81.3   81.1
8          Кегенский    0.0    0.0   15.5   14.9   14.6   14.3
9       Кербулакский   24.2   23.9   23.4   23.1   22.0   21.5
10         Коксуский   21.6   21.0   20.9   20.2   19.5   19.7
11      Каратальский   24.2   23.8   22.9   23.0   22.6   21.1
12       Карасайский  113.4  120.4  125.8  128.1  129.0  130.0
13      Панфиловский   61.5   61.5   61.3   61.2   58.4   59.2
14      Райымбекский   41.7   38.4   22.3   19.9   19.4   18.3
15       Саркандский   20.3   19.1   18.5   17.4   16.5   15.7
16        Талгарский   93.2   93.8   94.0   97.2   96.6   97.9
17     Ескельдинский   23.8   23.6   23.0   22.1   21.4   21.0
18         Уйгурский   32.2   31.1   30.6   30.0   28.9   28.8
19          Илийский   94.2   93.2   94.5   95.6   98.3   99.9

In [141]:
alm_empl.columns = ['rayon', 2016, 2017, 2018, 2019, 2020, 2021]

rayons = ['Taldykorgan_city', 'Konayev_city', 'Tekeli_city', 'Aksu', 'Alakol', 'Balkhash', 'Enbekshikazak', 'Zhambyl', 'Kegen', 'Kerbulak', 'Koksu', 'Karatal', 'Karasay', 'Panfilov', 'Rayimbek', 'Sarkan', 'Talgar', 'Yeskeldi', 'Uyghur', 'Ile']

alm_empl['rayon'] = rayons

for i in [2016, 2017, 2018, 2019, 2020, 2021]:
    alm_empl[i] = alm_empl[i].astype(float)

alm_empl.loc[14, [2016, 2017, 2018, 2019, 2020, 2021]] = alm_empl.loc[14, [2016, 2017, 2018, 2019, 2020, 2021]] + alm_empl.loc[8, [2016, 2017, 2018, 2019, 2020, 2021]]
alm_empl = alm_empl.drop(8).reset_index(drop=True)

alm_empl_16_21 = alm_empl.melt(id_vars='rayon', value_vars=[2016, 2017, 2018, 2019, 2020, 2021], var_name='year', value_name='employment')

almaty_empl = pd.concat([alm_empl_16_21, almaty_empl_22_23], ignore_index=True)
almaty_empl

                rayon  year  employment
0    Taldykorgan_city  2016        85.3
1        Konayev_city  2016        31.6
2         Tekeli_city  2016        16.6
3                Aksu  2016        18.9
4              Alakol  2016        35.1
..                ...   ...         ...
147           Karasay  2023       150.7
148          Rayimbek  2023        24.8
149            Talgar  2023       117.1
150            Uyghur  2023        28.2
151               Ile  2023       125.2

[152 rows x 3 columns]

## Other controls

In [142]:
taldykorgan = pd.read_excel(Path("../Data/Controls/Zhetisu_All.xls"), sheet_name="г.а.Талдыкорган", header=3, usecols='B, C:E', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

taldykorgan.columns = ['Indicator', 2022, 2023, 2024]
taldykorgan = taldykorgan.loc[[56, 77, 125]].reset_index(drop=True)

taldykorgan['Indicator'] = ['agriculture', 'production', 'retail']
taldykorgan[2024] = taldykorgan[2024].astype(str)
taldykorgan[2024] = taldykorgan[2024].str.replace(',', '.')
taldykorgan[2024] = taldykorgan[2024].str.replace(')', '')
taldykorgan[2024] = taldykorgan[2024].str.replace(' ', '')
taldykorgan[2024] = taldykorgan[2024].astype(float)

taldykorgan = pd.melt(taldykorgan, id_vars=['Indicator'], var_name='year', value_name='value')
taldykorgan = taldykorgan.pivot(index='year', columns='Indicator', values='value').reset_index()
taldykorgan.insert(0, 'rayon', 'Taldykorgan_city')
taldykorgan.columns.name = None

In [143]:
tekeli = pd.read_excel(Path("../Data/Controls/Zhetisu_All.xls"), sheet_name="г.а.Текели", header=3, usecols='B, C:E', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

tekeli.columns = ['Indicator', 2022, 2023, 2024]
tekeli = tekeli.loc[[56, 77, 125]].reset_index(drop=True)

tekeli['Indicator'] = ['agriculture', 'production', 'retail']
tekeli[2024] = tekeli[2024].astype(str)
tekeli[2024] = tekeli[2024].str.replace(',', '.')
tekeli[2024] = tekeli[2024].str.replace(')', '')
tekeli[2024] = tekeli[2024].str.replace(' ', '')
tekeli[2024] = tekeli[2024].astype(float)

tekeli = pd.melt(tekeli, id_vars=['Indicator'], var_name='year', value_name='value')
tekeli = tekeli.pivot(index='year', columns='Indicator', values='value').reset_index()
tekeli.insert(0, 'rayon', 'Tekeli_city')
tekeli.columns.name = None

In [144]:
aksu = pd.read_excel(Path("../Data/Controls/Zhetisu_All.xls"), sheet_name="Аксуский", header=3, usecols='B, C:E', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

aksu.columns = ['Indicator', 2022, 2023, 2024]
aksu = aksu.loc[[56, 77, 125]].reset_index(drop=True)

aksu['Indicator'] = ['agriculture', 'production', 'retail']
aksu[2024] = aksu[2024].astype(str)
aksu[2024] = aksu[2024].str.replace(',', '.')
aksu[2024] = aksu[2024].str.replace(')', '')
aksu[2024] = aksu[2024].str.replace(' ', '')
aksu[2024] = aksu[2024].astype(float)

aksu = pd.melt(aksu, id_vars=['Indicator'], var_name='year', value_name='value')
aksu = aksu.pivot(index='year', columns='Indicator', values='value').reset_index()
aksu.insert(0, 'rayon', 'Aksu')
aksu.columns.name = None

In [145]:
alakol = pd.read_excel(Path("../Data/Controls/Zhetisu_All.xls"), sheet_name="Алакольский", header=3, usecols='B, C:E', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

alakol.columns = ['Indicator', 2022, 2023, 2024]
alakol = alakol.loc[[56, 77, 125]].reset_index(drop=True)

alakol['Indicator'] = ['agriculture', 'production', 'retail']
alakol[2024] = alakol[2024].astype(str)
alakol[2024] = alakol[2024].str.replace(',', '.')
alakol[2024] = alakol[2024].str.replace(')', '')
alakol[2024] = alakol[2024].str.replace(' ', '')
alakol[2024] = alakol[2024].astype(float)

alakol = pd.melt(alakol, id_vars=['Indicator'], var_name='year', value_name='value')
alakol = alakol.pivot(index='year', columns='Indicator', values='value').reset_index()
alakol.insert(0, 'rayon', 'Alakol')
alakol.columns.name = None

In [146]:
kerbulak = pd.read_excel(Path("../Data/Controls/Zhetisu_All.xls"), sheet_name="Кербулакский", header=3, usecols='B, C:E', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

kerbulak.columns = ['Indicator', 2022, 2023, 2024]
kerbulak = kerbulak.loc[[56, 77, 125]].reset_index(drop=True)

kerbulak['Indicator'] = ['agriculture', 'production', 'retail']
kerbulak[2024] = kerbulak[2024].astype(str)
kerbulak[2024] = kerbulak[2024].str.replace(',', '.')
kerbulak[2024] = kerbulak[2024].str.replace(')', '')
kerbulak[2024] = kerbulak[2024].str.replace(' ', '')
kerbulak[2024] = kerbulak[2024].astype(float)

kerbulak = pd.melt(kerbulak, id_vars=['Indicator'], var_name='year', value_name='value')
kerbulak = kerbulak.pivot(index='year', columns='Indicator', values='value').reset_index()
kerbulak.insert(0, 'rayon', 'Kerbulak')
kerbulak.columns.name = None

In [147]:
koksu = pd.read_excel(Path("../Data/Controls/Zhetisu_All.xls"), sheet_name="Коксуский", header=3, usecols='B, C:E', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

koksu.columns = ['Indicator', 2022, 2023, 2024]
koksu = koksu.loc[[56, 77, 125]].reset_index(drop=True)

koksu['Indicator'] = ['agriculture', 'production', 'retail']
koksu[2024] = koksu[2024].astype(str)
koksu[2024] = koksu[2024].str.replace(',', '.')
koksu[2024] = koksu[2024].str.replace(')', '')
koksu[2024] = koksu[2024].str.replace(' ', '')
koksu[2024] = koksu[2024].astype(float)

koksu = pd.melt(koksu, id_vars=['Indicator'], var_name='year', value_name='value')
koksu = koksu.pivot(index='year', columns='Indicator', values='value').reset_index()
koksu.insert(0, 'rayon', 'Koksu')
koksu.columns.name = None

In [148]:
karatal = pd.read_excel(Path("../Data/Controls/Zhetisu_All.xls"), sheet_name="Каратальский", header=3, usecols='B, C:E', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

karatal.columns = ['Indicator', 2022, 2023, 2024]
karatal = karatal.loc[[56, 77, 125]].reset_index(drop=True)

karatal['Indicator'] = ['agriculture', 'production', 'retail']
karatal[2024] = karatal[2024].astype(str)
karatal[2024] = karatal[2024].str.replace(',', '.')
karatal[2024] = karatal[2024].str.replace(')', '')
karatal[2024] = karatal[2024].str.replace(' ', '')
karatal[2024] = karatal[2024].astype(float)

karatal = pd.melt(karatal, id_vars=['Indicator'], var_name='year', value_name='value')
karatal = karatal.pivot(index='year', columns='Indicator', values='value').reset_index()
karatal.insert(0, 'rayon', 'Karatal')
karatal.columns.name = None

In [149]:
panfilov = pd.read_excel(Path("../Data/Controls/Zhetisu_All.xls"), sheet_name="Панфиловский", header=3, usecols='B, C:E', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

panfilov.columns = ['Indicator', 2022, 2023, 2024]
panfilov = panfilov.loc[[56, 77, 125]].reset_index(drop=True)

panfilov['Indicator'] = ['agriculture', 'production', 'retail']
panfilov[2024] = panfilov[2024].astype(str)
panfilov[2024] = panfilov[2024].str.replace(',', '.')
panfilov[2024] = panfilov[2024].str.replace(')', '')
panfilov[2024] = panfilov[2024].str.replace(' ', '')
panfilov[2024] = panfilov[2024].astype(float)

panfilov = pd.melt(panfilov, id_vars=['Indicator'], var_name='year', value_name='value')
panfilov = panfilov.pivot(index='year', columns='Indicator', values='value').reset_index()
panfilov.insert(0, 'rayon', 'Panfilov')
panfilov.columns.name = None

In [150]:
sarkan = pd.read_excel(Path("../Data/Controls/Zhetisu_All.xls"), sheet_name="Сарканский", header=3, usecols='B, C:E', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

sarkan.columns = ['Indicator', 2022, 2023, 2024]
sarkan = sarkan.loc[[56, 77, 125]].reset_index(drop=True)

sarkan['Indicator'] = ['agriculture', 'production', 'retail']
sarkan[2024] = sarkan[2024].astype(str)
sarkan[2024] = sarkan[2024].str.replace(',', '.')
sarkan[2024] = sarkan[2024].str.replace(')', '')
sarkan[2024] = sarkan[2024].str.replace(' ', '')
sarkan[2024] = sarkan[2024].astype(float)

sarkan = pd.melt(sarkan, id_vars=['Indicator'], var_name='year', value_name='value')
sarkan = sarkan.pivot(index='year', columns='Indicator', values='value').reset_index()
sarkan.insert(0, 'rayon', 'Sarkan')
sarkan.columns.name = None

In [151]:
yeskeldi = pd.read_excel(Path("../Data/Controls/Zhetisu_All.xls"), sheet_name="Ескельдинский", header=3, usecols='B, C:E', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

yeskeldi.columns = ['Indicator', 2022, 2023, 2024]
yeskeldi = yeskeldi.loc[[56, 77, 125]].reset_index(drop=True)

yeskeldi['Indicator'] = ['agriculture', 'production', 'retail']
yeskeldi[2024] = yeskeldi[2024].astype(str)
yeskeldi[2024] = yeskeldi[2024].str.replace(',', '.')
yeskeldi[2024] = yeskeldi[2024].str.replace(')', '')
yeskeldi[2024] = yeskeldi[2024].str.replace(' ', '')
yeskeldi[2024] = yeskeldi[2024].astype(float)

yeskeldi = pd.melt(yeskeldi, id_vars=['Indicator'], var_name='year', value_name='value')
yeskeldi = yeskeldi.pivot(index='year', columns='Indicator', values='value').reset_index()
yeskeldi.insert(0, 'rayon', 'Yeskeldi')
yeskeldi.columns.name = None

In [152]:
konayev = pd.read_excel(Path("../Data/Controls/Almaty_All.xls"), sheet_name="г.а.Конаев", header=3, usecols='B, AB:AI', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

konayev.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
konayev = konayev.loc[[56, 77, 125]].reset_index(drop=True)

konayev['Indicator'] = ['agriculture', 'production', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    konayev[i] = konayev[i].astype(str)
    konayev[i] = konayev[i].str.replace(',', '.')
    konayev[i] = konayev[i].str.replace(')', '')
    konayev[i] = konayev[i].str.replace(' ', '')
    konayev[i] = konayev[i].str.replace('\xa0', '')
    konayev[i] = konayev[i].astype(float)

konayev = pd.melt(konayev, id_vars=['Indicator'], var_name='year', value_name='value')
konayev = konayev.pivot(index='year', columns='Indicator', values='value').reset_index()
konayev.insert(0, 'rayon', 'Konayev_city')
konayev.columns.name = None

In [153]:
balkhash = pd.read_excel(Path("../Data/Controls/Almaty_All.xls"), sheet_name="Балхашский", header=3, usecols='B, AB:AI', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

balkhash.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
balkhash = balkhash.loc[[56, 77, 125]].reset_index(drop=True)

balkhash['Indicator'] = ['agriculture', 'production', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    balkhash[i] = balkhash[i].astype(str)
    balkhash[i] = balkhash[i].str.replace(',', '.')
    balkhash[i] = balkhash[i].str.replace(')', '')
    balkhash[i] = balkhash[i].str.replace(' ', '')
    balkhash[i] = balkhash[i].str.replace('\xa0', '')
    balkhash[i] = balkhash[i].astype(float)

balkhash = pd.melt(balkhash, id_vars=['Indicator'], var_name='year', value_name='value')
balkhash = balkhash.pivot(index='year', columns='Indicator', values='value').reset_index()
balkhash.insert(0, 'rayon', 'Balkhash')
balkhash.columns.name = None

In [154]:
enbekshikazak = pd.read_excel(Path("../Data/Controls/Almaty_All.xls"), sheet_name="Енбекшиказахский", header=3, usecols='B, AB:AI', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

enbekshikazak.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
enbekshikazak = enbekshikazak.loc[[56, 77, 125]].reset_index(drop=True)

enbekshikazak['Indicator'] = ['agriculture', 'production', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    enbekshikazak[i] = enbekshikazak[i].astype(str)
    enbekshikazak[i] = enbekshikazak[i].str.replace(',', '.')
    enbekshikazak[i] = enbekshikazak[i].str.replace(')', '')
    enbekshikazak[i] = enbekshikazak[i].str.replace(' ', '')
    enbekshikazak[i] = enbekshikazak[i].str.replace('\xa0', '')
    enbekshikazak[i] = enbekshikazak[i].astype(float)

enbekshikazak = pd.melt(enbekshikazak, id_vars=['Indicator'], var_name='year', value_name='value')
enbekshikazak = enbekshikazak.pivot(index='year', columns='Indicator', values='value').reset_index()
enbekshikazak.insert(0, 'rayon', 'Enbekshikazak')
enbekshikazak.columns.name = None

In [155]:
zhambyl = pd.read_excel(Path("../Data/Controls/Almaty_All.xls"), sheet_name="Жамбылский", header=3, usecols='B, AB:AI', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

zhambyl.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
zhambyl = zhambyl.loc[[56, 77, 125]].reset_index(drop=True)

zhambyl['Indicator'] = ['agriculture', 'production', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    zhambyl[i] = zhambyl[i].astype(str)
    zhambyl[i] = zhambyl[i].str.replace(',', '.')
    zhambyl[i] = zhambyl[i].str.replace(')', '')
    zhambyl[i] = zhambyl[i].str.replace(' ', '')
    zhambyl[i] = zhambyl[i].str.replace('\xa0', '')
    zhambyl[i] = zhambyl[i].astype(float)

zhambyl = pd.melt(zhambyl, id_vars=['Indicator'], var_name='year', value_name='value')
zhambyl = zhambyl.pivot(index='year', columns='Indicator', values='value').reset_index()
zhambyl.insert(0, 'rayon', 'Zhambyl')
zhambyl.columns.name = None

In [156]:
kegen = pd.read_excel(Path("../Data/Controls/Almaty_All.xls"), sheet_name="Кегенский", header=3, usecols='B, C:H', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

kegen.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
kegen = kegen.loc[[56, 77, 125]].reset_index(drop=True)

kegen['Indicator'] = ['agriculture', 'production', 'retail']

for i in [2018, 2019, 2020, 2021, 2022, 2023]:
    kegen[i] = kegen[i].astype(str)
    kegen[i] = kegen[i].str.replace(',', '.')
    kegen[i] = kegen[i].str.replace(')', '')
    kegen[i] = kegen[i].str.replace(' ', '')
    kegen[i] = kegen[i].str.replace('\xa0', '')
    kegen[i] = kegen[i].astype(float)

kegen = pd.melt(kegen, id_vars=['Indicator'], var_name='year', value_name='value')
kegen = kegen.pivot(index='year', columns='Indicator', values='value').reset_index()
kegen.insert(0, 'rayon', 'Kegen')
kegen.columns.name = None

In [157]:
karasay = pd.read_excel(Path("../Data/Controls/Almaty_All.xls"), sheet_name="Карасайский", header=3, usecols='B, AB:AI', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

karasay.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
karasay = karasay.loc[[56, 77, 125]].reset_index(drop=True)

karasay['Indicator'] = ['agriculture', 'production', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    karasay[i] = karasay[i].astype(str)
    karasay[i] = karasay[i].str.replace(',', '.')
    karasay[i] = karasay[i].str.replace(')', '')
    karasay[i] = karasay[i].str.replace(' ', '')
    karasay[i] = karasay[i].str.replace('\xa0', '')
    karasay[i] = karasay[i].astype(float)

karasay = pd.melt(karasay, id_vars=['Indicator'], var_name='year', value_name='value')
karasay = karasay.pivot(index='year', columns='Indicator', values='value').reset_index()
karasay.insert(0, 'rayon', 'Karasay')
karasay.columns.name = None

In [158]:
rayimbek = pd.read_excel(Path("../Data/Controls/Almaty_All.xls"), sheet_name="Райымбекский", header=3, usecols='B, AB:AI', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

rayimbek.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
rayimbek = rayimbek.loc[[56, 77, 125]].reset_index(drop=True)

rayimbek['Indicator'] = ['agriculture', 'production', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    rayimbek[i] = rayimbek[i].astype(str)
    rayimbek[i] = rayimbek[i].str.replace(',', '.')
    rayimbek[i] = rayimbek[i].str.replace(')', '')
    rayimbek[i] = rayimbek[i].str.replace(' ', '')
    rayimbek[i] = rayimbek[i].str.replace('\xa0', '')
    rayimbek[i] = rayimbek[i].astype(float)

rayimbek = pd.melt(rayimbek, id_vars=['Indicator'], var_name='year', value_name='value')
rayimbek = rayimbek.pivot(index='year', columns='Indicator', values='value').reset_index()
rayimbek.insert(0, 'rayon', 'Rayimbek')
rayimbek.columns.name = None

for i in [2018, 2019, 2020, 2021, 2022, 2023]:
    rayimbek.loc[rayimbek['year'] == i, 'agriculture'] = float(rayimbek.loc[rayimbek['year'] == i, 'agriculture']) + float(kegen.loc[kegen['year'] == i, 'agriculture'])
    rayimbek.loc[rayimbek['year'] == i, 'production'] = float(rayimbek.loc[rayimbek['year'] == i, 'production']) + float(kegen.loc[kegen['year'] == i, 'production'])
    rayimbek.loc[rayimbek['year'] == i, 'retail'] = float(rayimbek.loc[rayimbek['year'] == i, 'retail']) + float(kegen.loc[kegen['year'] == i, 'retail'])

/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/24224223.py:22: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'agriculture'] = float(rayimbek.loc[rayimbek['year'] == i, 'agriculture']) + float(kegen.loc[kegen['year'] == i, 'agriculture'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/24224223.py:23: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'production'] = float(rayimbek.loc[rayimbek['year'] == i, 'production']) + float(kegen.loc[kegen['year'] == i, 'production'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/24224223.py:24: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'retail'] = float(rayimbek.loc[rayimbek['year'] == i, 'retail']) + float(kegen.loc[kegen['year'] == i, 'retail'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/24224223.py:22: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'agriculture'] = float(rayimbek.loc[rayimbek['year'] == i, 'agriculture']) + float(kegen.loc[kegen['year'] == i, 'agriculture'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/24224223.py:23: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'production'] = float(rayimbek.loc[rayimbek['year'] == i, 'production']) + float(kegen.loc[kegen['year'] == i, 'production'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/24224223.py:24: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'retail'] = float(rayimbek.loc[rayimbek['year'] == i, 'retail']) + float(kegen.loc[kegen['year'] == i, 'retail'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/24224223.py:22: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'agriculture'] = float(rayimbek.loc[rayimbek['year'] == i, 'agriculture']) + float(kegen.loc[kegen['year'] == i, 'agriculture'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/24224223.py:23: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'production'] = float(rayimbek.loc[rayimbek['year'] == i, 'production']) + float(kegen.loc[kegen['year'] == i, 'production'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/24224223.py:24: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'retail'] = float(rayimbek.loc[rayimbek['year'] == i, 'retail']) + float(kegen.loc[kegen['year'] == i, 'retail'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/24224223.py:22: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'agriculture'] = float(rayimbek.loc[rayimbek['year'] == i, 'agriculture']) + float(kegen.loc[kegen['year'] == i, 'agriculture'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/24224223.py:23: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'production'] = float(rayimbek.loc[rayimbek['year'] == i, 'production']) + float(kegen.loc[kegen['year'] == i, 'production'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/24224223.py:24: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'retail'] = float(rayimbek.loc[rayimbek['year'] == i, 'retail']) + float(kegen.loc[kegen['year'] == i, 'retail'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/24224223.py:22: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'agriculture'] = float(rayimbek.loc[rayimbek['year'] == i, 'agriculture']) + float(kegen.loc[kegen['year'] == i, 'agriculture'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/24224223.py:23: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'production'] = float(rayimbek.loc[rayimbek['year'] == i, 'production']) + float(kegen.loc[kegen['year'] == i, 'production'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/24224223.py:24: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'retail'] = float(rayimbek.loc[rayimbek['year'] == i, 'retail']) + float(kegen.loc[kegen['year'] == i, 'retail'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/24224223.py:22: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'agriculture'] = float(rayimbek.loc[rayimbek['year'] == i, 'agriculture']) + float(kegen.loc[kegen['year'] == i, 'agriculture'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/24224223.py:23: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'production'] = float(rayimbek.loc[rayimbek['year'] == i, 'production']) + float(kegen.loc[kegen['year'] == i, 'production'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/24224223.py:24: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'retail'] = float(rayimbek.loc[rayimbek['year'] == i, 'retail']) + float(kegen.loc[kegen['year'] == i, 'retail'])

In [159]:
talgar = pd.read_excel(Path("../Data/Controls/Almaty_All.xls"), sheet_name="Талгарский", header=3, usecols='B, AB:AI', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

talgar.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
talgar = talgar.loc[[56, 77, 125]].reset_index(drop=True)

talgar['Indicator'] = ['agriculture', 'production', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    talgar[i] = talgar[i].astype(str)
    talgar[i] = talgar[i].str.replace(',', '.')
    talgar[i] = talgar[i].str.replace(')', '')
    talgar[i] = talgar[i].str.replace(' ', '')
    talgar[i] = talgar[i].str.replace('\xa0', '')
    talgar[i] = talgar[i].astype(float)

talgar = pd.melt(talgar, id_vars=['Indicator'], var_name='year', value_name='value')
talgar = talgar.pivot(index='year', columns='Indicator', values='value').reset_index()
talgar.insert(0, 'rayon', 'Talgar')
talgar.columns.name = None

In [160]:
uyghur = pd.read_excel(Path("../Data/Controls/Almaty_All.xls"), sheet_name="Уйгурский", header=3, usecols='B, AB:AI', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

uyghur.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
uyghur = uyghur.loc[[56, 77, 125]].reset_index(drop=True)

uyghur['Indicator'] = ['agriculture', 'production', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    uyghur[i] = uyghur[i].astype(str)
    uyghur[i] = uyghur[i].str.replace(',', '.')
    uyghur[i] = uyghur[i].str.replace(')', '')
    uyghur[i] = uyghur[i].str.replace(' ', '')
    uyghur[i] = uyghur[i].str.replace('\xa0', '')
    uyghur[i] = uyghur[i].astype(float)

uyghur = pd.melt(uyghur, id_vars=['Indicator'], var_name='year', value_name='value')
uyghur = uyghur.pivot(index='year', columns='Indicator', values='value').reset_index()
uyghur.insert(0, 'rayon', 'Uyghur')
uyghur.columns.name = None

In [161]:
ile = pd.read_excel(Path("../Data/Controls/Almaty_All.xls"), sheet_name="Илийский", header=3, usecols='B, AB:AI', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

ile.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
ile = ile.loc[[56, 77, 125]].reset_index(drop=True)

ile['Indicator'] = ['agriculture', 'production', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    ile[i] = ile[i].astype(str)
    ile[i] = ile[i].str.replace(',', '.')
    ile[i] = ile[i].str.replace(')', '')
    ile[i] = ile[i].str.replace(' ', '')
    ile[i] = ile[i].str.replace('\xa0', '')
    ile[i] = ile[i].astype(float)

ile = pd.melt(ile, id_vars=['Indicator'], var_name='year', value_name='value')
ile = ile.pivot(index='year', columns='Indicator', values='value').reset_index()
ile.insert(0, 'rayon', 'Ile')
ile.columns.name = None

In [162]:
almaty_controls = pd.concat([taldykorgan, tekeli, aksu, alakol, kerbulak, koksu, karatal, panfilov, sarkan, yeskeldi, konayev, balkhash, enbekshikazak, zhambyl, karasay, rayimbek, talgar, uyghur, ile], ignore_index=True)
almaty_controls

                rayon  year    agriculture  production    retail
0    Taldykorgan_city  2022        25868.4      125703  111957.2
1    Taldykorgan_city  2023        28315.5    139586.1    121794
2    Taldykorgan_city  2024      31986.418  166554.818  137325.6
3         Tekeli_city  2022         5460.2     29201.3    8447.9
4         Tekeli_city  2023         9566.4     36590.9    8914.7
..                ...   ...            ...         ...       ...
97                Ile  2019   78623.591785    323504.0   75497.1
98                Ile  2020        89322.3    482686.5   80413.3
99                Ile  2021        94182.9    537141.9   86168.0
100               Ile  2022       108355.9    712553.7  100200.5
101               Ile  2023  125078.501027    717105.0  106412.0

[102 rows x 5 columns]

## PPI

In [163]:
almaty_ppi = pd.read_excel(Path("../Data/PPI/Almaty.xls"), header=5, usecols='Z:AF', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

almaty_ppi.columns = [2016, 2017, 2018, 2019, 2020, 2021, 2022]

rayons = list(almaty_inv['rayon'].unique())

dfs = []

for rayon in rayons:
    df_temp = pd.DataFrame({
        'rayon': rayon,
        'year': range(2016, 2023),
        'ppi': almaty_ppi.values[0]
    })
    dfs.append(df_temp)

almaty_ppi = pd.concat(dfs, ignore_index=True)

almaty_ppi

           rayon  year    ppi
0           Aksu  2016  111.4
1           Aksu  2017  104.6
2           Aksu  2018  107.2
3           Aksu  2019  105.9
4           Aksu  2020  105.4
..           ...   ...    ...
135  Alatau_city  2018  107.2
136  Alatau_city  2019  105.9
137  Alatau_city  2020  105.4
138  Alatau_city  2021  107.5
139  Alatau_city  2022  115.0

[140 rows x 3 columns]

## Combine together

In [164]:
dfs = [almaty_inv, almaty_empl, almaty_controls, almaty_ppi]

almaty_merged = reduce(lambda left, right: pd.merge(left, right, on=['rayon', 'year'], how='outer'), dfs)

almaty_merged

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year,employment,agriculture,production,retail,ppi
0,Aksu,1960440.0,21135.0,21135,338507.0,Almaty,2016,18.9,NaN,NaN,NaN,111.4
1,Aksu,3776354.0,13403.0,544,1379173.0,Almaty,2017,18.9,NaN,NaN,NaN,104.6
2,Aksu,9926249.0,2228.0,2228,1261975.0,Almaty,2018,18.1,NaN,NaN,NaN,107.2
3,Aksu,12974898.0,115616.0,115616,7185253.0,Almaty,2019,18.1,NaN,NaN,NaN,105.9
4,Aksu,14688817.0,1169390.0,1169390,7579270.0,Almaty,2020,17.4,NaN,NaN,NaN,105.4
...,...,...,...,...,...,...,...,...,...,...,...,...
174,Zhambyl,20079790.0,4594545.0,1294715,9991101.0,Almaty,2020,81.3,63252.2,20051.6,15585.7,105.4
175,Zhambyl,21363798.0,5167718.0,4683327,12520896,Almaty,2021,81.1,65931.7,22136.3,16729.2,107.5
176,Zhambyl,31782899.0,5970398.0,5970398.0,10750287.0,Almaty,2022,78.1,80803.2,23505.1,16163.1,115.0
177,Zhambyl,30223976.0,15128599.0,15128599.0,15104859.0,Almaty,2023,78.4,80627.025943,21456.4,23717.5,NaN
178,Zhambyl,53175462.0,59797102.0,59797102.0,23714834.0,Almaty,2024,NaN,NaN,NaN,NaN,NaN

# Karagandy oblast and Ulytau oblast

## Investments

### 2022-2024

In [165]:
ulytau_all_2022 = pd.read_excel(Path("../Data/Investments/Ulytau/2022_Investments.xls"), sheet_name='13', header=4, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
ulytau_all_2023 = pd.read_excel(Path("../Data/Investments/Ulytau/2023_Investments.xlsx"), sheet_name='19', header=3, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
ulytau_all_2024 = pd.read_excel(Path("../Data/Investments/Ulytau/2024_Investments.xlsx"), sheet_name='16', header=3, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

ulytau_non_2022 = pd.read_excel(Path("../Data/Investments/Ulytau/2022_Investments.xls"), sheet_name='14', header=4, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
ulytau_non_2023 = pd.read_excel(Path("../Data/Investments/Ulytau/2023_Investments.xlsx"), sheet_name='20', header=3, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
ulytau_non_2024 = pd.read_excel(Path("../Data/Investments/Ulytau/2024_Investments.xlsx"), sheet_name='17', header=3, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [166]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [ulytau_all_2022, ulytau_all_2023, ulytau_all_2024]:
    df.columns = all_columns
    df.drop(3, inplace=True)
    df.reset_index(drop=True, inplace=True)

for df in [ulytau_non_2022, ulytau_non_2023, ulytau_non_2024]:
    df.columns = non_columns
    df.drop(3, inplace=True)
    df.reset_index(drop=True, inplace=True)
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

rayon_names = ['Zhezkazgan_city', 'Karazhal_city', 'Satpayev_city', 'Zhanaarka', 'Ulytau']

for df in [ulytau_all_2022, ulytau_all_2023, ulytau_all_2024, ulytau_non_2022, ulytau_non_2023, ulytau_non_2024]:
    df['rayon'] = rayon_names

ulytau_2022 = ulytau_all_2022.merge(ulytau_non_2022, on='rayon')
ulytau_2023 = ulytau_all_2023.merge(ulytau_non_2023, on='rayon')
ulytau_2024 = ulytau_all_2024.merge(ulytau_non_2024, on='rayon')

dfs = [ulytau_2022, ulytau_2023, ulytau_2024]

for i in range(3):
    df = dfs[i]
    df['oblast'] = 'Karagandy'
    if i == 0:
        df['year'] = 2022
    elif i == 1:
        df['year'] = 2023
    else:
        df['year'] = 2024

In [167]:
ulytau_2022

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year
0,Zhezkazgan_city,33633647.0,9521918.0,9521918.0,24556304.0,Karagandy,2022
1,Karazhal_city,0.0,0.0,0.0,1108912.0,Karagandy,2022
2,Satpayev_city,48045657.0,2323675.0,2323675.0,44168892.0,Karagandy,2022
3,Zhanaarka,26563453.0,486362.0,0.0,23294146.0,Karagandy,2022
4,Ulytau,0.0,0.0,0.0,4970789.0,Karagandy,2022

In [168]:
karagandy_all_2022 = pd.read_excel(Path("../Data/Investments/Karagandy/2022_Investments.xls"), sheet_name='13', header=4, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
karagandy_all_2023 = pd.read_excel(Path("../Data/Investments/Karagandy/2023_Investments.xls"), sheet_name='19', header=3, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
karagandy_all_2024 = pd.read_excel(Path("../Data/Investments/Karagandy/2024_Investments.xls"), sheet_name='14', header=3, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

karagandy_non_2022 = pd.read_excel(Path("../Data/Investments/Karagandy/2022_Investments.xls"), sheet_name='14', header=4, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
karagandy_non_2023 = pd.read_excel(Path("../Data/Investments/Karagandy/2023_Investments.xls"), sheet_name='20', header=3, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
karagandy_non_2024 = pd.read_excel(Path("../Data/Investments/Karagandy/2024_Investments.xls"), sheet_name='15', header=3, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [169]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [karagandy_all_2022, karagandy_all_2023, karagandy_all_2024]:
    df.columns = all_columns
    df.drop(6, inplace=True)
    df.reset_index(drop=True, inplace=True)

for df in [karagandy_non_2022, karagandy_non_2023, karagandy_non_2024]:
    df.columns = non_columns
    df.drop(6, inplace=True)
    df.reset_index(drop=True, inplace=True)
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

rayon_names = ['Karagandy_city', 'Balkhash_city', 'Priozersk_city', 'Saran_city', 'Temirtau_city', 'Shakhtinsk_city', 'Abay', 'Aktogay', 'Bukhar_zhyrau', 'Karkaraly', 'Nura', 'Osakarov', 'Shet']

dfs = [karagandy_all_2022, karagandy_all_2023, karagandy_all_2024, karagandy_non_2022, karagandy_non_2023, karagandy_non_2024]

for i in range(6):
    df = dfs[i]
    df['rayon'] = rayon_names

kar_2022 = karagandy_all_2022.merge(karagandy_non_2022, on='rayon')
kar_2023 = karagandy_all_2023.merge(karagandy_non_2023, on='rayon')
kar_2024 = karagandy_all_2024.merge(karagandy_non_2024, on='rayon')

dfs = [kar_2022, kar_2023, kar_2024]

for i in range(3):
    df = dfs[i]
    df['oblast'] = 'Karagandy'
    if i == 0:
        df['year'] = 2022
    elif i == 1:
        df['year'] = 2023
    else:
        df['year'] = 2024

karagandy_2022 = pd.concat([ulytau_2022, kar_2022], ignore_index=True)
karagandy_2023 = pd.concat([ulytau_2023, kar_2023], ignore_index=True)
karagandy_2024 = pd.concat([ulytau_2024, kar_2024], ignore_index=True)

### 2014-2021

In [170]:
kar_all_2014 = camelot.read_pdf(Path("../Data/Investments/Karagandy/2014_Investments.pdf"), pages='22', flavor='stream')[0].df

Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)
Ignoring wrong pointing object 27 0 (offset 0)
Ignoring wrong pointing object 29 0 (offset 0)
Ignoring wrong pointing object 31 0 (offset 0)
Ignoring wrong pointing object 33 0 (offset 0)
Ignoring wrong pointing object 35 0 (offset 0)
Ignoring wrong pointing object 37 0 (offset 0)
Ignoring wrong pointing object 52 0 (offset 0)
Ignoring wrong pointing object 94 0 (offset 0)
Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)
Ignoring wrong pointing object 27 0 (offset 0)
Ignoring wrong pointing object 29 0 (offset 0)
Ignoring wrong pointing object 31 0 (offset 0)
Ignoring wrong pointing object 33 0 (offset 0)
Ignoring wrong pointing object 35 0 (offset 0)
Ignoring wrong pointing object 37 0 (offset 0)
Ignoring wrong pointing object 52 0 (offset 0)
Ignoring wrong pointing object 94 0 (offset 0)

In [171]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']

rayons = ['Karagandy_city', 'Balkhash_city', 'Zhezkazgan_city', 'Karazhal_city', 'Priozersk_city', 'Saran_city', 'Satpayev_city', 'Temirtau_city', 'Shakhtinsk_city', 'Abay', 'Aktogay', 'Bukhar_zhyrau', 'Zhanaarka', 'Karkaraly', 'Nura', 'Osakarov', 'Ulytau', 'Shet']

kar_all_2014 = kar_all_2014[[0, 3, 5]]
kar_all_2014 = kar_all_2014.drop([0, 1, 2, 3, 4, 14]).reset_index(drop=True)
kar_all_2014.columns = all_columns
kar_all_2014['rayon'] = rayons
kar_all_2014['l_all_inv'] = kar_all_2014['l_all_inv'].str.replace(' ', '').astype(int)
kar_all_2014['f_all_inv'] = kar_all_2014['f_all_inv'].str.replace(' ', '').astype(int)


kar_all_2014['oblast'] = 'Karagandy'
kar_all_2014['year'] = 2014

In [172]:
kar_all_2015 = pd.read_excel(Path("../Data/Investments/Karagandy/2015_Investments/Internal_vs_external.xls"), header=6, usecols='A, C, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kar_nonextr_2015 = pd.read_excel(Path("../Data/Investments/Karagandy/2015_Investments/Greenfield_investments.xls"), header=7, usecols='A, B, C', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True).loc[:17]

kar_all_2016 = pd.read_excel(Path("../Data/Investments/Karagandy/2016_Investments/Internal_vs_external.xls"), header=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kar_nonextr_2016 = pd.read_excel(Path("../Data/Investments/Karagandy/2016_Investments/Greenfield_investments.xls"), header=7, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True).loc[:17]

kar_all_2017 = pd.read_excel(Path("../Data/Investments/Karagandy/2017_Investments/Internal_vs_external.xls"), header=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kar_nonextr_2017 = pd.read_excel(Path("../Data/Investments/Karagandy/2017_Investments/Greenfield_investments.xls"), header=7, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True).loc[:17]

kar_all_2018 = pd.read_excel(Path("../Data/Investments/Karagandy/2018_Investments/Internal_vs_external.xls"), header=5, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kar_nonextr_2018 = pd.read_excel(Path("../Data/Investments/Karagandy/2018_Investments/Greenfield_investments.xls"), header=5, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True).loc[:17]

kar_all_2019 = pd.read_excel(Path("../Data/Investments/Karagandy/2019_Investments.xls"), sheet_name='14', header=4, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kar_nonextr_2019 = pd.read_excel(Path("../Data/Investments/Karagandy/2019_Investments.xls"), sheet_name='15', header=4, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

kar_all_2020 = pd.read_excel(Path("../Data/Investments/Karagandy/2020_Investments.xls"), sheet_name='13', header=4, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kar_nonextr_2020 = pd.read_excel(Path("../Data/Investments/Karagandy/2020_Investments.xls"), sheet_name='14', header=4, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

kar_all_2021 = pd.read_excel(Path("../Data/Investments/Karagandy/2021_Investments.xls"), sheet_name='13', header=4, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kar_nonextr_2021 = pd.read_excel(Path("../Data/Investments/Karagandy/2021_Investments.xls"), sheet_name='14', header=4, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [173]:
rayons = ['Karagandy_city', 'Balkhash_city', 'Zhezkazgan_city', 'Karazhal_city', 'Priozersk_city', 'Saran_city', 'Satpayev_city', 'Temirtau_city', 'Shakhtinsk_city', 'Abay', 'Aktogay', 'Bukhar_zhyrau', 'Zhanaarka', 'Karkaraly', 'Nura', 'Osakarov', 'Ulytau', 'Shet']

all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']


dfs = [kar_all_2015, kar_all_2016, kar_all_2017, kar_all_2018, kar_all_2019, kar_all_2020, kar_all_2021]
for i in range(7):
    df = dfs[i]
    df.columns = all_columns
    if i in [4, 5, 6]:
        df.drop(9, inplace=True)
        df.reset_index(drop=True, inplace=True)
    df['rayon'] = rayons

dfs = [kar_nonextr_2015, kar_nonextr_2016, kar_nonextr_2017, kar_nonextr_2018, kar_nonextr_2019, kar_nonextr_2020, kar_nonextr_2021]
for i in range(7):
    df = dfs[i]
    df.columns = non_columns
    if i in [4, 5, 6]:
        df.drop(9, inplace=True)
        df.reset_index(drop=True, inplace=True)
    df['rayon'] = rayons
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

karagandy_2015 = kar_all_2015.merge(kar_nonextr_2015, on='rayon')
karagandy_2016 = kar_all_2016.merge(kar_nonextr_2016, on='rayon')
karagandy_2017 = kar_all_2017.merge(kar_nonextr_2017, on='rayon')
karagandy_2018 = kar_all_2018.merge(kar_nonextr_2018, on='rayon')
karagandy_2019 = kar_all_2019.merge(kar_nonextr_2019, on='rayon')
karagandy_2020 = kar_all_2020.merge(kar_nonextr_2020, on='rayon')
karagandy_2021 = kar_all_2021.merge(kar_nonextr_2021, on='rayon')


dfs = [karagandy_2015, karagandy_2016, karagandy_2017, karagandy_2018, karagandy_2019, karagandy_2020, karagandy_2021]

for i in range(7):
    df = dfs[i]
    df['oblast'] = 'Karagandy'
    if i == 0:
        df['year'] = 2015
    elif i == 1:
        df['year'] = 2016
    elif i == 2:
        df['year'] = 2017
    elif i == 3:
        df['year'] = 2018
    elif i == 4:
        df['year'] = 2019
    elif i == 5:
        df['year'] = 2020
    else:
        df['year'] = 2021


karagandy_inv = pd.concat([kar_all_2014, karagandy_2015, karagandy_2016, karagandy_2017, karagandy_2018, karagandy_2019, karagandy_2020, karagandy_2021, karagandy_2022, karagandy_2023, karagandy_2024], ignore_index=True)
karagandy_inv

,rayon,l_all_inv,f_all_inv,oblast,year,f_nonextr_inv,l_nonextr_inv
0,Karagandy_city,67334639.0,11449051.0,Karagandy,2014,NaN,NaN
1,Balkhash_city,8971021.0,6816891.0,Karagandy,2014,NaN,NaN
2,Zhezkazgan_city,7166840.0,7279427.0,Karagandy,2014,NaN,NaN
3,Karazhal_city,1682691.0,994012.0,Karagandy,2014,NaN,NaN
4,Priozersk_city,3819459.0,7868.0,Karagandy,2014,NaN,NaN
...,...,...,...,...,...,...,...
193,Bukhar_zhyrau,50799431.0,4792124.0,Karagandy,2024,4508362.0,34489110.0
194,Karkaraly,12985045.0,1017864.0,Karagandy,2024,0.0,4650333.0
195,Nura,19758381.0,10239926.0,Karagandy,2024,5711238.0,8227596.0
196,Osakarov,42533620.0,66777.0,Karagandy,2024,0.0,28827398.0
197,Shet,49674026.0,56926852.0,Karagandy,2024,48448374.0,29897416.0

## Employment

### 2022-2023

In [174]:
ulytau_empl = pd.read_excel(Path("../Data/Employment/Ulytau.xlsx"), skiprows=16, nrows=5, header=None, usecols='A:C')
kar_empl = pd.read_excel(Path("../Data/Employment/Karagandy.xls"), skiprows=30, nrows=18, header=None, usecols='A, J:K', na_values=['x', 'х', '-', '', ' ']).dropna().reset_index(drop=True)

In [175]:
ulytau_empl.columns = ['rayon', 2022, 2023]

rayons = ['Zhezkazgan_city', 'Karazhal_city', 'Satpayev_city', 'Zhanaarka', 'Ulytau']

ulytau_empl['rayon'] = rayons

ulytau_empl[2022] = ulytau_empl[2022].astype(float)
ulytau_empl[2023] = ulytau_empl[2023].astype(float)

kar_empl.columns = ['rayon', 2022, 2023]

rayons = ['Karagandy_city', 'Balkhash_city', 'Priozersk_city', 'Saran_city', 'Temirtau_city', 'Shakhtinsk_city', 'Abay', 'Aktogay', 'Bukhar_zhyrau', 'Karkaraly', 'Nura', 'Osakarov', 'Shet']

kar_empl['rayon'] = rayons

kar_empl[2022] = kar_empl[2022].astype(float)
kar_empl[2023] = kar_empl[2023].astype(float)

karagandy_empl = pd.concat([ulytau_empl, kar_empl], ignore_index=True)

kar_empl_22_23 = karagandy_empl.melt(id_vars='rayon', value_vars=[2022, 2023], var_name='year', value_name='employment')

### 2014-2021

In [176]:
kar_empl = pd.read_excel(Path("../Data/Employment/Karagandy.xls"), skiprows=30, nrows=18, header=None, usecols='A, B:I', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
kar_empl

                     0      1      2      3      4      5      6      7      8
0         Қарағанды қ.  243.5  253.9  239.0  228.9  228.7  222.6  227.8  222.5
1            Балқаш қ.   38.6   39.0   36.8   36.6   37.1   39.8   36.8   37.9
2         Жезқазған қ.   43.8   44.2   41.9   41.9   41.5   42.0   40.0   41.2
3           Қаражал қ.    8.5    7.6    7.6    7.4    8.8    8.6    9.0    8.4
4       Приозер қаласы    6.9    6.8    7.4    7.6    7.5    7.7    6.9    6.9
5             Саран қ.   24.4   25.9   24.8   24.7   24.5   24.1   25.2   24.7
6           Сәтбаев қ.   33.5   32.4   31.3   31.9   30.4   31.1   31.0   30.7
7          Теміртау қ.   90.8   98.2   90.0   91.0   91.6   93.8   93.6   91.5
8          Шахтинск қ.   28.1   29.2   22.9   24.3   25.0   24.1   23.6   24.5
9          Абай ауданы   26.2   25.9   26.5   28.8   29.0   30.9   27.6   32.1
10      Ақтоғай ауданы    7.3    9.4    9.5    8.9    8.3    8.2    7.6    8.1
11  Бұқар жырау ауданы   29.6   28.9   30.1   28.4   26.4   25.6   25.7   25.2
12     Жаңаарқа ауданы   15.8   14.6   12.7   16.9   19.9   15.3   14.0   17.4
13    Қарқаралы ауданы   20.2   20.7   19.9   22.4   22.6   22.0   19.6   20.5
14         Нұра ауданы   15.2   13.9   10.7   11.7   11.6   10.3   11.9   10.8
15     Осакаров ауданы   17.5   17.3   17.8   17.6   15.6   16.6   15.9   16.0
16       Ұлытау ауданы    7.5    7.6    7.6    6.3    6.3    6.1    6.5    6.3
17          Шет ауданы   21.0   19.1   19.9   17.1   19.4   19.8   19.3   18.8

In [177]:
kar_empl.columns = ['rayon', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]

rayons = ['Karagandy_city', 'Balkhash_city', 'Zhezkazgan_city', 'Karazhal_city', 'Priozersk_city', 'Saran_city', 'Satpayev_city', 'Temirtau_city', 'Shakhtinsk_city', 'Abay', 'Aktogay', 'Bukhar_zhyrau', 'Zhanaarka', 'Karkaraly', 'Nura', 'Osakarov', 'Ulytau', 'Shet']

kar_empl['rayon'] = rayons

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]:
    kar_empl[i] = kar_empl[i].astype(float)

kar_empl_14_21 = kar_empl.melt(id_vars='rayon', value_vars=[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021], var_name='year', value_name='employment')

karagandy_empl = pd.concat([kar_empl_14_21, kar_empl_22_23], ignore_index=True)
karagandy_empl

               rayon  year  employment
0     Karagandy_city  2014       243.5
1      Balkhash_city  2014        38.6
2    Zhezkazgan_city  2014        43.8
3      Karazhal_city  2014         8.5
4     Priozersk_city  2014         6.9
..               ...   ...         ...
175    Bukhar_zhyrau  2023        22.7
176        Karkaraly  2023        16.4
177             Nura  2023        11.7
178         Osakarov  2023        15.2
179             Shet  2023        18.1

[180 rows x 3 columns]

## Other controls

In [178]:
zhezkazgan = pd.read_excel(Path("../Data/Controls/Ulytau_All.xls"), sheet_name="г.а.Жезказган", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

zhezkazgan.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
zhezkazgan = zhezkazgan.loc[[71, 87, 140]].reset_index(drop=True)

zhezkazgan['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    zhezkazgan[i] = zhezkazgan[i].astype(str)
    zhezkazgan[i] = zhezkazgan[i].str.replace(',', '.')
    zhezkazgan[i] = zhezkazgan[i].str.replace(')', '')
    zhezkazgan[i] = zhezkazgan[i].str.replace(' ', '')
    zhezkazgan[i] = zhezkazgan[i].str.replace('\xa0', '')
    zhezkazgan[i] = zhezkazgan[i].astype(float)

zhezkazgan = pd.melt(zhezkazgan, id_vars=['Indicator'], var_name='year', value_name='value')
zhezkazgan = zhezkazgan.pivot(index='year', columns='Indicator', values='value').reset_index()
zhezkazgan.insert(0, 'rayon', 'Zhezkazgan_city')
zhezkazgan.columns.name = None

In [179]:
karazhal = pd.read_excel(Path("../Data/Controls/Ulytau_All.xls"), sheet_name="г.а.Каражал", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

karazhal.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
karazhal = karazhal.loc[[71, 87, 140]].reset_index(drop=True)

karazhal['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    karazhal[i] = karazhal[i].astype(str)
    karazhal[i] = karazhal[i].str.replace(',', '.')
    karazhal[i] = karazhal[i].str.replace(')', '')
    karazhal[i] = karazhal[i].str.replace(' ', '')
    karazhal[i] = karazhal[i].str.replace('\xa0', '')
    karazhal[i] = karazhal[i].str.replace('*', '')
    karazhal[i] = karazhal[i].astype(float)

karazhal = pd.melt(karazhal, id_vars=['Indicator'], var_name='year', value_name='value')
karazhal = karazhal.pivot(index='year', columns='Indicator', values='value').reset_index()
karazhal.insert(0, 'rayon', 'Karazhal_city')
karazhal.columns.name = None

In [180]:
karazhal_city = pd.read_excel(Path("../Data/Controls/Ulytau_All.xls"), sheet_name="г.Каражал", header=2, usecols='A, F:O', nrows=149, na_values=['x', 'х', '-', '', ' ', '...']).fillna(0)

karazhal_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
karazhal_city = karazhal_city.loc[[71, 87, 140]].reset_index(drop=True)

karazhal_city['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    karazhal_city[i] = karazhal_city[i].astype(str)
    karazhal_city[i] = karazhal_city[i].str.replace(',', '.')
    karazhal_city[i] = karazhal_city[i].str.replace(')', '')
    karazhal_city[i] = karazhal_city[i].str.replace(' ', '')
    karazhal_city[i] = karazhal_city[i].str.replace('\xa0', '')
    karazhal_city[i] = karazhal_city[i].str.replace('*', '')
    karazhal_city[i] = karazhal_city[i].astype(float)

karazhal_city = pd.melt(karazhal_city, id_vars=['Indicator'], var_name='year', value_name='value')
karazhal_city = karazhal_city.pivot(index='year', columns='Indicator', values='value').reset_index()
karazhal_city.insert(0, 'rayon', 'Karazhal_city')
karazhal_city.columns.name = None

karazhal[['agriculture', 'production', 'retail']] = karazhal[['agriculture', 'production', 'retail']] + karazhal_city[['agriculture', 'production', 'retail']]

In [181]:
satpayev = pd.read_excel(Path("../Data/Controls/Ulytau_All.xls"), sheet_name="г.а.Сатпаев", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

satpayev.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
satpayev = satpayev.loc[[71, 87, 140]].reset_index(drop=True)

satpayev['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    satpayev[i] = satpayev[i].astype(str)
    satpayev[i] = satpayev[i].str.replace(',', '.')
    satpayev[i] = satpayev[i].str.replace(')', '')
    satpayev[i] = satpayev[i].str.replace(' ', '')
    satpayev[i] = satpayev[i].str.replace('\xa0', '')
    satpayev[i] = satpayev[i].str.replace('*', '')
    satpayev[i] = satpayev[i].astype(float)

satpayev = pd.melt(satpayev, id_vars=['Indicator'], var_name='year', value_name='value')
satpayev = satpayev.pivot(index='year', columns='Indicator', values='value').reset_index()
satpayev.insert(0, 'rayon', 'Satpayev_city')
satpayev.columns.name = None

In [182]:
satpayev_city = pd.read_excel(Path("../Data/Controls/Ulytau_All.xls"), sheet_name="г.Сатпаев", header=2, usecols='A, F:O', nrows=149, na_values=['x', 'х', '-', '', ' ', '...']).fillna(0)

satpayev_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
satpayev_city = satpayev_city.loc[[71, 87, 140]].reset_index(drop=True)

satpayev_city['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    satpayev_city[i] = satpayev_city[i].astype(str)
    satpayev_city[i] = satpayev_city[i].str.replace(',', '.')
    satpayev_city[i] = satpayev_city[i].str.replace(')', '')
    satpayev_city[i] = satpayev_city[i].str.replace(' ', '')
    satpayev_city[i] = satpayev_city[i].str.replace('\xa0', '')
    satpayev_city[i] = satpayev_city[i].str.replace('*', '')
    satpayev_city[i] = satpayev_city[i].astype(float)

satpayev_city = pd.melt(satpayev_city, id_vars=['Indicator'], var_name='year', value_name='value')
satpayev_city = satpayev_city.pivot(index='year', columns='Indicator', values='value').reset_index()
satpayev_city.insert(0, 'rayon', 'Satpayev_city')
satpayev_city.columns.name = None

satpayev[['agriculture', 'production', 'retail']] = satpayev[['agriculture', 'production', 'retail']] + satpayev_city[['agriculture', 'production', 'retail']]

In [183]:
zhanaarka = pd.read_excel(Path("../Data/Controls/Ulytau_All.xls"), sheet_name="Жанааркинский район", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

zhanaarka.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
zhanaarka = zhanaarka.loc[[71, 87, 140]].reset_index(drop=True)

zhanaarka['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    zhanaarka[i] = zhanaarka[i].astype(str)
    zhanaarka[i] = zhanaarka[i].str.replace(',', '.')
    zhanaarka[i] = zhanaarka[i].str.replace(')', '')
    zhanaarka[i] = zhanaarka[i].str.replace(' ', '')
    zhanaarka[i] = zhanaarka[i].str.replace('\xa0', '')
    zhanaarka[i] = zhanaarka[i].str.replace('*', '')
    zhanaarka[i] = zhanaarka[i].astype(float)

zhanaarka = pd.melt(zhanaarka, id_vars=['Indicator'], var_name='year', value_name='value')
zhanaarka = zhanaarka.pivot(index='year', columns='Indicator', values='value').reset_index()
zhanaarka.insert(0, 'rayon', 'Zhanaarka')
zhanaarka.columns.name = None

In [184]:
ulytau = pd.read_excel(Path("../Data/Controls/Ulytau_All.xls"), sheet_name="Улытауский район", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

ulytau.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
ulytau = ulytau.loc[[71, 87, 140]].reset_index(drop=True)

ulytau['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    ulytau[i] = ulytau[i].astype(str)
    ulytau[i] = ulytau[i].str.replace(',', '.')
    ulytau[i] = ulytau[i].str.replace(')', '')
    ulytau[i] = ulytau[i].str.replace(' ', '')
    ulytau[i] = ulytau[i].str.replace('\xa0', '')
    ulytau[i] = ulytau[i].str.replace('*', '')
    ulytau[i] = ulytau[i].astype(float)

ulytau = pd.melt(ulytau, id_vars=['Indicator'], var_name='year', value_name='value')
ulytau = ulytau.pivot(index='year', columns='Indicator', values='value').reset_index()
ulytau.insert(0, 'rayon', 'Ulytau')
ulytau.columns.name = None

In [185]:
karagandy = pd.read_excel(Path("../Data/Controls/Karagandy_All.xls"), sheet_name="Караганда г.а.", header=2, usecols='A, Y:AI', nrows=148, na_values=['x', 'х', '-', '', ' ', '...'])

karagandy.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
karagandy = karagandy.loc[[70, 86, 139]].reset_index(drop=True)

karagandy['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    karagandy[i] = karagandy[i].astype(str)
    karagandy[i] = karagandy[i].str.replace(',', '.')
    karagandy[i] = karagandy[i].str.replace(')', '')
    karagandy[i] = karagandy[i].str.replace(' ', '')
    karagandy[i] = karagandy[i].str.replace('\xa0', '')
    karagandy[i] = karagandy[i].str.replace('*', '')
    karagandy[i] = karagandy[i].astype(float)

karagandy = pd.melt(karagandy, id_vars=['Indicator'], var_name='year', value_name='value')
karagandy = karagandy.pivot(index='year', columns='Indicator', values='value').reset_index()
karagandy.insert(0, 'rayon', 'Karagandy_city')
karagandy.columns.name = None

In [186]:
balkhash = pd.read_excel(Path("../Data/Controls/Karagandy_All.xls"), sheet_name="Балхаш г.а.", header=2, usecols='A, Y:AI', nrows=148, na_values=['x', 'х', '-', '', ' ', '...'])

balkhash.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
balkhash = balkhash.loc[[70, 86, 139]].reset_index(drop=True)

balkhash['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    balkhash[i] = balkhash[i].astype(str)
    balkhash[i] = balkhash[i].str.replace(',', '.')
    balkhash[i] = balkhash[i].str.replace(')', '')
    balkhash[i] = balkhash[i].str.replace(' ', '')
    balkhash[i] = balkhash[i].str.replace('\xa0', '')
    balkhash[i] = balkhash[i].str.replace('*', '')
    balkhash[i] = balkhash[i].astype(float)

balkhash = pd.melt(balkhash, id_vars=['Indicator'], var_name='year', value_name='value')
balkhash = balkhash.pivot(index='year', columns='Indicator', values='value').reset_index()
balkhash.insert(0, 'rayon', 'Balkhash_city')
balkhash.columns.name = None

In [187]:
balkhash_city = pd.read_excel(Path("../Data/Controls/Karagandy_All.xls"), sheet_name="Балхаш (моногород)", header=2, usecols='A, F:P', nrows=164, na_values=['x', 'х', '-', '-', '', ' ', '...']).fillna(0)

balkhash_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
balkhash_city = balkhash_city.loc[[87, 115, 161]].reset_index(drop=True)

balkhash_city['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    balkhash_city[i] = balkhash_city[i].astype(str)
    balkhash_city[i] = balkhash_city[i].str.replace(',', '.')
    balkhash_city[i] = balkhash_city[i].str.replace(')', '')
    balkhash_city[i] = balkhash_city[i].str.replace(' ', '')
    balkhash_city[i] = balkhash_city[i].str.replace('\xa0', '')
    balkhash_city[i] = balkhash_city[i].str.replace('*', '')
    balkhash_city[i] = balkhash_city[i].astype(float)

balkhash_city = pd.melt(balkhash_city, id_vars=['Indicator'], var_name='year', value_name='value')
balkhash_city = balkhash_city.pivot(index='year', columns='Indicator', values='value').reset_index()
balkhash_city.insert(0, 'rayon', 'Balkhash_city')
balkhash_city.columns.name = None

balkhash[['agriculture', 'production', 'retail']] = balkhash[['agriculture', 'production', 'retail']] + balkhash_city[['agriculture', 'production', 'retail']]

In [188]:
priozersk = pd.read_excel(Path("../Data/Controls/Karagandy_All.xls"), sheet_name="г. Приозерск", header=2, usecols='A, Y:AI', nrows=148, na_values=['x', 'х', '-', '', ' ', '...'])

priozersk.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
priozersk = priozersk.loc[[70, 86, 139]].reset_index(drop=True)

priozersk['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    priozersk[i] = priozersk[i].astype(str)
    priozersk[i] = priozersk[i].str.replace(',', '.')
    priozersk[i] = priozersk[i].str.replace(')', '')
    priozersk[i] = priozersk[i].str.replace(' ', '')
    priozersk[i] = priozersk[i].str.replace('\xa0', '')
    priozersk[i] = priozersk[i].str.replace('*', '')
    priozersk[i] = priozersk[i].astype(float)

priozersk = pd.melt(priozersk, id_vars=['Indicator'], var_name='year', value_name='value')
priozersk = priozersk.pivot(index='year', columns='Indicator', values='value').reset_index()
priozersk.insert(0, 'rayon', 'Priozersk_city')
priozersk.columns.name = None

In [189]:
saran = pd.read_excel(Path("../Data/Controls/Karagandy_All.xls"), sheet_name="Сарань г.а.", header=2, usecols='A, Y:AI', nrows=148, na_values=['x', 'х', '-', '', ' ', '...'])

saran.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
saran = saran.loc[[70, 86, 139]].reset_index(drop=True)

saran['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    saran[i] = saran[i].astype(str)
    saran[i] = saran[i].str.replace(',', '.')
    saran[i] = saran[i].str.replace(')', '')
    saran[i] = saran[i].str.replace(' ', '')
    saran[i] = saran[i].str.replace('\xa0', '')
    saran[i] = saran[i].str.replace('*', '')
    saran[i] = saran[i].astype(float)

saran = pd.melt(saran, id_vars=['Indicator'], var_name='year', value_name='value')
saran = saran.pivot(index='year', columns='Indicator', values='value').reset_index()
saran.insert(0, 'rayon', 'Saran_city')
saran.columns.name = None

In [190]:
temirtau = pd.read_excel(Path("../Data/Controls/Karagandy_All.xls"), sheet_name="Темиртау г.а.", header=2, usecols='A, Y:AI', nrows=148, na_values=['x', 'х', '-', '', ' ', '...'])

temirtau.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
temirtau = temirtau.loc[[70, 86, 139]].reset_index(drop=True)

temirtau['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    temirtau[i] = temirtau[i].astype(str)
    temirtau[i] = temirtau[i].str.replace(',', '.')
    temirtau[i] = temirtau[i].str.replace(')', '')
    temirtau[i] = temirtau[i].str.replace(' ', '')
    temirtau[i] = temirtau[i].str.replace('\xa0', '')
    temirtau[i] = temirtau[i].str.replace('*', '')
    temirtau[i] = temirtau[i].astype(float)

temirtau = pd.melt(temirtau, id_vars=['Indicator'], var_name='year', value_name='value')
temirtau = temirtau.pivot(index='year', columns='Indicator', values='value').reset_index()
temirtau.insert(0, 'rayon', 'Temirtau_city')
temirtau.columns.name = None

In [191]:
temirtau_city = pd.read_excel(Path("../Data/Controls/Karagandy_All.xls"), sheet_name="Темиртау (моногород)", header=2, usecols='A, F:P', nrows=164, na_values=['x', 'х', '-', '-', '', ' ', '...']).fillna(0)

temirtau_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
temirtau_city = temirtau_city.loc[[87, 115, 161]].reset_index(drop=True)

temirtau_city['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    temirtau_city[i] = temirtau_city[i].astype(str)
    temirtau_city[i] = temirtau_city[i].str.replace(',', '.')
    temirtau_city[i] = temirtau_city[i].str.replace(')', '')
    temirtau_city[i] = temirtau_city[i].str.replace(' ', '')
    temirtau_city[i] = temirtau_city[i].str.replace('\xa0', '')
    temirtau_city[i] = temirtau_city[i].str.replace('*', '')
    temirtau_city[i] = temirtau_city[i].astype(float)

temirtau_city = pd.melt(temirtau_city, id_vars=['Indicator'], var_name='year', value_name='value')
temirtau_city = temirtau_city.pivot(index='year', columns='Indicator', values='value').reset_index()
temirtau_city.insert(0, 'rayon', 'Temirtau_city')
temirtau_city.columns.name = None

temirtau[['agriculture', 'production', 'retail']] = temirtau[['agriculture', 'production', 'retail']] + temirtau_city[['agriculture', 'production', 'retail']]

In [192]:
shakhtinsk = pd.read_excel(Path("../Data/Controls/Karagandy_All.xls"), sheet_name="Шахтинск г.а.", header=2, usecols='A, Y:AI', nrows=148, na_values=['x', 'х', '-', '', ' ', '...'])

shakhtinsk.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
shakhtinsk = shakhtinsk.loc[[70, 86, 139]].reset_index(drop=True)

shakhtinsk['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    shakhtinsk[i] = shakhtinsk[i].astype(str)
    shakhtinsk[i] = shakhtinsk[i].str.replace(',', '.')
    shakhtinsk[i] = shakhtinsk[i].str.replace(')', '')
    shakhtinsk[i] = shakhtinsk[i].str.replace(' ', '')
    shakhtinsk[i] = shakhtinsk[i].str.replace('\xa0', '')
    shakhtinsk[i] = shakhtinsk[i].str.replace('*', '')
    shakhtinsk[i] = shakhtinsk[i].astype(float)

shakhtinsk = pd.melt(shakhtinsk, id_vars=['Indicator'], var_name='year', value_name='value')
shakhtinsk = shakhtinsk.pivot(index='year', columns='Indicator', values='value').reset_index()
shakhtinsk.insert(0, 'rayon', 'Shakhtinsk_city')
shakhtinsk.columns.name = None

In [193]:
shakhtinsk_city = pd.read_excel(Path("../Data/Controls/Karagandy_All.xls"), sheet_name="Шахтинск (моногород)", header=2, usecols='A, F:P', nrows=164, na_values=['x', 'х', '-', '…', '', ' ', '...']).fillna(0)

shakhtinsk_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
shakhtinsk_city = shakhtinsk_city.loc[[88, 116, 162]].reset_index(drop=True)

shakhtinsk_city['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    shakhtinsk_city[i] = shakhtinsk_city[i].astype(str)
    shakhtinsk_city[i] = shakhtinsk_city[i].str.replace(',', '.')
    shakhtinsk_city[i] = shakhtinsk_city[i].str.replace(')', '')
    shakhtinsk_city[i] = shakhtinsk_city[i].str.replace(' ', '')
    shakhtinsk_city[i] = shakhtinsk_city[i].str.replace('\xa0', '')
    shakhtinsk_city[i] = shakhtinsk_city[i].str.replace('*', '')
    shakhtinsk_city[i] = shakhtinsk_city[i].astype(float)

shakhtinsk_city = pd.melt(shakhtinsk_city, id_vars=['Indicator'], var_name='year', value_name='value')
shakhtinsk_city = shakhtinsk_city.pivot(index='year', columns='Indicator', values='value').reset_index()
shakhtinsk_city.insert(0, 'rayon', 'Shakhtinsk_city')
shakhtinsk_city.columns.name = None

shakhtinsk[['agriculture', 'production', 'retail']] = shakhtinsk[['agriculture', 'production', 'retail']] + shakhtinsk_city[['agriculture', 'production', 'retail']]

In [194]:
abay = pd.read_excel(Path("../Data/Controls/Karagandy_All.xls"), sheet_name="Абайский", header=2, usecols='A, Y:AI', nrows=148, na_values=['x', 'х', '-', '', ' ', '...'])

abay.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
abay = abay.loc[[70, 86, 139]].reset_index(drop=True)

abay['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    abay[i] = abay[i].astype(str)
    abay[i] = abay[i].str.replace(',', '.')
    abay[i] = abay[i].str.replace(')', '')
    abay[i] = abay[i].str.replace(' ', '')
    abay[i] = abay[i].str.replace('\xa0', '')
    abay[i] = abay[i].str.replace('*', '')
    abay[i] = abay[i].astype(float)

abay = pd.melt(abay, id_vars=['Indicator'], var_name='year', value_name='value')
abay = abay.pivot(index='year', columns='Indicator', values='value').reset_index()
abay.insert(0, 'rayon', 'Abay')
abay.columns.name = None

In [195]:
abay_city = pd.read_excel(Path("../Data/Controls/Karagandy_All.xls"), sheet_name="Абай (моногород)", header=2, usecols='A, F:P', nrows=164, na_values=['x', 'х', '-', '-', '', ' ', '...']).fillna(0)

abay_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
abay_city = abay_city.loc[[87, 115, 161]].reset_index(drop=True)

abay_city['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    abay_city[i] = abay_city[i].astype(str)
    abay_city[i] = abay_city[i].str.replace(',', '.')
    abay_city[i] = abay_city[i].str.replace(')', '')
    abay_city[i] = abay_city[i].str.replace(' ', '')
    abay_city[i] = abay_city[i].str.replace('\xa0', '')
    abay_city[i] = abay_city[i].str.replace('*', '')
    abay_city[i] = abay_city[i].astype(float)

abay_city = pd.melt(abay_city, id_vars=['Indicator'], var_name='year', value_name='value')
abay_city = abay_city.pivot(index='year', columns='Indicator', values='value').reset_index()
abay_city.insert(0, 'rayon', 'Abay')
abay_city.columns.name = None

abay[['agriculture', 'production', 'retail']] = abay[['agriculture', 'production', 'retail']] + abay_city[['agriculture', 'production', 'retail']]

In [196]:
aktogay = pd.read_excel(Path("../Data/Controls/Karagandy_All.xls"), sheet_name="Актогайский", header=2, usecols='A, Y:AI', nrows=148, na_values=['x', 'х', '-', '', ' ', '...'])

aktogay.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
aktogay = aktogay.loc[[70, 86, 139]].reset_index(drop=True)

aktogay['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    aktogay[i] = aktogay[i].astype(str)
    aktogay[i] = aktogay[i].str.replace(',', '.')
    aktogay[i] = aktogay[i].str.replace(')', '')
    aktogay[i] = aktogay[i].str.replace(' ', '')
    aktogay[i] = aktogay[i].str.replace('\xa0', '')
    aktogay[i] = aktogay[i].str.replace('*', '')
    aktogay[i] = aktogay[i].astype(float)

aktogay = pd.melt(aktogay, id_vars=['Indicator'], var_name='year', value_name='value')
aktogay = aktogay.pivot(index='year', columns='Indicator', values='value').reset_index()
aktogay.insert(0, 'rayon', 'Aktogay')
aktogay.columns.name = None

In [197]:
bukhar_zhyrau = pd.read_excel(Path("../Data/Controls/Karagandy_All.xls"), sheet_name="Бухар-Жырауский", header=2, usecols='A, Y:AI', nrows=148, na_values=['x', 'х', '-', '', ' ', '...'])

bukhar_zhyrau.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
bukhar_zhyrau = bukhar_zhyrau.loc[[70, 86, 139]].reset_index(drop=True)

bukhar_zhyrau['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    bukhar_zhyrau[i] = bukhar_zhyrau[i].astype(str)
    bukhar_zhyrau[i] = bukhar_zhyrau[i].str.replace(',', '.')
    bukhar_zhyrau[i] = bukhar_zhyrau[i].str.replace(')', '')
    bukhar_zhyrau[i] = bukhar_zhyrau[i].str.replace(' ', '')
    bukhar_zhyrau[i] = bukhar_zhyrau[i].str.replace('\xa0', '')
    bukhar_zhyrau[i] = bukhar_zhyrau[i].str.replace('*', '')
    bukhar_zhyrau[i] = bukhar_zhyrau[i].astype(float)

bukhar_zhyrau = pd.melt(bukhar_zhyrau, id_vars=['Indicator'], var_name='year', value_name='value')
bukhar_zhyrau = bukhar_zhyrau.pivot(index='year', columns='Indicator', values='value').reset_index()
bukhar_zhyrau.insert(0, 'rayon', 'Bukhar_zhyrau')
bukhar_zhyrau.columns.name = None

In [198]:
karkaraly = pd.read_excel(Path("../Data/Controls/Karagandy_All.xls"), sheet_name="Каркаралинский", header=2, usecols='A, Y:AI', nrows=148, na_values=['x', 'х', '-', '', ' ', '...'])

karkaraly.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
karkaraly = karkaraly.loc[[70, 86, 139]].reset_index(drop=True)

karkaraly['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    karkaraly[i] = karkaraly[i].astype(str)
    karkaraly[i] = karkaraly[i].str.replace(',', '.')
    karkaraly[i] = karkaraly[i].str.replace(')', '')
    karkaraly[i] = karkaraly[i].str.replace(' ', '')
    karkaraly[i] = karkaraly[i].str.replace('\xa0', '')
    karkaraly[i] = karkaraly[i].str.replace('*', '')
    karkaraly[i] = karkaraly[i].astype(float)

karkaraly = pd.melt(karkaraly, id_vars=['Indicator'], var_name='year', value_name='value')
karkaraly = karkaraly.pivot(index='year', columns='Indicator', values='value').reset_index()
karkaraly.insert(0, 'rayon', 'Karkaraly')
karkaraly.columns.name = None

In [199]:
nura = pd.read_excel(Path("../Data/Controls/Karagandy_All.xls"), sheet_name="Нуринский", header=2, usecols='A, Y:AI', nrows=148, na_values=['x', 'х', '-', '', ' ', '...'])

nura.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
nura = nura.loc[[70, 86, 139]].reset_index(drop=True)

nura['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    nura[i] = nura[i].astype(str)
    nura[i] = nura[i].str.replace(',', '.')
    nura[i] = nura[i].str.replace(')', '')
    nura[i] = nura[i].str.replace(' ', '')
    nura[i] = nura[i].str.replace('\xa0', '')
    nura[i] = nura[i].str.replace('*', '')
    nura[i] = nura[i].astype(float)

nura = pd.melt(nura, id_vars=['Indicator'], var_name='year', value_name='value')
nura = nura.pivot(index='year', columns='Indicator', values='value').reset_index()
nura.insert(0, 'rayon', 'Nura')
nura.columns.name = None

In [200]:
osakarov = pd.read_excel(Path("../Data/Controls/Karagandy_All.xls"), sheet_name="Осакаровский", header=2, usecols='A, Y:AI', nrows=148, na_values=['x', 'х', '-', '', ' ', '...'])

osakarov.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
osakarov = osakarov.loc[[70, 86, 139]].reset_index(drop=True)

osakarov['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    osakarov[i] = osakarov[i].astype(str)
    osakarov[i] = osakarov[i].str.replace(',', '.')
    osakarov[i] = osakarov[i].str.replace(')', '')
    osakarov[i] = osakarov[i].str.replace(' ', '')
    osakarov[i] = osakarov[i].str.replace('\xa0', '')
    osakarov[i] = osakarov[i].str.replace('*', '')
    osakarov[i] = osakarov[i].astype(float)

osakarov = pd.melt(osakarov, id_vars=['Indicator'], var_name='year', value_name='value')
osakarov = osakarov.pivot(index='year', columns='Indicator', values='value').reset_index()
osakarov.insert(0, 'rayon', 'Osakarov')
osakarov.columns.name = None

In [201]:
shet = pd.read_excel(Path("../Data/Controls/Karagandy_All.xls"), sheet_name="Шетский", header=2, usecols='A, Y:AI', nrows=148, na_values=['x', 'х', '-', '', ' ', '...'])

shet.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
shet = shet.loc[[70, 86, 139]].reset_index(drop=True)

shet['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    shet[i] = shet[i].astype(str)
    shet[i] = shet[i].str.replace(',', '.')
    shet[i] = shet[i].str.replace(')', '')
    shet[i] = shet[i].str.replace(' ', '')
    shet[i] = shet[i].str.replace('\xa0', '')
    shet[i] = shet[i].str.replace('*', '')
    shet[i] = shet[i].astype(float)

shet = pd.melt(shet, id_vars=['Indicator'], var_name='year', value_name='value')
shet = shet.pivot(index='year', columns='Indicator', values='value').reset_index()
shet.insert(0, 'rayon', 'Shet')
shet.columns.name = None

In [202]:
shet

   rayon  year   agriculture  production  retail
0   Shet  2014  20289.800000   27260.624  1365.8
1   Shet  2015  23068.600000   21633.000  1421.7
2   Shet  2016  27062.600000   31692.600  1682.5
3   Shet  2017  29880.600000   47669.568  1871.9
4   Shet  2018  33441.245625   64957.192  1993.8
5   Shet  2019  41217.660988   91721.800  2120.4
6   Shet  2020  43137.528369  110796.400  1952.3
7   Shet  2021  57304.783483  147581.600  3570.3
8   Shet  2022  66215.802075  154644.655  5038.4
9   Shet  2023  60982.200000  120256.030  6965.0
10  Shet  2024  63030.800000  145804.964  8355.2

In [203]:
karagandy_controls = pd.concat([zhezkazgan, karazhal, satpayev, zhanaarka, ulytau, karagandy, balkhash, priozersk, saran, temirtau, shakhtinsk, abay, aktogay, bukhar_zhyrau, karkaraly, nura, osakarov, shet], ignore_index=True)
karagandy_controls

               rayon  year   agriculture  production   retail
0    Zhezkazgan_city  2014   3895.600000  168812.105  25064.2
1    Zhezkazgan_city  2015   3895.100000  194396.124  26016.8
2    Zhezkazgan_city  2016   4025.200000  266883.200  30656.2
3    Zhezkazgan_city  2017   4607.900000  336161.462  34530.7
4    Zhezkazgan_city  2018   4982.751914  333609.724  37689.7
..               ...   ...           ...         ...      ...
188             Shet  2020  43137.528369  110796.400   1952.3
189             Shet  2021  57304.783483  147581.600   3570.3
190             Shet  2022  66215.802075  154644.655   5038.4
191             Shet  2023  60982.200000  120256.030   6965.0
192             Shet  2024  63030.800000  145804.964   8355.2

[193 rows x 5 columns]

## PPI

In [204]:
karagandy_ppi = pd.read_excel(Path("../Data/PPI/Karagandy.xls"), header=4, usecols='Y:AI', nrows=216, na_values=['x', 'х', '-', '', ' ', '...'])

karagandy_ppi.columns = [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

rayons = list(karagandy_inv['rayon'].unique())

dfs = []

for rayon in rayons:
    df_temp = pd.DataFrame({
        'rayon': rayon,
        'year': range(2014, 2025),
        'ppi': karagandy_ppi.values[75]
    })
    dfs.append(df_temp)

karagandy_ppi = pd.concat(dfs, ignore_index=True)

karagandy_ppi['ppi'] = karagandy_ppi['ppi'].astype(str).str.replace(',', '.')
karagandy_ppi['ppi'] = karagandy_ppi['ppi'].astype(str).str.replace(')', '')
karagandy_ppi['ppi'] = karagandy_ppi['ppi'].astype(str).str.replace(' ', '')
karagandy_ppi['ppi'] = karagandy_ppi['ppi'].astype(str).str.replace('\xa0', '')
karagandy_ppi['ppi'] = karagandy_ppi['ppi'].astype(str).str.replace('*', '')
karagandy_ppi['ppi'] = karagandy_ppi['ppi'].astype(float)

karagandy_ppi

              rayon  year      ppi
0    Karagandy_city  2014  104.500
1    Karagandy_city  2015  111.700
2    Karagandy_city  2016  120.300
3    Karagandy_city  2017  107.800
4    Karagandy_city  2018  108.600
..              ...   ...      ...
193            Shet  2020  115.500
194            Shet  2021  135.100
195            Shet  2022   98.325
196            Shet  2023   97.700
197            Shet  2024  107.627

[198 rows x 3 columns]

## Combine together

In [205]:
dfs = [karagandy_inv, karagandy_empl, karagandy_controls, karagandy_ppi]

karagandy_merged = reduce(lambda left, right: pd.merge(left, right, on=['rayon', 'year'], how='outer'), dfs)

karagandy_merged

,rayon,l_all_inv,f_all_inv,oblast,year,f_nonextr_inv,l_nonextr_inv,employment,agriculture,production,retail,ppi
0,Abay,9788627.0,4526939.0,Karagandy,2014,NaN,NaN,26.2,17088.700000,95346.620,6579.1,104.500
1,Abay,3870710.0,4181405.0,Karagandy,2015,1077837,1375895.0,25.9,18923.200000,100841.801,6553.6,111.700
2,Abay,4242734.0,5169779.0,Karagandy,2016,960936,1686099.0,26.5,21069.100000,113395.581,7314.9,120.300
3,Abay,6618758.0,4885502.0,Karagandy,2017,2306472.0,1237898.0,28.8,26984.700000,124694.659,7725.2,107.800
4,Abay,5897212.0,10862193.0,Karagandy,2018,4519550.0,757320.0,29.0,29159.777958,97302.898,8154.4,108.600
...,...,...,...,...,...,...,...,...,...,...,...,...
193,Zhezkazgan_city,31356084.0,6214278.0,Karagandy,2020,6172047.0,13505279.0,40.0,6479.320708,626780.700,43185.1,115.500
194,Zhezkazgan_city,31300213.0,10759936.0,Karagandy,2021,10710774.0,20877790.0,41.2,8260.219568,729839.800,46712.7,135.100
195,Zhezkazgan_city,33633647.0,9521918.0,Karagandy,2022,9521918.0,24556304.0,42833.0,9415.700000,808023.000,53633.7,98.325
196,Zhezkazgan_city,62451164.0,21436790.0,Karagandy,2023,21403790.0,41973016.0,42474.0,13334.400000,833781.000,72528.7,97.700
197,Zhezkazgan_city,70952389.0,31234999.0,Karagandy,2024,30983472.0,37798324.0,NaN,NaN,NaN,NaN,107.627

# Aktobe oblast

## Investments

In [206]:
aktobe_all_2016 = pd.read_excel(Path("../Data/Investments/Aktobe/2016_Investments/Internal_vs_external.xls"), header=7, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
aktobe_all_2017 = pd.read_excel(Path("../Data/Investments/Aktobe/2017_Investments/Internal_vs_extrenal.xls"), header=7, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
aktobe_all_2018 = pd.read_excel(Path("../Data/Investments/Aktobe/2018_Investments/Internal_vs_external.xlsx"), header=7, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
aktobe_all_2019 = pd.read_excel(Path("../Data/Investments/Aktobe/2019_Investments.xls"), sheet_name='16.', header=5, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
aktobe_all_2020 = pd.read_excel(Path("../Data/Investments/Aktobe/2020_Investments.xls"), sheet_name='15', header=5, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
aktobe_all_2021 = pd.read_excel(Path("../Data/Investments/Aktobe/2021_Investments.xls"), sheet_name='15', header=4, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
aktobe_all_2022 = pd.read_excel(Path("../Data/Investments/Aktobe/2022_Investments.xls"), sheet_name='15', header=4, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
aktobe_all_2023 = pd.read_excel(Path("../Data/Investments/Aktobe/2023_Investments.xlsx"), sheet_name='19', header=4, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
aktobe_all_2024 = pd.read_excel(Path("../Data/Investments/Aktobe/2024_Investments.xlsx"), sheet_name='14', header=4, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

aktobe_non_2016 = pd.read_excel(Path("../Data/Investments/Aktobe/2016_Investments/Greenfield_investments.xls"), header=7, usecols='A, B, D', nrows=14, na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
aktobe_non_2017 = pd.read_excel(Path("../Data/Investments/Aktobe/2017_Investments/Greenfield_investments.xls"), header=7, usecols='A, B, D', nrows=14, na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
aktobe_non_2018 = pd.read_excel(Path("../Data/Investments/Aktobe/2018_Investments/Greenfield_investments.xlsx"), header=7, usecols='A, B, D', nrows=14, na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
aktobe_non_2019 = pd.read_excel(Path("../Data/Investments/Aktobe/2019_Investments.xls"), sheet_name='17.', header=5, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
aktobe_non_2020 = pd.read_excel(Path("../Data/Investments/Aktobe/2020_Investments.xls"), sheet_name='16.', header=5, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
aktobe_non_2021 = pd.read_excel(Path("../Data/Investments/Aktobe/2021_Investments.xls"), sheet_name='16.', header=4, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
aktobe_non_2022 = pd.read_excel(Path("../Data/Investments/Aktobe/2022_Investments.xls"), sheet_name='16.', header=4, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
aktobe_non_2023 = pd.read_excel(Path("../Data/Investments/Aktobe/2023_Investments.xlsx"), sheet_name='20', header=4, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
aktobe_non_2024 = pd.read_excel(Path("../Data/Investments/Aktobe/2024_Investments.xlsx"), sheet_name='15', header=4, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [207]:
aktobe_all_2016

     Unnamed: 0  внутренние   внешние
0   Ақтөбе қ.ә.   138841548  15108594
1          Алға    11418509     24935
2     Әйтеке би     5617788     37408
3      Байғанин    30103707   9800245
4       Қарғалы     2647045        82
5         Қобда     3459597       325
6        Мәртөк     4559449     42225
7      Мұғалжар    43948404  19018358
8          Ойыл     1734036   1515748
9         Темір     5002192   4188965
10      Хромтау    18301182  20298158
11       Шалқар    29279087   7240437
12        Ырғыз     1465487      1430

In [208]:
aktobe_non_2016

     Unnamed: 0  Unnamed: 1  внешние инвестиции
0   Ақтөбе қ.ә.   123787996          14145969.0
1          Алға     8077110             24935.0
2     Әйтеке би     3156976                 0.0
3      Байғанин     6726079            245675.0
4       Қарғалы      845692                82.0
5         Қобда     1082168               325.0
6        Мәртөк     1331747               344.0
7      Мұғалжар    14630772            501051.0
8          Ойыл     1075717                 0.0
9         Темір      984318             12953.0
10      Хромтау     2948757            274303.0
11       Шалқар    27651081           6795124.0
12        Ырғыз      849959              1430.0

In [209]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [aktobe_all_2016, aktobe_all_2017, aktobe_all_2018, aktobe_all_2019, aktobe_all_2020, aktobe_all_2021, aktobe_all_2022, aktobe_all_2023, aktobe_all_2024]:
    df.columns = all_columns

for df in [aktobe_non_2016, aktobe_non_2017, aktobe_non_2018, aktobe_non_2019, aktobe_non_2020, aktobe_non_2021, aktobe_non_2022, aktobe_non_2023, aktobe_non_2024]:
    df.columns = non_columns
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

rayon_names = ['Aktobe_city', 'Alga', 'Aiteke_bi', 'Baiganin', 'Kargaly', 'Kobda', 'Martok', 'Mugalzhar', 'Oyil', 'Temir', 'Khromtau', 'Shalkar', 'Yrgyz']

for df in [aktobe_all_2016, aktobe_all_2017, aktobe_all_2018, aktobe_all_2019, aktobe_all_2020, aktobe_all_2021, aktobe_all_2022, aktobe_all_2023, aktobe_all_2024, aktobe_non_2016, aktobe_non_2017, aktobe_non_2018, aktobe_non_2019, aktobe_non_2020, aktobe_non_2021, aktobe_non_2022, aktobe_non_2023, aktobe_non_2024]:
    df['rayon'] = rayon_names

aktobe_2016 = aktobe_all_2016.merge(aktobe_non_2016, on='rayon')
aktobe_2017 = aktobe_all_2017.merge(aktobe_non_2017, on='rayon')
aktobe_2018 = aktobe_all_2018.merge(aktobe_non_2018, on='rayon')
aktobe_2019 = aktobe_all_2019.merge(aktobe_non_2019, on='rayon')
aktobe_2020 = aktobe_all_2020.merge(aktobe_non_2020, on='rayon')
aktobe_2021 = aktobe_all_2021.merge(aktobe_non_2021, on='rayon')
aktobe_2022 = aktobe_all_2022.merge(aktobe_non_2022, on='rayon')
aktobe_2023 = aktobe_all_2023.merge(aktobe_non_2023, on='rayon')
aktobe_2024 = aktobe_all_2024.merge(aktobe_non_2024, on='rayon')

dfs = [aktobe_2016, aktobe_2017, aktobe_2018, aktobe_2019, aktobe_2020, aktobe_2021, aktobe_2022, aktobe_2023, aktobe_2024]

for i in range(9):
    df = dfs[i]
    df['oblast'] = 'Aktobe'
    df['year'] = 2016 + i

aktobe_inv = pd.concat([aktobe_2016, aktobe_2017, aktobe_2018, aktobe_2019, aktobe_2020, aktobe_2021, aktobe_2022, aktobe_2023, aktobe_2024], ignore_index=True)
aktobe_inv

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year
0,Aktobe_city,138841548,15108594.0,14145969.0,109642027.0,Aktobe,2016
1,Alga,11418509,24935.0,24935.0,8052175.0,Aktobe,2016
2,Aiteke_bi,5617788,37408.0,0.0,3156976.0,Aktobe,2016
3,Baiganin,30103707,9800245.0,245675.0,6480404.0,Aktobe,2016
4,Kargaly,2647045,82.0,82.0,845610.0,Aktobe,2016
...,...,...,...,...,...,...,...
112,Oyil,11195154,375410.0,0.0,1002610.0,Aktobe,2024
113,Temir,28097768,13819615.0,202898.0,3923988.0,Aktobe,2024
114,Khromtau,204236017,39631349.0,1336224.0,14345514.0,Aktobe,2024
115,Shalkar,17553684,1884499.0,1843584.0,10611069.0,Aktobe,2024
116,Yrgyz,10486291,145003.0,145003.0,3784664.0,Aktobe,2024

## Employment

In [210]:
aktobe_empl = pd.read_excel(Path("../Data/Employment/Aktobe.xlsx"), skiprows=26, nrows=13, header=None, usecols='A, D:K', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
aktobe_empl

               0      3      4      5      6      7      8      9      10
0        г.Актобе  222.5  227.5  232.6  232.0  233.8  234.8  249.5  255.7
1      Алгинский    18.1   17.2   18.4   17.7   17.5   17.6   18.1   18.0
2   Айтекебийский   11.4   11.5   11.5   11.6   11.5   11.8    9.8   10.7
3    Байганинский   10.7   10.7   10.8   11.2   11.6   12.1   11.8   11.3
4    Каргалинский    8.5    8.5    8.1    8.5    7.9    8.3    7.2    7.9
5      Хобдинский   10.6   10.2    9.3    9.4    9.0    9.2    7.6    8.8
6      Мартукский   15.2   14.3   14.7   14.1   14.7   14.8   14.2   14.3
7    Мугалжарский   34.4   34.8   35.3   36.0   35.7   36.0   35.3   35.0
8         Уилский    9.4    8.6    9.8    9.7    9.7    9.9    7.9    8.2
9       Темирский   17.4   16.7   17.0   16.6   16.2   16.2   15.2   16.4
10    Хромтауский   21.2   21.1   21.6   21.6   20.8   21.2   22.7   21.3
11     Шалкарский   22.1   21.2   21.4   21.1   21.0   21.4   19.3   20.5
12      Иргизский    7.0    6.7    7.2    6.9    6.9    6.5    6.2    6.8

In [211]:
aktobe_empl.columns = ['rayon', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]

rayons = ['Aktobe_city', 'Alga', 'Aiteke_bi', 'Baiganin', 'Kargaly', 'Kobda', 'Martok', 'Mugalzhar', 'Oyil', 'Temir', 'Khromtau', 'Shalkar', 'Yrgyz']

aktobe_empl['rayon'] = rayons

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    aktobe_empl[i] = aktobe_empl[i].astype(float)

aktobe_employment = aktobe_empl.melt(id_vars='rayon', value_vars=[2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023], var_name='year', value_name='employment')

aktobe_employment

           rayon  year  employment
0    Aktobe_city  2016       222.5
1           Alga  2016        18.1
2      Aiteke_bi  2016        11.4
3       Baiganin  2016        10.7
4        Kargaly  2016         8.5
..           ...   ...         ...
99          Oyil  2023         8.2
100        Temir  2023        16.4
101     Khromtau  2023        21.3
102      Shalkar  2023        20.5
103        Yrgyz  2023         6.8

[104 rows x 3 columns]

## Other controls

In [212]:
aktobe_city = pd.read_excel(Path("../Data/Controls/Aktobe_All.xls"), sheet_name="г. Актобе", header=2, usecols='A, R:Y', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

aktobe_city.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
aktobe_city = aktobe_city.loc[[109, 85, 142]].reset_index(drop=True)

aktobe_city['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    aktobe_city[i] = aktobe_city[i].astype(str)
    aktobe_city[i] = aktobe_city[i].str.replace(',', '.')
    aktobe_city[i] = aktobe_city[i].str.replace(')', '')
    aktobe_city[i] = aktobe_city[i].str.replace(' ', '')
    aktobe_city[i] = aktobe_city[i].str.replace('\xa0', '')
    aktobe_city[i] = aktobe_city[i].str.replace('*', '')
    aktobe_city[i] = aktobe_city[i].astype(float)

aktobe_city = pd.melt(aktobe_city, id_vars=['Indicator'], var_name='year', value_name='value')
aktobe_city = aktobe_city.pivot(index='year', columns='Indicator', values='value').reset_index()
aktobe_city.insert(0, 'rayon', 'Aktobe_city')
aktobe_city.columns.name = None

In [213]:
alga = pd.read_excel(Path("../Data/Controls/Aktobe_All.xls"), sheet_name="Алгинский", header=2, usecols='A, R:Y', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

alga.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
alga = alga.loc[[112, 89, 141]].reset_index(drop=True)

alga['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    alga[i] = alga[i].astype(str)
    alga[i] = alga[i].str.replace(',', '.')
    alga[i] = alga[i].str.replace(')', '')
    alga[i] = alga[i].str.replace(' ', '')
    alga[i] = alga[i].str.replace('\xa0', '')
    alga[i] = alga[i].str.replace('*', '')
    alga[i] = alga[i].astype(float)

alga = pd.melt(alga, id_vars=['Indicator'], var_name='year', value_name='value')
alga = alga.pivot(index='year', columns='Indicator', values='value').reset_index()
alga.insert(0, 'rayon', 'Alga')
alga.columns.name = None

In [214]:
aiteke_bi = pd.read_excel(Path("../Data/Controls/Aktobe_All.xls"), sheet_name="Айтекебийский", header=2, usecols='A, R:Y', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

aiteke_bi.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
aiteke_bi = aiteke_bi.loc[[111, 88, 140]].reset_index(drop=True)

aiteke_bi['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    aiteke_bi[i] = aiteke_bi[i].astype(str)
    aiteke_bi[i] = aiteke_bi[i].str.replace(',', '.')
    aiteke_bi[i] = aiteke_bi[i].str.replace(')', '')
    aiteke_bi[i] = aiteke_bi[i].str.replace(' ', '')
    aiteke_bi[i] = aiteke_bi[i].str.replace('\xa0', '')
    aiteke_bi[i] = aiteke_bi[i].str.replace('*', '')
    aiteke_bi[i] = aiteke_bi[i].astype(float)

aiteke_bi = pd.melt(aiteke_bi, id_vars=['Indicator'], var_name='year', value_name='value')
aiteke_bi = aiteke_bi.pivot(index='year', columns='Indicator', values='value').reset_index()
aiteke_bi.insert(0, 'rayon', 'Aiteke_bi')
aiteke_bi.columns.name = None

In [215]:
baiganin = pd.read_excel(Path("../Data/Controls/Aktobe_All.xls"), sheet_name="Байганинский", header=2, usecols='A, R:Y', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

baiganin.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
baiganin = baiganin.loc[[112, 88, 141]].reset_index(drop=True)

baiganin['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    baiganin[i] = baiganin[i].astype(str)
    baiganin[i] = baiganin[i].str.replace(',', '.')
    baiganin[i] = baiganin[i].str.replace(')', '')
    baiganin[i] = baiganin[i].str.replace(' ', '')
    baiganin[i] = baiganin[i].str.replace('\xa0', '')
    baiganin[i] = baiganin[i].str.replace('*', '')
    baiganin[i] = baiganin[i].astype(float)

baiganin = pd.melt(baiganin, id_vars=['Indicator'], var_name='year', value_name='value')
baiganin = baiganin.pivot(index='year', columns='Indicator', values='value').reset_index()
baiganin.insert(0, 'rayon', 'Baiganin')
baiganin.columns.name = None

In [216]:
kargaly = pd.read_excel(Path("../Data/Controls/Aktobe_All.xls"), sheet_name="Каргалинский", header=2, usecols='A, R:Y', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

kargaly.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
kargaly = kargaly.loc[[111, 88, 140]].reset_index(drop=True)

kargaly['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    kargaly[i] = kargaly[i].astype(str)
    kargaly[i] = kargaly[i].str.replace(',', '.')
    kargaly[i] = kargaly[i].str.replace(')', '')
    kargaly[i] = kargaly[i].str.replace(' ', '')
    kargaly[i] = kargaly[i].str.replace('\xa0', '')
    kargaly[i] = kargaly[i].str.replace('*', '')
    kargaly[i] = kargaly[i].astype(float)

kargaly = pd.melt(kargaly, id_vars=['Indicator'], var_name='year', value_name='value')
kargaly = kargaly.pivot(index='year', columns='Indicator', values='value').reset_index()
kargaly.insert(0, 'rayon', 'Kargaly')
kargaly.columns.name = None

In [217]:
kobda = pd.read_excel(Path("../Data/Controls/Aktobe_All.xls"), sheet_name="Хобдинский", header=2, usecols='A, R:Y', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

kobda.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
kobda = kobda.loc[[113, 90, 142]].reset_index(drop=True)

kobda['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    kobda[i] = kobda[i].astype(str)
    kobda[i] = kobda[i].str.replace(',', '.')
    kobda[i] = kobda[i].str.replace(')', '')
    kobda[i] = kobda[i].str.replace(' ', '')
    kobda[i] = kobda[i].str.replace('\xa0', '')
    kobda[i] = kobda[i].str.replace('*', '')
    kobda[i] = kobda[i].astype(float)

kobda = pd.melt(kobda, id_vars=['Indicator'], var_name='year', value_name='value')
kobda = kobda.pivot(index='year', columns='Indicator', values='value').reset_index()
kobda.insert(0, 'rayon', 'Kobda')
kobda.columns.name = None

In [218]:
martok = pd.read_excel(Path("../Data/Controls/Aktobe_All.xls"), sheet_name="Мартукский", header=2, usecols='A, R:Y', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

martok.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
martok = martok.loc[[112, 88, 141]].reset_index(drop=True)

martok['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    martok[i] = martok[i].astype(str)
    martok[i] = martok[i].str.replace(',', '.')
    martok[i] = martok[i].str.replace(')', '')
    martok[i] = martok[i].str.replace(' ', '')
    martok[i] = martok[i].str.replace('\xa0', '')
    martok[i] = martok[i].str.replace('*', '')
    martok[i] = martok[i].astype(float)

martok = pd.melt(martok, id_vars=['Indicator'], var_name='year', value_name='value')
martok = martok.pivot(index='year', columns='Indicator', values='value').reset_index()
martok.insert(0, 'rayon', 'Martok')
martok.columns.name = None

In [219]:
mugalzhar = pd.read_excel(Path("../Data/Controls/Aktobe_All.xls"), sheet_name="Мугалжарский", header=2, usecols='A, R:Y', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

mugalzhar.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
mugalzhar = mugalzhar.loc[[112, 89, 141]].reset_index(drop=True)

mugalzhar['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    mugalzhar[i] = mugalzhar[i].astype(str)
    mugalzhar[i] = mugalzhar[i].str.replace(',', '.')
    mugalzhar[i] = mugalzhar[i].str.replace(')', '')
    mugalzhar[i] = mugalzhar[i].str.replace(' ', '')
    mugalzhar[i] = mugalzhar[i].str.replace('\xa0', '')
    mugalzhar[i] = mugalzhar[i].str.replace('*', '')
    mugalzhar[i] = mugalzhar[i].astype(float)

mugalzhar = pd.melt(mugalzhar, id_vars=['Indicator'], var_name='year', value_name='value')
mugalzhar = mugalzhar.pivot(index='year', columns='Indicator', values='value').reset_index()
mugalzhar.insert(0, 'rayon', 'Mugalzhar')
mugalzhar.columns.name = None

In [220]:
oyil = pd.read_excel(Path("../Data/Controls/Aktobe_All.xls"), sheet_name="Уилский", header=2, usecols='A, R:Y', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

oyil.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
oyil = oyil.loc[[112, 89, 141]].reset_index(drop=True)

oyil['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    oyil[i] = oyil[i].astype(str)
    oyil[i] = oyil[i].str.replace(',', '.')
    oyil[i] = oyil[i].str.replace(')', '')
    oyil[i] = oyil[i].str.replace(' ', '')
    oyil[i] = oyil[i].str.replace('\xa0', '')
    oyil[i] = oyil[i].str.replace('*', '')
    oyil[i] = oyil[i].astype(float)

oyil = pd.melt(oyil, id_vars=['Indicator'], var_name='year', value_name='value')
oyil = oyil.pivot(index='year', columns='Indicator', values='value').reset_index()
oyil.insert(0, 'rayon', 'Oyil')
oyil.columns.name = None

In [221]:
temir = pd.read_excel(Path("../Data/Controls/Aktobe_All.xls"), sheet_name="Темирский", header=2, usecols='A, R:Y', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

temir.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
temir = temir.loc[[111, 88, 141]].reset_index(drop=True)

temir['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    temir[i] = temir[i].astype(str)
    temir[i] = temir[i].str.replace(',', '.')
    temir[i] = temir[i].str.replace(')', '')
    temir[i] = temir[i].str.replace(' ', '')
    temir[i] = temir[i].str.replace('\xa0', '')
    temir[i] = temir[i].str.replace('*', '')
    temir[i] = temir[i].astype(float)

temir = pd.melt(temir, id_vars=['Indicator'], var_name='year', value_name='value')
temir = temir.pivot(index='year', columns='Indicator', values='value').reset_index()
temir.insert(0, 'rayon', 'Temir')
temir.columns.name = None

In [222]:
khromtau = pd.read_excel(Path("../Data/Controls/Aktobe_All.xls"), sheet_name="Хромтауский", header=2, usecols='A, R:Y', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

khromtau.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
khromtau = khromtau.loc[[112, 89, 141]].reset_index(drop=True)

khromtau['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    khromtau[i] = khromtau[i].astype(str)
    khromtau[i] = khromtau[i].str.replace(',', '.')
    khromtau[i] = khromtau[i].str.replace(')', '')
    khromtau[i] = khromtau[i].str.replace(' ', '')
    khromtau[i] = khromtau[i].str.replace('\xa0', '')
    khromtau[i] = khromtau[i].str.replace('*', '')
    khromtau[i] = khromtau[i].astype(float)

khromtau = pd.melt(khromtau, id_vars=['Indicator'], var_name='year', value_name='value')
khromtau = khromtau.pivot(index='year', columns='Indicator', values='value').reset_index()
khromtau.insert(0, 'rayon', 'Khromtau')
khromtau.columns.name = None

In [223]:
khromtau_city = pd.read_excel(Path("../Data/Controls/Aktobe_All.xls"), sheet_name="г. Хромтау", header=2, usecols='A, AA:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...', '…'])

khromtau_city.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
khromtau_city = khromtau_city.loc[[80, 115, 146]].reset_index(drop=True)

khromtau_city['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    khromtau_city[i] = khromtau_city[i].astype(str)
    khromtau_city[i] = khromtau_city[i].str.replace(',', '.')
    khromtau_city[i] = khromtau_city[i].str.replace(')', '')
    khromtau_city[i] = khromtau_city[i].str.replace(' ', '')
    khromtau_city[i] = khromtau_city[i].str.replace('\xa0', '')
    khromtau_city[i] = khromtau_city[i].str.replace('*', '')
    khromtau_city[i] = khromtau_city[i].astype(float)

khromtau_city = pd.melt(khromtau_city, id_vars=['Indicator'], var_name='year', value_name='value')
khromtau_city = khromtau_city.pivot(index='year', columns='Indicator', values='value').reset_index()
khromtau_city.insert(0, 'rayon', 'Khromtau_city')
khromtau_city.columns.name = None
khromtau_city = khromtau_city.fillna(0)

khromtau['agriculture'] = khromtau['agriculture'] + khromtau_city['agriculture']
khromtau['production'] = khromtau['production'] + khromtau_city['production']
khromtau['retail'] = khromtau['retail'] + khromtau_city['retail']

In [224]:
shalkar = pd.read_excel(Path("../Data/Controls/Aktobe_All.xls"), sheet_name="Шалкарский", header=2, usecols='A, R:Y', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

shalkar.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
shalkar = shalkar.loc[[112, 89, 141]].reset_index(drop=True)

shalkar['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    shalkar[i] = shalkar[i].astype(str)
    shalkar[i] = shalkar[i].str.replace(',', '.')
    shalkar[i] = shalkar[i].str.replace(')', '')
    shalkar[i] = shalkar[i].str.replace(' ', '')
    shalkar[i] = shalkar[i].str.replace('\xa0', '')
    shalkar[i] = shalkar[i].str.replace('*', '')
    shalkar[i] = shalkar[i].astype(float)

shalkar = pd.melt(shalkar, id_vars=['Indicator'], var_name='year', value_name='value')
shalkar = shalkar.pivot(index='year', columns='Indicator', values='value').reset_index()
shalkar.insert(0, 'rayon', 'Shalkar')
shalkar.columns.name = None

In [225]:
yrgyz = pd.read_excel(Path("../Data/Controls/Aktobe_All.xls"), sheet_name="Иргизский", header=2, usecols='A, R:Y', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

yrgyz.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
yrgyz = yrgyz.loc[[111, 88, 144]].reset_index(drop=True)

yrgyz['Indicator'] = ['production', 'agriculture', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    yrgyz[i] = yrgyz[i].astype(str)
    yrgyz[i] = yrgyz[i].str.replace(',', '.')
    yrgyz[i] = yrgyz[i].str.replace(')', '')
    yrgyz[i] = yrgyz[i].str.replace(' ', '')
    yrgyz[i] = yrgyz[i].str.replace('\xa0', '')
    yrgyz[i] = yrgyz[i].str.replace('*', '')
    yrgyz[i] = yrgyz[i].astype(float)

yrgyz = pd.melt(yrgyz, id_vars=['Indicator'], var_name='year', value_name='value')
yrgyz = yrgyz.pivot(index='year', columns='Indicator', values='value').reset_index()
yrgyz.insert(0, 'rayon', 'Yrgyz')
yrgyz.columns.name = None

In [226]:
aktobe_controls = pd.concat([aktobe_city, alga, aiteke_bi, baiganin, kargaly, kobda, martok, mugalzhar, oyil, temir, khromtau, shalkar, yrgyz], ignore_index=True)
aktobe_controls

           rayon  year  agriculture  production    retail
0    Aktobe_city  2016      19609.3  373390.000  453070.3
1    Aktobe_city  2017      22200.0  527838.000  443660.5
2    Aktobe_city  2018      25501.1  588694.000  467925.6
3    Aktobe_city  2019      29122.4  580650.000  486014.2
4    Aktobe_city  2020      33577.7  564726.000  538176.9
..           ...   ...          ...         ...       ...
99         Yrgyz  2019      12366.7     751.000    1720.9
100        Yrgyz  2020      14947.2     676.500    2411.3
101        Yrgyz  2021      17778.7     594.000    3603.2
102        Yrgyz  2022      21037.3     353.848    4608.8
103        Yrgyz  2023      17378.2     518.000    4908.2

[104 rows x 5 columns]

## PPI

In [227]:
aktobe_ppi = pd.read_excel(Path("../Data/PPI/Aktobe.xlsx"), header=2, usecols='AA:AH', nrows=216, na_values=['x', 'х', '-', '', ' ', '...'])

aktobe_ppi.columns = [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]

rayons = list(aktobe_inv['rayon'].unique())

dfs = []

for rayon in rayons:
    df_temp = pd.DataFrame({
        'rayon': rayon,
        'year': range(2016, 2024),
        'ppi': aktobe_ppi.values[64]
    })
    dfs.append(df_temp)

aktobe_ppi = pd.concat(dfs, ignore_index=True)

aktobe_ppi['ppi'] = aktobe_ppi['ppi'].astype(str).str.replace(',', '.')
aktobe_ppi['ppi'] = aktobe_ppi['ppi'].astype(str).str.replace(')', '')
aktobe_ppi['ppi'] = aktobe_ppi['ppi'].astype(str).str.replace(' ', '')
aktobe_ppi['ppi'] = aktobe_ppi['ppi'].astype(str).str.replace('\xa0', '')
aktobe_ppi['ppi'] = aktobe_ppi['ppi'].astype(str).str.replace('*', '')
aktobe_ppi['ppi'] = aktobe_ppi['ppi'].astype(float)

aktobe_ppi

           rayon  year    ppi
0    Aktobe_city  2016  113.1
1    Aktobe_city  2017  118.0
2    Aktobe_city  2018  102.2
3    Aktobe_city  2019  107.1
4    Aktobe_city  2020   84.9
..           ...   ...    ...
99         Yrgyz  2019  107.1
100        Yrgyz  2020   84.9
101        Yrgyz  2021  149.3
102        Yrgyz  2022  134.7
103        Yrgyz  2023   90.1

[104 rows x 3 columns]

## Combine together

In [228]:
aktobe_employment

           rayon  year  employment
0    Aktobe_city  2016       222.5
1           Alga  2016        18.1
2      Aiteke_bi  2016        11.4
3       Baiganin  2016        10.7
4        Kargaly  2016         8.5
..           ...   ...         ...
99          Oyil  2023         8.2
100        Temir  2023        16.4
101     Khromtau  2023        21.3
102      Shalkar  2023        20.5
103        Yrgyz  2023         6.8

[104 rows x 3 columns]

In [229]:
dfs = [aktobe_inv, aktobe_employment, aktobe_controls, aktobe_ppi]

aktobe_merged = reduce(lambda left, right: pd.merge(left, right, on=['rayon', 'year'], how='outer'), dfs)

aktobe_merged

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year,employment,agriculture,production,retail,ppi
0,Aiteke_bi,5617788,37408.0,0.0,3156976.0,Aktobe,2016,11.4,19792.6,2243.000,4717.5,113.1
1,Aiteke_bi,4690205,25072.0,2043.0,2952906.0,Aktobe,2017,11.5,21608.9,2447.000,5126.6,118.0
2,Aiteke_bi,4671048,381908.0,381908.0,1909510.0,Aktobe,2018,11.5,24059.8,5338.000,5900.6,102.2
3,Aiteke_bi,6226602,14690.0,14663.0,1689892.0,Aktobe,2019,11.6,25794.9,8798.000,6281.1,107.1
4,Aiteke_bi,7629261,1327953.0,31124.0,1885386.0,Aktobe,2020,11.5,35037.2,7802.000,7112.6,84.9
...,...,...,...,...,...,...,...,...,...,...,...,...
112,Yrgyz,4453883,11055.0,11055.0,1533088.0,Aktobe,2020,6.9,14947.2,676.500,2411.3,84.9
113,Yrgyz,5421140,0.0,0.0,2319348.0,Aktobe,2021,6.5,17778.7,594.000,3603.2,149.3
114,Yrgyz,6605763,0.0,0.0,2898755.0,Aktobe,2022,6.2,21037.3,353.848,4608.8,134.7
115,Yrgyz,11171476,0.0,0.0,3619097.0,Aktobe,2023,6.8,17378.2,518.000,4908.2,90.1
116,Yrgyz,10486291,145003.0,145003.0,3784664.0,Aktobe,2024,NaN,NaN,NaN,NaN,NaN

# Almaty city

## Investments

In [230]:
alm_city_all_2014 = pd.read_excel(Path("../Data/Investments/Almaty-city/2014_Investments.xls"), header=7, nrows=9, usecols='A, C, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
alm_city_all_2015 = pd.read_excel(Path("../Data/Investments/Almaty-city/2015_Investments.xls"), sheet_name='TAB 11', header=7, nrows=9, usecols='A, C, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
alm_city_all_2016 = pd.read_excel(Path("../Data/Investments/Almaty-city/2016_Investments.xls"), sheet_name='ТАБ 13', header=8, nrows=9, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
alm_city_all_2017 = pd.read_excel(Path("../Data/Investments/Almaty-city/2017_Investments.xls"), sheet_name='ТАВ 14', header=7, nrows=9, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
alm_city_all_2018 = pd.read_excel(Path("../Data/Investments/Almaty-city/2018_Investments/Internal_vs_external.xls"), header=7, nrows=9, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
alm_city_all_2019 = pd.read_excel(Path("../Data/Investments/Almaty-city/2019_Investments.xls"), sheet_name='13.', header=5, nrows=9, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
alm_city_all_2020 = pd.read_excel(Path("../Data/Investments/Almaty-city/2020_Investments.xls"), sheet_name='12.', header=5, nrows=9, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
alm_city_all_2021 = pd.read_excel(Path("../Data/Investments/Almaty-city/2021_Investments.xls"), sheet_name='12.', header=5, nrows=9, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
alm_city_all_2022 = pd.read_excel(Path("../Data/Investments/Almaty-city/2022_Investments.xls"), sheet_name='12.', header=5, nrows=9, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
alm_city_all_2023 = pd.read_excel(Path("../Data/Investments/Almaty-city/2023_Investments.xlsx"), sheet_name='18', header=3, nrows=9, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
alm_city_all_2024 = pd.read_excel(Path("../Data/Investments/Almaty-city/2024_Investments.xlsx"), sheet_name='13', header=3, nrows=9, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

alm_city_non_2018 = pd.read_excel(Path("../Data/Investments/Almaty-city/2018_Investments/Greenfield_investments.xls"), header=10, nrows=9, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
alm_city_non_2019 = pd.read_excel(Path("../Data/Investments/Almaty-city/2019_Investments.xls"), sheet_name='14.', header=7, nrows=9, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
alm_city_non_2020 = pd.read_excel(Path("../Data/Investments/Almaty-city/2020_Investments.xls"), sheet_name='13.', header=7, nrows=9, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
alm_city_non_2021 = pd.read_excel(Path("../Data/Investments/Almaty-city/2021_Investments.xls"), sheet_name='13.', header=7, nrows=9, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
alm_city_non_2022 = pd.read_excel(Path("../Data/Investments/Almaty-city/2022_Investments.xls"), sheet_name='13.', header=7, nrows=9, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
alm_city_non_2023 = pd.read_excel(Path("../Data/Investments/Almaty-city/2023_Investments.xlsx"), sheet_name='19', header=3, nrows=9, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
alm_city_non_2024 = pd.read_excel(Path("../Data/Investments/Almaty-city/2024_Investments.xlsx"), sheet_name='14', header=3, nrows=9, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [231]:
alm_city_all_2018

  Unnamed: 0  внутренние   внешние
0     Алатау    81836001   4553715
1     Алмалы    77287289  15254709
2     Әуезов    64931824   2801160
3  Бостандық   149434154  35737524
4     Жетісу    38536586   7069004
5      Медеу   130049430  31896670
6  Наурызбай    39308419   1500134
7    Түрксіб    39025124  12339123

In [232]:
alm_city_non_2024

       Unnamed: 0  Unnamed: 1  внешние инвестиции
0   Алмалинский     260689181            29806461
1    Алатауский     314661250            17873947
2     Ауэзовский    108391680             2654747
3   Бостандыкский   396276350            62253611
4  Жетысуский       105360971            20970208
5   Медеуский       264484298            71343200
6   Наурызбайский   119493282             2543118
7     Турксибский   199376600            53781169

In [233]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [alm_city_all_2018, alm_city_all_2019,
           alm_city_all_2020, alm_city_all_2021, alm_city_all_2022,
           alm_city_all_2023, alm_city_all_2024]:
    df.columns = all_columns

for df in [alm_city_non_2018, alm_city_non_2019, alm_city_non_2020,
           alm_city_non_2021, alm_city_non_2022, alm_city_non_2023,
           alm_city_non_2024]:
    df.columns = non_columns
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

In [234]:
rayon_map = {
    'Алатау': 'Alatau',
    'Алмалы': 'Almaly',
    'Әуезов': 'Auezov',
    'Бостандық': 'Bostandyk',
    'Жетісу': 'Zhetysu',
    'Медеу': 'Medeu',
    'Наурызбай': 'Nauryzbay',
    'Түрксіб': 'Turksib',

    'Алатауский': 'Alatau',
    'Алмалинский': 'Almaly',
    'Ауэзовский': 'Auezov',
    'Бостандыкский': 'Bostandyk',
    'Жетысуский': 'Zhetysu',
    'Медеуский': 'Medeu',
    'Наурызбайский': 'Nauryzbay',
    'Турксибский': 'Turksib'
}

In [235]:
# ----- ALL investments -----
alm_city_all_2018['rayon'] = alm_city_all_2018['rayon'].replace(rayon_map)
alm_city_all_2019['rayon'] = alm_city_all_2019['rayon'].replace(rayon_map)
alm_city_all_2020['rayon'] = alm_city_all_2020['rayon'].replace(rayon_map)
alm_city_all_2021['rayon'] = alm_city_all_2021['rayon'].replace(rayon_map)
alm_city_all_2022['rayon'] = alm_city_all_2022['rayon'].replace(rayon_map)
alm_city_all_2023['rayon'] = alm_city_all_2023['rayon'].replace(rayon_map)
alm_city_all_2024['rayon'] = alm_city_all_2024['rayon'].replace(rayon_map)

# ----- NON-extractive investments -----
alm_city_non_2018['rayon'] = alm_city_non_2018['rayon'].replace(rayon_map)
alm_city_non_2019['rayon'] = alm_city_non_2019['rayon'].replace(rayon_map)
alm_city_non_2020['rayon'] = alm_city_non_2020['rayon'].replace(rayon_map)
alm_city_non_2021['rayon'] = alm_city_non_2021['rayon'].replace(rayon_map)
alm_city_non_2022['rayon'] = alm_city_non_2022['rayon'].replace(rayon_map)
alm_city_non_2023['rayon'] = alm_city_non_2023['rayon'].replace(rayon_map)
alm_city_non_2024['rayon'] = alm_city_non_2024['rayon'].replace(rayon_map)

In [236]:
alm_city_all_2018

       rayon  l_all_inv  f_all_inv
0     Alatau   81836001    4553715
1     Almaly   77287289   15254709
2     Auezov   64931824    2801160
3  Bostandyk  149434154   35737524
4    Zhetysu   38536586    7069004
5      Medeu  130049430   31896670
6  Nauryzbay   39308419    1500134
7    Turksib   39025124   12339123

In [237]:
alm_city_non_2023

            rayon  f_nonextr_inv  l_nonextr_inv
0   Алмалинский         26500132      312252822
1    Алатауский          3233739      154544214
2     Ауэзовский         6383176       78890112
3       Bostandyk       51906086      306267648
4  Жетысуский           17744313       71935568
5   Медеуский           67657174      284522636
6       Nauryzbay       15035128      101581770
7         Turksib       54138754       72747349

In [238]:
# merge
# alm_city_2014 = alm_city_all_2014
# alm_city_2015 = alm_city_all_2015
# alm_city_2016 = alm_city_all_2016
# alm_city_2017 = alm_city_all_2017
alm_city_2018 = alm_city_all_2018.merge(alm_city_non_2018, on='rayon', how='left')
alm_city_2019 = alm_city_all_2019.merge(alm_city_non_2019, on='rayon', how='left')
alm_city_2020 = alm_city_all_2020.merge(alm_city_non_2020, on='rayon', how='left')
alm_city_2021 = alm_city_all_2021.merge(alm_city_non_2021, on='rayon', how='left')
alm_city_2022 = alm_city_all_2022.merge(alm_city_non_2022, on='rayon', how='left')
alm_city_2023 = alm_city_all_2023.merge(alm_city_non_2023, on='rayon', how='left')
alm_city_2024 = alm_city_all_2024.merge(alm_city_non_2024, on='rayon', how='left')

dfs = [alm_city_2018, alm_city_2019, alm_city_2020, alm_city_2021, alm_city_2022, alm_city_2023, alm_city_2024]

for i in range(7):
    df = dfs[i]
    df['oblast'] = 'Almaty city'
    df['year'] = 2018 + i

alm_city_inv = pd.concat([alm_city_2018, alm_city_2019, alm_city_2020, alm_city_2021, alm_city_2022, alm_city_2023, alm_city_2024], ignore_index=True)
alm_city_inv['rayon'] = (
    alm_city_inv['rayon']
        .str.strip()          # remove hidden spaces
        .replace(rayon_map)   # enforce English names
)
alm_city_inv

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year
0,Alatau,81836001,4553715,4553715,43895959,Almaty city,2018
1,Almaly,77287289,15254709,15254709,53160475,Almaty city,2018
2,Auezov,64931824,2801160,2801160,38840360,Almaty city,2018
3,Bostandyk,149434154,35737524,35737524,125041455,Almaty city,2018
4,Zhetysu,38536586,7069004,7069004,29058169,Almaty city,2018
5,Medeu,130049430,31896670,31896670,107097498,Almaty city,2018
6,Nauryzbay,39308419,1500134,1500134,31902255,Almaty city,2018
7,Turksib,39025124,12339123,12339123,30615001,Almaty city,2018
8,Alatau,92829588,9094588,9094588,58908496,Almaty city,2019
9,Almaly,85051809,17896763,17896763,72236313,Almaty city,2019
10,Auezov,62497055,4126390,4126390,36833133,Almaty city,2019
11,Bostandyk,159852932,44205541,44205541,149209588,Almaty city,2019
12,Zhetysu,36770110,12008759,12008759,30052169,Almaty city,2019
13,Medeu,141963544,40920533,40920533,127485882,Almaty city,2019
14,Nauryzbay,40754051,4888165,4888165,33782314,Almaty city,2019
15,Turksib,48620446,19493366,19493366,37752047,Almaty city,2019
16,Almaly,94054799,23021109,23021109,83513468,Almaty city,2020
17,Alatau,136193071,14271868,14271868,87746129,Almaty city,2020
18,Auezov,63269991,2102438,2102438,45420980,Almaty city,2020
19,Bostandyk,181998032,39711131,39706396,159248959,Almaty city,2020
20,Zhetysu,41089088,8166843,8166843,33584355,Almaty city,2020
21,Medeu,141100639,26489189,26489189,125858280,Almaty city,2020
22,Nauryzbay,117848919,419663,419663,52451557,Almaty city,2020
23,Turksib,64555558,16931545,16931545,48771614,Almaty city,2020
24,Almaly,128894248,24955234,24955234,96684274,Almaty city,2021
25,Alatau,125713417,18461168,18461168,94741590,Almaty city,2021
26,Auezov,76487756,9246884,9246884,54633452,Almaty city,2021
27,Bostandyk,231850293,52808161,52808161,203380323,Almaty city,2021
28,Zhetysu,60210191,8852288,8852288,50765615,Almaty city,2021
29,Medeu,171199557,32062218,32062218,149316633,Almaty city,2021
30,Nauryzbay,124028453,2848641,2848641,86373158,Almaty city,2021
31,Turksib,92238555,25882158,25882158,55929948,Almaty city,2021
32,Almaly,120131873,23518133,23518133,108394744,Almaty city,2022
33,Alatau,124346999,1489185,1489185,82587032,Almaty city,2022
34,Auezov,95719291,5309707,5309707,76576627,Almaty city,2022
35,Bostandyk,321533479,65416909,65416909,283823979,Almaty city,2022
36,Zhetysu,64277226,19425879,19425879,51099186,Almaty city,2022
37,Medeu,193681328,43206775,43206775,182854560,Almaty city,2022
38,Nauryzbay,132851547,501437,501437,95855370,Almaty city,2022
39,Turksib,168121252,21030377,21030377,109414802,Almaty city,2022
40,Almaly,339709904,26500132,26500132,312252822,Almaty city,2023
41,Alatau,183331837,3233739,3233739,154544214,Almaty city,2023
42,Auezov,95259366,6383176,6383176,78890112,Almaty city,2023
43,Bostandyk,338310652,51906086,51906086,306267648,Almaty city,2023
44,Zhetysu,85565861,17744313,17744313,71935568,Almaty city,2023
45,Medeu,292810636,67657174,67657174,284522636,Almaty city,2023
46,Nauryzbay,127085584,15035128,15035128,101581770,Almaty city,2023
47,Turksib,98510990,54138754,54138754,72747349,Almaty city,2023
48,Almaly,249500158,29806461,29806461,230882720,Almaty city,2024
49,Alatau,342316245,17873947,17873947,296787303,Almaty city,2024
50,Auezov,117201109,2654747,2654747,105736933,Almaty city,2024
51,Bostandyk,366325868,62253611,62253611,334022739,Almaty city,2024
52,Zhetysu,103191108,20970208,20970208,84390763,Almaty city,2024
53,Medeu,213096634,71343200,71343200,193141098,Almaty city,2024
54,Nauryzbay,170206701,2543118,2543118,116950164,Almaty city,2024
55,Turksib,164160914,53781169,53781169,145595431,Almaty city,2024

### Almaty city - 2014-2018 Investments Separate

In [239]:
for df in [alm_city_all_2014, alm_city_all_2015,
           alm_city_all_2016, alm_city_all_2017, alm_city_all_2018]:
    df.columns = all_columns

alm_city_all_2014['rayon'] = alm_city_all_2014['rayon'].replace(rayon_map)
alm_city_all_2015['rayon'] = alm_city_all_2015['rayon'].replace(rayon_map)
alm_city_all_2016['rayon'] = alm_city_all_2016['rayon'].replace(rayon_map)
alm_city_all_2017['rayon'] = alm_city_all_2017['rayon'].replace(rayon_map)

In [240]:
dfs = [alm_city_all_2014, alm_city_all_2015, alm_city_all_2016, alm_city_all_2017]

for i in range(4):
    df = dfs[i]
    df['oblast'] = 'Almaty city'
    df['year'] = 2014 + i

In [241]:
alm_city_all_2014

       rayon  l_all_inv  f_all_inv       oblast  year
0     Alatau   67882858    2243243  Almaty city  2014
1     Almaly   63327488   14630326  Almaty city  2014
2     Јуезов   52040160    4198961  Almaty city  2014
3  Бостандыќ   99621172   20702397  Almaty city  2014
4    Zhetysu   24994713    4240792  Almaty city  2014
5      Medeu   78868502   24476107  Almaty city  2014
6  Nauryzbay    7908917       3316  Almaty city  2014
7    Тїрксіб   38837692    6751773  Almaty city  2014

In [242]:
alm_city_all_2014['rayon'] = alm_city_all_2014['rayon'].replace({
    'Јуезов': 'Auezov',
    'Бостандыќ': 'Bostandyk',
    'Тїрксіб': 'Turksib'
})

In [243]:
combined_df = pd.concat(
    [alm_city_all_2014, alm_city_all_2015, alm_city_all_2016, alm_city_all_2017],
    ignore_index=True,
    sort=False
)

In [244]:
combined_df

        rayon  l_all_inv  f_all_inv       oblast  year
0      Alatau   67882858    2243243  Almaty city  2014
1      Almaly   63327488   14630326  Almaty city  2014
2      Auezov   52040160    4198961  Almaty city  2014
3   Bostandyk   99621172   20702397  Almaty city  2014
4     Zhetysu   24994713    4240792  Almaty city  2014
5       Medeu   78868502   24476107  Almaty city  2014
6   Nauryzbay    7908917       3316  Almaty city  2014
7     Turksib   38837692    6751773  Almaty city  2014
8      Alatau   99119106     902986  Almaty city  2015
9      Almaly   49186265   12626985  Almaty city  2015
10     Auezov   51367815    4459493  Almaty city  2015
11  Bostandyk  107443711   15833801  Almaty city  2015
12    Zhetysu   27880190    4376237  Almaty city  2015
13      Medeu   94514024   14416730  Almaty city  2015
14  Nauryzbay    5004054     297701  Almaty city  2015
15    Turksib   41694688    3572115  Almaty city  2015
16     Alatau   65812135    1411132  Almaty city  2016
17     Almaly   62469412   17402417  Almaty city  2016
18     Auezov   55082964    2660569  Almaty city  2016
19  Bostandyk  111288696   24185384  Almaty city  2016
20    Zhetysu   44763652    6199409  Almaty city  2016
21      Medeu   98576707   15522613  Almaty city  2016
22  Nauryzbay   22094253     286633  Almaty city  2016
23    Turksib   46168138    7484591  Almaty city  2016
24     Alatau   56574397    3348217  Almaty city  2017
25     Almaly   86434783   16902564  Almaty city  2017
26     Auezov   59450050    3463586  Almaty city  2017
27  Bostandyk  131400584   26086371  Almaty city  2017
28    Zhetysu   37380528    6754723  Almaty city  2017
29      Medeu   98937936   25028328  Almaty city  2017
30  Nauryzbay   29024958     535262  Almaty city  2017
31    Turksib   49129735    9470853  Almaty city  2017

In [245]:
alm_city_inv = pd.concat([combined_df, alm_city_inv], ignore_index=True, sort=False)
alm_city_inv

,rayon,l_all_inv,f_all_inv,oblast,year,f_nonextr_inv,l_nonextr_inv
0,Alatau,67882858,2243243,Almaty city,2014,NaN,NaN
1,Almaly,63327488,14630326,Almaty city,2014,NaN,NaN
2,Auezov,52040160,4198961,Almaty city,2014,NaN,NaN
3,Bostandyk,99621172,20702397,Almaty city,2014,NaN,NaN
4,Zhetysu,24994713,4240792,Almaty city,2014,NaN,NaN
...,...,...,...,...,...,...,...
83,Bostandyk,366325868,62253611,Almaty city,2024,62253611.0,334022739.0
84,Zhetysu,103191108,20970208,Almaty city,2024,20970208.0,84390763.0
85,Medeu,213096634,71343200,Almaty city,2024,71343200.0,193141098.0
86,Nauryzbay,170206701,2543118,Almaty city,2024,2543118.0,116950164.0
87,Turksib,164160914,53781169,Almaty city,2024,53781169.0,145595431.0

## Employment

In [246]:
alm_city_empl = pd.read_excel(Path("../Data/Employment/Almaty-city.xls"), skiprows=18, nrows=9, header=None, usecols='A, D:L', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
alm_city_empl

,0,3,4,5,6,7,8,9,10,11
0,г.Алматы,867.898,889.606,911.923,936.544,959.309,982.774,997.963,1045.5,1083.0
1,Алмалинский район,105.977,105.713,106.244,104.771,102.956,104.313,123.687,127.1,131.6
2,Алатауский район,108.588,118.651,127.609,137.611,146.505,153.579,160.923,173.2,180.0
3,Ауэзовский район,135.994,136.373,136.639,138.282,144.273,145.390,157.919,162.6,164.4
4,Бостандыкский район,175.153,176.795,181.426,185.598,187.913,193.601,154.945,164.2,169.8
5,Жетысуский район,79.348,79.404,79.878,81.331,83.292,84.477,93.242,95.5,96.9
6,Медеуский район,107.951,110.572,111.403,112.564,113.901,115.246,119.116,124.5,126.6
7,Наурызбайский район,47.488,52.588,58.233,63.818,66.647,70.037,73.417,82.7,92.3
8,Турксибский район,107.399,109.510,110.491,112.569,113.822,116.131,114.714,115.7,121.5

In [247]:
alm_city_empl.columns = ['rayon', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

rayons = ['Almaty city', 'Almaly', 'Alatau', 'Auezov', 'Bostandyk', 'Zhetysu', 'Medeu', 'Nauryzbay', 'Turksib']

alm_city_empl['rayon'] = rayons

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    alm_city_empl[i] = alm_city_empl[i].astype(float)

almaty_city_employment = alm_city_empl.melt(id_vars='rayon', value_vars=[2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024], var_name='year', value_name='employment')
almaty_city_employment = almaty_city_employment.drop(almaty_city_employment[almaty_city_employment['rayon'] == 'Almaty city'].index)
almaty_city_employment

        rayon  year  employment
1      Almaly  2016     105.977
2      Alatau  2016     108.588
3      Auezov  2016     135.994
4   Bostandyk  2016     175.153
5     Zhetysu  2016      79.348
..        ...   ...         ...
76  Bostandyk  2024     169.800
77    Zhetysu  2024      96.900
78      Medeu  2024     126.600
79  Nauryzbay  2024      92.300
80    Turksib  2024     121.500

[72 rows x 3 columns]

In [248]:
# Suppose the column with the values is the second column in the dataframe
col_to_check = almaty_city_employment.columns[2]  # adjust index if needed

# Get the values for the two rows
value_auezov_2019 = almaty_city_employment.loc[
    (almaty_city_employment['rayon'] == 'Auezov') & (almaty_city_employment['year'] == 2019),
    col_to_check
].values

value_medeu_2021 = almaty_city_employment.loc[
    (almaty_city_employment['rayon'] == 'Medeu') & (almaty_city_employment['year'] == 2021),
    col_to_check
].values

# Check if both values match
if (len(value_auezov_2019) > 0 and value_auezov_2019[0] == 138.282) and \
   (len(value_medeu_2021) > 0 and value_medeu_2021[0] == 115.246):
    print("✅ The statement is TRUE")
else:
    print("❌ The statement is FALSE")

✅ The statement is TRUE

## Other Controls

In [249]:
alm_city_agriculture = pd.read_excel(Path("../Data/Controls/Almaty-city_Agriculture.xls"), skiprows=5, nrows=8, header=None, usecols='A:J', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
alm_city_agriculture

,0,1,2,3,4,5,6,7,8,9
0,Алмалинский,162.6,159.8,151.7,137.4,339.9,383.4,236.597798,271.0,259.1
1,Алатауский,1028.3,2290.8,3060.8,3372.6,3927.4,3947.9,647.325990,583.6,2688.6
2,Ауэзовский,98.8,112.5,106.1,97.8,138.6,158.1,170.283512,189.7,198.4
3,Бостандыкский,243.4,276.3,293.4,337.9,276.0,242.3,264.189846,221.7,207.1
4,Жетысуский,390.0,389.2,396.0,402.1,533.5,638.8,654.789267,674.9,878.0
5,Медеуский,1133.8,1188.5,1258.8,1090.1,1293.4,1382.4,1517.635497,1558.5,1611.5
6,Наурызбайский,610.9,697.6,739.6,784.2,669.3,669.1,803.838749,737.9,815.8
7,Турксибский,574.4,625.4,588.1,577.2,633.9,637.6,768.566678,816.3,863.0

In [250]:
alm_city_agriculture.columns = ['rayon', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

rayons = ['Almaly', 'Alatau', 'Auezov', 'Bostandyk', 'Zhetysu', 'Medeu', 'Nauryzbay', 'Turksib']

alm_city_agriculture['rayon'] = rayons

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    alm_city_agriculture[i] = alm_city_agriculture[i].astype(float)

alm_city_agriculture = alm_city_agriculture.melt(id_vars='rayon', value_vars=[2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024], var_name='year', value_name='agriculture')

alm_city_agriculture

        rayon  year  agriculture
0      Almaly  2016        162.6
1      Alatau  2016       1028.3
2      Auezov  2016         98.8
3   Bostandyk  2016        243.4
4     Zhetysu  2016        390.0
..        ...   ...          ...
67  Bostandyk  2024        207.1
68    Zhetysu  2024        878.0
69      Medeu  2024       1611.5
70  Nauryzbay  2024        815.8
71    Turksib  2024        863.0

[72 rows x 3 columns]

In [251]:
alm_city_production = pd.read_excel(Path("../Data/Controls/Almaty-city_Production.xls"), skiprows=5, nrows=8, header=None, usecols='A, N:W', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
alm_city_production

,0,13,14,15,16,17,18,19,20,21,22
0,Алмалинский,177593,139707,135299,164771,174712,161575,167823,179846,199116.594,214325
1,Алатауский,57798,58493,72024,80516,82285,82963,153066,319838,531133.323,686665
2,Ауэзовский,81428,78484,93774,97488,103597,117729,108058,119953,110288.130,113587
3,Бостандыкский,69567,67158,85958,79128,75067,85340,77117,81877,94214.425,105327
4,Жетысуский,156689,143948,163340,195238,198904,226336,241574,272916,313820.167,373765
5,Медеуский,96634,81056,111310,132437,112883,119612,105270,110515,147888.826,159742
6,Наурызбайский,2500,3691,2771,4425,4541,5750,6698,7467,13543.330,16072
7,Турксибский,96738,90444,112321,148534,165896,201882,222036,289077,351680.605,423984

In [252]:
alm_city_production.columns = ['rayon', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]

rayons = ['Almaly', 'Alatau', 'Auezov', 'Bostandyk', 'Zhetysu', 'Medeu', 'Nauryzbay', 'Turksib']

alm_city_production['rayon'] = rayons

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    alm_city_production[i] = alm_city_production[i].astype(float)

alm_city_production = alm_city_production.melt(id_vars='rayon', value_vars=[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023], var_name='year', value_name='production')

alm_city_production

        rayon  year  production
0      Almaly  2014    177593.0
1      Alatau  2014     57798.0
2      Auezov  2014     81428.0
3   Bostandyk  2014     69567.0
4     Zhetysu  2014    156689.0
..        ...   ...         ...
75  Bostandyk  2023    105327.0
76    Zhetysu  2023    373765.0
77      Medeu  2023    159742.0
78  Nauryzbay  2023     16072.0
79    Turksib  2023    423984.0

[80 rows x 3 columns]

In [253]:
alm_city_retail = pd.read_excel(Path("../Data/Controls/Almaty-city_Retail.xlsx"), sheet_name="торговля", skiprows=3, nrows=8, header=None, usecols='A, Z:AI', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
alm_city_retail

,0,25,26,27,28,29,30,31,32,33,34
0,Алмалинский,267.0,376.1,501.2,"595,9",681,752.2,698.702394,753.307509,720.144096,883.0
1,Алатауский,148.0,173.1,120.0,"198,7","242,9",259.3,250.744501,291.947888,403.268541,566.0
2,Ауэзовский,188.4,236.0,292.8,"260,6","293,3",313.3,435.820219,480.314931,648.917828,595.0
3,Бостандыкский,190.7,230.3,412.2,"380,6",425,458.5,445.278094,604.339752,787.799910,1347.1
4,Жетысуский,399.9,326.9,373.1,"463,0","549,3",786.4,825.262645,997.470933,1119.949847,853.6
5,Медеуский,269.0,329.1,315.1,"325,3","362,8",486.8,443.716982,486.243614,731.891218,1449.5
6,Наурызбайский,0.2,0.2,5.6,"11,6","15,8",25.4,16.651234,17.016829,118.502886,54.3
7,Түрксибский,178.1,114.9,173.7,"222,8","281,6",300.8,315.503018,413.851454,653.143315,552.7

In [254]:
alm_city_retail.columns = ['rayon', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]

rayons = ['Almaly', 'Alatau', 'Auezov', 'Bostandyk', 'Zhetysu', 'Medeu', 'Nauryzbay', 'Turksib']

alm_city_retail['rayon'] = rayons

# Replace commas with dots and convert to float
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    alm_city_retail[i] = alm_city_retail[i].astype(str).str.replace(',', '.').astype(float)


alm_city_retail = alm_city_retail.melt(
    id_vars='rayon', 
    value_vars=[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023], 
    var_name='year', 
    value_name='retail'
)

alm_city_retail

        rayon  year  retail
0      Almaly  2014   267.0
1      Alatau  2014   148.0
2      Auezov  2014   188.4
3   Bostandyk  2014   190.7
4     Zhetysu  2014   399.9
..        ...   ...     ...
75  Bostandyk  2023  1347.1
76    Zhetysu  2023   853.6
77      Medeu  2023  1449.5
78  Nauryzbay  2023    54.3
79    Turksib  2023   552.7

[80 rows x 3 columns]

In [255]:
# Merge production and retail first
merged_df = pd.merge(
    alm_city_production,
    alm_city_retail,
    on=['rayon', 'year'],
    how='outer'
)

# Merge the result with agriculture
merged_df = pd.merge(
    merged_df,
    alm_city_agriculture,
    on=['rayon', 'year'],
    how='outer'
)

# Optional: sort by rayon and year for clarity
merged_df = merged_df.sort_values(['rayon', 'year']).reset_index(drop=True)

almaty_city_controls = merged_df

In [256]:
almaty_city_controls

      rayon  year  production       retail  agriculture
0    Alatau  2014   57798.000   148.000000          NaN
1    Alatau  2015   58493.000   173.100000          NaN
2    Alatau  2016   72024.000   120.000000  1028.300000
3    Alatau  2017   80516.000   198.700000  2290.800000
4    Alatau  2018   82285.000   242.900000  3060.800000
..      ...   ...         ...          ...          ...
83  Zhetysu  2020  241574.000   825.262645   533.500000
84  Zhetysu  2021  272916.000   997.470933   638.800000
85  Zhetysu  2022  313820.167  1119.949847   654.789267
86  Zhetysu  2023  373765.000   853.600000   674.900000
87  Zhetysu  2024         NaN          NaN   878.000000

[88 rows x 5 columns]

## PPI

In [257]:
# 1. Read PPI data
alm_city_ppi_raw = pd.read_excel(
    Path("../Data/PPI/Almaty-city.xls"),
    header=3,
    usecols='X:AH',
    nrows=8,
    na_values=['x', 'х', '-', '', ' ', '...']
)

# 2. Select the needed row (4th from bottom)
alm_city_ppi_raw = alm_city_ppi_raw.iloc[[-4]]

# 3. Assign year columns
alm_city_ppi_raw.columns = [
    2014, 2015, 2016, 2017, 2018,
    2019, 2020, 2021, 2022, 2023, 2024
]

# 4. Extract PPI values correctly (1D array)
ppi_values = alm_city_ppi_raw.iloc[0].values

# 5. Get rayons
rayons = alm_city_inv['rayon'].unique()

# 6. Build long-format dataframe
dfs = []
for rayon in rayons:
    df_temp = pd.DataFrame({
        'rayon': rayon,
        'year': range(2014, 2025),
        'ppi': ppi_values
    })
    dfs.append(df_temp)

alm_city_ppi = pd.concat(dfs, ignore_index=True)

# 7. Clean PPI values
alm_city_ppi['ppi'] = (
    alm_city_ppi['ppi']
    .astype(str)
    .str.replace(',', '.', regex=False)
    .str.replace(')', '', regex=False)
    .str.replace(' ', '', regex=False)
    .str.replace('\xa0', '', regex=False)
    .str.replace('*', '', regex=False)
    .astype(float)
)

# 8. Result
alm_city_ppi

      rayon  year    ppi
0    Alatau  2014  108.6
1    Alatau  2015  108.8
2    Alatau  2016  106.9
3    Alatau  2017  107.2
4    Alatau  2018  104.1
..      ...   ...    ...
83  Turksib  2020  105.4
84  Turksib  2021  111.9
85  Turksib  2022  113.6
86  Turksib  2023  104.5
87  Turksib  2024  106.9

[88 rows x 3 columns]

## Combine together

In [258]:
alm_city_inv

,rayon,l_all_inv,f_all_inv,oblast,year,f_nonextr_inv,l_nonextr_inv
0,Alatau,67882858,2243243,Almaty city,2014,NaN,NaN
1,Almaly,63327488,14630326,Almaty city,2014,NaN,NaN
2,Auezov,52040160,4198961,Almaty city,2014,NaN,NaN
3,Bostandyk,99621172,20702397,Almaty city,2014,NaN,NaN
4,Zhetysu,24994713,4240792,Almaty city,2014,NaN,NaN
...,...,...,...,...,...,...,...
83,Bostandyk,366325868,62253611,Almaty city,2024,62253611.0,334022739.0
84,Zhetysu,103191108,20970208,Almaty city,2024,20970208.0,84390763.0
85,Medeu,213096634,71343200,Almaty city,2024,71343200.0,193141098.0
86,Nauryzbay,170206701,2543118,Almaty city,2024,2543118.0,116950164.0
87,Turksib,164160914,53781169,Almaty city,2024,53781169.0,145595431.0

In [259]:
dfs = [alm_city_inv, almaty_city_employment, almaty_city_controls, alm_city_ppi]
alm_city_merged = reduce(lambda left, right: pd.merge(left, right, on=['rayon', 'year'], how='outer'), dfs)
alm_city_merged

,rayon,l_all_inv,f_all_inv,oblast,year,f_nonextr_inv,l_nonextr_inv,employment,production,retail,agriculture,ppi
0,Alatau,67882858,2243243,Almaty city,2014,NaN,NaN,NaN,57798.000,148.000000,NaN,108.6
1,Alatau,99119106,902986,Almaty city,2015,NaN,NaN,NaN,58493.000,173.100000,NaN,108.8
2,Alatau,65812135,1411132,Almaty city,2016,NaN,NaN,108.588,72024.000,120.000000,1028.300000,106.9
3,Alatau,56574397,3348217,Almaty city,2017,NaN,NaN,118.651,80516.000,198.700000,2290.800000,107.2
4,Alatau,81836001,4553715,Almaty city,2018,4553715.0,43895959.0,127.609,82285.000,242.900000,3060.800000,104.1
...,...,...,...,...,...,...,...,...,...,...,...,...
83,Zhetysu,41089088,8166843,Almaty city,2020,8166843.0,33584355.0,83.292,241574.000,825.262645,533.500000,105.4
84,Zhetysu,60210191,8852288,Almaty city,2021,8852288.0,50765615.0,84.477,272916.000,997.470933,638.800000,111.9
85,Zhetysu,64277226,19425879,Almaty city,2022,19425879.0,51099186.0,93.242,313820.167,1119.949847,654.789267,113.6
86,Zhetysu,85565861,17744313,Almaty city,2023,17744313.0,71935568.0,95.500,373765.000,853.600000,674.900000,104.5
87,Zhetysu,103191108,20970208,Almaty city,2024,20970208.0,84390763.0,96.900,NaN,NaN,878.000000,106.9

# Akmola

## Investments

In [260]:
akmola_all_2014 = pd.read_excel(Path("../Data/Investments/Akmola/2014_Investments/Internal_vs_external.xls"), header=7, nrows=20, usecols='A, C, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
akmola_all_2016 = pd.read_excel(Path("../Data/Investments/Akmola/2016_Investments/Internal_vs_external.xls"), header=8, nrows=20, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
akmola_all_2017 = pd.read_excel(Path("../Data/Investments/Akmola/2017_Investments/Internal_vs_external.xls"), header=8, nrows=20, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
akmola_all_2018 = pd.read_excel(Path("../Data/Investments/Akmola/2018_Investments/Internal_vs_external.xls"), header=6, nrows=20, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
akmola_all_2019 = pd.read_excel(Path("../Data/Investments/Akmola/2019_Investments.xls"), sheet_name='14', header=3, nrows=20, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
akmola_all_2020 = pd.read_excel(Path("../Data/Investments/Akmola/2020_Investments.xls"), sheet_name='13', header=3, nrows=20, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
akmola_all_2021 = pd.read_excel(Path("../Data/Investments/Akmola/2021_Investments.xls"), sheet_name='13', header=3, nrows=20, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
akmola_all_2022 = pd.read_excel(Path("../Data/Investments/Akmola/2022_Investments.xlsx"), sheet_name='21', header=3, nrows=21, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
akmola_all_2023 = pd.read_excel(Path("../Data/Investments/Akmola/2023_Investments.xlsx"), sheet_name='21', header=3, nrows=21, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
akmola_all_2024 = pd.read_excel(Path("../Data/Investments/Akmola/2024_Investments.xlsx"), sheet_name='14', header=3, nrows=21, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)


akmola_non_2014 = pd.read_excel(Path("../Data/Investments/Akmola/2014_Investments/Greenfield_investments.xls"), header=7, nrows=20, usecols='A, B, C', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
akmola_non_2016 = pd.read_excel(Path("../Data/Investments/Akmola/2016_Investments/Greenfield_investments.xls"), header=7, nrows=20, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
akmola_non_2017 = pd.read_excel(Path("../Data/Investments/Akmola/2017_Investments/Greenfield_investments.xls"), header=7, nrows=20, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
akmola_non_2018 = pd.read_excel(Path("../Data/Investments/Akmola/2018_Investments/Greenfield_investments.xls"), header=5, nrows=20, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
akmola_non_2019 = pd.read_excel(Path("../Data/Investments/Akmola/2019_Investments.xls"), sheet_name='15', header=3, nrows=20, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
akmola_non_2020 = pd.read_excel(Path("../Data/Investments/Akmola/2020_Investments.xls"), sheet_name='14', header=3, nrows=20, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
akmola_non_2021 = pd.read_excel(Path("../Data/Investments/Akmola/2021_Investments.xls"), sheet_name='14', header=3, nrows=21, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
akmola_non_2022 = pd.read_excel(Path("../Data/Investments/Akmola/2022_Investments.xlsx"), sheet_name='22', header=3, nrows=21, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
akmola_non_2023 = pd.read_excel(Path("../Data/Investments/Akmola/2023_Investments.xlsx"), sheet_name='22', header=3, nrows=21, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
akmola_non_2024 = pd.read_excel(Path("../Data/Investments/Akmola/2024_Investments.xlsx"), sheet_name='15', header=3, nrows=21, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [261]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [akmola_all_2014,
           akmola_all_2016, akmola_all_2017, akmola_all_2018,
           akmola_all_2019, akmola_all_2020, akmola_all_2021,
           akmola_all_2022, akmola_all_2023, akmola_all_2024]:
    df.columns = all_columns

for df in [akmola_non_2014, akmola_non_2016,
           akmola_non_2017, akmola_non_2018, akmola_non_2019,
           akmola_non_2020, akmola_non_2021, akmola_non_2022,
           akmola_non_2023, akmola_non_2024]:
    df.columns = non_columns
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

In [262]:
rayon_map = {
    # Kazakh names (from akmola_all)
    'Көкшетау қ.ә.': 'Kokshetau city',
    'Степногор қ.ә.': 'Stepnogorsk city',
    'Ақкөл ': 'Akkol',
    'Аршалы ': 'Arshaly',
    'Астрахан ': 'Astrakhan',
    'Атбасар ': 'Atbasar',
    'Бұланды ': 'Bulandy',
    'Бурабай ': 'Burabay',
    'Егіндікөл ': 'Egindykol',
    'Еңбекшілдер ': 'Enbekshilder',
    'Ерейментау ': 'Ereymentau',
    'Есіл ': 'Yesil',
    'Жақсы ': 'Zhaksyn',
    'Жарқайың ': 'Zharkain',
    'Зеренді ': 'Zerendi',
    'Қорғалжын ': 'Korgalzhyn',
    'Сандықтау ': 'Sandyktau',
    'Целиноград ': 'Tselinograd',
    'Шортанды ': 'Shortandy',
    'Степногорск қ.ә.': 'Stepnogorsk city',
    'Қосшы қ.ә.': 'Kosshi city',
    'Біржан сал': 'Birzhan Sal',

    # Russian names (from akmola_non)
    'г.а. Кокшетау ': 'Kokshetau city',
    'г.а. Косшы': 'Kosshi city',
    'г.а. Степногорска': 'Stepnogorsk city',
    'Аккольский': 'Akkol',
    'Аршалынский': 'Arshaly',
    'Астраханский': 'Astrakhan',
    'Атбасарский': 'Atbasar',
    'Буландынский': 'Bulandy',
    'Егиндыкольский': 'Egindykol',
    'Биржан сал': 'Birzhan Sal',
    'Ерейментауский': 'Ereymentau',
    'Есильский': 'Yesil',
    'Жаксынский': 'Zhaksyn',
    'Жаркаинский': 'Zharkain',
    'Зерендинский': 'Zerendi',
    'Коргалжынский': 'Korgalzhyn',
    'Сандыктауский': 'Sandyktau',
    'Целиноградский': 'Tselinograd',
    'Шортандинский': 'Shortandy',
    'Бурабайский': 'Burabay'
}

In [263]:
# ----- ALL investments -----
akmola_all_2014['rayon'] = akmola_all_2014['rayon'].replace(rayon_map)
akmola_all_2016['rayon'] = akmola_all_2016['rayon'].replace(rayon_map)
akmola_all_2017['rayon'] = akmola_all_2017['rayon'].replace(rayon_map)
akmola_all_2018['rayon'] = akmola_all_2018['rayon'].replace(rayon_map)
akmola_all_2019['rayon'] = akmola_all_2019['rayon'].replace(rayon_map)
akmola_all_2020['rayon'] = akmola_all_2020['rayon'].replace(rayon_map)
akmola_all_2021['rayon'] = akmola_all_2021['rayon'].replace(rayon_map)
akmola_all_2022['rayon'] = akmola_all_2022['rayon'].replace(rayon_map)
akmola_all_2023['rayon'] = akmola_all_2023['rayon'].replace(rayon_map)
akmola_all_2024['rayon'] = akmola_all_2024['rayon'].replace(rayon_map)

# ----- NON-extractive investments -----
akmola_non_2014['rayon'] = akmola_non_2014['rayon'].replace(rayon_map)
akmola_non_2016['rayon'] = akmola_non_2016['rayon'].replace(rayon_map)
akmola_non_2017['rayon'] = akmola_non_2017['rayon'].replace(rayon_map)
akmola_non_2018['rayon'] = akmola_non_2018['rayon'].replace(rayon_map)
akmola_non_2019['rayon'] = akmola_non_2019['rayon'].replace(rayon_map)
akmola_non_2020['rayon'] = akmola_non_2020['rayon'].replace(rayon_map)
akmola_non_2021['rayon'] = akmola_non_2021['rayon'].replace(rayon_map)
akmola_non_2022['rayon'] = akmola_non_2022['rayon'].replace(rayon_map)
akmola_non_2023['rayon'] = akmola_non_2023['rayon'].replace(rayon_map)
akmola_non_2024['rayon'] = akmola_non_2024['rayon'].replace(rayon_map)

In [264]:
akmola_2016 = akmola_all_2016.merge(akmola_non_2016, on='rayon', how='left')
akmola_2017 = akmola_all_2017.merge(akmola_non_2017, on='rayon', how='left')
akmola_2018 = akmola_all_2018.merge(akmola_non_2018, on='rayon', how='left')
akmola_2019 = akmola_all_2019.merge(akmola_non_2019, on='rayon', how='left')
akmola_2020 = akmola_all_2020.merge(akmola_non_2020, on='rayon', how='left')
akmola_2021 = akmola_all_2021.merge(akmola_non_2021, on='rayon', how='left')
akmola_2022 = akmola_all_2022.merge(akmola_non_2022, on='rayon', how='left')
akmola_2023 = akmola_all_2023.merge(akmola_non_2023, on='rayon', how='left')
akmola_2024 = akmola_all_2024.merge(akmola_non_2024, on='rayon', how='left')

dfs = [akmola_2016, akmola_2017, akmola_2018, akmola_2019, akmola_2020, akmola_2021, akmola_2022, akmola_2023, akmola_2024]

for i in range(9):
    df = dfs[i]
    df['oblast'] = 'Akmola'
    df['year'] = 2016 + i

akmola_inv = pd.concat([akmola_2016, akmola_2017, akmola_2018, akmola_2019, akmola_2020, akmola_2021, akmola_2022, akmola_2023, akmola_2024], ignore_index=True)
akmola_inv['rayon'] = (
    akmola_inv['rayon']
        .str.strip()          # remove hidden spaces
        .replace(rayon_map)   # enforce English names
)
akmola_inv

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year
0,Kokshetau city,28483097.0,1720145.0,1592194.0,22048177.0,Akmola,2016
1,Stepnogorsk city,7135367.0,4690126.0,942576.0,6250538.0,Akmola,2016
2,Akkol,9483391.0,52136.0,52136.0,1300876.0,Akmola,2016
3,Arshaly,27601041.0,33322.0,29725.0,4011761.0,Akmola,2016
4,Astrakhan,6633931.0,7680.0,7680.0,1050818.0,Akmola,2016
...,...,...,...,...,...,...,...
169,Korgalzhyn,0.0,0.0,0.0,1122427.0,Akmola,2024
170,Sandyktau,9467141.0,96416.0,0.0,1959891.0,Akmola,2024
171,Tselinograd,112624504.0,11264.0,11264.0,30733788.0,Akmola,2024
172,Shortandy,13345883.0,678564.0,0.0,4054668.0,Akmola,2024
173,Burabay,32850159.0,9706286.0,5575635.0,16587025.0,Akmola,2024

In [265]:
akmola_2014 = akmola_all_2014.merge(akmola_non_2014, on='rayon', how='left')
akmola_2014['oblast'] = 'Akmola'
akmola_2014['year'] = 2014
akmola_2014

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year
0,Kokshetau city,25362109,1187782,1187782.0,18402222.0,Akmola,2014
1,Stepnogorsk city,5797836,2960574,1637284.0,2956251.0,Akmola,2014
2,Akkol,4538180,33806,33806.0,1380767.0,Akmola,2014
3,Arshaly,16840780,460895,402926.0,5001929.0,Akmola,2014
4,Astrakhan,3189134,236788,51388.0,354737.0,Akmola,2014
5,Atbasar,5773568,83754,83754.0,3079041.0,Akmola,2014
6,Bulandy,4944398,222326,209247.0,1355944.0,Akmola,2014
7,Burabay,11441072,167488,167488.0,3221601.0,Akmola,2014
8,Egindykol,1896090,33291,6275.0,1040371.0,Akmola,2014
9,Enbekshilder,27747393,335245,99294.0,25435349.0,Akmola,2014
10,Ereymentau,10605765,2129673,2129673.0,9650125.0,Akmola,2014
11,Yesil,4445182,44866,44866.0,3424336.0,Akmola,2014
12,Zhaksyn,2152768,29658,29658.0,350538.0,Akmola,2014
13,Zharkain,3243157,98529,96464.0,1071602.0,Akmola,2014
14,Zerendi,7443949,392166,63454.0,1663870.0,Akmola,2014
15,Korgalzhyn,1908865,3233,3233.0,409347.0,Akmola,2014
16,Sandyktau,3567018,164391,164391.0,922389.0,Akmola,2014
17,Tselinograd,28691450,27408,27408.0,5584826.0,Akmola,2014
18,Shortandy,2869600,71446,0.0,1088540.0,Akmola,2014

In [266]:
akmola_inv = pd.concat([akmola_2014, akmola_inv], ignore_index=True)
akmola_inv

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year
0,Kokshetau city,25362109.0,1187782.0,1187782.0,18402222.0,Akmola,2014
1,Stepnogorsk city,5797836.0,2960574.0,1637284.0,2956251.0,Akmola,2014
2,Akkol,4538180.0,33806.0,33806.0,1380767.0,Akmola,2014
3,Arshaly,16840780.0,460895.0,402926.0,5001929.0,Akmola,2014
4,Astrakhan,3189134.0,236788.0,51388.0,354737.0,Akmola,2014
...,...,...,...,...,...,...,...
188,Korgalzhyn,0.0,0.0,0.0,1122427.0,Akmola,2024
189,Sandyktau,9467141.0,96416.0,0.0,1959891.0,Akmola,2024
190,Tselinograd,112624504.0,11264.0,11264.0,30733788.0,Akmola,2024
191,Shortandy,13345883.0,678564.0,0.0,4054668.0,Akmola,2024
192,Burabay,32850159.0,9706286.0,5575635.0,16587025.0,Akmola,2024

In [267]:
akmola_inv['rayon'].unique()

array(['Kokshetau city', 'Stepnogorsk city', 'Akkol', 'Arshaly',
       'Astrakhan', 'Atbasar', 'Bulandy', 'Burabay', 'Egindykol',
       'Enbekshilder', 'Ereymentau', 'Yesil', 'Zhaksyn', 'Zharkain',
       'Zerendi', 'Korgalzhyn', 'Sandyktau', 'Tselinograd', 'Shortandy',
       'Birzhan Sal', 'Kosshi city'], dtype=object)

## Employment

In [268]:
akmola_empl = pd.read_excel(Path("../Data/Employment/Akmola.xlsx"), skiprows=32, nrows=20, header=None, usecols='A:L', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
akmola_empl

,0,1,2,3,4,5,6,7,8,9,10,11
0,г.а. Кокшетау,88.5,90.7,91.9,92.4,91.4,91.0,86.7,86.3,98.9,90.0,90.7
1,г.а. Косшы,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26.6,27.8,29.1
2,г.а. Степногорска,38.1,38.2,39.9,39.4,39.2,38.7,36.6,35.9,36.0,34.0,34.0
3,Аккольский,15.0,13.7,13.2,12.6,13.0,12.8,12.6,13.2,12.8,13.1,12.0
4,Аршалынский,16.2,14.6,15.0,14.5,14.7,14.7,14.7,14.9,13.8,14.0,13.7
5,Астраханский,14.9,14.0,14.1,13.6,13.8,13.7,13.6,12.9,11.4,10.7,10.4
6,Атбасарский,29.3,28.1,28.0,27.4,27.0,26.7,25.6,25.0,23.1,22.7,22.9
7,Буландынский,19.5,17.7,18.0,17.9,17.8,17.6,17.7,18.5,16.8,15.0,14.3
8,Егиндыкольский,3.5,3.3,3.4,3.0,3.2,3.2,3.1,2.6,2.8,2.9,2.6
9,Биржан сал,9.3,8.5,8.4,8.1,7.6,7.4,7.0,6.8,6.9,6.6,6.3
10,Ерейментауский,15.8,14.6,14.7,13.9,13.8,13.6,13.8,12.8,13.5,12.1,12.3
11,Есильский,15.4,14.0,14.4,14.0,13.6,13.2,12.8,12.4,12.2,12.0,11.3
12,Жаксынский,12.0,11.2,11.4,11.0,10.9,10.8,10.3,10.1,8.7,8.4,8.3
13,Жаркаинский,8.7,8.1,8.3,7.9,7.9,7.8,7.4,7.1,7.2,7.0,6.3
14,Зерендинский,23.5,22.3,21.6,21.0,20.8,21.0,19.6,19.6,18.9,18.4,17.5
15,Коргалжынский,5.2,4.9,4.7,4.4,4.2,4.1,4.0,4.2,3.8,3.9,3.3
16,Сандыктауский,11.5,10.2,10.1,9.7,9.6,9.5,9.5,9.1,9.3,9.7,8.8
17,Целиноградский,35.4,35.2,38.0,37.2,39.7,41.4,43.2,46.0,40.9,40.5,42.5
18,Шортандинский,17.1,15.7,17.1,16.2,16.3,16.1,16.1,16.0,15.6,15.7,14.4
19,Бурабайский,43.8,43.1,44.2,44.1,44.2,44.7,43.7,43.6,42.2,42.6,41.1

In [269]:
akmola_empl.columns = ['rayon', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

rayons = ['Kokshetau city', 'Kosshi city', 'Stepnogorsk city', 'Akkol', 'Arshaly', 'Astrakhan', 'Atbasar', 'Bulandy',
         'Egindykol', 'Birzhan Sal', 'Ereymentau', 'Yesil', 'Zhaksyn', 'Zharkain', 'Zerendi', 'Korgalzhyn', 'Sandyktau',
         'Tselinograd', 'Shortandy', 'Burabay']

akmola_empl['rayon'] = rayons

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    akmola_empl[i] = akmola_empl[i].astype(float)

akmola_employment = akmola_empl.melt(id_vars='rayon', value_vars=[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024], var_name='year', value_name='employment')

akmola_employment

                rayon  year  employment
0      Kokshetau city  2014        88.5
1         Kosshi city  2014         0.0
2    Stepnogorsk city  2014        38.1
3               Akkol  2014        15.0
4             Arshaly  2014        16.2
..                ...   ...         ...
215        Korgalzhyn  2024         3.3
216         Sandyktau  2024         8.8
217       Tselinograd  2024        42.5
218         Shortandy  2024        14.4
219           Burabay  2024        41.1

[220 rows x 3 columns]

## Other Controls

In [270]:
kokshetau_city = pd.read_excel(Path("../Data/Controls/Akmola_All.xlsx"), sheet_name="г.а. Кокшетау", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

kokshetau_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
kokshetau_city = kokshetau_city.loc[[49, 81, 133]].reset_index(drop=True)
kokshetau_city['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    kokshetau_city[i] = kokshetau_city[i].astype(str)
    kokshetau_city[i] = kokshetau_city[i].str.replace(',', '.')
    kokshetau_city[i] = kokshetau_city[i].str.replace(')', '')
    kokshetau_city[i] = kokshetau_city[i].str.replace(' ', '')
    kokshetau_city[i] = kokshetau_city[i].str.replace('\xa0', '')
    kokshetau_city[i] = kokshetau_city[i].str.replace('*', '')
    kokshetau_city[i] = kokshetau_city[i].astype(float)

kokshetau_city = pd.melt(kokshetau_city, id_vars=['Indicator'], var_name='year', value_name='value')
kokshetau_city = kokshetau_city.pivot(index='year', columns='Indicator', values='value').reset_index()
kokshetau_city.insert(0, 'rayon', 'Kokshetau city')
kokshetau_city.columns.name = None
kokshetau_city

            rayon  year  agriculture  production    retail
0  Kokshetau city  2014  1964.000000     82158.1   97495.8
1  Kokshetau city  2015  3212.900000     83694.5  104833.6
2  Kokshetau city  2016  3481.400000     99581.4  124935.2
3  Kokshetau city  2017  4320.600000    106302.3  144202.6
4  Kokshetau city  2018  4774.900000    105998.9  184575.9
5  Kokshetau city  2019  5070.600000    112034.8  199561.8
6  Kokshetau city  2020  5855.100000    178650.5  165988.7
7  Kokshetau city  2021  7895.245308    237133.6  138971.2
8  Kokshetau city  2022  8912.227875    264376.4  185993.7
9  Kokshetau city  2023  7302.800000    313518.2  185855.8

In [271]:
kosshi_city = pd.read_excel(Path("../Data/Controls/Akmola_All.xlsx"), sheet_name="г.а. Косшы", header=2, usecols='A:G', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

kosshi_city.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
kosshi_city = kosshi_city.loc[[49, 81, 133]].reset_index(drop=True)
kosshi_city['Indicator'] = ['production', 'agriculture', 'retail']

kosshi_city = pd.melt(kosshi_city, id_vars=['Indicator'], var_name='year', value_name='value')
kosshi_city = kosshi_city.pivot(index='year', columns='Indicator', values='value').reset_index()
kosshi_city.insert(0, 'rayon', 'Kosshi city')
kosshi_city.columns.name = None
kosshi_city

         rayon  year agriculture production  retail
0  Kosshi city  2018         NaN        NaN     NaN
1  Kosshi city  2019         NaN        NaN     NaN
2  Kosshi city  2020         NaN          …     NaN
3  Kosshi city  2021  545.874354     8819.5  3777.3
4  Kosshi city  2022  726.785613     9117.6  5313.2
5  Kosshi city  2023         475    11911.3  6892.5

In [272]:
stepnogorsk_city = pd.read_excel(Path("../Data/Controls/Akmola_All.xlsx"), sheet_name="г.а.Степногорск", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

stepnogorsk_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
stepnogorsk_city = stepnogorsk_city.loc[[49, 81, 133]].reset_index(drop=True)
stepnogorsk_city['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    stepnogorsk_city[i] = stepnogorsk_city[i].astype(str)
    stepnogorsk_city[i] = stepnogorsk_city[i].str.replace(',', '.')
    stepnogorsk_city[i] = stepnogorsk_city[i].str.replace(')', '')
    stepnogorsk_city[i] = stepnogorsk_city[i].str.replace(' ', '')
    stepnogorsk_city[i] = stepnogorsk_city[i].str.replace('\xa0', '')
    stepnogorsk_city[i] = stepnogorsk_city[i].str.replace('*', '')
    stepnogorsk_city[i] = stepnogorsk_city[i].astype(float)

stepnogorsk_city = pd.melt(stepnogorsk_city, id_vars=['Indicator'], var_name='year', value_name='value')
stepnogorsk_city = stepnogorsk_city.pivot(index='year', columns='Indicator', values='value').reset_index()
stepnogorsk_city.insert(0, 'rayon', 'Stepnogorsk city')
stepnogorsk_city.columns.name = None
stepnogorsk_city

              rayon  year  agriculture  production   retail
0  Stepnogorsk city  2014  2212.100000     69044.3  15462.6
1  Stepnogorsk city  2015  2899.200000     69540.3  16615.6
2  Stepnogorsk city  2016  3152.800000     95937.9  25011.5
3  Stepnogorsk city  2017  3839.800000     94195.4  28213.6
4  Stepnogorsk city  2018  3968.056169    140072.9  27546.4
5  Stepnogorsk city  2019  4166.300000    165779.6  27546.4
6  Stepnogorsk city  2020  4904.800000    192799.0  25246.5
7  Stepnogorsk city  2021  6638.288706    194574.1  21382.5
8  Stepnogorsk city  2022  8263.969195    405339.9  18986.7
9  Stepnogorsk city  2023  5648.500000    408753.0  29431.2

In [273]:
akkol = pd.read_excel(Path("../Data/Controls/Akmola_All.xlsx"), sheet_name="Аккольский", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

akkol.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
akkol = akkol.loc[[49, 81, 133]].reset_index(drop=True)
akkol['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    akkol[i] = akkol[i].astype(str)
    akkol[i] = akkol[i].str.replace(',', '.')
    akkol[i] = akkol[i].str.replace(')', '')
    akkol[i] = akkol[i].str.replace(' ', '')
    akkol[i] = akkol[i].str.replace('\xa0', '')
    akkol[i] = akkol[i].str.replace('*', '')
    akkol[i] = akkol[i].astype(float)

akkol = pd.melt(akkol, id_vars=['Indicator'], var_name='year', value_name='value')
akkol = akkol.pivot(index='year', columns='Indicator', values='value').reset_index()
akkol.insert(0, 'rayon', 'Akkol')
akkol.columns.name = None
akkol

   rayon  year   agriculture  production  retail
0  Akkol  2014   8460.500000      4355.1  6016.3
1  Akkol  2015  10851.500000      4219.1  5663.1
2  Akkol  2016  12535.400000      4536.8  5455.5
3  Akkol  2017  14226.700000      5871.0  6933.5
4  Akkol  2018  15488.055535      4678.0  6941.0
5  Akkol  2019  18875.200000      5012.7  5580.6
6  Akkol  2020  25483.700000      5688.2  3511.7
7  Akkol  2021  29131.844423      6045.4  7973.2
8  Akkol  2022  41323.748640      6559.6  8527.1
9  Akkol  2023  22405.600000      6306.6  7289.4

In [274]:
arshaly = pd.read_excel(Path("../Data/Controls/Akmola_All.xlsx"), sheet_name="Аршалынский", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

arshaly.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
arshaly = arshaly.loc[[49, 81, 133]].reset_index(drop=True)
arshaly['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    arshaly[i] = arshaly[i].astype(str)
    arshaly[i] = arshaly[i].str.replace(',', '.')
    arshaly[i] = arshaly[i].str.replace(')', '')
    arshaly[i] = arshaly[i].str.replace(' ', '')
    arshaly[i] = arshaly[i].str.replace('\xa0', '')
    arshaly[i] = arshaly[i].str.replace('*', '')
    arshaly[i] = arshaly[i].astype(float)

arshaly = pd.melt(arshaly, id_vars=['Indicator'], var_name='year', value_name='value')
arshaly = arshaly.pivot(index='year', columns='Indicator', values='value').reset_index()
arshaly.insert(0, 'rayon', 'Arshaly')
arshaly.columns.name = None
arshaly

     rayon  year   agriculture  production   retail
0  Arshaly  2014  11936.600000     14691.2   5666.8
1  Arshaly  2015  13316.600000     16252.5   5207.5
2  Arshaly  2016  16140.700000     18133.6   5738.6
3  Arshaly  2017  16702.300000     14871.5  10888.4
4  Arshaly  2018  20312.084189     16165.9   7496.1
5  Arshaly  2019  21268.900000     19988.1   7444.1
6  Arshaly  2020  33048.200000     25277.7   6119.6
7  Arshaly  2021  36128.323503     38620.7   6342.9
8  Arshaly  2022  45754.242292     54048.4   7106.4
9  Arshaly  2023  33242.600000     83290.7  12154.2

In [275]:
astrakhan = pd.read_excel(Path("../Data/Controls/Akmola_All.xlsx"), sheet_name="Астраханский", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

astrakhan.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
astrakhan = astrakhan.loc[[49, 81, 133]].reset_index(drop=True)
astrakhan['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    astrakhan[i] = astrakhan[i].astype(str)
    astrakhan[i] = astrakhan[i].str.replace(',', '.')
    astrakhan[i] = astrakhan[i].str.replace(')', '')
    astrakhan[i] = astrakhan[i].str.replace(' ', '')
    astrakhan[i] = astrakhan[i].str.replace('\xa0', '')
    astrakhan[i] = astrakhan[i].str.replace('*', '')
    astrakhan[i] = astrakhan[i].astype(float)

astrakhan = pd.melt(astrakhan, id_vars=['Indicator'], var_name='year', value_name='value')
astrakhan = astrakhan.pivot(index='year', columns='Indicator', values='value').reset_index()
astrakhan.insert(0, 'rayon', 'Astrakhan')
astrakhan.columns.name = None
astrakhan

       rayon  year   agriculture  production   retail
0  Astrakhan  2014  16283.200000      3579.1  2341.10
1  Astrakhan  2015  18474.700000      4649.9  2488.60
2  Astrakhan  2016  23330.400000      6152.3  3805.50
3  Astrakhan  2017  23463.400000      4241.3  4174.99
4  Astrakhan  2018  27680.350539      4859.8  3028.80
5  Astrakhan  2019  30850.100000      4134.9  7147.10
6  Astrakhan  2020  45347.400000      4466.8  5358.20
7  Astrakhan  2021  50705.543561      4619.1  3048.70
8  Astrakhan  2022  61077.411544      5477.4  8679.50
9  Astrakhan  2023  39616.600000      6685.8  4846.90

In [276]:
atbasar = pd.read_excel(Path("../Data/Controls/Akmola_All.xlsx"), sheet_name="Атбасарский", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

atbasar.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
atbasar = atbasar.loc[[49, 81, 133]].reset_index(drop=True)
atbasar['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    atbasar[i] = atbasar[i].astype(str)
    atbasar[i] = atbasar[i].str.replace(',', '.')
    atbasar[i] = atbasar[i].str.replace(')', '')
    atbasar[i] = atbasar[i].str.replace(' ', '')
    atbasar[i] = atbasar[i].str.replace('\xa0', '')
    atbasar[i] = atbasar[i].str.replace('*', '')
    atbasar[i] = atbasar[i].astype(float)

atbasar = pd.melt(atbasar, id_vars=['Indicator'], var_name='year', value_name='value')
atbasar = atbasar.pivot(index='year', columns='Indicator', values='value').reset_index()
atbasar.insert(0, 'rayon', 'Atbasar')
atbasar.columns.name = None
atbasar

     rayon  year   agriculture  production   retail
0  Atbasar  2014  19129.400000     16015.0   6793.8
1  Atbasar  2015  21949.900000     14943.1   7296.6
2  Atbasar  2016  27379.400000     14713.6  14644.8
3  Atbasar  2017  29398.200000     18135.1  17147.9
4  Atbasar  2018  29684.147805     20009.4  13764.2
5  Atbasar  2019  36265.300000     28362.6  13292.4
6  Atbasar  2020  45729.400000     20260.6   9738.9
7  Atbasar  2021  47333.030494     17465.7  17623.8
8  Atbasar  2022  75848.808840     26152.3  13254.8
9  Atbasar  2023  50599.100000     30776.1  22080.5

In [277]:
birzhan_sal = pd.read_excel(Path("../Data/Controls/Akmola_All.xlsx"), sheet_name="Биржан сал", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

birzhan_sal.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
birzhan_sal = birzhan_sal.loc[[49, 81, 133]].reset_index(drop=True)
birzhan_sal['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    birzhan_sal[i] = birzhan_sal[i].astype(str)
    birzhan_sal[i] = birzhan_sal[i].str.replace(',', '.')
    birzhan_sal[i] = birzhan_sal[i].str.replace(')', '')
    birzhan_sal[i] = birzhan_sal[i].str.replace(' ', '')
    birzhan_sal[i] = birzhan_sal[i].str.replace('\xa0', '')
    birzhan_sal[i] = birzhan_sal[i].str.replace('*', '')
    birzhan_sal[i] = birzhan_sal[i].astype(float)

birzhan_sal = pd.melt(birzhan_sal, id_vars=['Indicator'], var_name='year', value_name='value')
birzhan_sal = birzhan_sal.pivot(index='year', columns='Indicator', values='value').reset_index()
birzhan_sal.insert(0, 'rayon', 'Birzhan Sal')
birzhan_sal.columns.name = None
birzhan_sal

         rayon  year   agriculture  production  retail
0  Birzhan Sal  2014  10721.900000     12488.3  1071.5
1  Birzhan Sal  2015  13997.800000     12236.4  1141.5
2  Birzhan Sal  2016  16609.300000     14363.0  1300.8
3  Birzhan Sal  2017  17547.700000     16777.4  1531.7
4  Birzhan Sal  2018  19916.623720     21587.3  1505.1
5  Birzhan Sal  2019  21769.300000     25448.5  2314.9
6  Birzhan Sal  2020  31075.000000     30329.8   790.1
7  Birzhan Sal  2021  30365.035988     37796.6  1301.2
8  Birzhan Sal  2022  37731.966279     39077.0  1807.1
9  Birzhan Sal  2023  27259.000000     34742.8  1580.5

In [278]:
bulandy = pd.read_excel(Path("../Data/Controls/Akmola_All.xlsx"), sheet_name="Буландынский", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

bulandy.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
bulandy = bulandy.loc[[49, 81, 132]].reset_index(drop=True)
bulandy['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    bulandy[i] = bulandy[i].astype(str)
    bulandy[i] = bulandy[i].str.replace(',', '.')
    bulandy[i] = bulandy[i].str.replace(')', '')
    bulandy[i] = bulandy[i].str.replace(' ', '')
    bulandy[i] = bulandy[i].str.replace('\xa0', '')
    bulandy[i] = bulandy[i].str.replace('*', '')
    bulandy[i] = bulandy[i].astype(float)

bulandy = pd.melt(bulandy, id_vars=['Indicator'], var_name='year', value_name='value')
bulandy = bulandy.pivot(index='year', columns='Indicator', values='value').reset_index()
bulandy.insert(0, 'rayon', 'Bulandy')
bulandy.columns.name = None
bulandy

     rayon  year    agriculture  production   retail
0  Bulandy  2014   11685.400000      3550.9   3753.2
1  Bulandy  2015   15100.200000      4047.1   3139.5
2  Bulandy  2016   17213.900000      3233.3   4059.4
3  Bulandy  2017   18348.700000      4304.2   4596.9
4  Bulandy  2018   21492.473565      6205.1   5255.1
5  Bulandy  2019   35902.000000     19949.6   4492.9
6  Bulandy  2020   54818.200000     24503.9   5811.2
7  Bulandy  2021   81934.280321     51652.9   9656.2
8  Bulandy  2022  123525.830705     69125.6   9364.5
9  Bulandy  2023  119580.800000    102643.5  12557.6

In [279]:
burabay = pd.read_excel(Path("../Data/Controls/Akmola_All.xlsx"), sheet_name="Бурабайский", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

burabay.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
burabay = burabay.loc[[49, 81, 133]].reset_index(drop=True)
burabay['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    burabay[i] = burabay[i].astype(str)
    burabay[i] = burabay[i].str.replace(',', '.')
    burabay[i] = burabay[i].str.replace(')', '')
    burabay[i] = burabay[i].str.replace(' ', '')
    burabay[i] = burabay[i].str.replace('\xa0', '')
    burabay[i] = burabay[i].str.replace('*', '')
    burabay[i] = burabay[i].astype(float)

burabay = pd.melt(burabay, id_vars=['Indicator'], var_name='year', value_name='value')
burabay = burabay.pivot(index='year', columns='Indicator', values='value').reset_index()
burabay.insert(0, 'rayon', 'Burabay')
burabay.columns.name = None
burabay

     rayon  year   agriculture  production   retail
0  Burabay  2014  15633.500000     18035.6   5011.8
1  Burabay  2015  20712.100000     21790.1   6269.4
2  Burabay  2016  23137.600000     30637.8   5557.6
3  Burabay  2017  27603.000000     31781.7   7312.9
4  Burabay  2018  29587.052458     40715.4  17135.3
5  Burabay  2019  31024.600000     47345.7  17641.9
6  Burabay  2020  38939.100000     66635.5  22576.3
7  Burabay  2021  47237.923069     55555.4  40786.7
8  Burabay  2022  58238.880478     80458.1  35187.8
9  Burabay  2023  34051.400000    136532.7  35859.6

In [280]:
egindykol = pd.read_excel(Path("../Data/Controls/Akmola_All.xlsx"), sheet_name="Егиндыкольский", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

egindykol.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
egindykol = egindykol.loc[[49, 81, 133]].reset_index(drop=True)
egindykol['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    egindykol[i] = egindykol[i].astype(str)
    egindykol[i] = egindykol[i].str.replace(',', '.')
    egindykol[i] = egindykol[i].str.replace(')', '')
    egindykol[i] = egindykol[i].str.replace(' ', '')
    egindykol[i] = egindykol[i].str.replace('\xa0', '')
    egindykol[i] = egindykol[i].str.replace('*', '')
    egindykol[i] = egindykol[i].astype(float)

egindykol = pd.melt(egindykol, id_vars=['Indicator'], var_name='year', value_name='value')
egindykol = egindykol.pivot(index='year', columns='Indicator', values='value').reset_index()
egindykol.insert(0, 'rayon', 'Egindykol')
egindykol.columns.name = None
egindykol

       rayon  year   agriculture  production  retail
0  Egindykol  2014  11203.100000       697.2   683.8
1  Egindykol  2015  12815.300000       804.0   726.7
2  Egindykol  2016  14916.500000       870.4  1831.5
3  Egindykol  2017  13368.500000      1038.1  2724.9
4  Egindykol  2018  14809.140813      1342.1  2580.4
5  Egindykol  2019  16751.100000      1146.7  2574.8
6  Egindykol  2020  28860.900000      1246.5   643.1
7  Egindykol  2021  32029.230586      1501.1  1084.3
8  Egindykol  2022  38702.652162      1421.0   129.8
9  Egindykol  2023  21683.200000      1004.2   324.7

In [281]:
ereymentau = pd.read_excel(Path("../Data/Controls/Akmola_All.xlsx"), sheet_name="Ерейментауский", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

ereymentau.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
ereymentau = ereymentau.loc[[49, 81, 133]].reset_index(drop=True)
ereymentau['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    ereymentau[i] = ereymentau[i].astype(str)
    ereymentau[i] = ereymentau[i].str.replace(',', '.')
    ereymentau[i] = ereymentau[i].str.replace(')', '')
    ereymentau[i] = ereymentau[i].str.replace(' ', '')
    ereymentau[i] = ereymentau[i].str.replace('\xa0', '')
    ereymentau[i] = ereymentau[i].str.replace('*', '')
    ereymentau[i] = ereymentau[i].astype(float)

ereymentau = pd.melt(ereymentau, id_vars=['Indicator'], var_name='year', value_name='value')
ereymentau = ereymentau.pivot(index='year', columns='Indicator', values='value').reset_index()
ereymentau.insert(0, 'rayon', 'Ereymentau')
ereymentau.columns.name = None
ereymentau

        rayon  year   agriculture  production   retail
0  Ereymentau  2014   8508.500000      7211.2   2582.6
1  Ereymentau  2015  10545.100000     11553.8   2331.9
2  Ereymentau  2016  12730.500000     12689.7   2605.6
3  Ereymentau  2017  13209.400000     16635.8   3346.8
4  Ereymentau  2018  14914.942321     12986.8   3301.7
5  Ereymentau  2019  16924.600000     13029.1   3136.1
6  Ereymentau  2020  21933.000000     13180.7   3061.3
7  Ereymentau  2021  28470.912808     18104.5  13795.0
8  Ereymentau  2022  35951.165147     19671.9  17947.3
9  Ereymentau  2023  20193.400000     19820.4   7519.9

In [282]:
yesil = pd.read_excel(Path("../Data/Controls/Akmola_All.xlsx"), sheet_name="Есильский", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

yesil.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
yesil = yesil.loc[[49, 81, 132]].reset_index(drop=True)
yesil['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    yesil[i] = yesil[i].astype(str)
    yesil[i] = yesil[i].str.replace(',', '.')
    yesil[i] = yesil[i].str.replace(')', '')
    yesil[i] = yesil[i].str.replace(' ', '')
    yesil[i] = yesil[i].str.replace('\xa0', '')
    yesil[i] = yesil[i].str.replace('*', '')
    yesil[i] = yesil[i].astype(float)

yesil = pd.melt(yesil, id_vars=['Indicator'], var_name='year', value_name='value')
yesil = yesil.pivot(index='year', columns='Indicator', values='value').reset_index()
yesil.insert(0, 'rayon', 'Yesil')
yesil.columns.name = None
yesil

   rayon  year   agriculture  production  retail
0  Yesil  2014  17259.900000      4354.3  3839.5
1  Yesil  2015  21468.500000      6005.7  4042.0
2  Yesil  2016  25071.600000      6908.6  6362.9
3  Yesil  2017  27284.600000      5358.0  4526.3
4  Yesil  2018  22082.309590      2819.8  5370.0
5  Yesil  2019  30075.000000      2841.3  6693.9
6  Yesil  2020  38827.800000      3242.0  7894.2
7  Yesil  2021  38777.147515      3623.6  6372.9
8  Yesil  2022  75535.810806      2859.1  3991.3
9  Yesil  2023  42228.800000      3036.6  5656.0

In [283]:
zharkain = pd.read_excel(Path("../Data/Controls/Akmola_All.xlsx"), sheet_name="Жаркаинский", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

zharkain.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
zharkain = zharkain.loc[[49, 81, 133]].reset_index(drop=True)
zharkain['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    zharkain[i] = zharkain[i].astype(str)
    zharkain[i] = zharkain[i].str.replace(',', '.')
    zharkain[i] = zharkain[i].str.replace(')', '')
    zharkain[i] = zharkain[i].str.replace(' ', '')
    zharkain[i] = zharkain[i].str.replace('\xa0', '')
    zharkain[i] = zharkain[i].str.replace('*', '')
    zharkain[i] = zharkain[i].astype(float)

zharkain = pd.melt(zharkain, id_vars=['Indicator'], var_name='year', value_name='value')
zharkain = zharkain.pivot(index='year', columns='Indicator', values='value').reset_index()
zharkain.insert(0, 'rayon', 'Zharkain')
zharkain.columns.name = None
zharkain

      rayon  year   agriculture  production  retail
0  Zharkain  2014  20002.000000      1921.4   977.9
1  Zharkain  2015  22923.500000      1973.7  1037.7
2  Zharkain  2016  28124.600000      2518.7  3943.2
3  Zharkain  2017  26272.500000      2495.3  4420.1
4  Zharkain  2018  28493.113216      2932.7  3235.7
5  Zharkain  2019  35134.300000      3564.1  3067.9
6  Zharkain  2020  43677.200000      3960.4  1487.2
7  Zharkain  2021  34586.454852      4234.2  1379.3
8  Zharkain  2022  89229.240982      3668.2  5169.5
9  Zharkain  2023  35983.400000      4129.0  4849.2

In [284]:
zhaksyn = pd.read_excel(Path("../Data/Controls/Akmola_All.xlsx"), sheet_name="Жаксынский", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

zhaksyn.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
zhaksyn = zhaksyn.loc[[49, 81, 132]].reset_index(drop=True)
zhaksyn['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    zhaksyn[i] = zhaksyn[i].astype(str)
    zhaksyn[i] = zhaksyn[i].str.replace(',', '.')
    zhaksyn[i] = zhaksyn[i].str.replace(')', '')
    zhaksyn[i] = zhaksyn[i].str.replace(' ', '')
    zhaksyn[i] = zhaksyn[i].str.replace('\xa0', '')
    zhaksyn[i] = zhaksyn[i].str.replace('*', '')
    zhaksyn[i] = zhaksyn[i].astype(float)

zhaksyn = pd.melt(zhaksyn, id_vars=['Indicator'], var_name='year', value_name='value')
zhaksyn = zhaksyn.pivot(index='year', columns='Indicator', values='value').reset_index()
zhaksyn.insert(0, 'rayon', 'Zhaksyn')
zhaksyn.columns.name = None
zhaksyn

     rayon  year   agriculture  production  retail
0  Zhaksyn  2014  20521.800000      1991.6  1565.4
1  Zhaksyn  2015  24308.200000      2241.0  1628.0
2  Zhaksyn  2016  27745.800000      2918.2  1552.1
3  Zhaksyn  2017  30922.100000      3223.5  1448.1
4  Zhaksyn  2018  30483.413430      2521.5  1816.6
5  Zhaksyn  2019  40516.400000      2721.6  1131.3
6  Zhaksyn  2020  45928.900000      2801.9   936.8
7  Zhaksyn  2021  46609.066854      3486.0  1898.6
8  Zhaksyn  2022  81476.475718      2889.8   901.3
9  Zhaksyn  2023  44741.000000      2684.0  2416.7

In [285]:
zerendi = pd.read_excel(Path("../Data/Controls/Akmola_All.xlsx"), sheet_name="Зерендинский", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

zerendi.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
zerendi = zerendi.loc[[49, 81, 133]].reset_index(drop=True)
zerendi['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    zerendi[i] = zerendi[i].astype(str)
    zerendi[i] = zerendi[i].str.replace(',', '.')
    zerendi[i] = zerendi[i].str.replace(')', '')
    zerendi[i] = zerendi[i].str.replace(' ', '')
    zerendi[i] = zerendi[i].str.replace('\xa0', '')
    zerendi[i] = zerendi[i].str.replace('*', '')
    zerendi[i] = zerendi[i].astype(float)

zerendi = pd.melt(zerendi, id_vars=['Indicator'], var_name='year', value_name='value')
zerendi = zerendi.pivot(index='year', columns='Indicator', values='value').reset_index()
zerendi.insert(0, 'rayon', 'Zerendi')
zerendi.columns.name = None
zerendi

     rayon  year   agriculture  production  retail
0  Zerendi  2014  17254.500000     48816.3  4568.3
1  Zerendi  2015  22301.200000     48033.0  3837.2
2  Zerendi  2016  25737.000000     96410.6  2905.8
3  Zerendi  2017  35489.800000    185211.1  2405.8
4  Zerendi  2018  33697.933131    206858.5  2490.5
5  Zerendi  2019  42634.400000    249521.7  4105.9
6  Zerendi  2020  53604.600000    356539.9  2527.4
7  Zerendi  2021  61106.198825    342681.7  6451.9
8  Zerendi  2022  89920.051538    362876.6  2184.1
9  Zerendi  2023  51326.300000    414101.4  3657.7

In [286]:
korgalzhyn = pd.read_excel(Path("../Data/Controls/Akmola_All.xlsx"), sheet_name="Коргалжынский", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

korgalzhyn.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
korgalzhyn = korgalzhyn.loc[[49, 81, 133]].reset_index(drop=True)
korgalzhyn['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    korgalzhyn[i] = korgalzhyn[i].astype(str)
    korgalzhyn[i] = korgalzhyn[i].str.replace(',', '.')
    korgalzhyn[i] = korgalzhyn[i].str.replace(')', '')
    korgalzhyn[i] = korgalzhyn[i].str.replace(' ', '')
    korgalzhyn[i] = korgalzhyn[i].str.replace('\xa0', '')
    korgalzhyn[i] = korgalzhyn[i].str.replace('*', '')
    korgalzhyn[i] = korgalzhyn[i].astype(float)

korgalzhyn = pd.melt(korgalzhyn, id_vars=['Indicator'], var_name='year', value_name='value')
korgalzhyn = korgalzhyn.pivot(index='year', columns='Indicator', values='value').reset_index()
korgalzhyn.insert(0, 'rayon', 'Korgalzhyn')
korgalzhyn.columns.name = None
korgalzhyn

        rayon  year   agriculture  production  retail
0  Korgalzhyn  2014   5275.000000      1768.4   353.5
1  Korgalzhyn  2015   6049.700000      2642.9   369.5
2  Korgalzhyn  2016   8274.200000      3240.8   416.4
3  Korgalzhyn  2017   6752.300000      2813.4   594.2
4  Korgalzhyn  2018  10847.132872      2657.0   581.8
5  Korgalzhyn  2019   9565.700000      3869.9   691.9
6  Korgalzhyn  2020  16345.900000      1738.1   229.7
7  Korgalzhyn  2021  17473.178088      1576.2  2002.5
8  Korgalzhyn  2022  17700.929454      2039.3  3169.1
9  Korgalzhyn  2023  11001.100000      1674.7   382.7

In [287]:
sandyktau = pd.read_excel(Path("../Data/Controls/Akmola_All.xlsx"), sheet_name="Сандыктауский", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

sandyktau.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
sandyktau = sandyktau.loc[[49, 81, 132]].reset_index(drop=True)
sandyktau['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    sandyktau[i] = sandyktau[i].astype(str)
    sandyktau[i] = sandyktau[i].str.replace(',', '.')
    sandyktau[i] = sandyktau[i].str.replace(')', '')
    sandyktau[i] = sandyktau[i].str.replace(' ', '')
    sandyktau[i] = sandyktau[i].str.replace('\xa0', '')
    sandyktau[i] = sandyktau[i].str.replace('*', '')
    sandyktau[i] = sandyktau[i].astype(float)

sandyktau = pd.melt(sandyktau, id_vars=['Indicator'], var_name='year', value_name='value')
sandyktau = sandyktau.pivot(index='year', columns='Indicator', values='value').reset_index()
sandyktau.insert(0, 'rayon', 'Sandyktau')
sandyktau.columns.name = None
sandyktau

       rayon  year   agriculture  production  retail
0  Sandyktau  2014  16212.800000      1889.6  1566.7
1  Sandyktau  2015  19325.700000      1861.8  1473.4
2  Sandyktau  2016  22634.600000      2474.6  2899.9
3  Sandyktau  2017  28610.800000      2268.5  3509.2
4  Sandyktau  2018  24606.717076      2629.7  3763.0
5  Sandyktau  2019  33719.000000      1918.9  2484.1
6  Sandyktau  2020  48572.600000      2329.2  1420.3
7  Sandyktau  2021  48671.188450      2433.0  2272.3
8  Sandyktau  2022  92394.964808      2071.1  2626.1
9  Sandyktau  2023  50154.500000      2317.2  2105.4

In [288]:
tselinograd = pd.read_excel(Path("../Data/Controls/Akmola_All.xlsx"), sheet_name="Целиноградский", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

tselinograd.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
tselinograd = tselinograd.loc[[49, 81, 133]].reset_index(drop=True)
tselinograd['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    tselinograd[i] = tselinograd[i].astype(str)
    tselinograd[i] = tselinograd[i].str.replace(',', '.')
    tselinograd[i] = tselinograd[i].str.replace(')', '')
    tselinograd[i] = tselinograd[i].str.replace(' ', '')
    tselinograd[i] = tselinograd[i].str.replace('\xa0', '')
    tselinograd[i] = tselinograd[i].str.replace('*', '')
    tselinograd[i] = tselinograd[i].astype(float)

tselinograd = pd.melt(tselinograd, id_vars=['Indicator'], var_name='year', value_name='value')
tselinograd = tselinograd.pivot(index='year', columns='Indicator', values='value').reset_index()
tselinograd.insert(0, 'rayon', 'Tselinograd')
tselinograd.columns.name = None
tselinograd

         rayon  year   agriculture  production   retail
0  Tselinograd  2014  15223.500000      8885.2   1952.6
1  Tselinograd  2015  18517.700000     16716.2   1518.6
2  Tselinograd  2016  24415.400000     22449.5   1533.2
3  Tselinograd  2017  26875.600000     25700.8   5452.7
4  Tselinograd  2018  36231.446075     32184.4   4664.9
5  Tselinograd  2019  36384.200000     37220.4   6618.7
6  Tselinograd  2020  57232.600000     41331.6   6356.1
7  Tselinograd  2021  60317.531788     45768.1   5286.8
8  Tselinograd  2022  65411.542418     49027.6  10818.7
9  Tselinograd  2023  51602.400000     51309.6  11161.0

In [289]:
shortandy = pd.read_excel(Path("../Data/Controls/Akmola_All.xlsx"), sheet_name="Шортандинский", header=2, usecols='A, Y:AH', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

shortandy.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
shortandy = shortandy.loc[[49, 81, 133]].reset_index(drop=True)
shortandy['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    shortandy[i] = shortandy[i].astype(str)
    shortandy[i] = shortandy[i].str.replace(',', '.')
    shortandy[i] = shortandy[i].str.replace(')', '')
    shortandy[i] = shortandy[i].str.replace(' ', '')
    shortandy[i] = shortandy[i].str.replace('\xa0', '')
    shortandy[i] = shortandy[i].str.replace('*', '')
    shortandy[i] = shortandy[i].astype(float)

shortandy = pd.melt(shortandy, id_vars=['Indicator'], var_name='year', value_name='value')
shortandy = shortandy.pivot(index='year', columns='Indicator', values='value').reset_index()
shortandy.insert(0, 'rayon', 'Shortandy')
shortandy.columns.name = None
shortandy

       rayon  year   agriculture  production   retail
0  Shortandy  2014   9135.400000     10652.8   4186.5
1  Shortandy  2015  12123.400000     12197.3   4429.1
2  Shortandy  2016  15567.400000     17843.6   5183.6
3  Shortandy  2017  13935.000000     20065.4   5689.6
4  Shortandy  2018  17620.656250     32501.0   3803.1
5  Shortandy  2019  20576.700000     47271.5   5610.0
6  Shortandy  2020  31928.100000     65528.3   5622.3
7  Shortandy  2021  34665.159296     63244.9   4746.7
8  Shortandy  2022  44693.007367     93623.3   6978.3
9  Shortandy  2023  24515.200000    122602.8  11037.2

In [290]:
akmola_controls = pd.concat([kokshetau_city, kosshi_city, stepnogorsk_city, akkol, arshaly, astrakhan, atbasar, birzhan_sal, bulandy, burabay, egindykol, ereymentau, yesil, zharkain, zhaksyn, zerendi, korgalzhyn, sandyktau, tselinograd, shortandy], ignore_index=True)
akmola_controls

              rayon  year   agriculture production    retail
0    Kokshetau city  2014        1964.0    82158.1   97495.8
1    Kokshetau city  2015        3212.9    83694.5  104833.6
2    Kokshetau city  2016        3481.4    99581.4  124935.2
3    Kokshetau city  2017        4320.6   106302.3  144202.6
4    Kokshetau city  2018        4774.9   105998.9  184575.9
..              ...   ...           ...        ...       ...
191       Shortandy  2019       20576.7    47271.5    5610.0
192       Shortandy  2020       31928.1    65528.3    5622.3
193       Shortandy  2021  34665.159296    63244.9    4746.7
194       Shortandy  2022  44693.007367    93623.3    6978.3
195       Shortandy  2023       24515.2   122602.8   11037.2

[196 rows x 5 columns]

## PPI

In [291]:
akmola_ppi = pd.read_excel(Path("../Data/PPI/Akmola.xls"), header=2, usecols='Y:AH', nrows=216, na_values=['x', 'х', '-', '', ' ', '...'])

akmola_ppi.columns = [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]

rayons = list(akmola_inv['rayon'].unique())

dfs = []

for rayon in rayons:
    df_temp = pd.DataFrame({
        'rayon': rayon,
        'year': range(2014, 2024),
        'ppi': akmola_ppi.values[69]
    })
    dfs.append(df_temp)

akmola_ppi = pd.concat(dfs, ignore_index=True)

akmola_ppi['ppi'] = akmola_ppi['ppi'].astype(str).str.replace(',', '.')
akmola_ppi['ppi'] = akmola_ppi['ppi'].astype(str).str.replace(')', '')
akmola_ppi['ppi'] = akmola_ppi['ppi'].astype(str).str.replace(' ', '')
akmola_ppi['ppi'] = akmola_ppi['ppi'].astype(str).str.replace('\xa0', '')
akmola_ppi['ppi'] = akmola_ppi['ppi'].astype(str).str.replace('*', '')
akmola_ppi['ppi'] = akmola_ppi['ppi'].astype(float)

akmola_ppi

              rayon  year    ppi
0    Kokshetau city  2014  104.5
1    Kokshetau city  2015  108.6
2    Kokshetau city  2016  109.7
3    Kokshetau city  2017  102.8
4    Kokshetau city  2018  107.7
..              ...   ...    ...
205     Kosshi city  2019  113.0
206     Kosshi city  2020  101.9
207     Kosshi city  2021  109.5
208     Kosshi city  2022  105.3
209     Kosshi city  2023  104.8

[210 rows x 3 columns]

## Combine

In [292]:
dfs_akmola = [akmola_inv, akmola_employment, akmola_controls, akmola_ppi]
akmola_merged = reduce(lambda left, right: pd.merge(left, right, on=['rayon', 'year'], how='outer'), dfs_akmola)
akmola_merged

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year,employment,agriculture,production,retail,ppi
0,Akkol,4538180.0,33806.0,33806.0,1380767.0,Akmola,2014,15.0,8460.5,4355.1,6016.3,104.5
1,Akkol,NaN,NaN,NaN,NaN,NaN,2015,13.7,10851.5,4219.1,5663.1,108.6
2,Akkol,9483391.0,52136.0,52136.0,1300876.0,Akmola,2016,13.2,12535.4,4536.8,5455.5,109.7
3,Akkol,8156066.0,54000.0,54000.0,1905603.0,Akmola,2017,12.6,14226.7,5871.0,6933.5,102.8
4,Akkol,5284638.0,402879.0,402879.0,1494698.0,Akmola,2018,13.0,15488.055535,4678.0,6941.0,107.7
...,...,...,...,...,...,...,...,...,...,...,...,...
225,Zharkain,4300624.0,156324.0,156324.0,1049283.0,Akmola,2020,7.4,43677.2,3960.4,1487.2,101.9
226,Zharkain,7093497.0,44656.0,8000.0,2443418.0,Akmola,2021,7.1,34586.454852,4234.2,1379.3,109.5
227,Zharkain,7303474.0,17824.0,17824.0,1255415.0,Akmola,2022,7.2,89229.240982,3668.2,5169.5,105.3
228,Zharkain,9479457.0,2069699.0,2069699.0,1267990.0,Akmola,2023,7.0,35983.4,4129.0,4849.2,104.8
229,Zharkain,10291425.0,881.0,881.0,6229375.0,Akmola,2024,6.3,NaN,NaN,NaN,NaN

# Astana city

## Investments

In [293]:
astana_city_all_2014 = pd.read_excel(Path("../Data/Investments/Astana-city/2014_Investments.xls"), header=5, nrows=5, usecols='A, C:D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
astana_city_all_2015 = pd.read_excel(Path("../Data/Investments/Astana-city/2015_Investments/Internal_vs_external.xls"), header=5, nrows=5, usecols='A, C:D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
astana_city_all_2016 = pd.read_excel(Path("../Data/Investments/Astana-city/2016_Investments/Internal_vs_external.xls"), header=4, nrows=5, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
astana_city_all_2017 = pd.read_excel(Path("../Data/Investments/Astana-city/2017_Investments/Internal_vs_external.xls"), header=4, nrows=5, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
astana_city_all_2018 = pd.read_excel(Path("../Data/Investments/Astana-city/2018_Investments/Internal_vs_external.xls"), header=4, nrows=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
astana_city_all_2019 = pd.read_excel(Path("../Data/Investments/Astana-city/2019_Investments.xls"), sheet_name='12.', header=6, nrows=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
astana_city_all_2020 = pd.read_excel(Path("../Data/Investments/Astana-city/2020_Investments.xls"), sheet_name='11.', header=4, nrows=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
astana_city_all_2021 = pd.read_excel(Path("../Data/Investments/Astana-city/2021_Investments.xls"), sheet_name='12.', header=4, nrows=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
astana_city_all_2022 = pd.read_excel(Path("../Data/Investments/Astana-city/2022_Investments.xls"), sheet_name='12', header=4, nrows=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
astana_city_all_2023 = pd.read_excel(Path("../Data/Investments/Astana-city/2023_Investments.xlsx"), sheet_name='15', header=2, nrows=7, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
astana_city_all_2024 = pd.read_excel(Path("../Data/Investments/Astana-city/2024_Investments.xls"), sheet_name='13', header=2, nrows=7, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

astana_city_non_2015 = pd.read_excel(Path("../Data/Investments/Astana-city/2015_Investments/Greenfield_investments.xls"), header=5, nrows=5, usecols='A, B, C', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
astana_city_non_2016 = pd.read_excel(Path("../Data/Investments/Astana-city/2016_Investments/Greenfield_investments.xls"), header=5, nrows=5, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
astana_city_non_2017 = pd.read_excel(Path("../Data/Investments/Astana-city/2017_Investments/Greenfield_investments.xls"), header=5, nrows=5, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
astana_city_non_2018 = pd.read_excel(Path("../Data/Investments/Astana-city/2018_Investments/Greenfield_investments.xls"), header=5, nrows=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
astana_city_non_2019 = pd.read_excel(Path("../Data/Investments/Astana-city/2019_Investments.xls"), sheet_name='13.', header=6, nrows=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
astana_city_non_2020 = pd.read_excel(Path("../Data/Investments/Astana-city/2020_Investments.xls"), sheet_name='12.', header=4, nrows=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
astana_city_non_2021 = pd.read_excel(Path("../Data/Investments/Astana-city/2021_Investments.xls"), sheet_name='13.', header=4, nrows=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
astana_city_non_2022 = pd.read_excel(Path("../Data/Investments/Astana-city/2022_Investments.xls"), sheet_name='13', header=4, nrows=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
astana_city_non_2023 = pd.read_excel(Path("../Data/Investments/Astana-city/2023_Investments.xlsx"), sheet_name='16', header=3, nrows=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
astana_city_non_2024 = pd.read_excel(Path("../Data/Investments/Astana-city/2024_Investments.xls"), sheet_name='14', header=2, nrows=7, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [294]:
dfs = [astana_city_all_2014, astana_city_all_2015, astana_city_all_2016, astana_city_all_2017, astana_city_all_2018, astana_city_all_2019, astana_city_all_2020, astana_city_all_2021,
      astana_city_all_2022, astana_city_all_2023, astana_city_all_2024]

lists = []

for df in dfs:
    lists.extend(df.iloc[:, 0].unique())

unique_lists = pd.Series(lists).unique()
unique_lists

array(['Астана қ.', '"Алматы" ауданы', '"Есіл" ауданы',
       '"Сарыарқа" ауданы', 'Астана қаласы', '"Байқоңыр" ауданы',
       'Нұр-Сұлтан қаласы', 'Алматы ауданы', 'Есіл ауданы',
       'Сарыарқа ауданы', 'Байқоңыр ауданы', 'г. Астана', 'район Алматы ',
       'район Есиль', 'район Сарыарка ', 'район Байконыр ', 'район Нура ',
       'район Есиль ', 'район Байкоңыр ', 'район Нұра '], dtype=object)

In [295]:
dfs = [astana_city_non_2015, astana_city_non_2016, astana_city_non_2017, astana_city_non_2018, astana_city_non_2019, astana_city_non_2020,
      astana_city_non_2021, astana_city_non_2022, astana_city_non_2023, astana_city_non_2024]

lists = []

for df in dfs:
    lists.extend(df.iloc[:, 0].unique())

unique_lists = pd.Series(lists).unique()
unique_lists

array(['Астана қаласы', '"Алматы" ауданы', '"Есіл" ауданы',
       '"Сарыарқа" ауданы', '"Байқоңыр" ауданы', 'Нұр-Сұлтан қаласы',
       'Алматы ауданы', 'Есіл ауданы', 'Сарыарқа ауданы',
       'Байқоңыр ауданы', 'район Алматы ', 'район Есиль',
       'район Сарыарка ', 'район Байконыр ', 'район Нура ', 'г. Астана',
       'район Есиль ', 'район Байкоңыр ', 'район Нұра '], dtype=object)

In [296]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [astana_city_all_2014, astana_city_all_2015, astana_city_all_2016, astana_city_all_2017, astana_city_all_2018, astana_city_all_2019, astana_city_all_2020, astana_city_all_2021,
      astana_city_all_2022, astana_city_all_2023, astana_city_all_2024]:
    df.columns = all_columns

for df in [astana_city_non_2015, astana_city_non_2016, astana_city_non_2017, astana_city_non_2018, astana_city_non_2019, astana_city_non_2020,
      astana_city_non_2021, astana_city_non_2022, astana_city_non_2023, astana_city_non_2024]:
    df.columns = non_columns
    
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

In [297]:
rayon_map_astana = {

    # ---- City-level names ----
    'Астана қ.': 'Astana city',
    'Астана қаласы': 'Astana city',
    'Нұр-Сұлтан қаласы': 'Astana city',
    'г. Астана': 'Astana city',

    # ---- Almaty ----
    '"Алматы" ауданы': 'Almaty',
    'Алматы ауданы': 'Almaty',
    'район Алматы ': 'Almaty',
    'район Алматы': 'Almaty',

    # ---- Yesil ----
    '"Есіл" ауданы': 'Yesil',
    'Есіл ауданы': 'Yesil',
    'район Есиль': 'Yesil',
    'район Есиль ': 'Yesil',

    # ---- Saryarka ----
    '"Сарыарқа" ауданы': 'Saryarka',
    'Сарыарқа ауданы': 'Saryarka',
    'район Сарыарка ': 'Saryarka',
    'район Сарыарка': 'Saryarka',

    # ---- Baikonur ----
    '"Байқоңыр" ауданы': 'Baikonur',
    'Байқоңыр ауданы': 'Baikonur',
    'район Байконыр ': 'Baikonur',
    'район Байкоңыр ': 'Baikonur',
    'район Байқоңыр': 'Baikonur',

    # ---- Nura ----
    'район Нура ': 'Nura',
    'район Нұра ': 'Nura'
}

In [298]:
astana_city_all_2024

             rayon   l_all_inv f_all_inv
0        г. Астана  1811034746  87488064
1    район Алматы    169091523  15116409
2     район Есиль    595052920  55005495
3  район Сарыарка    139952512   3341486
4  район Байкоңыр    372558262  12217881
5      район Нұра    534379529   1806795

In [299]:
# ----- ALL investments -----
astana_city_all_2014['rayon'] = astana_city_all_2014['rayon'].replace(rayon_map_astana)
astana_city_all_2015['rayon'] = astana_city_all_2015['rayon'].replace(rayon_map_astana)
astana_city_all_2016['rayon'] = astana_city_all_2016['rayon'].replace(rayon_map_astana)
astana_city_all_2017['rayon'] = astana_city_all_2017['rayon'].replace(rayon_map_astana)
astana_city_all_2018['rayon'] = astana_city_all_2018['rayon'].replace(rayon_map_astana)
astana_city_all_2019['rayon'] = astana_city_all_2019['rayon'].replace(rayon_map_astana)
astana_city_all_2020['rayon'] = astana_city_all_2020['rayon'].replace(rayon_map_astana)
astana_city_all_2021['rayon'] = astana_city_all_2021['rayon'].replace(rayon_map_astana)
astana_city_all_2022['rayon'] = astana_city_all_2022['rayon'].replace(rayon_map_astana)
astana_city_all_2023['rayon'] = astana_city_all_2023['rayon'].replace(rayon_map_astana)
astana_city_all_2024['rayon'] = astana_city_all_2024['rayon'].replace(rayon_map_astana)

# ----- NON-extractive investments -----
astana_city_non_2015['rayon'] = astana_city_non_2015['rayon'].replace(rayon_map_astana)
astana_city_non_2016['rayon'] = astana_city_non_2016['rayon'].replace(rayon_map_astana)
astana_city_non_2017['rayon'] = astana_city_non_2017['rayon'].replace(rayon_map_astana)
astana_city_non_2018['rayon'] = astana_city_non_2018['rayon'].replace(rayon_map_astana)
astana_city_non_2019['rayon'] = astana_city_non_2019['rayon'].replace(rayon_map_astana)
astana_city_non_2020['rayon'] = astana_city_non_2020['rayon'].replace(rayon_map_astana)
astana_city_non_2021['rayon'] = astana_city_non_2021['rayon'].replace(rayon_map_astana)
astana_city_non_2022['rayon'] = astana_city_non_2022['rayon'].replace(rayon_map_astana)
astana_city_non_2023['rayon'] = astana_city_non_2023['rayon'].replace(rayon_map_astana)
astana_city_non_2024['rayon'] = astana_city_non_2024['rayon'].replace(rayon_map_astana)

In [300]:
astana_city_2015 = astana_city_all_2015.merge(astana_city_non_2015, on='rayon', how='left')
astana_city_2016 = astana_city_all_2016.merge(astana_city_non_2016, on='rayon', how='left')
astana_city_2017 = astana_city_all_2017.merge(astana_city_non_2017, on='rayon', how='left')
astana_city_2018 = astana_city_all_2018.merge(astana_city_non_2018, on='rayon', how='left')
astana_city_2019 = astana_city_all_2019.merge(astana_city_non_2019, on='rayon', how='left')
astana_city_2020 = astana_city_all_2020.merge(astana_city_non_2020, on='rayon', how='left')
astana_city_2021 = astana_city_all_2021.merge(astana_city_non_2021, on='rayon', how='left')
astana_city_2022 = astana_city_all_2022.merge(astana_city_non_2022, on='rayon', how='left')
astana_city_2023 = astana_city_all_2023.merge(astana_city_non_2023, on='rayon', how='left')
astana_city_2024 = astana_city_all_2024.merge(astana_city_non_2024, on='rayon', how='left')

dfs = [astana_city_2015, astana_city_2016, astana_city_2017, astana_city_2018, astana_city_2019, astana_city_2020, astana_city_2021, astana_city_2022, astana_city_2023, astana_city_2024]

for i in range(10):
    df = dfs[i]
    df['oblast'] = 'Astana city'
    df['year'] = 2015 + i

astana_city_inv = pd.concat([astana_city_2015, astana_city_2016, astana_city_2017, astana_city_2018, astana_city_2019, astana_city_2020, astana_city_2021, astana_city_2022, astana_city_2023, astana_city_2024], ignore_index=True)
astana_city_inv['rayon'] = (
    astana_city_inv['rayon']
        .str.strip()          # remove hidden spaces
        .replace(rayon_map)   # enforce English names
)
astana_city_inv

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year
0,Astana city,743781853,28919802,28919802,512765338.0,Astana city,2015
1,Almaty,167342610,15633540,15633540,150607688.0,Astana city,2015
2,Yesil,380158754,11010619,11010619,277951634.0,Astana city,2015
3,Saryarka,196280489,2275643,2275643,84206016.0,Astana city,2015
4,Astana city,789719293,47972656,47972657,570779502.0,Astana city,2016
5,Almaty,168845711,13696825,13696826,145196687.0,Astana city,2016
6,Yesil,457878764,30201531,30201531,364762091.0,Astana city,2016
7,Saryarka,162994818,4074300,4074300,60820724.0,Astana city,2016
8,Astana city,749596330,195051183,195051183,548676567.0,Astana city,2017
9,Almaty,131567660,12074169,12074169,122643236.0,Astana city,2017
10,Yesil,446771526,179598846,179598846,375406016.0,Astana city,2017
11,Saryarka,171257144,3378168,3378168,50627315.0,Astana city,2017
12,Astana city,801179442,255554276,255554276,649115465.0,Astana city,2018
13,Almaty,128851836,8531136,8531137,117773627.0,Astana city,2018
14,Yesil,448157106,230799111,230799111,419349100.0,Astana city,2018
15,Saryarka,193836297,14547907,14547907,84471093.0,Astana city,2018
16,Baikonur,30334203,1676122,1676122,27521644.0,Astana city,2018
17,Astana city,700131011,213568136,213568136,561435219.0,Astana city,2019
18,Almaty,97991520,14734002,14734002,87823511.0,Astana city,2019
19,Yesil,426525264,185488837,185488837,382433993.0,Astana city,2019
20,Saryarka,112353466,10381534,10381534,33997577.0,Astana city,2019
21,Baikonur,63260761,2963763,2963763,57180138.0,Astana city,2019
22,Astana city,977226793,138340740,138340740,732491210.0,Astana city,2020
23,Almaty,155279227,9999262,9999262,127882002.0,Astana city,2020
24,Yesil,657847290,118984373,118984373,525487030.0,Astana city,2020
25,Saryarka,98290485,3894312,3894312,23300152.0,Astana city,2020
26,Baikonur,65809791,5462793,5462793,55822026.0,Astana city,2020
27,Astana city,1150347167,63151459,63151459,966377336.0,Astana city,2021
28,Almaty,133540907,15999691,15999691,111984621.0,Astana city,2021
29,Yesil,778154089,34411216,34411216,689450285.0,Astana city,2021
30,Saryarka,112746153,9496629,9496629,50313480.0,Astana city,2021
31,Baikonur,125906015,3243924,3243924,114628948.0,Astana city,2021
32,Astana city,1331845813,114939989,114939989,1044139344.0,Astana city,2022
33,Almaty,193432117,7667729,7667729,130574153.0,Astana city,2022
34,Yesil,905455615,48839417,48839417,741674253.0,Astana city,2022
35,Saryarka,120716495,56027709,56027709,71922398.0,Astana city,2022
36,Baikonur,112241586,2405134,2405134,99968540.0,Astana city,2022
37,Astana city,1601788859,53243127,NaN,NaN,Astana city,2023
38,Almaty,222851056,14502304,14502304.0,111256609.0,Astana city,2023
39,Yesil,523034326,10984758,10984758.0,339108250.0,Astana city,2023
40,Saryarka,99385300,5199771,5199771.0,72513790.0,Astana city,2023
41,Baikonur,336447119,16142383,16142383.0,295077865.0,Astana city,2023
42,Nura,420071059,6413912,6413912.0,342519787.0,Astana city,2023
43,Astana city,1811034746,87488064,87488064,1231584390.0,Astana city,2024
44,Almaty,169091523,15116409,15116409,112539960.0,Astana city,2024
45,Yesil,595052920,55005495,55005495,305170896.0,Astana city,2024
46,Saryarka,139952512,3341486,3341486,79600063.0,Astana city,2024
47,Baikonur,372558262,12217881,12217881,344052158.0,Astana city,2024
48,Nura,534379529,1806795,1806795,390221311.0,Astana city,2024

In [301]:
# Replace Nura with Yesil
astana_city_inv['rayon'] = astana_city_inv['rayon'].replace('Nura', 'Yesil')

# Drop Astana city rows
astana_city_inv = astana_city_inv[astana_city_inv['rayon'] != 'Astana city']

# Group and aggregate
astana_city_inv = (
    astana_city_inv
    .groupby(['year','rayon'], as_index=False)
    .agg({
        'l_all_inv': 'sum',
        'f_all_inv': 'sum',
        'f_nonextr_inv': 'sum',
        'l_nonextr_inv': 'sum'
    })
)

# Add oblast column
astana_city_inv['oblast'] = 'Astana city'

In [302]:
astana_city_2014 = astana_city_all_2014
astana_city_2014['oblast'] = 'Astana city'
astana_city_2014['year'] = 2014
astana_city_inv = pd.concat([astana_city_2014, astana_city_inv], ignore_index=True)
astana_city_inv

,rayon,l_all_inv,f_all_inv,oblast,year,f_nonextr_inv,l_nonextr_inv
0,Astana city,618708743,25424883,Astana city,2014,NaN,NaN
1,Almaty,140584191,11223734,Astana city,2014,NaN,NaN
2,Yesil,262913632,11955722,Astana city,2014,NaN,NaN
3,Saryarka,215210920,2245427,Astana city,2014,NaN,NaN
4,Almaty,167342610,15633540,Astana city,2015,15633540,150607688.0
5,Saryarka,196280489,2275643,Astana city,2015,2275643,84206016.0
6,Yesil,380158754,11010619,Astana city,2015,11010619,277951634.0
7,Almaty,168845711,13696825,Astana city,2016,13696826,145196687.0
8,Saryarka,162994818,4074300,Astana city,2016,4074300,60820724.0
9,Yesil,457878764,30201531,Astana city,2016,30201531,364762091.0
10,Almaty,131567660,12074169,Astana city,2017,12074169,122643236.0
11,Saryarka,171257144,3378168,Astana city,2017,3378168,50627315.0
12,Yesil,446771526,179598846,Astana city,2017,179598846,375406016.0
13,Almaty,128851836,8531136,Astana city,2018,8531137,117773627.0
14,Baikonur,30334203,1676122,Astana city,2018,1676122,27521644.0
15,Saryarka,193836297,14547907,Astana city,2018,14547907,84471093.0
16,Yesil,448157106,230799111,Astana city,2018,230799111,419349100.0
17,Almaty,97991520,14734002,Astana city,2019,14734002,87823511.0
18,Baikonur,63260761,2963763,Astana city,2019,2963763,57180138.0
19,Saryarka,112353466,10381534,Astana city,2019,10381534,33997577.0
20,Yesil,426525264,185488837,Astana city,2019,185488837,382433993.0
21,Almaty,155279227,9999262,Astana city,2020,9999262,127882002.0
22,Baikonur,65809791,5462793,Astana city,2020,5462793,55822026.0
23,Saryarka,98290485,3894312,Astana city,2020,3894312,23300152.0
24,Yesil,657847290,118984373,Astana city,2020,118984373,525487030.0
25,Almaty,133540907,15999691,Astana city,2021,15999691,111984621.0
26,Baikonur,125906015,3243924,Astana city,2021,3243924,114628948.0
27,Saryarka,112746153,9496629,Astana city,2021,9496629,50313480.0
28,Yesil,778154089,34411216,Astana city,2021,34411216,689450285.0
29,Almaty,193432117,7667729,Astana city,2022,7667729,130574153.0
30,Baikonur,112241586,2405134,Astana city,2022,2405134,99968540.0
31,Saryarka,120716495,56027709,Astana city,2022,56027709,71922398.0
32,Yesil,905455615,48839417,Astana city,2022,48839417,741674253.0
33,Almaty,222851056,14502304,Astana city,2023,14502304.0,111256609.0
34,Baikonur,336447119,16142383,Astana city,2023,16142383.0,295077865.0
35,Saryarka,99385300,5199771,Astana city,2023,5199771.0,72513790.0
36,Yesil,943105385,17398670,Astana city,2023,17398670.0,681628037.0
37,Almaty,169091523,15116409,Astana city,2024,15116409,112539960.0
38,Baikonur,372558262,12217881,Astana city,2024,12217881,344052158.0
39,Saryarka,139952512,3341486,Astana city,2024,3341486,79600063.0
40,Yesil,1129432449,56812290,Astana city,2024,56812290,695392207.0

## Employment

In [303]:
astana_city_empl = pd.read_excel(Path("../Data/Employment/Astana-city.xlsx"), skiprows=16, nrows=5, header=None, usecols='A:K', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
astana_city_empl.columns = ['rayon', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
astana_city_empl['rayon'] = astana_city_empl['rayon'].replace(rayon_map_astana)

astana_city_empl

for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    astana_city_empl[i] = astana_city_empl[i].astype(float)
astana_city_employment = astana_city_empl.melt(id_vars='rayon', value_vars=[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023], var_name='year', value_name='employment')

astana_city_employment

          rayon  year  employment
0   Astana city  2014     431.596
1        Almaty  2014     195.522
2         Yesil  2014      58.305
3      Saryarka  2014     177.769
4      Baikonur  2014       0.000
5   Astana city  2015     466.087
6        Almaty  2015     206.316
7         Yesil  2015      67.211
8      Saryarka  2015     192.560
9      Baikonur  2015       0.000
10  Astana city  2016     466.056
11       Almaty  2016     201.143
12        Yesil  2016      72.916
13     Saryarka  2016     191.997
14     Baikonur  2016       0.000
15  Astana city  2017     497.534
16       Almaty  2017     213.764
17        Yesil  2017      84.142
18     Saryarka  2017     199.628
19     Baikonur  2017       0.000
20  Astana city  2018     507.473
21       Almaty  2018     148.682
22        Yesil  2018      95.897
23     Saryarka  2018     160.652
24     Baikonur  2018     102.242
25  Astana city  2019     553.331
26       Almaty  2019     142.205
27        Yesil  2019     114.017
28     Saryarka  2019     173.013
29     Baikonur  2019     124.096
30  Astana city  2020     563.432
31       Almaty  2020     136.324
32        Yesil  2020     134.711
33     Saryarka  2020     174.392
34     Baikonur  2020     118.005
35  Astana city  2021     580.298
36       Almaty  2021     136.959
37        Yesil  2021     148.602
38     Saryarka  2021     176.372
39     Baikonur  2021     118.365
40  Astana city  2022     625.512
41       Almaty  2022     157.614
42        Yesil  2022     172.034
43     Saryarka  2022     175.953
44     Baikonur  2022     119.911
45  Astana city  2023     658.700
46       Almaty  2023     170.000
47        Yesil  2023     198.400
48     Saryarka  2023     171.600
49     Baikonur  2023     118.700

## Controls

In [304]:
almaty_rayon = pd.read_excel(Path("../Data/Controls/Astana-city_All.xlsx"), sheet_name="Алматы", header=2, usecols='A, S:AB', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])

almaty_rayon.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
almaty_rayon = almaty_rayon.loc[[82, 57, 141]].reset_index(drop=True)
almaty_rayon['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    almaty_rayon[i] = almaty_rayon[i].astype(str)
    almaty_rayon[i] = almaty_rayon[i].str.replace(',', '.')
    almaty_rayon[i] = almaty_rayon[i].str.replace(')', '')
    almaty_rayon[i] = almaty_rayon[i].str.replace(' ', '')
    almaty_rayon[i] = almaty_rayon[i].str.replace('\xa0', '')
    almaty_rayon[i] = almaty_rayon[i].str.replace('*', '')
    almaty_rayon[i] = almaty_rayon[i].astype(float)

almaty_rayon = pd.melt(almaty_rayon, id_vars=['Indicator'], var_name='year', value_name='value')
almaty_rayon = almaty_rayon.pivot(index='year', columns='Indicator', values='value').reset_index()
almaty_rayon.insert(0, 'rayon', 'Almaty')
almaty_rayon.columns.name = None
almaty_rayon

    rayon  year  agriculture  production    retail
0  Almaty  2014  2009.800000    209768.7  338821.4
1  Almaty  2015  1344.900000    260820.5  345429.6
2  Almaty  2016   716.800000    339764.1  474647.2
3  Almaty  2017   865.600000    447263.7  526917.7
4  Almaty  2018   605.300000    409551.7  399413.0
5  Almaty  2019   516.600000    600723.0  324509.8
6  Almaty  2020   184.300000    874496.2  325582.2
7  Almaty  2021   219.900000   1147647.5  470836.6
8  Almaty  2022   246.900000   1456233.7  421563.1
9  Almaty  2023   230.947483   1399140.2  436787.9

In [305]:
baikonyr = pd.read_excel(Path("../Data/Controls/Astana-city_All.xlsx"), sheet_name="Байконыр", header=2, usecols='B:H', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])
baikonyr.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
baikonyr = baikonyr.loc[[82, 57, 141]].reset_index(drop=True)
baikonyr['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2018, 2019, 2020, 2021, 2022, 2023]:
    baikonyr[i] = baikonyr[i].astype(str)
    baikonyr[i] = baikonyr[i].str.replace(',', '.')
    baikonyr[i] = baikonyr[i].str.replace(')', '')
    baikonyr[i] = baikonyr[i].str.replace(' ', '')
    baikonyr[i] = baikonyr[i].str.replace('\xa0', '')
    baikonyr[i] = baikonyr[i].str.replace('*', '')
    baikonyr[i] = baikonyr[i].astype(float)
baikonyr
baikonyr = pd.melt(baikonyr, id_vars=['Indicator'], var_name='year', value_name='value')
baikonyr = baikonyr.pivot(index='year', columns='Indicator', values='value').reset_index()
baikonyr.insert(0, 'rayon', 'Baikonur')
baikonyr.columns.name = None
baikonyr

      rayon  year  agriculture  production    retail
0  Baikonur  2018   224.100000    154611.2  201773.0
1  Baikonur  2019   119.500000    164573.2  270853.2
2  Baikonur  2020   162.400000    167971.5  382923.0
3  Baikonur  2021    63.400000    224371.7  376875.5
4  Baikonur  2022    74.500000    300186.2  454731.8
5  Baikonur  2023    76.559057    311192.0  469734.4

In [306]:
yesil = pd.read_excel(Path("../Data/Controls/Astana-city_All.xlsx"), sheet_name="Есиль", header=2, usecols='B, H:R', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])
yesil
yesil.columns = ['Indicator', 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
yesil = yesil.loc[[82, 57, 141]].reset_index(drop=True)
yesil['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    yesil[i] = yesil[i].astype(str)
    yesil[i] = yesil[i].str.replace(',', '.')
    yesil[i] = yesil[i].str.replace(')', '')
    yesil[i] = yesil[i].str.replace(' ', '')
    yesil[i] = yesil[i].str.replace('\xa0', '')
    yesil[i] = yesil[i].str.replace('*', '')
    yesil[i] = yesil[i].astype(float)

yesil = pd.melt(yesil, id_vars=['Indicator'], var_name='year', value_name='value')
yesil = yesil.pivot(index='year', columns='Indicator', values='value').reset_index()
yesil.insert(0, 'rayon', 'Yesil')
yesil.columns.name = None
yesil

    rayon  year  agriculture  production    retail
0   Yesil  2013   267.200000     48218.6   55486.5
1   Yesil  2014   231.700000     38191.8   69830.7
2   Yesil  2015   243.200000     33635.2  126271.1
3   Yesil  2016   161.100000     22338.1  115524.7
4   Yesil  2017   165.800000     38560.5  211260.6
5   Yesil  2018    81.800000     32306.3  229012.9
6   Yesil  2019    64.000000     62902.0  336309.7
7   Yesil  2020    48.500000     75409.9  396493.1
8   Yesil  2021   105.400000     77205.8  501664.8
9   Yesil  2022   118.400000     94772.5  871785.8
10  Yesil  2023   152.186857     62155.3  605585.8

In [307]:
saryarka = pd.read_excel(Path("../Data/Controls/Astana-city_All.xlsx"), sheet_name="Сарыарка", header=2, usecols='B, S:AB', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])
saryarka.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
saryarka = saryarka.loc[[82, 57, 141]].reset_index(drop=True)
saryarka['Indicator'] = ['production', 'agriculture', 'retail']
saryarka
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    saryarka[i] = saryarka[i].astype(str)
    saryarka[i] = saryarka[i].str.replace(',', '.')
    saryarka[i] = saryarka[i].str.replace(')', '')
    saryarka[i] = saryarka[i].str.replace(' ', '')
    saryarka[i] = saryarka[i].str.replace('\xa0', '')
    saryarka[i] = saryarka[i].str.replace('*', '')
    saryarka[i] = saryarka[i].astype(float)

saryarka = pd.melt(saryarka, id_vars=['Indicator'], var_name='year', value_name='value')
saryarka = saryarka.pivot(index='year', columns='Indicator', values='value').reset_index()
saryarka.insert(0, 'rayon', 'Saryarka')
saryarka.columns.name = None
saryarka

      rayon  year  agriculture  production    retail
0  Saryarka  2014   629.400000     96723.1  268938.6
1  Saryarka  2015   828.800000     94675.9  271198.6
2  Saryarka  2016   155.000000     92310.3  322899.2
3  Saryarka  2017   277.300000     88103.0  305762.3
4  Saryarka  2018   140.000000     50205.2  313551.2
5  Saryarka  2019   105.200000     56147.2  335857.3
6  Saryarka  2020   101.900000     66578.1  264474.6
7  Saryarka  2021   114.400000     94689.4  343301.1
8  Saryarka  2022   130.300000    120155.1  410897.4
9  Saryarka  2023   138.084938    122728.7  517781.6

In [308]:
nura = pd.read_excel(Path("../Data/Controls/Astana-city_All.xlsx"), sheet_name="Нура", header=2, usecols='B, C', nrows=149, na_values=['x', 'х', '-', '', ' ', '...'])
nura.columns = ['Indicator', 2023]
nura = nura.loc[[82, 57, 141]].reset_index(drop=True)
nura['Indicator'] = ['production', 'agriculture', 'retail']
nura
for i in [2023]:
    nura[i] = nura[i].astype(str)
    nura[i] = nura[i].str.replace(',', '.')
    nura[i] = nura[i].str.replace(')', '')
    nura[i] = nura[i].str.replace(' ', '')
    nura[i] = nura[i].str.replace('\xa0', '')
    nura[i] = nura[i].str.replace('*', '')
    nura[i] = nura[i].astype(float)

nura = pd.melt(nura, id_vars=['Indicator'], var_name='year', value_name='value')
nura = nura.pivot(index='year', columns='Indicator', values='value').reset_index()
nura.insert(0, 'rayon', 'Yesil')
nura.columns.name = None
nura

   rayon  year  agriculture  production    retail
0  Yesil  2023          NaN     35709.6  563697.5

In [309]:
astana_city_controls = pd.concat([almaty_rayon, baikonyr, yesil, saryarka, nura], ignore_index=True)
astana_city_controls

       rayon  year  agriculture  production    retail
0     Almaty  2014  2009.800000    209768.7  338821.4
1     Almaty  2015  1344.900000    260820.5  345429.6
2     Almaty  2016   716.800000    339764.1  474647.2
3     Almaty  2017   865.600000    447263.7  526917.7
4     Almaty  2018   605.300000    409551.7  399413.0
5     Almaty  2019   516.600000    600723.0  324509.8
6     Almaty  2020   184.300000    874496.2  325582.2
7     Almaty  2021   219.900000   1147647.5  470836.6
8     Almaty  2022   246.900000   1456233.7  421563.1
9     Almaty  2023   230.947483   1399140.2  436787.9
10  Baikonur  2018   224.100000    154611.2  201773.0
11  Baikonur  2019   119.500000    164573.2  270853.2
12  Baikonur  2020   162.400000    167971.5  382923.0
13  Baikonur  2021    63.400000    224371.7  376875.5
14  Baikonur  2022    74.500000    300186.2  454731.8
15  Baikonur  2023    76.559057    311192.0  469734.4
16     Yesil  2013   267.200000     48218.6   55486.5
17     Yesil  2014   231.700000     38191.8   69830.7
18     Yesil  2015   243.200000     33635.2  126271.1
19     Yesil  2016   161.100000     22338.1  115524.7
20     Yesil  2017   165.800000     38560.5  211260.6
21     Yesil  2018    81.800000     32306.3  229012.9
22     Yesil  2019    64.000000     62902.0  336309.7
23     Yesil  2020    48.500000     75409.9  396493.1
24     Yesil  2021   105.400000     77205.8  501664.8
25     Yesil  2022   118.400000     94772.5  871785.8
26     Yesil  2023   152.186857     62155.3  605585.8
27  Saryarka  2014   629.400000     96723.1  268938.6
28  Saryarka  2015   828.800000     94675.9  271198.6
29  Saryarka  2016   155.000000     92310.3  322899.2
30  Saryarka  2017   277.300000     88103.0  305762.3
31  Saryarka  2018   140.000000     50205.2  313551.2
32  Saryarka  2019   105.200000     56147.2  335857.3
33  Saryarka  2020   101.900000     66578.1  264474.6
34  Saryarka  2021   114.400000     94689.4  343301.1
35  Saryarka  2022   130.300000    120155.1  410897.4
36  Saryarka  2023   138.084938    122728.7  517781.6
37     Yesil  2023          NaN     35709.6  563697.5

In [310]:
# Replace Nura with Yesil
astana_city_controls['rayon'] = astana_city_controls['rayon'].replace('Nura', 'Yesil')

# Drop Astana city rows
astana_city_controls = astana_city_controls[astana_city_controls['rayon'] != 'Astana city']

# Group and aggregate
astana_city_controls = (
    astana_city_controls
    .groupby(['year','rayon'], as_index=False)
    .agg({
        'agriculture': 'sum',
        'production': 'sum',
        'retail': 'sum'
    })
)

# Add oblast column
astana_city_controls

    year     rayon  agriculture  production     retail
0   2013     Yesil   267.200000     48218.6    55486.5
1   2014    Almaty  2009.800000    209768.7   338821.4
2   2014  Saryarka   629.400000     96723.1   268938.6
3   2014     Yesil   231.700000     38191.8    69830.7
4   2015    Almaty  1344.900000    260820.5   345429.6
5   2015  Saryarka   828.800000     94675.9   271198.6
6   2015     Yesil   243.200000     33635.2   126271.1
7   2016    Almaty   716.800000    339764.1   474647.2
8   2016  Saryarka   155.000000     92310.3   322899.2
9   2016     Yesil   161.100000     22338.1   115524.7
10  2017    Almaty   865.600000    447263.7   526917.7
11  2017  Saryarka   277.300000     88103.0   305762.3
12  2017     Yesil   165.800000     38560.5   211260.6
13  2018    Almaty   605.300000    409551.7   399413.0
14  2018  Baikonur   224.100000    154611.2   201773.0
15  2018  Saryarka   140.000000     50205.2   313551.2
16  2018     Yesil    81.800000     32306.3   229012.9
17  2019    Almaty   516.600000    600723.0   324509.8
18  2019  Baikonur   119.500000    164573.2   270853.2
19  2019  Saryarka   105.200000     56147.2   335857.3
20  2019     Yesil    64.000000     62902.0   336309.7
21  2020    Almaty   184.300000    874496.2   325582.2
22  2020  Baikonur   162.400000    167971.5   382923.0
23  2020  Saryarka   101.900000     66578.1   264474.6
24  2020     Yesil    48.500000     75409.9   396493.1
25  2021    Almaty   219.900000   1147647.5   470836.6
26  2021  Baikonur    63.400000    224371.7   376875.5
27  2021  Saryarka   114.400000     94689.4   343301.1
28  2021     Yesil   105.400000     77205.8   501664.8
29  2022    Almaty   246.900000   1456233.7   421563.1
30  2022  Baikonur    74.500000    300186.2   454731.8
31  2022  Saryarka   130.300000    120155.1   410897.4
32  2022     Yesil   118.400000     94772.5   871785.8
33  2023    Almaty   230.947483   1399140.2   436787.9
34  2023  Baikonur    76.559057    311192.0   469734.4
35  2023  Saryarka   138.084938    122728.7   517781.6
36  2023     Yesil   152.186857     97864.9  1169283.3

## PPI

In [311]:
astana_city_ppi = pd.read_excel(
    Path("../Data/PPI/Astana-city.xls"),
    header=2,
    usecols='X:AH',
    nrows=216,
    na_values=['x', 'х', '-', '', ' ', '...']
)

astana_city_ppi.columns = [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

rayons = list(astana_city_inv['rayon'].unique())

dfs = []

for rayon in rayons:
    df_temp = pd.DataFrame({
        'rayon': [rayon] * len(range(2014, 2025)),
        'year': list(range(2014, 2025)),
        'ppi': astana_city_ppi.iloc[1].values
    })
    dfs.append(df_temp)

astana_city_ppi = pd.concat(dfs, ignore_index=True)

astana_city_ppi['ppi'] = astana_city_ppi['ppi'].astype(str).str.replace(',', '.')
astana_city_ppi['ppi'] = astana_city_ppi['ppi'].astype(str).str.replace(')', '')
astana_city_ppi['ppi'] = astana_city_ppi['ppi'].astype(str).str.replace(' ', '')
astana_city_ppi['ppi'] = astana_city_ppi['ppi'].astype(str).str.replace('\xa0', '')
astana_city_ppi['ppi'] = astana_city_ppi['ppi'].astype(str).str.replace('*', '')
astana_city_ppi['ppi'] = astana_city_ppi['ppi'].astype(float)


astana_city_ppi

          rayon  year    ppi
0   Astana city  2014  106.4
1   Astana city  2015   98.6
2   Astana city  2016  106.5
3   Astana city  2017  111.5
4   Astana city  2018  109.4
5   Astana city  2019  101.0
6   Astana city  2020  102.8
7   Astana city  2021  111.5
8   Astana city  2022  103.1
9   Astana city  2023   97.7
10  Astana city  2024  105.3
11       Almaty  2014  106.4
12       Almaty  2015   98.6
13       Almaty  2016  106.5
14       Almaty  2017  111.5
15       Almaty  2018  109.4
16       Almaty  2019  101.0
17       Almaty  2020  102.8
18       Almaty  2021  111.5
19       Almaty  2022  103.1
20       Almaty  2023   97.7
21       Almaty  2024  105.3
22        Yesil  2014  106.4
23        Yesil  2015   98.6
24        Yesil  2016  106.5
25        Yesil  2017  111.5
26        Yesil  2018  109.4
27        Yesil  2019  101.0
28        Yesil  2020  102.8
29        Yesil  2021  111.5
30        Yesil  2022  103.1
31        Yesil  2023   97.7
32        Yesil  2024  105.3
33     Saryarka  2014  106.4
34     Saryarka  2015   98.6
35     Saryarka  2016  106.5
36     Saryarka  2017  111.5
37     Saryarka  2018  109.4
38     Saryarka  2019  101.0
39     Saryarka  2020  102.8
40     Saryarka  2021  111.5
41     Saryarka  2022  103.1
42     Saryarka  2023   97.7
43     Saryarka  2024  105.3
44     Baikonur  2014  106.4
45     Baikonur  2015   98.6
46     Baikonur  2016  106.5
47     Baikonur  2017  111.5
48     Baikonur  2018  109.4
49     Baikonur  2019  101.0
50     Baikonur  2020  102.8
51     Baikonur  2021  111.5
52     Baikonur  2022  103.1
53     Baikonur  2023   97.7
54     Baikonur  2024  105.3

## Combine

In [312]:
dfs_astana_city = [astana_city_inv, astana_city_employment, astana_city_controls, astana_city_ppi]
astana_city_merged = reduce(lambda left, right: pd.merge(left, right, on=['rayon', 'year'], how='outer'), dfs_astana_city)
# Drop Astana city rows
astana_city_merged = astana_city_merged[astana_city_merged['rayon'] != 'Astana city']
astana_city_merged

,rayon,l_all_inv,f_all_inv,oblast,year,f_nonextr_inv,l_nonextr_inv,employment,agriculture,production,retail,ppi
0,Almaty,140584191,11223734,Astana city,2014,NaN,NaN,195.522,2009.800000,209768.7,338821.4,106.4
1,Almaty,167342610,15633540,Astana city,2015,15633540,150607688.0,206.316,1344.900000,260820.5,345429.6,98.6
2,Almaty,168845711,13696825,Astana city,2016,13696826,145196687.0,201.143,716.800000,339764.1,474647.2,106.5
3,Almaty,131567660,12074169,Astana city,2017,12074169,122643236.0,213.764,865.600000,447263.7,526917.7,111.5
4,Almaty,128851836,8531136,Astana city,2018,8531137,117773627.0,148.682,605.300000,409551.7,399413.0,109.4
5,Almaty,97991520,14734002,Astana city,2019,14734002,87823511.0,142.205,516.600000,600723.0,324509.8,101.0
6,Almaty,155279227,9999262,Astana city,2020,9999262,127882002.0,136.324,184.300000,874496.2,325582.2,102.8
7,Almaty,133540907,15999691,Astana city,2021,15999691,111984621.0,136.959,219.900000,1147647.5,470836.6,111.5
8,Almaty,193432117,7667729,Astana city,2022,7667729,130574153.0,157.614,246.900000,1456233.7,421563.1,103.1
9,Almaty,222851056,14502304,Astana city,2023,14502304.0,111256609.0,170.000,230.947483,1399140.2,436787.9,97.7
10,Almaty,169091523,15116409,Astana city,2024,15116409,112539960.0,NaN,NaN,NaN,NaN,105.3
22,Baikonur,NaN,NaN,NaN,2014,NaN,NaN,0.000,NaN,NaN,NaN,106.4
23,Baikonur,NaN,NaN,NaN,2015,NaN,NaN,0.000,NaN,NaN,NaN,98.6
24,Baikonur,NaN,NaN,NaN,2016,NaN,NaN,0.000,NaN,NaN,NaN,106.5
25,Baikonur,NaN,NaN,NaN,2017,NaN,NaN,0.000,NaN,NaN,NaN,111.5
26,Baikonur,30334203,1676122,Astana city,2018,1676122,27521644.0,102.242,224.100000,154611.2,201773.0,109.4
27,Baikonur,63260761,2963763,Astana city,2019,2963763,57180138.0,124.096,119.500000,164573.2,270853.2,101.0
28,Baikonur,65809791,5462793,Astana city,2020,5462793,55822026.0,118.005,162.400000,167971.5,382923.0,102.8
29,Baikonur,125906015,3243924,Astana city,2021,3243924,114628948.0,118.365,63.400000,224371.7,376875.5,111.5
30,Baikonur,112241586,2405134,Astana city,2022,2405134,99968540.0,119.911,74.500000,300186.2,454731.8,103.1
31,Baikonur,336447119,16142383,Astana city,2023,16142383.0,295077865.0,118.700,76.559057,311192.0,469734.4,97.7
32,Baikonur,372558262,12217881,Astana city,2024,12217881,344052158.0,NaN,NaN,NaN,NaN,105.3
33,Saryarka,215210920,2245427,Astana city,2014,NaN,NaN,177.769,629.400000,96723.1,268938.6,106.4
34,Saryarka,196280489,2275643,Astana city,2015,2275643,84206016.0,192.560,828.800000,94675.9,271198.6,98.6
35,Saryarka,162994818,4074300,Astana city,2016,4074300,60820724.0,191.997,155.000000,92310.3,322899.2,106.5
36,Saryarka,171257144,3378168,Astana city,2017,3378168,50627315.0,199.628,277.300000,88103.0,305762.3,111.5
37,Saryarka,193836297,14547907,Astana city,2018,14547907,84471093.0,160.652,140.000000,50205.2,313551.2,109.4
38,Saryarka,112353466,10381534,Astana city,2019,10381534,33997577.0,173.013,105.200000,56147.2,335857.3,101.0
39,Saryarka,98290485,3894312,Astana city,2020,3894312,23300152.0,174.392,101.900000,66578.1,264474.6,102.8
40,Saryarka,112746153,9496629,Astana city,2021,9496629,50313480.0,176.372,114.400000,94689.4,343301.1,111.5
41,Saryarka,120716495,56027709,Astana city,2022,56027709,71922398.0,175.953,130.300000,120155.1,410897.4,103.1
42,Saryarka,99385300,5199771,Astana city,2023,5199771.0,72513790.0,171.600,138.084938,122728.7,517781.6,97.7
43,Saryarka,139952512,3341486,Astana city,2024,3341486,79600063.0,NaN,NaN,NaN,NaN,105.3
44,Yesil,NaN,NaN,NaN,2013,NaN,NaN,NaN,267.200000,48218.6,55486.5,NaN
45,Yesil,262913632,11955722,Astana city,2014,NaN,NaN,58.305,231.700000,38191.8,69830.7,106.4
46,Yesil,380158754,11010619,Astana city,2015,11010619,277951634.0,67.211,243.200000,33635.2,126271.1,98.6
47,Yesil,457878764,30201531,Astana city,2016,30201531,364762091.0,72.916,161.100000,22338.1,115524.7,106.5
48,Yesil,446771526,179598846,Astana city,2017,179598846,375406016.0,84.142,165.800000,38560.5,211260.6,111.5
49,Yesil,448157106,230799111,Astana city,2018,230799111,419349100.0,95.897,81.800000,32306.3,229012.9,109.4
50,Yesil,426525264,185488837,Astana city,2019,185488837,382433993.0,114.017,64.000000,62902.0,336309.7,101.0
51,Yesil,657847290,118984373,Astana city,2020,118984373,525487030.0,134.711,48.500000,75409.9,396493.1,102.8
52,Yesil,778154089,34411216,Astana city,2021,34411216,689450285.0,148.602,105.400000,77205.8,501664.8,111.5
53,Yesil,905455615,48839417,Astana city,2022,48839417,741674253.0,172.034,118.400000,94772.5,871785.8,103.1
54,Yesil,943105385,17398670,Astana city,2023,17398670.0,681628037.0,198.400,152.186857,97864.9,1169283.3,97.7
55,Yesil,1129432449,56812290,Astana city,2024,56812290,695392207.0,NaN,NaN,NaN,NaN,105.3

# Atyrau

## Investments

In [313]:
atyrau_all_2016 = pd.read_excel(Path("../Data/Investments/Atyrau/2016_Investments/Internal_vs_external.xls"), header=6, nrows=9, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
atyrau_all_2017 = pd.read_excel(Path("../Data/Investments/Atyrau/2017_Investments/Internal_vs_external.xls"), header=6, nrows=9, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
atyrau_all_2018 = pd.read_excel(Path("../Data/Investments/Atyrau/2018_Investments/Internal_vs_external.xls"), header=6, nrows=9, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
atyrau_all_2019 = pd.read_excel(Path("../Data/Investments/Atyrau/2019_Investments.xls"), sheet_name='14', header=4, nrows=9, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
atyrau_all_2020 = pd.read_excel(Path("../Data/Investments/Atyrau/2020_Investments.xls"), sheet_name='13', header=4, nrows=9, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
atyrau_all_2021 = pd.read_excel(Path("../Data/Investments/Atyrau/2021_Investments.xlsx"), sheet_name='13', header=3, nrows=9, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
atyrau_all_2022 = pd.read_excel(Path("../Data/Investments/Atyrau/2022_Investments.xlsx"), sheet_name='14', header=3, nrows=9, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
atyrau_all_2023 = pd.read_excel(Path("../Data/Investments/Atyrau/2023_Investments.xlsx"), sheet_name='18', header=3, nrows=9, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
atyrau_all_2024 = pd.read_excel(Path("../Data/Investments/Atyrau/2024_Investments.xlsx"), sheet_name='14', header=3, nrows=9, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

atyrau_non_2016 = pd.read_excel(Path("../Data/Investments/Atyrau/2016_Investments/Greenfield_investments.xls"), header=7, nrows=9, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
atyrau_non_2017 = pd.read_excel(Path("../Data/Investments/Atyrau/2017_Investments/Greenfield_investments.xls"), header=7, nrows=9, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
atyrau_non_2018 = pd.read_excel(Path("../Data/Investments/Atyrau/2018_Investments/Greenfield_investments.xls"), header=7, nrows=9, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
atyrau_non_2019 = pd.read_excel(Path("../Data/Investments/Atyrau/2019_Investments.xls"), sheet_name='15', header=4, nrows=9, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
atyrau_non_2020 = pd.read_excel(Path("../Data/Investments/Atyrau/2020_Investments.xls"), sheet_name='14', header=4, nrows=9, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
atyrau_non_2021 = pd.read_excel(Path("../Data/Investments/Atyrau/2021_Investments.xlsx"), sheet_name='14', header=4, nrows=9, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
atyrau_non_2022 = pd.read_excel(Path("../Data/Investments/Atyrau/2022_Investments.xlsx"), sheet_name='15', header=3, nrows=9, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
atyrau_non_2023 = pd.read_excel(Path("../Data/Investments/Atyrau/2023_Investments.xlsx"), sheet_name='19', header=3, nrows=9, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
atyrau_non_2024 = pd.read_excel(Path("../Data/Investments/Atyrau/2024_Investments.xlsx"), sheet_name='15', header=3, nrows=9, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [314]:
dfs = [atyrau_all_2016, atyrau_all_2017, atyrau_all_2018, atyrau_all_2019, atyrau_all_2020, atyrau_all_2021,
      atyrau_all_2022, atyrau_all_2023, atyrau_all_2024]

lists = []

for df in dfs:
    lists.extend(df.iloc[:, 0].unique())

unique_lists = pd.Series(lists).unique()
unique_lists

array(['Атырау қ.ә.', 'Жылыой ', 'Индер', 'Исатай ', 'Құрманғазы',
       'Қызылқоға ', 'Мақат ', 'Махамбет ', 'Атырау г.а.', 'Жылыойский',
       'Индерский', 'Исатайский', 'Курмангазинский', 'Кзылкогинский',
       'Макатский', 'Махамбетский'], dtype=object)

In [315]:
dfs = [atyrau_non_2016, atyrau_non_2017, atyrau_non_2018, atyrau_non_2019, atyrau_non_2020, atyrau_non_2021,
      atyrau_non_2022, atyrau_non_2023, atyrau_non_2024]

lists = []

for df in dfs:
    lists.extend(df.iloc[:, 0].unique())

unique_lists = pd.Series(lists).unique()
unique_lists

array(['Атырау қ.ә.', 'Жылыой ', 'Индер', 'Исатай ', 'Құрманғазы',
       'Қызылқоға ', 'Мақат ', 'Махамбет ', 'Атырау г.а.', 'Жылыойский',
       'Индерский', 'Исатайский', 'Курмангазинский', 'Кзылкогинский',
       'Макатский', 'Махамбетский'], dtype=object)

In [316]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [atyrau_all_2016, atyrau_all_2017, atyrau_all_2018, atyrau_all_2019, atyrau_all_2020, atyrau_all_2021,
      atyrau_all_2022, atyrau_all_2023, atyrau_all_2024]:
    df.columns = all_columns

for df in [atyrau_non_2016, atyrau_non_2017, atyrau_non_2018, atyrau_non_2019, atyrau_non_2020,
      atyrau_non_2021, atyrau_non_2022, atyrau_non_2023, atyrau_non_2024]:
    df.columns = non_columns
    
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

In [317]:
rayon_map_atyrau = {

    # ---- City ----
    'Атырау қ.ә.': 'Atyrau city',
    'Атырау г.а.': 'Atyrau city',
    'Атырауская г.а': 'Atyrau city',
    'Атырау  Г.А.': 'Atyrau city',

    # ---- Zhylyoi ----
    'Жылыой ': 'Zhylyoi',
    'Жылыойский': 'Zhylyoi',
    'Жылыойский район': 'Zhylyoi',
    'Жылыой': 'Zhylyoi',

    # ---- Inder ----
    'Индер': 'Inder',
    'Индерский': 'Inder',
    "Индерский район": 'Inder',
    "Индер": 'Inder',
    'Индер ': 'Inder',

    # ---- Isatai ----
    'Исатай ': 'Isatai',
    'Исатайский': 'Isatai',
    'Исатайский район': 'Isatai',
    'Исатай': 'Isatai',

    # ---- Kurmangazy ----
    'Құрманғазы': 'Kurmangazy',
    'Курмангазинский': 'Kurmangazy',
    'Курмангазинский район': 'Kurmangazy',
    'Курмангазы': 'Kurmangazy',
    'Құрманғазы ': 'Kurmangazy',

    # ---- Kyzylkoga ----
    'Қызылқоға ': 'Kyzylkoga',
    'Кзылкогинский': 'Kyzylkoga',
    'Кзылкогинский район': 'Kyzylkoga',
    'Кызылкога': 'Kyzylkoga',

    # ---- Makat ----
    'Мақат ': 'Makat',
    'Макатский': 'Makat',
    'Макатский район': 'Makat',
    'Макат': 'Makat',

    # ---- Makhambet ----
    'Махамбет ': 'Makhambet',
    'Махамбетский': 'Makhambet',
    'Махамбетский район': 'Makhambet'
}

In [318]:
# ----- ALL investments -----
atyrau_all_2016['rayon'] = atyrau_all_2016['rayon'].replace(rayon_map_atyrau)
atyrau_all_2017['rayon'] = atyrau_all_2017['rayon'].replace(rayon_map_atyrau)
atyrau_all_2018['rayon'] = atyrau_all_2018['rayon'].replace(rayon_map_atyrau)
atyrau_all_2019['rayon'] = atyrau_all_2019['rayon'].replace(rayon_map_atyrau)
atyrau_all_2020['rayon'] = atyrau_all_2020['rayon'].replace(rayon_map_atyrau)
atyrau_all_2021['rayon'] = atyrau_all_2021['rayon'].replace(rayon_map_atyrau)
atyrau_all_2022['rayon'] = atyrau_all_2022['rayon'].replace(rayon_map_atyrau)
atyrau_all_2023['rayon'] = atyrau_all_2023['rayon'].replace(rayon_map_atyrau)
atyrau_all_2024['rayon'] = atyrau_all_2024['rayon'].replace(rayon_map_atyrau)

# ----- NON-extractive investments -----
atyrau_non_2016['rayon'] = atyrau_non_2016['rayon'].replace(rayon_map_atyrau)
atyrau_non_2017['rayon'] = atyrau_non_2017['rayon'].replace(rayon_map_atyrau)
atyrau_non_2018['rayon'] = atyrau_non_2018['rayon'].replace(rayon_map_atyrau)
atyrau_non_2019['rayon'] = atyrau_non_2019['rayon'].replace(rayon_map_atyrau)
atyrau_non_2020['rayon'] = atyrau_non_2020['rayon'].replace(rayon_map_atyrau)
atyrau_non_2021['rayon'] = atyrau_non_2021['rayon'].replace(rayon_map_atyrau)
atyrau_non_2022['rayon'] = atyrau_non_2022['rayon'].replace(rayon_map_atyrau)
atyrau_non_2023['rayon'] = atyrau_non_2023['rayon'].replace(rayon_map_atyrau)
atyrau_non_2024['rayon'] = atyrau_non_2024['rayon'].replace(rayon_map_atyrau)

In [319]:
atyrau_2016 = atyrau_all_2016.merge(atyrau_non_2016, on='rayon', how='left')
atyrau_2017 = atyrau_all_2017.merge(atyrau_non_2017, on='rayon', how='left')
atyrau_2018 = atyrau_all_2018.merge(atyrau_non_2018, on='rayon', how='left')
atyrau_2019 = atyrau_all_2019.merge(atyrau_non_2019, on='rayon', how='left')
atyrau_2020 = atyrau_all_2020.merge(atyrau_non_2020, on='rayon', how='left')
atyrau_2021 = atyrau_all_2021.merge(atyrau_non_2021, on='rayon', how='left')
atyrau_2022 = atyrau_all_2022.merge(atyrau_non_2022, on='rayon', how='left')
atyrau_2023 = atyrau_all_2023.merge(atyrau_non_2023, on='rayon', how='left')
atyrau_2024 = atyrau_all_2024.merge(atyrau_non_2024, on='rayon', how='left')

dfs = [atyrau_2016, atyrau_2017, atyrau_2018, atyrau_2019, atyrau_2020, atyrau_2021, atyrau_2022, atyrau_2023, atyrau_2024]

for i in range(9):
    df = dfs[i]
    df['oblast'] = 'Atyrau'
    df['year'] = 2016 + i

atyrau_inv = pd.concat([atyrau_2016, atyrau_2017, atyrau_2018, atyrau_2019, atyrau_2020, atyrau_2021, atyrau_2022, atyrau_2023, atyrau_2024], ignore_index=True)
atyrau_inv['rayon'] = (
    atyrau_inv['rayon']
        .str.strip()          # remove hidden spaces
        .replace(rayon_map)   # enforce English names
)
atyrau_inv

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year
0,Atyrau city,368274513,454770336,93846749.0,182036874.0,Atyrau,2016
1,Zhylyoi,577504940,527411484,8278158.0,12717932.0,Atyrau,2016
2,Inder,2607016,128407,128407.0,922894.0,Atyrau,2016
3,Isatai,18857847,11111499,10710440.0,11393399.0,Atyrau,2016
4,Kurmangazy,23413784,15134481,13690385.0,14098926.0,Atyrau,2016
...,...,...,...,...,...,...,...
67,Isatai,50093576,15080117,549486.0,4274409.0,Atyrau,2024
68,Kurmangazy,28856634,346786,346786.0,9518865.0,Atyrau,2024
69,Kyzylkoga,41198801,4121325,3083519.0,6050803.0,Atyrau,2024
70,Makat,261680542,44103586,44046278.0,64410099.0,Atyrau,2024
71,Makhambet,37976490,8069357,7987191.0,16326089.0,Atyrau,2024

## Employment

In [320]:
atyrau_empl = pd.read_excel(Path("../Data/Employment/Atyrau.xlsx"), skiprows=21, nrows=8, header=None, usecols='A:L', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
atyrau_empl.columns = ['rayon', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
atyrau_empl['rayon'] = atyrau_empl['rayon'].replace(rayon_map_atyrau)
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    atyrau_empl[i] = atyrau_empl[i].astype(float)
atyrau_employment = atyrau_empl.melt(id_vars='rayon', value_vars=[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024], var_name='year', value_name='employment')
atyrau_employment

          rayon  year  employment
0   Atyrau city  2014       145.3
1       Zhylyoi  2014        37.3
2         Inder  2014        15.1
3        Isatai  2014        12.8
4    Kurmangazy  2014        30.0
..          ...   ...         ...
83       Isatai  2024        11.3
84   Kurmangazy  2024        23.9
85    Kyzylkoga  2024        14.8
86        Makat  2024        15.5
87    Makhambet  2024        13.4

[88 rows x 3 columns]

## Other Controls

### Production Atyrau

In [321]:
atyrau_production = pd.read_excel(Path("../Data/Controls/Atyrau_Production.xls"), skiprows=6, nrows=8, header=None, usecols='A, Y:AI', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
atyrau_production.columns = ['rayon', 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
atyrau_production['rayon'] = atyrau_production['rayon'].replace(rayon_map_atyrau)
atyrau_production
for i in [2013, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    atyrau_production[i] = atyrau_production[i].astype(float)
    atyrau_product = atyrau_production.melt(id_vars='rayon', value_vars=[2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023], var_name='year', value_name='production')
atyrau_product

          rayon  year  production
0   Atyrau city  2013         0.0
1       Zhylyoi  2013     29423.3
2         Inder  2013         0.0
3        Isatai  2013      1216.1
4    Kurmangazy  2013        50.8
..          ...   ...         ...
83       Isatai  2023       937.0
84   Kurmangazy  2023        31.1
85    Kyzylkoga  2023       740.8
86        Makat  2023       479.5
87    Makhambet  2023        25.2

[88 rows x 3 columns]

### Agriculture Atyrau

In [322]:
atyrau_agriculture = pd.read_excel(Path("../Data/Controls/Atyrau_Agriculture.xls"), skiprows=5, nrows=8, header=None, usecols='A, U:AE', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
atyrau_agriculture.columns = ['rayon', 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
atyrau_agriculture['rayon'] = atyrau_agriculture['rayon'].replace(rayon_map_atyrau)
for i in [2013, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    atyrau_agriculture[i] = atyrau_agriculture[i].astype(float)
    atyrau_agricul = atyrau_agriculture.melt(id_vars='rayon', value_vars=[2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023], var_name='year', value_name='agriculture')
atyrau_agricul

          rayon  year   agriculture
0   Atyrau city  2013   8728.100000
1       Zhylyoi  2013   4749.700000
2         Inder  2013   5895.400000
3        Isatai  2013   4367.200000
4    Kurmangazy  2013  10205.700000
..          ...   ...           ...
83       Isatai  2023   8902.620639
84   Kurmangazy  2023  21492.631531
85    Kyzylkoga  2023  17516.982535
86        Makat  2023   1243.326260
87    Makhambet  2023  21886.251218

[88 rows x 3 columns]

### Retail Atyrau

In [323]:
atyrau_retail = pd.read_excel(Path("../Data/Controls/Atyrau_Retail.xls"), skiprows=5, nrows=8, header=None, usecols='A, O:Y', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
atyrau_retail.columns = ['rayon', 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
atyrau_retail['rayon'] = atyrau_retail['rayon'].replace(rayon_map_atyrau)
atyrau_retail[2022] = (
    atyrau_retail[2022]
    .astype(str)
    .str.replace(',', '.', regex=False).str.replace(' ', '', regex=False)
)
atyrau_retail
for i in [2013, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    atyrau_retail[i] = atyrau_retail[i].astype(float)
    atyrau_reta = atyrau_retail.melt(id_vars='rayon', value_vars=[2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023], var_name='year', value_name='retail')
atyrau_reta

          rayon  year    retail
0   Atyrau city  2013  137046.7
1       Zhylyoi  2013    7286.2
2         Inder  2013    1013.9
3        Isatai  2013    1787.8
4    Kurmangazy  2013    8556.7
..          ...   ...       ...
83       Isatai  2023   13256.0
84   Kurmangazy  2023    3610.9
85    Kyzylkoga  2023    1831.4
86        Makat  2023    4381.3
87    Makhambet  2023    1864.9

[88 rows x 3 columns]

In [324]:
atyrau_controls = (atyrau_product.merge(atyrau_agricul, on=['rayon', 'year']).merge(atyrau_reta, on=['rayon', 'year']))
atyrau_controls

          rayon  year  production   agriculture    retail
0   Atyrau city  2013         0.0   8728.100000  137046.7
1       Zhylyoi  2013     29423.3   4749.700000    7286.2
2         Inder  2013         0.0   5895.400000    1013.9
3        Isatai  2013      1216.1   4367.200000    1787.8
4    Kurmangazy  2013        50.8  10205.700000    8556.7
..          ...   ...         ...           ...       ...
83       Isatai  2023       937.0   8902.620639   13256.0
84   Kurmangazy  2023        31.1  21492.631531    3610.9
85    Kyzylkoga  2023       740.8  17516.982535    1831.4
86        Makat  2023       479.5   1243.326260    4381.3
87    Makhambet  2023        25.2  21886.251218    1864.9

[88 rows x 5 columns]

## PPI

In [325]:
atyrau_ppi = pd.read_excel(
    Path("../Data/PPI/Atyrau.xls"),
    header=2,
    usecols='X:AH',
    nrows=65,
    na_values=['x', 'х', '-', '', ' ', '...']
)
atyrau_ppi.columns = [2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
rayons = list(atyrau_inv['rayon'].unique())

dfs = []

for rayon in rayons:
    df_temp = pd.DataFrame({
        'rayon': [rayon] * len(range(2013, 2024)),
        'year': list(range(2013, 2024)),
        'ppi': atyrau_ppi.iloc[-1].values
    })
    dfs.append(df_temp)

atyrau_ppi = pd.concat(dfs, ignore_index=True)
atyrau_ppi['ppi'] = atyrau_ppi['ppi'].astype(str).str.replace(',', '.')
atyrau_ppi['ppi'] = atyrau_ppi['ppi'].astype(str).str.replace(')', '')
atyrau_ppi['ppi'] = atyrau_ppi['ppi'].astype(str).str.replace(' ', '')
atyrau_ppi['ppi'] = atyrau_ppi['ppi'].astype(str).str.replace('\xa0', '')
atyrau_ppi['ppi'] = atyrau_ppi['ppi'].astype(str).str.replace('*', '')
atyrau_ppi['ppi'] = atyrau_ppi['ppi'].astype(float)

atyrau_ppi

          rayon  year    ppi
0   Atyrau city  2013   97.0
1   Atyrau city  2014   97.0
2   Atyrau city  2015   88.0
3   Atyrau city  2016  112.0
4   Atyrau city  2017  122.7
..          ...   ...    ...
83    Makhambet  2019   93.6
84    Makhambet  2020   69.1
85    Makhambet  2021  188.8
86    Makhambet  2022  119.6
87    Makhambet  2023  111.0

[88 rows x 3 columns]

## Combine

In [326]:
dfs_atyrau = [atyrau_inv, atyrau_employment, atyrau_controls, atyrau_ppi]
atyrau_merged = reduce(lambda left, right: pd.merge(left, right, on=['rayon', 'year'], how='outer'), dfs_atyrau)
atyrau_merged

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year,employment,production,agriculture,retail,ppi
0,Atyrau city,NaN,NaN,NaN,NaN,NaN,2013,NaN,0.0,8728.100000,137046.7,97.0
1,Atyrau city,NaN,NaN,NaN,NaN,NaN,2014,145.3,0.0,9142.700000,162964.6,97.0
2,Atyrau city,NaN,NaN,NaN,NaN,NaN,2015,158.5,0.0,9453.300000,143850.3,88.0
3,Atyrau city,3.682745e+08,4.547703e+08,93846749.0,182036874.0,Atyrau,2016,156.1,957.0,10792.100000,198616.0,112.0
4,Atyrau city,6.665059e+08,2.054812e+08,101953175.0,362310777.0,Atyrau,2017,163.6,8286.5,11890.100000,224739.1,122.7
...,...,...,...,...,...,...,...,...,...,...,...,...
91,Zhylyoi,1.361682e+09,1.276583e+09,9839398.0,16136036.0,Atyrau,2020,36.6,29317.3,6702.600000,20035.2,69.1
92,Zhylyoi,1.049014e+09,9.671620e+08,19187923.0,46838720.0,Atyrau,2021,37.3,29320.3,9922.800000,21112.6,188.8
93,Zhylyoi,1.089927e+09,1.033921e+09,24013184.0,33629019.0,Atyrau,2022,39.6,31905.1,11391.500000,40229.3,119.6
94,Zhylyoi,1.040185e+09,9.608689e+08,18573011.0,62898033.0,Atyrau,2023,39.1,31672.6,9418.187145,14886.0,111.0
95,Zhylyoi,6.402203e+08,4.890067e+08,20134572.0,49295578.0,Atyrau,2024,38.2,NaN,NaN,NaN,NaN

# Kostanay

## Investments

In [327]:
kostanay_all_2014 = pd.read_excel(Path("../Data/Investments/Kostanay/2014_Investments/Internal_vs_external.xls"), header=6, nrows=21, usecols='A, C, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kostanay_all_2015 = pd.read_excel(Path("../Data/Investments/Kostanay/2015_Investments/Internal_vs_external.xls"), header=6, nrows=21, usecols='A, C, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kostanay_all_2016 = pd.read_excel(Path("../Data/Investments/Kostanay/2016_Investments/Internal_vs_external.xls"), header=5, nrows=21, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kostanay_all_2017 = pd.read_excel(Path("../Data/Investments/Kostanay/2017_Investments/Internal_vs_external.xls"), header=5, nrows=21, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kostanay_all_2018 = pd.read_excel(Path("../Data/Investments/Kostanay/2018_Investments/Internal_vs_external.xls"), header=5, nrows=21, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kostanay_all_2019 = pd.read_excel(Path("../Data/Investments/Kostanay/2019_Investments.xls"), sheet_name='13.', header=4, nrows=21, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kostanay_all_2020 = pd.read_excel(Path("../Data/Investments/Kostanay/2020_Investments.xls"), sheet_name='13.', header=4, nrows=21, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kostanay_all_2021 = pd.read_excel(Path("../Data/Investments/Kostanay/2021_Investments.xls"), sheet_name='13.', header=4, nrows=21, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kostanay_all_2022 = pd.read_excel(Path("../Data/Investments/Kostanay/2022_Investments.xls"), sheet_name='13.', header=4, nrows=21, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kostanay_all_2023 = pd.read_excel(Path("../Data/Investments/Kostanay/2023_Investments.xlsx"), sheet_name='19', header=3, nrows=21, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kostanay_all_2024 = pd.read_excel(Path("../Data/Investments/Kostanay/2024_Investments.xlsx"), sheet_name='14', header=3, nrows=21, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

kostanay_non_2014 = pd.read_excel(Path("../Data/Investments/Kostanay/2014_Investments/Greenfield_investments.xls"), header=6, nrows=21, usecols='A, B, C', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kostanay_non_2015 = pd.read_excel(Path("../Data/Investments/Kostanay/2015_Investments/Greenfield_investments.xls"), header=6, nrows=21, usecols='A, B, C', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kostanay_non_2016 = pd.read_excel(Path("../Data/Investments/Kostanay/2016_Investments/Greenfield_investments.xls"), header=6, nrows=21, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kostanay_non_2017 = pd.read_excel(Path("../Data/Investments/Kostanay/2017_Investments/Greenfield_investments.xls"), header=6, nrows=21, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kostanay_non_2018 = pd.read_excel(Path("../Data/Investments/Kostanay/2018_Investments/Greenfield_investments.xls"), header=6, nrows=21, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kostanay_non_2019 = pd.read_excel(Path("../Data/Investments/Kostanay/2019_Investments.xls"), sheet_name='14.', header=5, nrows=21, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kostanay_non_2020 = pd.read_excel(Path("../Data/Investments/Kostanay/2020_Investments.xls"), sheet_name='14.', header=5, nrows=21, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kostanay_non_2021 = pd.read_excel(Path("../Data/Investments/Kostanay/2021_Investments.xls"), sheet_name='14.', header=5, nrows=21, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kostanay_non_2022 = pd.read_excel(Path("../Data/Investments/Kostanay/2022_Investments.xls"), sheet_name='14.', header=5, nrows=21, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kostanay_non_2023 = pd.read_excel(Path("../Data/Investments/Kostanay/2023_Investments.xlsx"), sheet_name='20', header=3, nrows=21, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kostanay_non_2024 = pd.read_excel(Path("../Data/Investments/Kostanay/2024_Investments.xlsx"), sheet_name='15', header=3, nrows=21, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [328]:
kostanay_non_2014

      Unnamed: 0  Unnamed: 1  внешние инвестиции
0     Алтынсарин     2028890              7684.0
1      Амангелді      442453             21845.0
2       Әулиекөл     3174581              1550.0
3        Денисов     2221615            278049.0
4      Жангелдин      513252               874.0
5       Жітіқара     1021027              5222.0
6        Қамысты     4850949                 0.0
7      Қарабалық     3450367            105329.0
8         Қарасу     3092540              5508.0
9       Қостанай     9612748             44997.0
10     Меңдіқара      228105             36425.0
11      Науырзым      150118              4998.0
12       Сарыкөл     3348910                 0.0
13         Таран     2798355           4515311.0
14       Ұзынкөл     1638496             30000.0
15       Федоров     2896167              1399.0
16   Қостанай қ.    57209538           1237556.0
17  Арқалық қ.ә.     5539499            146919.0
18  Лисаков қ.ә.     1570480            800065.0
19  Рудный қ. ә.     9925389            249554.0

In [329]:
dfs = [kostanay_all_2014, kostanay_all_2015, kostanay_all_2016, kostanay_all_2017, kostanay_all_2018, kostanay_all_2019, kostanay_all_2020,
       kostanay_all_2021, kostanay_all_2022, kostanay_all_2023, kostanay_all_2024,
       kostanay_non_2014, kostanay_non_2015, kostanay_non_2016, kostanay_non_2017, kostanay_non_2018, kostanay_non_2019, kostanay_non_2020,
      kostanay_non_2021, kostanay_non_2022, kostanay_non_2023, kostanay_non_2024]

lists = []

for df in dfs:
    lists.extend(df.iloc[:, 0].unique())

unique_lists = pd.Series(lists).unique()
unique_lists

array(['Алтынсарин', 'Амангелді', 'Әулиекөл', 'Денисов', 'Жангелдин',
       'Жітіқара', 'Қамысты', 'Қарабалық', 'Қарасу', 'Қостанай',
       'Меңдіқара', 'Науырзым', 'Сарыкөл', 'Таран', 'Ұзынкөл', 'Федоров',
       'Қостанай қ.', 'Арқалық қ.ә.', 'Лисаков қ.ә.', 'Рудный қ. ә.',
       'Қостанай қаласы', 'Рудный қ.ә.', 'Бейiмбет Майлин',
       'г. Костанай ', 'Аркалык г.а.', 'Лисаков г.а.', 'Рудный г.а.',
       'Алтынсаринский', 'Амангельдинский', 'Аулиекольский',
       'Денисовский', 'Джангельдинский', 'Житикаринский', 'Камыстинский',
       'Карабалыкский', 'Карасуский', 'Костанайский', 'Мендыкаринский',
       'Наурзумский', 'Сарыкольский', 'Беимбета Майлина', 'Узункольский',
       'Федоровский', 'Лисаковск г.а.'], dtype=object)

In [330]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [kostanay_all_2014, kostanay_all_2015, kostanay_all_2016, kostanay_all_2017,
          kostanay_all_2018, kostanay_all_2019, kostanay_all_2020, kostanay_all_2021,
          kostanay_all_2022, kostanay_all_2023, kostanay_all_2024]:
    df.columns = all_columns

for df in [kostanay_non_2014, kostanay_non_2015, kostanay_non_2016, kostanay_non_2017,
          kostanay_non_2018, kostanay_non_2019, kostanay_non_2020, kostanay_non_2021,
          kostanay_non_2022, kostanay_non_2023, kostanay_non_2024]:
    df.columns = non_columns
    
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

In [331]:
rayon_map_kostanay = {

    # ---- Cities ----
    'Қостанай қ.': 'Kostanay city',
    'Қостанай қаласы': 'Kostanay city',
    'г. Костанай ': 'Kostanay city',
    'Костанайский ': 'Kostanay city',

    'Арқалық қ.ә.': 'Arkalyk city',
    'Аркалык г.а.': 'Arkalyk city',
    'Аркалык г.а. ': 'Arkalyk city',

    'Лисаков қ.ә.': 'Lisakovsk city',
    'Лисаков г.а.': 'Lisakovsk city',
    'Лисаковск г.а.': 'Lisakovsk city',

    'Рудный қ. ә.': 'Rudny city',
    'Рудный қ.ә.': 'Rudny city',
    'Рудный г.а.': 'Rudny city',

    # ---- Rayons ----
    'Алтынсарин': 'Altynsarin',
    'Алтынсаринский': 'Altynsarin',
    'Алтынсаринский ': 'Altynsarin',

    'Амангелді': 'Amangeldi',
    'Амангельдинский': 'Amangeldi',
    'Амангельдинский ': 'Amangeldi',

    'Әулиекөл': 'Auliekol',
    'Аулиекольский': 'Auliekol',
    'Аулиекольский ': 'Auliekol',

    'Денисов': 'Denisov',
    'Денисовский': 'Denisov',
    'Денисовский ': 'Denisov',

    'Жангелдин': 'Zhangeldin',
    'Джангельдинский': 'Zhangeldin',
    'Джангельдинский ': 'Zhangeldin',

    'Жітіқара': 'Zhitikara',
    'Житикаринский': 'Zhitikara',
    'Житикаринский ': 'Zhitikara',

    'Қамысты': 'Kamysty',
    'Камыстинский': 'Kamysty',
    'Камыстинский ': 'Kamysty',

    'Қарабалық': 'Karabalyk',
    'Карабалыкский': 'Karabalyk',
    'Карабалыкский ': 'Karabalyk',

    'Қарасу': 'Karasu',
    'Карасуский': 'Karasu',
    'Карасуский ': 'Karasu',

    'Қостанай': 'Kostanay',
    'Костанайский ': 'Kostanay',
    'Костанайский':'Kostanay',

    'Меңдіқара': 'Mendykara',
    'Мендыкаринский': 'Mendykara',
    'Мендыкаринский ': 'Mendykara',

    'Науырзым': 'Naurzum',
    'Наурзумский': 'Naurzum',
    'Наурзумский ': 'Naurzum',

    'Сарыкөл': 'Sarykol',
    'Сарыкольский': 'Sarykol',
    'Сарыкольский ': 'Sarykol',

    'Ұзынкөл': 'Uzunkol',
    'Узункольский': 'Uzunkol',
    'Узункольский ': 'Uzunkol',

    'Федоров': 'Fyodorov',
    'Федоровский': 'Fyodorov',
    'Федоровский ': 'Fyodorov',

    'Бейiмбет Майлин': 'Beimbet Mailin',
    'Беимбета Майлина': 'Beimbet Mailin',
    
    'Таран': "Taran"
}

In [332]:
# ----- ALL investments -----
kostanay_all_2014['rayon'] = kostanay_all_2014['rayon'].replace(rayon_map_kostanay)
kostanay_all_2015['rayon'] = kostanay_all_2015['rayon'].replace(rayon_map_kostanay)
kostanay_all_2016['rayon'] = kostanay_all_2016['rayon'].replace(rayon_map_kostanay)
kostanay_all_2017['rayon'] = kostanay_all_2017['rayon'].replace(rayon_map_kostanay)
kostanay_all_2018['rayon'] = kostanay_all_2018['rayon'].replace(rayon_map_kostanay)
kostanay_all_2019['rayon'] = kostanay_all_2019['rayon'].replace(rayon_map_kostanay)
kostanay_all_2020['rayon'] = kostanay_all_2020['rayon'].replace(rayon_map_kostanay)
kostanay_all_2021['rayon'] = kostanay_all_2021['rayon'].replace(rayon_map_kostanay)
kostanay_all_2022['rayon'] = kostanay_all_2022['rayon'].replace(rayon_map_kostanay)
kostanay_all_2023['rayon'] = kostanay_all_2023['rayon'].replace(rayon_map_kostanay)
kostanay_all_2024['rayon'] = kostanay_all_2024['rayon'].replace(rayon_map_kostanay)

# ----- NON-extractive investments -----
kostanay_non_2014['rayon'] = kostanay_non_2014['rayon'].replace(rayon_map_kostanay)
kostanay_non_2015['rayon'] = kostanay_non_2015['rayon'].replace(rayon_map_kostanay)
kostanay_non_2016['rayon'] = kostanay_non_2016['rayon'].replace(rayon_map_kostanay)
kostanay_non_2017['rayon'] = kostanay_non_2017['rayon'].replace(rayon_map_kostanay)
kostanay_non_2018['rayon'] = kostanay_non_2018['rayon'].replace(rayon_map_kostanay)
kostanay_non_2019['rayon'] = kostanay_non_2019['rayon'].replace(rayon_map_kostanay)
kostanay_non_2020['rayon'] = kostanay_non_2020['rayon'].replace(rayon_map_kostanay)
kostanay_non_2021['rayon'] = kostanay_non_2021['rayon'].replace(rayon_map_kostanay)
kostanay_non_2022['rayon'] = kostanay_non_2022['rayon'].replace(rayon_map_kostanay)
kostanay_non_2023['rayon'] = kostanay_non_2023['rayon'].replace(rayon_map_kostanay)
kostanay_non_2024['rayon'] = kostanay_non_2024['rayon'].replace(rayon_map_kostanay)

In [333]:
kostanay_2014 = kostanay_all_2014.merge(kostanay_non_2014, on='rayon', how='left')
kostanay_2015 = kostanay_all_2015.merge(kostanay_non_2015, on='rayon', how='left')
kostanay_2016 = kostanay_all_2016.merge(kostanay_non_2016, on='rayon', how='left')
kostanay_2017 = kostanay_all_2017.merge(kostanay_non_2017, on='rayon', how='left')
kostanay_2018 = kostanay_all_2018.merge(kostanay_non_2018, on='rayon', how='left')
kostanay_2019 = kostanay_all_2019.merge(kostanay_non_2019, on='rayon', how='left')
kostanay_2020 = kostanay_all_2020.merge(kostanay_non_2020, on='rayon', how='left')
kostanay_2021 = kostanay_all_2021.merge(kostanay_non_2021, on='rayon', how='left')
kostanay_2022 = kostanay_all_2022.merge(kostanay_non_2022, on='rayon', how='left')
kostanay_2023 = kostanay_all_2023.merge(kostanay_non_2023, on='rayon', how='left')
kostanay_2024 = kostanay_all_2024.merge(kostanay_non_2024, on='rayon', how='left')

dfs = [kostanay_2014, kostanay_2015, kostanay_2016, kostanay_2017, kostanay_2018, kostanay_2019, kostanay_2020, kostanay_2021, kostanay_2022, kostanay_2023, kostanay_2024]

for i in range(11):
    df = dfs[i]
    df['oblast'] = 'Kostanay'
    df['year'] = 2014 + i

kostanay_inv = pd.concat([kostanay_2014, kostanay_2015, kostanay_2016, kostanay_2017, kostanay_2018, kostanay_2019, kostanay_2020, kostanay_2021, kostanay_2022, kostanay_2023, kostanay_2024], ignore_index=True)
kostanay_inv['rayon'] = (
    kostanay_inv['rayon']
        .str.strip()          # remove hidden spaces
        .replace(rayon_map)   # enforce English names
)
kostanay_inv

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year
0,Altynsarin,2542234,7684.0,7684.0,2021206.0,Kostanay,2014
1,Amangeldi,813774,21845.0,21845.0,420608.0,Kostanay,2014
2,Auliekol,4165281,1550.0,1550.0,3173031.0,Kostanay,2014
3,Denisov,2911987,278049.0,278049.0,1943566.0,Kostanay,2014
4,Zhangeldin,688615,874.0,874.0,512378.0,Kostanay,2014
...,...,...,...,...,...,...,...
215,Naurzum,4014171,0.0,0.0,59445.0,Kostanay,2024
216,Sarykol,15246028,0.0,0.0,5436074.0,Kostanay,2024
217,Beimbet Mailin,9976940,12352424.0,7338.0,1513228.0,Kostanay,2024
218,Uzunkol,10958306,27021.0,27021.0,5221699.0,Kostanay,2024
219,Fyodorov,13459218,0.0,0.0,1230109.0,Kostanay,2024

## Employment

In [334]:
kostanay_empl = pd.read_excel(Path("../Data/Employment/Kostanay.xlsx"), skiprows=31, nrows=20, header=None, usecols='A:L', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
kostanay_empl.columns = ['rayon', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
kostanay_empl['rayon'] = kostanay_empl['rayon'].replace(rayon_map_kostanay)
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    kostanay_empl[i] = kostanay_empl[i].astype(float)
    kostanay_employment = kostanay_empl.melt(id_vars='rayon', value_vars=[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024], var_name='year', value_name='employment')
kostanay_employment

              rayon  year  employment
0     Kostanay city  2014    125089.0
1      Arkalyk city  2014     20802.0
2    Lisakovsk city  2014     23363.0
3        Rudny city  2014     71233.0
4        Altynsarin  2014      8709.0
..              ...   ...         ...
215         Naurzum  2024      4833.0
216         Sarykol  2024     10482.0
217  Beimbet Mailin  2024     10851.0
218         Uzunkol  2024      7650.0
219        Fyodorov  2024     13607.0

[220 rows x 3 columns]

## Other Controls

### Kostanay City

In [335]:
kostanay_city = pd.read_excel(Path("../Data/Controls/Kostanay_All.xlsx"), sheet_name="г. Костанай", header=2, usecols='A, Y:AH', nrows=160, na_values=['x', 'х', '-', '', ' ', '...'])
kostanay_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
kostanay_city = kostanay_city.loc[[79, 108, 151]].reset_index(drop=True)
kostanay_city['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    kostanay_city[i] = kostanay_city[i].astype(str)
    kostanay_city[i] = kostanay_city[i].str.replace(',', '.')
    kostanay_city[i] = kostanay_city[i].str.replace(')', '')
    kostanay_city[i] = kostanay_city[i].str.replace(' ', '')
    kostanay_city[i] = kostanay_city[i].str.replace('\xa0', '')
    kostanay_city[i] = kostanay_city[i].str.replace('*', '')
    kostanay_city[i] = kostanay_city[i].astype(float)
kostanay_city = pd.melt(kostanay_city, id_vars=['Indicator'], var_name='year', value_name='value')
kostanay_city = kostanay_city.pivot(index='year', columns='Indicator', values='value').reset_index()
kostanay_city.insert(0, 'rayon', 'Kostanay city')
kostanay_city.columns.name = None
kostanay_city

           rayon  year  agriculture   production    retail
0  Kostanay city  2014  4948.200000   175022.000  140329.5
1  Kostanay city  2015  4355.000000   165714.000  142770.4
2  Kostanay city  2016  4436.800000   212092.000  167367.5
3  Kostanay city  2017  5661.200000   279780.000  192128.5
4  Kostanay city  2018  5886.300000   306297.000  221433.2
5  Kostanay city  2019  7677.800000   460565.000  251975.4
6  Kostanay city  2020  7256.200000   673397.000  295052.1
7  Kostanay city  2021  8385.800000   885655.000  370682.1
8  Kostanay city  2022  8800.200000  1260759.000  429766.3
9  Kostanay city  2023  8619.498254  1579121.248  534579.1

In [336]:
arkalyk_city = pd.read_excel(Path("../Data/Controls/Kostanay_All.xlsx"), sheet_name="Аркалык г.а.", header=2, usecols='A, Y:AH', nrows=160, na_values=['x', 'х', '-', '', ' ', '...'])
arkalyk_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
arkalyk_city = arkalyk_city.loc[[79, 107, 150]].reset_index(drop=True)
arkalyk_city['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    arkalyk_city[i] = arkalyk_city[i].astype(str)
    arkalyk_city[i] = arkalyk_city[i].str.replace(',', '.')
    arkalyk_city[i] = arkalyk_city[i].str.replace(')', '')
    arkalyk_city[i] = arkalyk_city[i].str.replace(' ', '')
    arkalyk_city[i] = arkalyk_city[i].str.replace('\xa0', '')
    arkalyk_city[i] = arkalyk_city[i].str.replace('*', '')
    arkalyk_city[i] = arkalyk_city[i].astype(float)
arkalyk_city = pd.melt(arkalyk_city, id_vars=['Indicator'], var_name='year', value_name='value')
arkalyk_city = arkalyk_city.pivot(index='year', columns='Indicator', values='value').reset_index()
arkalyk_city.insert(0, 'rayon', 'Arkalyk city')
arkalyk_city.columns.name = None
arkalyk_city

          rayon  year   agriculture  production  retail
0  Arkalyk city  2014  10883.000000      5739.0  3106.6
1  Arkalyk city  2015  10254.700000      6360.0  3239.0
2  Arkalyk city  2016  12464.600000      7490.0  3773.8
3  Arkalyk city  2017  11805.000000      9422.0  4177.1
4  Arkalyk city  2018  14407.600000     11118.0  4587.4
5  Arkalyk city  2019  19387.700000     10144.0  4979.8
6  Arkalyk city  2020  28147.700000      6588.0  4983.2
7  Arkalyk city  2021  20008.600000      7046.0  5542.4
8  Arkalyk city  2022  42292.000000      8578.0  6925.9
9  Arkalyk city  2023  19391.500838      9004.0  7849.8

In [337]:
lisakovsk_city = pd.read_excel(Path("../Data/Controls/Kostanay_All.xlsx"), sheet_name="Лисаковск г.а.", header=2, usecols='A, Y:AH', nrows=160, na_values=['x', 'х', '-', '', ' ', '...'])
lisakovsk_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
lisakovsk_city = lisakovsk_city.loc[[79, 107, 150]].reset_index(drop=True)
lisakovsk_city['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    lisakovsk_city[i] = lisakovsk_city[i].astype(str)
    lisakovsk_city[i] = lisakovsk_city[i].str.replace(',', '.')
    lisakovsk_city[i] = lisakovsk_city[i].str.replace(')', '')
    lisakovsk_city[i] = lisakovsk_city[i].str.replace(' ', '')
    lisakovsk_city[i] = lisakovsk_city[i].str.replace('\xa0', '')
    lisakovsk_city[i] = lisakovsk_city[i].str.replace('*', '')
    lisakovsk_city[i] = lisakovsk_city[i].astype(float)
lisakovsk_city = pd.melt(lisakovsk_city, id_vars=['Indicator'], var_name='year', value_name='value')
lisakovsk_city = lisakovsk_city.pivot(index='year', columns='Indicator', values='value').reset_index()
lisakovsk_city.insert(0, 'rayon', 'Lisakovsk city')
lisakovsk_city.columns.name = None
lisakovsk_city

            rayon  year  agriculture  production   retail
0  Lisakovsk city  2014  1731.300000     26436.0   6665.5
1  Lisakovsk city  2015  1603.000000     26671.0   6948.2
2  Lisakovsk city  2016  1464.300000     34814.0   8152.6
3  Lisakovsk city  2017  1926.300000     37706.0   9704.6
4  Lisakovsk city  2018  1867.500000     52927.0  10819.0
5  Lisakovsk city  2019  1998.600000     59510.0  11758.2
6  Lisakovsk city  2020  2164.600000     58625.0  12648.9
7  Lisakovsk city  2021  2836.000000     82207.0  14206.0
8  Lisakovsk city  2022  2751.700000     82217.0  17960.7
9  Lisakovsk city  2023  2247.180459     90591.0  20415.1

In [338]:
rudny_city = pd.read_excel(Path("../Data/Controls/Kostanay_All.xlsx"), sheet_name="Рудный  г.а.", header=2, usecols='A, Y:AH', nrows=160, na_values=['x', 'х', '-', '', ' ', '...'])
rudny_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
rudny_city = rudny_city.loc[[79, 107, 150]].reset_index(drop=True)
rudny_city['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    rudny_city[i] = rudny_city[i].astype(str)
    rudny_city[i] = rudny_city[i].str.replace(',', '.')
    rudny_city[i] = rudny_city[i].str.replace(')', '')
    rudny_city[i] = rudny_city[i].str.replace(' ', '')
    rudny_city[i] = rudny_city[i].str.replace('\xa0', '')
    rudny_city[i] = rudny_city[i].str.replace('*', '')
    rudny_city[i] = rudny_city[i].astype(float)
rudny_city = pd.melt(rudny_city, id_vars=['Indicator'], var_name='year', value_name='value')
rudny_city = rudny_city.pivot(index='year', columns='Indicator', values='value').reset_index()
rudny_city.insert(0, 'rayon', 'Rudny city')
rudny_city.columns.name = None
rudny_city

        rayon  year  agriculture  production   retail
0  Rudny city  2014       6670.6    238133.0  38576.4
1  Rudny city  2015       6492.8    162235.0  40240.1
2  Rudny city  2016       6877.6    223018.0  47585.4
3  Rudny city  2017       8181.0    274742.0  55073.9
4  Rudny city  2018       7910.8    329511.0  61515.3
5  Rudny city  2019      10554.4    456207.0  66441.0
6  Rudny city  2020      11687.3    516727.0  63195.9
7  Rudny city  2021      15404.3   1004939.0  47782.3
8  Rudny city  2022      15848.7    715920.0  55311.6
9  Rudny city  2023      15530.2    609684.0  62830.1

In [339]:
altynsarin = pd.read_excel(Path("../Data/Controls/Kostanay_All.xlsx"), sheet_name="Алтынсаринский", header=2, usecols='A, Y:AH', nrows=160, na_values=['x', 'х', '-', '', ' ', '...'])
altynsarin.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
altynsarin = altynsarin.loc[[65, 91, 134]].reset_index(drop=True)
altynsarin['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    altynsarin[i] = altynsarin[i].astype(str)
    altynsarin[i] = altynsarin[i].str.replace(',', '.')
    altynsarin[i] = altynsarin[i].str.replace(')', '')
    altynsarin[i] = altynsarin[i].str.replace(' ', '')
    altynsarin[i] = altynsarin[i].str.replace('\xa0', '')
    altynsarin[i] = altynsarin[i].str.replace('*', '')
    altynsarin[i] = altynsarin[i].astype(float)
altynsarin = pd.melt(altynsarin, id_vars=['Indicator'], var_name='year', value_name='value')
altynsarin = altynsarin.pivot(index='year', columns='Indicator', values='value').reset_index()
altynsarin.insert(0, 'rayon', 'Altynsarin')
altynsarin.columns.name = None
altynsarin

        rayon  year  agriculture  production  retail
0  Altynsarin  2014  11962.20000      2364.0   408.5
1  Altynsarin  2015  14421.30000      1708.0   426.0
2  Altynsarin  2016  13886.60000      1692.0   497.1
3  Altynsarin  2017  17907.40000      2028.0   570.1
4  Altynsarin  2018  17603.90000      2463.0   618.4
5  Altynsarin  2019  15834.30000      1927.0   717.4
6  Altynsarin  2020  23912.30000      2436.0   770.3
7  Altynsarin  2021  29214.00000      2800.0   836.6
8  Altynsarin  2022  54795.90000      2714.0  1087.8
9  Altynsarin  2023  28546.14153      3042.0  1303.7

In [340]:
amangeldi = pd.read_excel(Path("../Data/Controls/Kostanay_All.xlsx"), sheet_name="Амангельдинский", header=2, usecols='A, Y:AH', nrows=160, na_values=['x', 'х', '-', '', ' ', '...'])
amangeldi.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
amangeldi = amangeldi.loc[[65, 91, 134]].reset_index(drop=True)
amangeldi['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    amangeldi[i] = amangeldi[i].astype(str)
    amangeldi[i] = amangeldi[i].str.replace(',', '.')
    amangeldi[i] = amangeldi[i].str.replace(')', '')
    amangeldi[i] = amangeldi[i].str.replace(' ', '')
    amangeldi[i] = amangeldi[i].str.replace('\xa0', '')
    amangeldi[i] = amangeldi[i].str.replace('*', '')
    amangeldi[i] = amangeldi[i].astype(float)
amangeldi = pd.melt(amangeldi, id_vars=['Indicator'], var_name='year', value_name='value')
amangeldi = amangeldi.pivot(index='year', columns='Indicator', values='value').reset_index()
amangeldi.insert(0, 'rayon', 'Amangeldi')
amangeldi.columns.name = None
amangeldi

       rayon  year   agriculture  production  retail
0  Amangeldi  2014   8077.000000       110.0   518.2
1  Amangeldi  2015   8922.300000       119.0   537.0
2  Amangeldi  2016  10197.000000       142.0   624.1
3  Amangeldi  2017  11107.900000       652.0   706.0
4  Amangeldi  2018  13470.500000      1709.0   782.5
5  Amangeldi  2019  17665.000000      1437.0   858.1
6  Amangeldi  2020  22394.000000      3579.0   764.3
7  Amangeldi  2021  22029.800000      4040.0   831.2
8  Amangeldi  2022  37603.800000      2193.0   994.5
9  Amangeldi  2023  17700.883058      1281.0  1125.9

In [341]:
auliekol = pd.read_excel(Path("../Data/Controls/Kostanay_All.xlsx"), sheet_name="Аулиекольский", header=2, usecols='A, Y:AH', nrows=160, na_values=['x', 'х', '-', '', ' ', '...'])
auliekol.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
auliekol = auliekol.loc[[65, 91, 134]].reset_index(drop=True)
auliekol['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    auliekol[i] = auliekol[i].astype(str)
    auliekol[i] = auliekol[i].str.replace(',', '.')
    auliekol[i] = auliekol[i].str.replace(')', '')
    auliekol[i] = auliekol[i].str.replace(' ', '')
    auliekol[i] = auliekol[i].str.replace('\xa0', '')
    auliekol[i] = auliekol[i].str.replace('*', '')
    auliekol[i] = auliekol[i].astype(float)
auliekol = pd.melt(auliekol, id_vars=['Indicator'], var_name='year', value_name='value')
auliekol = auliekol.pivot(index='year', columns='Indicator', values='value').reset_index()
auliekol.insert(0, 'rayon', 'Auliekol')
auliekol.columns.name = None
auliekol

      rayon  year   agriculture  production   retail
0  Auliekol  2014  15324.800000      4044.0   2700.7
1  Auliekol  2015  16553.900000      3735.0   2819.8
2  Auliekol  2016  18083.900000      3706.0   3291.3
3  Auliekol  2017  19911.800000      4816.0   3753.6
4  Auliekol  2018  19464.900000      5182.0   4112.0
5  Auliekol  2019  16957.100000      5597.0   4472.9
6  Auliekol  2020  31880.500000      4505.0   4802.2
7  Auliekol  2021  25094.200000      4808.0   6050.4
8  Auliekol  2022  49005.700000      6057.0   7146.6
9  Auliekol  2023  24904.077379      8792.0  11098.6

In [342]:
denisov = pd.read_excel(Path("../Data/Controls/Kostanay_All.xlsx"), sheet_name="Денисовский", header=2, usecols='A, Y:AH', nrows=160, na_values=['x', 'х', '-', '', ' ', '...'])
denisov.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
denisov = denisov.loc[[65, 91, 134]].reset_index(drop=True)
denisov['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    denisov[i] = denisov[i].astype(str)
    denisov[i] = denisov[i].str.replace(',', '.')
    denisov[i] = denisov[i].str.replace(')', '')
    denisov[i] = denisov[i].str.replace(' ', '')
    denisov[i] = denisov[i].str.replace('\xa0', '')
    denisov[i] = denisov[i].str.replace('*', '')
    denisov[i] = denisov[i].astype(float)
denisov = pd.melt(denisov, id_vars=['Indicator'], var_name='year', value_name='value')
denisov = denisov.pivot(index='year', columns='Indicator', values='value').reset_index()
denisov.insert(0, 'rayon', 'Denisov')
denisov.columns.name = None
denisov

     rayon  year   agriculture  production  retail
0  Denisov  2014  13373.900000      3875.0  1476.6
1  Denisov  2015  17177.500000      3664.0  1535.4
2  Denisov  2016  17991.300000      4662.0  1784.5
3  Denisov  2017  21961.000000      3905.0  1971.7
4  Denisov  2018  21093.500000      3118.0  2181.1
5  Denisov  2019  15201.500000      2142.0  2383.7
6  Denisov  2020  23440.300000      2306.0  2575.8
7  Denisov  2021  22181.200000      2047.0  2846.0
8  Denisov  2022  44623.600000      1127.0  3645.4
9  Denisov  2023  36732.033793      2327.0  4135.3

In [343]:
zhangeldin = pd.read_excel(Path("../Data/Controls/Kostanay_All.xlsx"), sheet_name="Джангельдинский", header=2, usecols='A, Y:AH', nrows=160, na_values=['x', 'х', '-', '', ' ', '...'])
zhangeldin.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
zhangeldin = zhangeldin.loc[[65, 91, 134]].reset_index(drop=True)
zhangeldin['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    zhangeldin[i] = zhangeldin[i].astype(str)
    zhangeldin[i] = zhangeldin[i].str.replace(',', '.')
    zhangeldin[i] = zhangeldin[i].str.replace(')', '')
    zhangeldin[i] = zhangeldin[i].str.replace(' ', '')
    zhangeldin[i] = zhangeldin[i].str.replace('\xa0', '')
    zhangeldin[i] = zhangeldin[i].str.replace('*', '')
    zhangeldin[i] = zhangeldin[i].astype(float)
zhangeldin = pd.melt(zhangeldin, id_vars=['Indicator'], var_name='year', value_name='value')
zhangeldin = zhangeldin.pivot(index='year', columns='Indicator', values='value').reset_index()
zhangeldin.insert(0, 'rayon', 'Zhangeldin')
zhangeldin.columns.name = None
zhangeldin

        rayon  year   agriculture  production  retail
0  Zhangeldin  2014   6713.100000       125.0   244.5
1  Zhangeldin  2015   7797.700000       146.0   254.2
2  Zhangeldin  2016   8991.500000        46.0   295.4
3  Zhangeldin  2017   9576.700000       110.0   336.2
4  Zhangeldin  2018  10480.600000       302.0   373.4
5  Zhangeldin  2019  12362.000000       269.0   406.8
6  Zhangeldin  2020  16133.600000       263.0   416.5
7  Zhangeldin  2021  17275.000000       314.0   455.9
8  Zhangeldin  2022  22227.500000       147.0   542.5
9  Zhangeldin  2023  12254.911128       157.0   614.2

In [344]:
zhitikara = pd.read_excel(Path("../Data/Controls/Kostanay_All.xlsx"), sheet_name="Житикаринский", header=2, usecols='A, Y:AH', nrows=160, na_values=['x', 'х', '-', '', ' ', '...'])
zhitikara.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
zhitikara = zhitikara.loc[[79, 107, 150]].reset_index(drop=True)
zhitikara['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    zhitikara[i] = zhitikara[i].astype(str)
    zhitikara[i] = zhitikara[i].str.replace(',', '.')
    zhitikara[i] = zhitikara[i].str.replace(')', '')
    zhitikara[i] = zhitikara[i].str.replace(' ', '')
    zhitikara[i] = zhitikara[i].str.replace('\xa0', '')
    zhitikara[i] = zhitikara[i].str.replace('*', '')
    zhitikara[i] = zhitikara[i].astype(float)
zhitikara = pd.melt(zhitikara, id_vars=['Indicator'], var_name='year', value_name='value')
zhitikara = zhitikara.pivot(index='year', columns='Indicator', values='value').reset_index()
zhitikara.insert(0, 'rayon', 'Zhitikara')
zhitikara.columns.name = None
zhitikara

       rayon  year   agriculture  production   retail
0  Zhitikara  2014   6616.100000     21505.0   3446.3
1  Zhitikara  2015   7474.600000     21230.0   3574.8
2  Zhitikara  2016   8814.700000     30217.0   4164.9
3  Zhitikara  2017  11732.700000     43755.0   4704.6
4  Zhitikara  2018  10546.300000     51965.0   5373.2
5  Zhitikara  2019   8353.900000     66317.0   5900.4
6  Zhitikara  2020  13894.300000     81027.0   6405.0
7  Zhitikara  2021  12917.800000     90505.0   8653.8
8  Zhitikara  2022  25244.400000     90034.0  10066.4
9  Zhitikara  2023  15945.707699     92413.0  15715.1

In [345]:
kamysty = pd.read_excel(Path("../Data/Controls/Kostanay_All.xlsx"), sheet_name="Камыстинский", header=2, usecols='A, Y:AH', nrows=160, na_values=['x', 'х', '-', '', ' ', '...'])
kamysty.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
kamysty = kamysty.loc[[65, 91, 134]].reset_index(drop=True)
kamysty['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    kamysty[i] = kamysty[i].astype(str)
    kamysty[i] = kamysty[i].str.replace(',', '.')
    kamysty[i] = kamysty[i].str.replace(')', '')
    kamysty[i] = kamysty[i].str.replace(' ', '')
    kamysty[i] = kamysty[i].str.replace('\xa0', '')
    kamysty[i] = kamysty[i].str.replace('*', '')
    kamysty[i] = kamysty[i].astype(float)
kamysty = pd.melt(kamysty, id_vars=['Indicator'], var_name='year', value_name='value')
kamysty = kamysty.pivot(index='year', columns='Indicator', values='value').reset_index()
kamysty.insert(0, 'rayon', 'Kamysty')
kamysty.columns.name = None
kamysty

     rayon  year   agriculture  production  retail
0  Kamysty  2014  10321.400000      1214.0   429.2
1  Kamysty  2015  12418.100000      1831.0   444.7
2  Kamysty  2016  14678.200000      1798.0   521.0
3  Kamysty  2017  17449.500000      2377.0   585.2
4  Kamysty  2018  18701.600000      2365.0   653.6
5  Kamysty  2019   9639.000000      2241.0   732.1
6  Kamysty  2020  27353.100000      3034.0   763.3
7  Kamysty  2021  18397.500000      5272.0   894.3
8  Kamysty  2022  45934.800000      5911.0  1159.1
9  Kamysty  2023  25888.612507      3654.0  1316.2

In [346]:
karabalyk = pd.read_excel(Path("../Data/Controls/Kostanay_All.xlsx"), sheet_name="Карабалыкский", header=2, usecols='A, Y:AH', nrows=160, na_values=['x', 'х', '-', '', ' ', '...'])
karabalyk.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
karabalyk = karabalyk.loc[[65, 91, 134]].reset_index(drop=True)
karabalyk['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    karabalyk[i] = karabalyk[i].astype(str)
    karabalyk[i] = karabalyk[i].str.replace(',', '.')
    karabalyk[i] = karabalyk[i].str.replace(')', '')
    karabalyk[i] = karabalyk[i].str.replace(' ', '')
    karabalyk[i] = karabalyk[i].str.replace('\xa0', '')
    karabalyk[i] = karabalyk[i].str.replace('*', '')
    karabalyk[i] = karabalyk[i].astype(float)
karabalyk = pd.melt(karabalyk, id_vars=['Indicator'], var_name='year', value_name='value')
karabalyk = karabalyk.pivot(index='year', columns='Indicator', values='value').reset_index()
karabalyk.insert(0, 'rayon', 'Karabalyk')
karabalyk.columns.name = None
karabalyk

       rayon  year   agriculture  production   retail
0  Karabalyk  2014  16436.400000      2580.0   3735.4
1  Karabalyk  2015  17065.900000      2741.0   3897.5
2  Karabalyk  2016  19522.400000      1807.0   4536.9
3  Karabalyk  2017  20423.100000      4055.0   4924.7
4  Karabalyk  2018  23267.800000      3173.0   5578.2
5  Karabalyk  2019  29510.200000      3238.0   6133.2
6  Karabalyk  2020  35347.800000      3219.0   6484.9
7  Karabalyk  2021  42572.500000      5593.0   9443.0
8  Karabalyk  2022  65715.500000      9020.0  11100.7
9  Karabalyk  2023  53650.346786     14653.0  12573.9

In [347]:
karasu = pd.read_excel(Path("../Data/Controls/Kostanay_All.xlsx"), sheet_name="Карасуский", header=2, usecols='A, Y:AH', nrows=160, na_values=['x', 'х', '-', '', ' ', '...'])
karasu.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
karasu = karasu.loc[[65, 91, 134]].reset_index(drop=True)
karasu['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    karasu[i] = karasu[i].astype(str)
    karasu[i] = karasu[i].str.replace(',', '.')
    karasu[i] = karasu[i].str.replace(')', '')
    karasu[i] = karasu[i].str.replace(' ', '')
    karasu[i] = karasu[i].str.replace('\xa0', '')
    karasu[i] = karasu[i].str.replace('*', '')
    karasu[i] = karasu[i].astype(float)
karasu = pd.melt(karasu, id_vars=['Indicator'], var_name='year', value_name='value')
karasu = karasu.pivot(index='year', columns='Indicator', values='value').reset_index()
karasu.insert(0, 'rayon', 'Karasu')
karasu.columns.name = None
karasu

    rayon  year   agriculture  production  retail
0  Karasu  2014   31678.00000      3026.0  2033.8
1  Karasu  2015   32219.10000      2685.0  2118.2
2  Karasu  2016   38155.60000      3084.0  2529.0
3  Karasu  2017   41187.40000      2925.0  2780.6
4  Karasu  2018   43923.10000      1499.0  3022.1
5  Karasu  2019   37539.10000      1187.0  3281.9
6  Karasu  2020   70623.40000      1970.0  3488.5
7  Karasu  2021   60242.20000      1563.0  4094.5
8  Karasu  2022  136663.80000       968.0  5098.1
9  Karasu  2023   72234.24623       554.0  5800.5

In [348]:
kostanay = pd.read_excel(Path("../Data/Controls/Kostanay_All.xlsx"), sheet_name="Костанайский", header=2, usecols='A, Y:AH', nrows=160, na_values=['x', 'х', '-', '', ' ', '...'])
kostanay.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
kostanay = kostanay.loc[[65, 93, 136]].reset_index(drop=True)
kostanay['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    kostanay[i] = kostanay[i].astype(str)
    kostanay[i] = kostanay[i].str.replace(',', '.')
    kostanay[i] = kostanay[i].str.replace(')', '')
    kostanay[i] = kostanay[i].str.replace(' ', '')
    kostanay[i] = kostanay[i].str.replace('\xa0', '')
    kostanay[i] = kostanay[i].str.replace('*', '')
    # kostanay[i] = kostanay[i].astype(float)
kostanay = pd.melt(kostanay, id_vars=['Indicator'], var_name='year', value_name='value')
kostanay = kostanay.pivot(index='year', columns='Indicator', values='value').reset_index()
kostanay.insert(0, 'rayon', 'Kostanay')
kostanay.columns.name = None
kostanay

      rayon  year        agriculture production   retail
0  Kostanay  2014            29832.5      18925    14204
1  Kostanay  2015            32952.3      18304  14719.3
2  Kostanay  2016            35513.5      19297  17488.6
3  Kostanay  2017            39350.9      20339    20839
4  Kostanay  2018            40329.3      21729  22823.9
5  Kostanay  2019            42453.9      25920  25633.3
6  Kostanay  2020            59206.8      22708  15196.4
7  Kostanay  2021            70387.8      23906  13604.7
8  Kostanay  2022              96425      35587    16238
9  Kostanay  2023  81504.25872832662      38121  18548.9

In [349]:
mendykara = pd.read_excel(Path("../Data/Controls/Kostanay_All.xlsx"), sheet_name="Мендыкаринский", header=2, usecols='A, Y:AH', nrows=160, na_values=['x', 'х', '-', '', ' ', '...'])
mendykara.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
mendykara = mendykara.loc[[65, 91, 134]].reset_index(drop=True)
mendykara['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    mendykara[i] = mendykara[i].astype(str)
    mendykara[i] = mendykara[i].str.replace(',', '.')
    mendykara[i] = mendykara[i].str.replace(')', '')
    mendykara[i] = mendykara[i].str.replace(' ', '')
    mendykara[i] = mendykara[i].str.replace('\xa0', '')
    mendykara[i] = mendykara[i].str.replace('*', '')
    # mendykara[i] = mendykara[i].astype(float)
mendykara = pd.melt(mendykara, id_vars=['Indicator'], var_name='year', value_name='value')
mendykara = mendykara.pivot(index='year', columns='Indicator', values='value').reset_index()
mendykara.insert(0, 'rayon', 'Mendykara')
mendykara.columns.name = None
mendykara

       rayon  year        agriculture production  retail
0  Mendykara  2014            17126.7       2585  3622.6
1  Mendykara  2015            18131.4       2991  3750.6
2  Mendykara  2016            19635.9       3447  4356.6
3  Mendykara  2017            24287.9       3795  4928.3
4  Mendykara  2018            25783.2       3202  5398.9
5  Mendykara  2019            30298.5       1347  5857.1
6  Mendykara  2020            40897.9       2312  5298.6
7  Mendykara  2021            51084.2       2706  5813.3
8  Mendykara  2022            66140.1       3195    6765
9  Mendykara  2023  40447.28257805534       2117  7651.7

In [350]:
naurzum = pd.read_excel(Path("../Data/Controls/Kostanay_All.xlsx"), sheet_name="Наурзумский", header=2, usecols='A, Y:AH', nrows=160, na_values=['x', 'х', '-', '', ' ', '...'])
naurzum.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
naurzum = naurzum.loc[[65, 91, 134]].reset_index(drop=True)
naurzum['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    naurzum[i] = naurzum[i].astype(str)
    naurzum[i] = naurzum[i].str.replace(',', '.')
    naurzum[i] = naurzum[i].str.replace(')', '')
    naurzum[i] = naurzum[i].str.replace(' ', '')
    naurzum[i] = naurzum[i].str.replace('\xa0', '')
    naurzum[i] = naurzum[i].str.replace('*', '')
    naurzum[i] = naurzum[i].astype(float)
naurzum = pd.melt(naurzum, id_vars=['Indicator'], var_name='year', value_name='value')
naurzum = naurzum.pivot(index='year', columns='Indicator', values='value').reset_index()
naurzum.insert(0, 'rayon', 'Naurzum')
naurzum.columns.name = None
naurzum

     rayon  year   agriculture  production  retail
0  Naurzum  2014   7776.600000        74.0   294.2
1  Naurzum  2015   9800.200000        43.0   305.8
2  Naurzum  2016  10804.300000       168.0   356.3
3  Naurzum  2017  12309.700000        92.0   406.4
4  Naurzum  2018  13136.300000       330.0   440.8
5  Naurzum  2019  10794.300000       258.0   477.5
6  Naurzum  2020  23979.000000       263.0   495.7
7  Naurzum  2021  17264.100000       285.0   539.5
8  Naurzum  2022  37138.500000       125.0   628.2
9  Naurzum  2023  19195.246089       102.0   711.9

In [351]:
sarykol = pd.read_excel(Path("../Data/Controls/Kostanay_All.xlsx"), sheet_name="Сарыкольский", header=2, usecols='A, Y:AH', nrows=160, na_values=['x', 'х', '-', '', ' ', '...'])
sarykol.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
sarykol = sarykol.loc[[65, 91, 134]].reset_index(drop=True)
sarykol['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    sarykol[i] = sarykol[i].astype(str)
    sarykol[i] = sarykol[i].str.replace(',', '.')
    sarykol[i] = sarykol[i].str.replace(')', '')
    sarykol[i] = sarykol[i].str.replace(' ', '')
    sarykol[i] = sarykol[i].str.replace('\xa0', '')
    sarykol[i] = sarykol[i].str.replace('*', '')
    sarykol[i] = sarykol[i].astype(float)
sarykol = pd.melt(sarykol, id_vars=['Indicator'], var_name='year', value_name='value')
sarykol = sarykol.pivot(index='year', columns='Indicator', values='value').reset_index()
sarykol.insert(0, 'rayon', 'Sarykol')
sarykol.columns.name = None
sarykol

     rayon  year   agriculture  production  retail
0  Sarykol  2014  18346.900000      2793.0  1931.0
1  Sarykol  2015  20276.400000      2911.0  2010.7
2  Sarykol  2016  20634.500000      5559.0  2340.4
3  Sarykol  2017  24759.100000      4821.0  2620.8
4  Sarykol  2018  25586.100000      3989.0  2918.9
5  Sarykol  2019  31255.600000      4736.0  3237.0
6  Sarykol  2020  45346.100000      4911.0  3392.1
7  Sarykol  2021  48800.900000      4138.0  4087.1
8  Sarykol  2022  91127.300000      5387.0  6626.5
9  Sarykol  2023  44401.996406      5042.0  7556.5

In [352]:
beimbet_mailin = pd.read_excel(Path("../Data/Controls/Kostanay_All.xlsx"), sheet_name="Беимбета Майлина", header=2, usecols='A, Y:AH', nrows=160, na_values=['x', 'х', '-', '', ' ', '...'])
beimbet_mailin.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
beimbet_mailin = beimbet_mailin.loc[[65, 91, 134]].reset_index(drop=True)
beimbet_mailin['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    beimbet_mailin[i] = beimbet_mailin[i].astype(str)
    beimbet_mailin[i] = beimbet_mailin[i].str.replace(',', '.')
    beimbet_mailin[i] = beimbet_mailin[i].str.replace(')', '')
    beimbet_mailin[i] = beimbet_mailin[i].str.replace(' ', '')
    beimbet_mailin[i] = beimbet_mailin[i].str.replace('\xa0', '')
    beimbet_mailin[i] = beimbet_mailin[i].str.replace('*', '')
    beimbet_mailin[i] = beimbet_mailin[i].astype(float)
beimbet_mailin = pd.melt(beimbet_mailin, id_vars=['Indicator'], var_name='year', value_name='value')
beimbet_mailin = beimbet_mailin.pivot(index='year', columns='Indicator', values='value').reset_index()
beimbet_mailin.insert(0, 'rayon', 'Beimbet Mailin')
beimbet_mailin.columns.name = None
beimbet_mailin

            rayon  year   agriculture  production  retail
0  Beimbet Mailin  2014  11246.700000     27420.0  2035.8
1  Beimbet Mailin  2015  12115.000000     20122.0  2112.0
2  Beimbet Mailin  2016  13593.700000     39176.0  2463.3
3  Beimbet Mailin  2017  16589.900000     58701.0  2810.7
4  Beimbet Mailin  2018  17300.200000     68769.0  3109.2
5  Beimbet Mailin  2019  15341.400000     84974.0  3392.0
6  Beimbet Mailin  2020  23705.800000    131361.0  3499.8
7  Beimbet Mailin  2021  23479.000000    179227.0  3895.4
8  Beimbet Mailin  2022  41620.600000    196843.0  4652.6
9  Beimbet Mailin  2023  28968.756109    173787.0  5660.7

In [353]:
uzunkol = pd.read_excel(Path("../Data/Controls/Kostanay_All.xlsx"), sheet_name="Узункольский", header=2, usecols='A, Y:AH', nrows=160, na_values=['x', 'х', '-', '', ' ', '...'])
uzunkol.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
uzunkol = uzunkol.loc[[65, 91, 134]].reset_index(drop=True)
uzunkol['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    uzunkol[i] = uzunkol[i].astype(str)
    uzunkol[i] = uzunkol[i].str.replace(',', '.')
    uzunkol[i] = uzunkol[i].str.replace(')', '')
    uzunkol[i] = uzunkol[i].str.replace(' ', '')
    uzunkol[i] = uzunkol[i].str.replace('\xa0', '')
    uzunkol[i] = uzunkol[i].str.replace('*', '')
    uzunkol[i] = uzunkol[i].astype(float)
uzunkol = pd.melt(uzunkol, id_vars=['Indicator'], var_name='year', value_name='value')
uzunkol = uzunkol.pivot(index='year', columns='Indicator', values='value').reset_index()
uzunkol.insert(0, 'rayon', 'Uzunkol')
uzunkol.columns.name = None
uzunkol

     rayon  year   agriculture  production  retail
0  Uzunkol  2014  13661.400000      2091.0   707.6
1  Uzunkol  2015  18045.600000      3074.0   739.2
2  Uzunkol  2016  17135.300000      5039.0   859.2
3  Uzunkol  2017  20750.800000      8443.0  1005.5
4  Uzunkol  2018  22992.500000     11546.0  1127.4
5  Uzunkol  2019  25145.100000     14941.0  1227.7
6  Uzunkol  2020  32370.700000     19061.0  1299.8
7  Uzunkol  2021  44045.600000     22855.0  1411.7
8  Uzunkol  2022  66575.700000     26464.0  2407.5
9  Uzunkol  2023  40675.357961     10761.0  2744.9

In [354]:
fyodorov = pd.read_excel(Path("../Data/Controls/Kostanay_All.xlsx"), sheet_name="Федоровский", header=2, usecols='A, Y:AH', nrows=160, na_values=['x', 'х', '-', '', ' ', '...'])
fyodorov.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
fyodorov = fyodorov.loc[[64, 90, 133]].reset_index(drop=True)
fyodorov['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    fyodorov[i] = fyodorov[i].astype(str)
    fyodorov[i] = fyodorov[i].str.replace(',', '.')
    fyodorov[i] = fyodorov[i].str.replace(')', '')
    fyodorov[i] = fyodorov[i].str.replace(' ', '')
    fyodorov[i] = fyodorov[i].str.replace('\xa0', '')
    fyodorov[i] = fyodorov[i].str.replace('*', '')
    fyodorov[i] = fyodorov[i].astype(float)
fyodorov = pd.melt(fyodorov, id_vars=['Indicator'], var_name='year', value_name='value')
fyodorov = fyodorov.pivot(index='year', columns='Indicator', values='value').reset_index()
fyodorov.insert(0, 'rayon', 'Fyodorov')
fyodorov.columns.name = None
fyodorov

      rayon  year   agriculture  production  retail
0  Fyodorov  2014  24159.100000      3803.0  1883.4
1  Fyodorov  2015  26531.500000      2947.0  1962.7
2  Fyodorov  2016  26156.300000      1690.0  2291.4
3  Fyodorov  2017  31220.100000      1862.0  3081.9
4  Fyodorov  2018  32903.700000      2181.0  3541.7
5  Fyodorov  2019  39859.300000      4026.0  4104.7
6  Fyodorov  2020  52737.000000      3656.0  4403.1
7  Fyodorov  2021  52977.500000      3205.0  4786.9
8  Fyodorov  2022  69609.400000      2953.0  5663.1
9  Fyodorov  2023  50655.121397      4259.0  7945.9

In [355]:
kostanay_controls = pd.concat([kostanay_city, arkalyk_city, lisakovsk_city, rudny_city, altynsarin, amangeldi, auliekol, denisov, zhangeldin, zhitikara, kamysty, karabalyk, karasu, kostanay, mendykara, naurzum, sarykol, beimbet_mailin, uzunkol, fyodorov], ignore_index=True)
kostanay_controls

             rayon  year   agriculture production    retail
0    Kostanay city  2014        4948.2   175022.0  140329.5
1    Kostanay city  2015        4355.0   165714.0  142770.4
2    Kostanay city  2016        4436.8   212092.0  167367.5
3    Kostanay city  2017        5661.2   279780.0  192128.5
4    Kostanay city  2018        5886.3   306297.0  221433.2
..             ...   ...           ...        ...       ...
195       Fyodorov  2019       39859.3     4026.0    4104.7
196       Fyodorov  2020       52737.0     3656.0    4403.1
197       Fyodorov  2021       52977.5     3205.0    4786.9
198       Fyodorov  2022       69609.4     2953.0    5663.1
199       Fyodorov  2023  50655.121397     4259.0    7945.9

[200 rows x 5 columns]

## PPI

In [356]:
kostanay_ppi = pd.read_excel(
    Path("../Data/PPI/Kostanay.xlsx"),
    header=2,
    usecols='X:AH',
    nrows=76,
    na_values=['x', 'х', '-', '', ' ', '...']
)
kostanay_ppi.columns = [2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
rayons = list(kostanay_inv['rayon'].unique())

dfs = []

for rayon in rayons:
    df_temp = pd.DataFrame({
        'rayon': [rayon] * len(range(2013, 2024)),
        'year': list(range(2013, 2024)),
        'ppi': kostanay_ppi.iloc[-1].values
    })
    dfs.append(df_temp)

kostanay_ppi = pd.concat(dfs, ignore_index=True)
kostanay_ppi['ppi'] = kostanay_ppi['ppi'].astype(str).str.replace(',', '.')
kostanay_ppi['ppi'] = kostanay_ppi['ppi'].astype(str).str.replace(')', '')
kostanay_ppi['ppi'] = kostanay_ppi['ppi'].astype(str).str.replace(' ', '')
kostanay_ppi['ppi'] = kostanay_ppi['ppi'].astype(str).str.replace('\xa0', '')
kostanay_ppi['ppi'] = kostanay_ppi['ppi'].astype(str).str.replace('*', '')
kostanay_ppi['ppi'] = kostanay_ppi['ppi'].astype(float)

kostanay_ppi

              rayon  year    ppi
0        Altynsarin  2013  111.6
1        Altynsarin  2014   98.4
2        Altynsarin  2015  112.2
3        Altynsarin  2016  111.9
4        Altynsarin  2017  103.5
..              ...   ...    ...
226  Beimbet Mailin  2019  115.4
227  Beimbet Mailin  2020  132.0
228  Beimbet Mailin  2021  121.2
229  Beimbet Mailin  2022  104.3
230  Beimbet Mailin  2023  111.6

[231 rows x 3 columns]

In [357]:
kostanay_ppi['rayon'].unique()
kostanay_ppi = kostanay_ppi.drop(kostanay_ppi[kostanay_ppi['year'] == 2013].index)

In [358]:
kostanay_ppi

              rayon  year    ppi
1        Altynsarin  2014   98.4
2        Altynsarin  2015  112.2
3        Altynsarin  2016  111.9
4        Altynsarin  2017  103.5
5        Altynsarin  2018  111.9
..              ...   ...    ...
226  Beimbet Mailin  2019  115.4
227  Beimbet Mailin  2020  132.0
228  Beimbet Mailin  2021  121.2
229  Beimbet Mailin  2022  104.3
230  Beimbet Mailin  2023  111.6

[210 rows x 3 columns]

In [359]:
kostanay_inv['rayon'].unique()

array(['Altynsarin', 'Amangeldi', 'Auliekol', 'Denisov', 'Zhangeldin',
       'Zhitikara', 'Kamysty', 'Karabalyk', 'Karasu', 'Kostanay',
       'Mendykara', 'Naurzum', 'Sarykol', 'Taran', 'Uzunkol', 'Fyodorov',
       'Kostanay city', 'Arkalyk city', 'Lisakovsk city', 'Rudny city',
       'Beimbet Mailin'], dtype=object)

In [360]:
kostanay_ppi['rayon'].unique()

array(['Altynsarin', 'Amangeldi', 'Auliekol', 'Denisov', 'Zhangeldin',
       'Zhitikara', 'Kamysty', 'Karabalyk', 'Karasu', 'Kostanay',
       'Mendykara', 'Naurzum', 'Sarykol', 'Taran', 'Uzunkol', 'Fyodorov',
       'Kostanay city', 'Arkalyk city', 'Lisakovsk city', 'Rudny city',
       'Beimbet Mailin'], dtype=object)

## Combine

In [361]:
dfs_kostanay = [kostanay_inv, kostanay_employment, kostanay_controls, kostanay_ppi]
kostanay_merged = reduce(lambda left, right: pd.merge(left, right, on=['rayon', 'year'], how='outer'), dfs_kostanay)
kostanay_merged

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year,employment,agriculture,production,retail,ppi
0,Altynsarin,2542234.0,7684.0,7684.0,2021206.0,Kostanay,2014,8709.0,11962.2,2364.0,408.5,98.4
1,Altynsarin,2293596.0,4461.0,1920.0,327600.0,Kostanay,2015,7414.0,14421.3,1708.0,426.0,112.2
2,Altynsarin,1310106.0,3666.0,1582.0,142116.0,Kostanay,2016,7618.0,13886.6,1692.0,497.1,111.9
3,Altynsarin,1387673.0,87196.0,947.0,168496.0,Kostanay,2017,7845.0,17907.4,2028.0,570.1,103.5
4,Altynsarin,1823464.0,19000.0,1601.0,262622.0,Kostanay,2018,7732.0,17603.9,2463.0,618.4,111.9
...,...,...,...,...,...,...,...,...,...,...,...,...
225,Zhitikara,9305975.0,5429965.0,574263.0,2347618.0,Kostanay,2020,26623.0,13894.3,81027.0,6405.0,132.0
226,Zhitikara,9088892.0,6850459.0,327708.0,3184821.0,Kostanay,2021,28066.0,12917.8,90505.0,8653.8,121.2
227,Zhitikara,9061165.0,5437932.0,328228.0,3423922.0,Kostanay,2022,23891.0,25244.4,90034.0,10066.4,104.3
228,Zhitikara,9535101.0,12507997.0,287248.0,2313714.0,Kostanay,2023,23467.0,15945.707699,92413.0,15715.1,111.6
229,Zhitikara,14695137.0,9779556.0,168430.0,3726434.0,Kostanay,2024,22449.0,NaN,NaN,NaN,NaN

# Kyzylorda

## Investments

In [362]:
kyzylorda_all_2014 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2014_Investments/Internal_vs_external.xls"), header=5, nrows=21, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kyzylorda_all_2015 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2015_Investments/Internal_vs_external.xls"), header=6, nrows=21, usecols='A, C, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kyzylorda_all_2016 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2016_Investments/Internal_vs_external.xls"), header=5, nrows=21, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kyzylorda_all_2017 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2017_Investments/Internal_vs_external.xls"), header=5, nrows=21, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kyzylorda_all_2018 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2018_Investments/Internal_vs_external.xls"), header=5, nrows=21, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kyzylorda_all_2019 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2019_Investments.xls"), sheet_name='14.', header=5, nrows=21, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kyzylorda_all_2020 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2020_Investments.xlsx"), sheet_name='13.', header=5, nrows=21, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kyzylorda_all_2021 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2021_Investments.xls"), sheet_name='13.', header=3, nrows=21, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kyzylorda_all_2022 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2022_Investments.xlsx"), sheet_name='13', header=3, nrows=21, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kyzylorda_all_2023 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2023_Investments.xlsx"), sheet_name='19', header=3, nrows=21, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kyzylorda_all_2024 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2024_Investments.xlsx"), sheet_name='14', header=4, nrows=21, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

kyzylorda_non_2014 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2014_Investments/Greenfield_investments.xls"), header=5, nrows=21, usecols='A, B, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kyzylorda_non_2015 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2015_Investments/Greenfield_investments.xls"), header=5, nrows=10, usecols='A, B, C', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kyzylorda_non_2016 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2016_Investments/Greenfield_investments.xls"), header=5, nrows=10, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kyzylorda_non_2017 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2017_Investments/Greenfield_investments.xls"), header=5, nrows=10, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kyzylorda_non_2018 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2018_Investments/Greenfield_investments.xls"), header=5, nrows=10, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kyzylorda_non_2019 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2019_Investments.xls"), sheet_name='15.', header=5, nrows=10, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kyzylorda_non_2020 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2020_Investments.xlsx"), sheet_name='14.', header=5, nrows=10, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kyzylorda_non_2021 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2021_Investments.xls"), sheet_name='14.', header=4, nrows=10, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kyzylorda_non_2022 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2022_Investments.xlsx"), sheet_name='14', header=3, nrows=10, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kyzylorda_non_2023 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2023_Investments.xlsx"), sheet_name='20', header=3, nrows=10, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
kyzylorda_non_2024 = pd.read_excel(Path("../Data/Investments/Kyzylorda/2024_Investments.xlsx"), sheet_name='15', header=4, nrows=10, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [363]:
dfs = [kyzylorda_all_2014, kyzylorda_all_2015, kyzylorda_all_2016, kyzylorda_all_2017, kyzylorda_all_2018, kyzylorda_all_2019, kyzylorda_all_2020,
       kyzylorda_all_2021, kyzylorda_all_2022, kyzylorda_all_2023, kyzylorda_all_2024,
       kyzylorda_non_2014, kyzylorda_non_2015, kyzylorda_non_2016, kyzylorda_non_2017, kyzylorda_non_2018, kyzylorda_non_2019, kyzylorda_non_2020,
      kyzylorda_non_2021, kyzylorda_non_2022, kyzylorda_non_2023, kyzylorda_non_2024]

lists = []

for df in dfs:
    lists.extend(df.iloc[:, 0].unique())

unique_lists = pd.Series(lists).unique()
unique_lists

array(['Қызылорда қ.ә.', 'Байқоңыр қ.', 'Арал ауданы', 'Жалағаш ауданы',
       'Жаңақорған ауданы', 'Қазалы ауданы', 'Қармақшы ауданы',
       'Сырдария ауданы', 'Шиелі ауданы', 'Арал', 'Жалағаш ',
       'Жаңақорған ', 'Қазалы ', 'Қармақшы', 'Сырдария ', 'Шиелі ',
       'Байқоңыр қ.ә.', 'Кызылорда г.а.', 'Байконыр г.а.', 'Аральский',
       'Жалагашский', 'Жанакорганский', 'Казалинский', 'Кармакшинский',
       'Сырдарийский', 'Шиелийский', 'Қызылорда г.а.', 'Байконыр г.а',
       'Сырдарьинский', 'Жаңақорған\nауданы', 'Арал ', 'Жаңақорған',
       'Қармақшы '], dtype=object)

In [364]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [kyzylorda_all_2014, kyzylorda_all_2015, kyzylorda_all_2016, kyzylorda_all_2017,
          kyzylorda_all_2018, kyzylorda_all_2019, kyzylorda_all_2020, kyzylorda_all_2021,
          kyzylorda_all_2022, kyzylorda_all_2023, kyzylorda_all_2024]:
    df.columns = all_columns

for df in [kyzylorda_non_2014, kyzylorda_non_2015, kyzylorda_non_2016, kyzylorda_non_2017,
          kyzylorda_non_2018, kyzylorda_non_2019, kyzylorda_non_2020, kyzylorda_non_2021,
          kyzylorda_non_2022, kyzylorda_non_2023, kyzylorda_non_2024]:
    df.columns = non_columns
    
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

In [365]:
rayon_map_kyzylorda = {

    # ---- Cities ----
    'Қызылорда қ.ә.': 'Kyzylorda city',
    'Қызылорда г.а.': 'Kyzylorda city',
    'Кызылорда г.а.': 'Kyzylorda city',

    'Байқоңыр қ.': 'Baikonur city',
    'Байқоңыр қ.ә.': 'Baikonur city',
    'Байконыр г.а.': 'Baikonur city',
    'Байконыр г.а': 'Baikonur city',

    # ---- Rayons ----
    'Арал ауданы': 'Aral',
    'Арал': 'Aral',
    'Арал ': 'Aral',
    'Аральский': 'Aral',

    'Жалағаш ауданы': 'Zhalagash',
    'Жалағаш ': 'Zhalagash',
    'Жалагашский': 'Zhalagash',
    'Жалагашский ': 'Zhalagash',

    'Жаңақорған ауданы': 'Zhanakorgan',
    'Жаңақорған': 'Zhanakorgan',
    'Жаңақорған ': 'Zhanakorgan',
    'Жаңақорған\nауданы': 'Zhanakorgan',
    'Жанакорганский': 'Zhanakorgan',
    'Жанакорганский ': 'Zhanakorgan',

    'Қазалы ауданы': 'Kazaly',
    'Қазалы ': 'Kazaly',
    'Казалинский': 'Kazaly',
    'Казалинский ': 'Kazaly',

    'Қармақшы ауданы': 'Karmakshy',
    'Қармақшы': 'Karmakshy',
    'Қармақшы ': 'Karmakshy',
    'Кармакшинский': 'Karmakshy',
    'Кармакшинский ': 'Karmakshy',

    'Сырдария ауданы': 'Syrdarya',
    'Сырдария ': 'Syrdarya',
    'Сырдарьинский': 'Syrdarya',
    'Сырдарийский': 'Syrdarya',
    'Сырдарьинский ': 'Syrdarya',

    'Шиелі ауданы': 'Shieli',
    'Шиелі ': 'Shieli',
    'Шиелийский': 'Shieli',
    'Шиелийский ': 'Shieli',
}

In [366]:
# ----- ALL investments -----
kyzylorda_all_2014['rayon'] = kyzylorda_all_2014['rayon'].replace(rayon_map_kyzylorda)
kyzylorda_all_2015['rayon'] = kyzylorda_all_2015['rayon'].replace(rayon_map_kyzylorda)
kyzylorda_all_2016['rayon'] = kyzylorda_all_2016['rayon'].replace(rayon_map_kyzylorda)
kyzylorda_all_2017['rayon'] = kyzylorda_all_2017['rayon'].replace(rayon_map_kyzylorda)
kyzylorda_all_2018['rayon'] = kyzylorda_all_2018['rayon'].replace(rayon_map_kyzylorda)
kyzylorda_all_2019['rayon'] = kyzylorda_all_2019['rayon'].replace(rayon_map_kyzylorda)
kyzylorda_all_2020['rayon'] = kyzylorda_all_2020['rayon'].replace(rayon_map_kyzylorda)
kyzylorda_all_2021['rayon'] = kyzylorda_all_2021['rayon'].replace(rayon_map_kyzylorda)
kyzylorda_all_2022['rayon'] = kyzylorda_all_2022['rayon'].replace(rayon_map_kyzylorda)
kyzylorda_all_2023['rayon'] = kyzylorda_all_2023['rayon'].replace(rayon_map_kyzylorda)
kyzylorda_all_2024['rayon'] = kyzylorda_all_2024['rayon'].replace(rayon_map_kyzylorda)

# ----- NON-extractive investments -----
kyzylorda_non_2014['rayon'] = kyzylorda_non_2014['rayon'].replace(rayon_map_kyzylorda)
kyzylorda_non_2015['rayon'] = kyzylorda_non_2015['rayon'].replace(rayon_map_kyzylorda)
kyzylorda_non_2016['rayon'] = kyzylorda_non_2016['rayon'].replace(rayon_map_kyzylorda)
kyzylorda_non_2017['rayon'] = kyzylorda_non_2017['rayon'].replace(rayon_map_kyzylorda)
kyzylorda_non_2018['rayon'] = kyzylorda_non_2018['rayon'].replace(rayon_map_kyzylorda)
kyzylorda_non_2019['rayon'] = kyzylorda_non_2019['rayon'].replace(rayon_map_kyzylorda)
kyzylorda_non_2020['rayon'] = kyzylorda_non_2020['rayon'].replace(rayon_map_kyzylorda)
kyzylorda_non_2021['rayon'] = kyzylorda_non_2021['rayon'].replace(rayon_map_kyzylorda)
kyzylorda_non_2022['rayon'] = kyzylorda_non_2022['rayon'].replace(rayon_map_kyzylorda)
kyzylorda_non_2023['rayon'] = kyzylorda_non_2023['rayon'].replace(rayon_map_kyzylorda)
kyzylorda_non_2024['rayon'] = kyzylorda_non_2024['rayon'].replace(rayon_map_kyzylorda)

In [367]:
kyzylorda_2014 = kyzylorda_all_2014.merge(kyzylorda_non_2014, on='rayon', how='left')
kyzylorda_2015 = kyzylorda_all_2015.merge(kyzylorda_non_2015, on='rayon', how='left')
kyzylorda_2016 = kyzylorda_all_2016.merge(kyzylorda_non_2016, on='rayon', how='left')
kyzylorda_2017 = kyzylorda_all_2017.merge(kyzylorda_non_2017, on='rayon', how='left')
kyzylorda_2018 = kyzylorda_all_2018.merge(kyzylorda_non_2018, on='rayon', how='left')
kyzylorda_2019 = kyzylorda_all_2019.merge(kyzylorda_non_2019, on='rayon', how='left')
kyzylorda_2020 = kyzylorda_all_2020.merge(kyzylorda_non_2020, on='rayon', how='left')
kyzylorda_2021 = kyzylorda_all_2021.merge(kyzylorda_non_2021, on='rayon', how='left')
kyzylorda_2022 = kyzylorda_all_2022.merge(kyzylorda_non_2022, on='rayon', how='left')
kyzylorda_2023 = kyzylorda_all_2023.merge(kyzylorda_non_2023, on='rayon', how='left')
kyzylorda_2024 = kyzylorda_all_2024.merge(kyzylorda_non_2024, on='rayon', how='left')

dfs = [kyzylorda_2014, kyzylorda_2015, kyzylorda_2016, kyzylorda_2017, kyzylorda_2018, kyzylorda_2019, kyzylorda_2020, kyzylorda_2021, kyzylorda_2022, kyzylorda_2023, kyzylorda_2024]

for i in range(11):
    df = dfs[i]
    df['oblast'] = 'Kyzylorda'
    df['year'] = 2014 + i

kyzylorda_inv = pd.concat([kyzylorda_2014, kyzylorda_2015, kyzylorda_2016, kyzylorda_2017, kyzylorda_2018, kyzylorda_2019, kyzylorda_2020, kyzylorda_2021, kyzylorda_2022, kyzylorda_2023, kyzylorda_2024], ignore_index=True)
kyzylorda_inv['rayon'] = (
    kyzylorda_inv['rayon']
        .str.strip()          # remove hidden spaces
        .replace(rayon_map)   # enforce English names
)
kyzylorda_inv

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year
0,Kyzylorda city,75977586,57209823.0,12691020.0,45852834.0,Kyzylorda,2014
1,Baikonur city,32053,0.0,0.0,32053.0,Kyzylorda,2014
2,Aral,19635352,4538566.0,4538566.0,19359041.0,Kyzylorda,2014
3,Zhalagash,3837183,360572.0,360572.0,3503755.0,Kyzylorda,2014
4,Zhanakorgan,11063714,1369077.0,760866.0,10377983.0,Kyzylorda,2014
...,...,...,...,...,...,...,...
94,Zhanakorgan,64434601,21249098.0,552909.0,13469373.0,Kyzylorda,2024
95,Kazaly,26967907,0.0,0.0,13688619.0,Kyzylorda,2024
96,Karmakshy,18464252,227395.0,45101.0,7751526.0,Kyzylorda,2024
97,Syrdarya,52223645,33001171.0,13860799.0,13446588.0,Kyzylorda,2024
98,Shieli,53644890,21747930.0,11329865.0,17022712.0,Kyzylorda,2024

## Employment

In [368]:
kyzylorda_empl = pd.read_excel(Path("../Data/Employment/Kyzylorda.xls"), skiprows=4, nrows=9, header=None, usecols='A:L', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
kyzylorda_empl.columns = ['rayon', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
kyzylorda_empl['rayon'] = kyzylorda_empl['rayon'].replace(rayon_map_kyzylorda)
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    kyzylorda_empl[i] = kyzylorda_empl[i].astype(float)
    kyzylorda_employment = kyzylorda_empl.melt(id_vars='rayon', value_vars=[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024], var_name='year', value_name='employment')
kyzylorda_employment

             rayon  year  employment
0   Kyzylorda city  2014    117188.0
1    Baikonur city  2014         0.0
2             Aral  2014     31155.0
3        Zhalagash  2014     16663.0
4      Zhanakorgan  2014     34695.0
..             ...   ...         ...
94     Zhanakorgan  2024     29662.0
95          Kazaly  2024     30360.0
96       Karmakshy  2024     21309.0
97        Syrdarya  2024     15418.0
98          Shieli  2024     34799.0

[99 rows x 3 columns]

## Other Controls

In [369]:
kyzylorda_city = pd.read_excel(Path("../Data/Controls/Kyzylorda_All.xls"), sheet_name="г.Кызылорда", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
kyzylorda_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
kyzylorda_city = kyzylorda_city.loc[[82, 109, 160]].reset_index(drop=True)
kyzylorda_city['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    kyzylorda_city[i] = kyzylorda_city[i].astype(str)
    kyzylorda_city[i] = kyzylorda_city[i].str.replace(',', '.')
    kyzylorda_city[i] = kyzylorda_city[i].str.replace(')', '')
    kyzylorda_city[i] = kyzylorda_city[i].str.replace(' ', '')
    kyzylorda_city[i] = kyzylorda_city[i].str.replace('\xa0', '')
    kyzylorda_city[i] = kyzylorda_city[i].str.replace('*', '')
    kyzylorda_city[i] = kyzylorda_city[i].astype(float)
kyzylorda_city = pd.melt(kyzylorda_city, id_vars=['Indicator'], var_name='year', value_name='value')
kyzylorda_city = kyzylorda_city.pivot(index='year', columns='Indicator', values='value').reset_index()
kyzylorda_city.insert(0, 'rayon', 'Kyzylorda city')
kyzylorda_city.columns.name = None
kyzylorda_city

            rayon  year  agriculture  production    retail
0  Kyzylorda city  2014       5502.8    902266.0  133532.7
1  Kyzylorda city  2015       5859.4    480895.0  138875.1
2  Kyzylorda city  2016       5717.5    508938.0  163398.6
3  Kyzylorda city  2017       6311.0    591397.0  186805.0
4  Kyzylorda city  2018       7463.1    801798.0  208357.2
5  Kyzylorda city  2019       8613.9    694477.0  227873.1
6  Kyzylorda city  2020       9958.4    479702.0  246294.6
7  Kyzylorda city  2021      13104.6    592170.0  269236.3
8  Kyzylorda city  2022      14126.6    634614.0  316295.4
9  Kyzylorda city  2023      15167.5    649939.0  377656.6

In [370]:
aral = pd.read_excel(Path("../Data/Controls/Kyzylorda_All.xls"), sheet_name="Арал", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
aral.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
aral = aral.loc[[83, 108, 159]].reset_index(drop=True)
aral['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    aral[i] = aral[i].astype(str)
    aral[i] = aral[i].str.replace(',', '.')
    aral[i] = aral[i].str.replace(')', '')
    aral[i] = aral[i].str.replace(' ', '')
    aral[i] = aral[i].str.replace('\xa0', '')
    aral[i] = aral[i].str.replace('*', '')
    aral[i] = aral[i].astype(float)
aral = pd.melt(aral, id_vars=['Indicator'], var_name='year', value_name='value')
aral = aral.pivot(index='year', columns='Indicator', values='value').reset_index()
aral.insert(0, 'rayon', 'Aral')
aral.columns.name = None
aral

  rayon  year  agriculture  production   retail
0  Aral  2014       4854.0      5588.0   6920.8
1  Aral  2015       6006.2      6427.0   7229.3
2  Aral  2016       6476.0      8325.0   8031.1
3  Aral  2017       6891.0      9968.0  10018.8
4  Aral  2018       8058.8     12314.0  11214.3
5  Aral  2019       9782.4     15577.0  12047.9
6  Aral  2020      11467.4     15716.0  12616.0
7  Aral  2021      13062.4     17407.0  13977.8
8  Aral  2022      15828.8     24219.0  16580.6
9  Aral  2023      15358.8     33679.0  19494.8

In [371]:
zhalagash = pd.read_excel(Path("../Data/Controls/Kyzylorda_All.xls"), sheet_name="Жалагаш", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
zhalagash.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
zhalagash = zhalagash.loc[[83, 108, 159]].reset_index(drop=True)
zhalagash['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    zhalagash[i] = zhalagash[i].astype(str)
    zhalagash[i] = zhalagash[i].str.replace(',', '.')
    zhalagash[i] = zhalagash[i].str.replace(')', '')
    zhalagash[i] = zhalagash[i].str.replace(' ', '')
    zhalagash[i] = zhalagash[i].str.replace('\xa0', '')
    zhalagash[i] = zhalagash[i].str.replace('*', '')
    zhalagash[i] = zhalagash[i].astype(float)
zhalagash = pd.melt(zhalagash, id_vars=['Indicator'], var_name='year', value_name='value')
zhalagash = zhalagash.pivot(index='year', columns='Indicator', values='value').reset_index()
zhalagash.insert(0, 'rayon', 'Zhalagash')
zhalagash.columns.name = None
zhalagash

       rayon  year  agriculture  production  retail
0  Zhalagash  2014      11123.1      2250.0  2351.8
1  Zhalagash  2015      12505.2      2835.0  2362.1
2  Zhalagash  2016      12036.1      3318.0  2883.3
3  Zhalagash  2017      13381.5      4387.0  3477.1
4  Zhalagash  2018      15337.9      5636.0  3814.1
5  Zhalagash  2019      20833.9      8651.0  4095.0
6  Zhalagash  2020      22917.0      7557.0  4194.4
7  Zhalagash  2021      25543.8     11014.0  4580.9
8  Zhalagash  2022      27434.6     33606.0  5332.3
9  Zhalagash  2023      33315.7     37526.0  6189.2

In [372]:
zhanakorgan = pd.read_excel(Path("../Data/Controls/Kyzylorda_All.xls"), sheet_name="Жанакорган", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
zhanakorgan.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
zhanakorgan = zhanakorgan.loc[[83, 108, 159]].reset_index(drop=True)
zhanakorgan['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    zhanakorgan[i] = zhanakorgan[i].astype(str)
    zhanakorgan[i] = zhanakorgan[i].str.replace(',', '.')
    zhanakorgan[i] = zhanakorgan[i].str.replace(')', '')
    zhanakorgan[i] = zhanakorgan[i].str.replace(' ', '')
    zhanakorgan[i] = zhanakorgan[i].str.replace('\xa0', '')
    zhanakorgan[i] = zhanakorgan[i].str.replace('*', '')
    zhanakorgan[i] = zhanakorgan[i].astype(float)
zhanakorgan = pd.melt(zhanakorgan, id_vars=['Indicator'], var_name='year', value_name='value')
zhanakorgan = zhanakorgan.pivot(index='year', columns='Indicator', values='value').reset_index()
zhanakorgan.insert(0, 'rayon', 'Zhanakorgan')
zhanakorgan.columns.name = None
zhanakorgan

         rayon  year  agriculture  production   retail
0  Zhanakorgan  2014       9614.0     43873.0   5789.6
1  Zhanakorgan  2015      11152.3     69199.0   5835.9
2  Zhanakorgan  2016      10830.1    108456.0   6808.0
3  Zhanakorgan  2017      12444.0     87411.0   6459.3
4  Zhanakorgan  2018      14675.9     82345.0   7213.8
5  Zhanakorgan  2019      18034.8     82419.0   7789.8
6  Zhanakorgan  2020      20997.8     83495.0   7824.9
7  Zhanakorgan  2021      24565.6     98861.0   8606.5
8  Zhanakorgan  2022      28907.2    127138.0  10041.9
9  Zhanakorgan  2023      30155.2    143361.0  11733.0

In [373]:
kazaly = pd.read_excel(Path("../Data/Controls/Kyzylorda_All.xls"), sheet_name="Казалы", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
kazaly.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
kazaly = kazaly.loc[[83, 108, 159]].reset_index(drop=True)
kazaly['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    kazaly[i] = kazaly[i].astype(str)
    kazaly[i] = kazaly[i].str.replace(',', '.')
    kazaly[i] = kazaly[i].str.replace(')', '')
    kazaly[i] = kazaly[i].str.replace(' ', '')
    kazaly[i] = kazaly[i].str.replace('\xa0', '')
    kazaly[i] = kazaly[i].str.replace('*', '')
    kazaly[i] = kazaly[i].astype(float)
kazaly = pd.melt(kazaly, id_vars=['Indicator'], var_name='year', value_name='value')
kazaly = kazaly.pivot(index='year', columns='Indicator', values='value').reset_index()
kazaly.insert(0, 'rayon', 'Kazaly')
kazaly.columns.name = None
kazaly

    rayon  year  agriculture  production   retail
0  Kazaly  2014       7425.8     10695.0   9272.1
1  Kazaly  2015       9974.6     11099.0   9989.0
2  Kazaly  2016      10703.0     11709.0  11337.2
3  Kazaly  2017      10941.0     10970.0  12315.4
4  Kazaly  2018      12899.3     12315.0  13766.8
5  Kazaly  2019      15824.9     14218.0  14854.4
6  Kazaly  2020      18006.3     16061.0  15670.7
7  Kazaly  2021      21623.9     17742.0  20458.4
8  Kazaly  2022      24358.6     19801.0  24193.0
9  Kazaly  2023      29456.9     26410.0  28459.4

In [374]:
karmakshy = pd.read_excel(Path("../Data/Controls/Kyzylorda_All.xls"), sheet_name="Кармакшы", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
karmakshy.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
karmakshy = karmakshy.loc[[82, 107, 158]].reset_index(drop=True)
karmakshy['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    karmakshy[i] = karmakshy[i].astype(str)
    karmakshy[i] = karmakshy[i].str.replace(',', '.')
    karmakshy[i] = karmakshy[i].str.replace(')', '')
    karmakshy[i] = karmakshy[i].str.replace(' ', '')
    karmakshy[i] = karmakshy[i].str.replace('\xa0', '')
    karmakshy[i] = karmakshy[i].str.replace('*', '')
    karmakshy[i] = karmakshy[i].astype(float)
karmakshy = pd.melt(karmakshy, id_vars=['Indicator'], var_name='year', value_name='value')
karmakshy = karmakshy.pivot(index='year', columns='Indicator', values='value').reset_index()
karmakshy.insert(0, 'rayon', 'Karmakshy')
karmakshy.columns.name = None
karmakshy

       rayon  year  agriculture  production   retail
0  Karmakshy  2014       8725.7      1929.0   3469.0
1  Karmakshy  2015       8887.5      1687.0   3730.9
2  Karmakshy  2016       8995.2      2452.0   4162.0
3  Karmakshy  2017       9851.9      3059.0   3891.9
4  Karmakshy  2018      10455.4      2755.0   4455.9
5  Karmakshy  2019      13370.2      2850.0   4776.7
6  Karmakshy  2020      14359.6      3626.0   4909.8
7  Karmakshy  2021      17772.3      3613.0   7427.8
8  Karmakshy  2022      18243.5      3673.0  11881.5
9  Karmakshy  2023      21365.6      8929.0  13940.1

In [375]:
syrdarya = pd.read_excel(Path("../Data/Controls/Kyzylorda_All.xls"), sheet_name="Сырдария", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
syrdarya.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
syrdarya = syrdarya.loc[[82, 107, 158]].reset_index(drop=True)
syrdarya['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    syrdarya[i] = syrdarya[i].astype(str)
    syrdarya[i] = syrdarya[i].str.replace(',', '.')
    syrdarya[i] = syrdarya[i].str.replace(')', '')
    syrdarya[i] = syrdarya[i].str.replace(' ', '')
    syrdarya[i] = syrdarya[i].str.replace('\xa0', '')
    syrdarya[i] = syrdarya[i].str.replace('*', '')
    syrdarya[i] = syrdarya[i].astype(float)
syrdarya = pd.melt(syrdarya, id_vars=['Indicator'], var_name='year', value_name='value')
syrdarya = syrdarya.pivot(index='year', columns='Indicator', values='value').reset_index()
syrdarya.insert(0, 'rayon', 'Syrdarya')
syrdarya.columns.name = None
syrdarya

      rayon  year  agriculture  production  retail
0  Syrdarya  2014       7379.4      1719.0  1607.2
1  Syrdarya  2015       9556.2      1880.0  1669.2
2  Syrdarya  2016       9454.1      1035.0  1969.1
3  Syrdarya  2017      10212.8      1370.0  1959.8
4  Syrdarya  2018      11808.3      1897.0  2166.2
5  Syrdarya  2019      15136.3      2366.0  2320.2
6  Syrdarya  2020      16553.0      4869.0  2280.5
7  Syrdarya  2021      21084.8      6540.0  2502.5
8  Syrdarya  2022      20757.2     58386.0  3415.3
9  Syrdarya  2023      27109.1     65899.0  3993.3

In [376]:
shieli = pd.read_excel(Path("../Data/Controls/Kyzylorda_All.xls"), sheet_name="Шиели", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
shieli.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
shieli = shieli.loc[[82, 108, 159]].reset_index(drop=True)
shieli['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    shieli[i] = shieli[i].astype(str)
    shieli[i] = shieli[i].str.replace(',', '.')
    shieli[i] = shieli[i].str.replace(')', '')
    shieli[i] = shieli[i].str.replace(' ', '')
    shieli[i] = shieli[i].str.replace('\xa0', '')
    shieli[i] = shieli[i].str.replace('*', '')
    shieli[i] = shieli[i].astype(float)
shieli = pd.melt(shieli, id_vars=['Indicator'], var_name='year', value_name='value')
shieli = shieli.pivot(index='year', columns='Indicator', values='value').reset_index()
shieli.insert(0, 'rayon', 'Shieli')
shieli.columns.name = None
shieli

    rayon  year  agriculture  production   retail
0  Shieli  2014      15515.4     26668.0   9356.5
1  Shieli  2015      15950.6     26732.0  10072.7
2  Shieli  2016      17369.1     24965.0  12131.5
3  Shieli  2017      19726.3     22839.0  14033.2
4  Shieli  2018      24470.2     24313.0  15943.1
5  Shieli  2019      28609.4     31406.0  17214.9
6  Shieli  2020      31216.5     42095.0  18014.6
7  Shieli  2021      36117.0     61080.0  19929.3
8  Shieli  2022      40675.4     69675.0  23785.9
9  Shieli  2023      45135.3     70531.0  28105.5

In [377]:
baikonur_city = pd.read_excel(Path("../Data/Controls/Kyzylorda_All.xls"), sheet_name="г.Байконыр", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
baikonur_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
baikonur_city = baikonur_city.loc[[79, 131, 129]].reset_index(drop=True)
baikonur_city['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    baikonur_city[i] = baikonur_city[i].astype(str)
    baikonur_city[i] = baikonur_city[i].str.replace(',', '.')
    baikonur_city[i] = baikonur_city[i].str.replace(')', '')
    baikonur_city[i] = baikonur_city[i].str.replace(' ', '')
    baikonur_city[i] = baikonur_city[i].str.replace('\xa0', '')
    baikonur_city[i] = baikonur_city[i].str.replace('*', '')
    baikonur_city[i] = baikonur_city[i].astype(float)
baikonur_city = pd.melt(baikonur_city, id_vars=['Indicator'], var_name='year', value_name='value')
baikonur_city = baikonur_city.pivot(index='year', columns='Indicator', values='value').reset_index()
baikonur_city.insert(0, 'rayon', 'Baikonur city')
baikonur_city.columns.name = None
baikonur_city

           rayon  year  agriculture  production  retail
0  Baikonur city  2014          NaN         4.0   775.2
1  Baikonur city  2015          NaN         4.0   378.1
2  Baikonur city  2016          NaN         2.0   216.5
3  Baikonur city  2017          NaN         6.0   289.4
4  Baikonur city  2018          NaN       250.0   320.6
5  Baikonur city  2019          NaN       182.0   342.4
6  Baikonur city  2020          NaN       147.0   128.7
7  Baikonur city  2021          NaN       173.0   277.0
8  Baikonur city  2022          NaN       106.0   369.9
9  Baikonur city  2023          NaN       713.0  1638.9

In [378]:
kyzylorda_controls = pd.concat([kyzylorda_city, aral, zhalagash, zhanakorgan, kazaly, karmakshy, syrdarya, shieli, baikonur_city], ignore_index=True)
kyzylorda_controls

             rayon  year  agriculture  production    retail
0   Kyzylorda city  2014       5502.8    902266.0  133532.7
1   Kyzylorda city  2015       5859.4    480895.0  138875.1
2   Kyzylorda city  2016       5717.5    508938.0  163398.6
3   Kyzylorda city  2017       6311.0    591397.0  186805.0
4   Kyzylorda city  2018       7463.1    801798.0  208357.2
..             ...   ...          ...         ...       ...
85   Baikonur city  2019          NaN       182.0     342.4
86   Baikonur city  2020          NaN       147.0     128.7
87   Baikonur city  2021          NaN       173.0     277.0
88   Baikonur city  2022          NaN       106.0     369.9
89   Baikonur city  2023          NaN       713.0    1638.9

[90 rows x 5 columns]

## PPI

In [379]:
kyzylorda_ppi = pd.read_excel(
    Path("../Data/PPI/Kyzylorda.xls"),
    header=2,
    usecols='Y:AH',
    nrows=79,
    na_values=['x', 'х', '-', '', ' ', '...']
)
kyzylorda_ppi.columns = [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
rayons = list(kyzylorda_inv['rayon'].unique())

dfs = []

for rayon in rayons:
    df_temp = pd.DataFrame({
        'rayon': [rayon] * len(range(2014, 2024)),
        'year': list(range(2014, 2024)),
        'ppi': kyzylorda_ppi.iloc[-1].values
    })
    dfs.append(df_temp)

kyzylorda_ppi = pd.concat(dfs, ignore_index=True)
kyzylorda_ppi['ppi'] = kyzylorda_ppi['ppi'].astype(str).str.replace(',', '.')
kyzylorda_ppi['ppi'] = kyzylorda_ppi['ppi'].astype(str).str.replace(')', '')
kyzylorda_ppi['ppi'] = kyzylorda_ppi['ppi'].astype(str).str.replace(' ', '')
kyzylorda_ppi['ppi'] = kyzylorda_ppi['ppi'].astype(str).str.replace('\xa0', '')
kyzylorda_ppi['ppi'] = kyzylorda_ppi['ppi'].astype(str).str.replace('*', '')
kyzylorda_ppi['ppi'] = kyzylorda_ppi['ppi'].astype(float)

kyzylorda_ppi

             rayon  year    ppi
0   Kyzylorda city  2014   90.7
1   Kyzylorda city  2015   84.1
2   Kyzylorda city  2016  127.6
3   Kyzylorda city  2017  127.9
4   Kyzylorda city  2018  117.9
..             ...   ...    ...
85          Shieli  2019  103.0
86          Shieli  2020   97.2
87          Shieli  2021  174.4
88          Shieli  2022  116.1
89          Shieli  2023   96.3

[90 rows x 3 columns]

## Combine

In [380]:
dfs_kyzylorda = [kyzylorda_inv, kyzylorda_employment, kyzylorda_controls, kyzylorda_ppi]
kyzylorda_merged = reduce(lambda left, right: pd.merge(left, right, on=['rayon', 'year'], how='outer'), dfs_kyzylorda)
kyzylorda_merged

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year,employment,agriculture,production,retail,ppi
0,Aral,19635352,4538566.0,4538566.0,19359041.0,Kyzylorda,2014,31155.0,4854.0,5588.0,6920.8,90.7
1,Aral,21154465,44316.0,44316.0,13408144.0,Kyzylorda,2015,30688.0,6006.2,6427.0,7229.3,84.1
2,Aral,4895000,474724.0,474724.0,1393997.0,Kyzylorda,2016,33117.0,6476.0,8325.0,8031.1,127.6
3,Aral,10489562,0.0,0.0,6293231.0,Kyzylorda,2017,31819.0,6891.0,9968.0,10018.8,127.9
4,Aral,28454069,72589.0,72589.0,23034876.0,Kyzylorda,2018,31853.0,8058.8,12314.0,11214.3,117.9
...,...,...,...,...,...,...,...,...,...,...,...,...
94,Zhanakorgan,21941045,4974442.0,2184181.0,4666736.0,Kyzylorda,2020,32536.0,20997.8,83495.0,7824.9,97.2
95,Zhanakorgan,24498182,8098287.0,1243975.0,7468753.0,Kyzylorda,2021,33221.0,24565.6,98861.0,8606.5,174.4
96,Zhanakorgan,24263958,28925808.0,237603.0,6080286.0,Kyzylorda,2022,29488.0,28907.2,127138.0,10041.9,116.1
97,Zhanakorgan,41359062,30251786.0,645223.0,8033978.0,Kyzylorda,2023,30119.0,30155.2,143361.0,11733.0,96.3
98,Zhanakorgan,64434601,21249098.0,552909.0,13469373.0,Kyzylorda,2024,29662.0,NaN,NaN,NaN,NaN

# Mangystau

## Investments

In [381]:
mangystau_all_2014 = pd.read_excel(Path("../Data/Investments/Mangystau/2014_Investments.xls"), header=5, nrows=8, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
mangystau_all_2015 = pd.read_excel(Path("../Data/Investments/Mangystau/2015_Investments.xls"), header=5, nrows=8, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
mangystau_all_2016 = pd.read_excel(Path("../Data/Investments/Mangystau/2016_Investments/Internal_vs_external.xls"), header=5, nrows=8, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
mangystau_all_2017 = pd.read_excel(Path("../Data/Investments/Mangystau/2017_Investments/Internal_vs_external.xls"), header=3, nrows=8, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
mangystau_all_2018 = pd.read_excel(Path("../Data/Investments/Mangystau/2018_Investments/Internal_vs_external.xls"), header=4, nrows=8, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
mangystau_all_2019 = pd.read_excel(Path("../Data/Investments/Mangystau/2019_Investments.xls"), sheet_name='14', header=4, nrows=8, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
mangystau_all_2020 = pd.read_excel(Path("../Data/Investments/Mangystau/2020_Investments.xls"), sheet_name='13', header=4, nrows=8, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
mangystau_all_2021 = pd.read_excel(Path("../Data/Investments/Mangystau/2021_Investments.xls"), sheet_name='13', header=4, nrows=8, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
mangystau_all_2022 = pd.read_excel(Path("../Data/Investments/Mangystau/2022_Investments.xlsx"), sheet_name='12', header=3, nrows=8, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
mangystau_all_2023 = pd.read_excel(Path("../Data/Investments/Mangystau/2023_Investments.xlsx"), sheet_name='19', header=3, nrows=8, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
mangystau_all_2024 = pd.read_excel(Path("../Data/Investments/Mangystau/2024_Investments.xlsx"), sheet_name='14', header=3, nrows=8, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

mangystau_non_2016 = pd.read_excel(Path("../Data/Investments/Mangystau/2016_Investments/Greenfield_investments.xls"), header=6, nrows=8, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
mangystau_non_2017 = pd.read_excel(Path("../Data/Investments/Mangystau/2017_Investments/Greenfield_investments.xls"), header=4, nrows=8, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
mangystau_non_2018 = pd.read_excel(Path("../Data/Investments/Mangystau/2018_Investments/Greenfield_investments.xls"), header=4, nrows=8, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
mangystau_non_2019 = pd.read_excel(Path("../Data/Investments/Mangystau/2019_Investments.xls"), sheet_name='15', header=4, nrows=8, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
mangystau_non_2020 = pd.read_excel(Path("../Data/Investments/Mangystau/2020_Investments.xls"), sheet_name='14', header=4, nrows=8, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
mangystau_non_2021 = pd.read_excel(Path("../Data/Investments/Mangystau/2021_Investments.xls"), sheet_name='14', header=4, nrows=8, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
mangystau_non_2022 = pd.read_excel(Path("../Data/Investments/Mangystau/2022_Investments.xlsx"), sheet_name='13', header=3, nrows=10, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
mangystau_non_2023 = pd.read_excel(Path("../Data/Investments/Mangystau/2023_Investments.xlsx"), sheet_name='20', header=3, nrows=10, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
mangystau_non_2024 = pd.read_excel(Path("../Data/Investments/Mangystau/2024_Investments.xlsx"), sheet_name='15', header=3, nrows=8, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [382]:
dfs = [mangystau_all_2014, mangystau_all_2015, mangystau_all_2016, mangystau_all_2017, mangystau_all_2018, mangystau_all_2019, mangystau_all_2020,
       mangystau_all_2021, mangystau_all_2022, mangystau_all_2023, mangystau_all_2024,
       mangystau_non_2016, mangystau_non_2017, mangystau_non_2018, mangystau_non_2019, mangystau_non_2020,
      mangystau_non_2021, mangystau_non_2022, mangystau_non_2023, mangystau_non_2024]

lists = []

for df in dfs:
    lists.extend(df.iloc[:, 0].unique())

unique_lists = pd.Series(lists).unique()
unique_lists

array(['Ақтау қ.ә.', 'Жаңаөзен қ.ә.', 'Бейнеу ауданы', 'Қарақия ауданы',
       'Маңғыстау ауданы', 'Мұнайлы ауданы', 'Түпқараған ауданы',
       'Ақтау қалалық әкімшілігі', 'Жаңаөзен қалалық әкімшілігі',
       'г.Актау', 'г.Жанаозен', 'Бейнеуский район', 'Каракиянский район',
       'Мангистауский район', 'Мунайлинский район',
       'Тупкараганский район', 'Актау городская администрация',
       'Жанаозен городская администрация'], dtype=object)

In [383]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [mangystau_all_2014, mangystau_all_2015, mangystau_all_2016, mangystau_all_2017,
          mangystau_all_2018, mangystau_all_2019, mangystau_all_2020, mangystau_all_2021,
          mangystau_all_2022, mangystau_all_2023, mangystau_all_2024]:
    df.columns = all_columns

for df in [mangystau_non_2016, mangystau_non_2017,
          mangystau_non_2018, mangystau_non_2019, mangystau_non_2020, mangystau_non_2021,
          mangystau_non_2022, mangystau_non_2023, mangystau_non_2024]:
    df.columns = non_columns
    
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

In [384]:
rayon_map_mangystau = {

    # ---- Cities ----
    'Ақтау қ.ә.': 'Aktau city',
    'Ақтау қалалық әкімшілігі': 'Aktau city',
    'г.Актау': 'Aktau city',
    'Актау городская администрация': 'Aktau city',
    'Актау г. а.': 'Aktau city',

    'Жаңаөзен қ.ә.': 'Zhanaozen city',
    'Жаңаөзен қалалық әкімшілігі': 'Zhanaozen city',
    'г.Жанаозен': 'Zhanaozen city',
    'Жанаозен городская администрация': 'Zhanaozen city',
    'Жанаозен г. а.': 'Zhanaozen city',

    # ---- Rayons ----
    'Бейнеу ауданы': 'Beineu',
    'Бейнеуский район': 'Beineu',
    'Бейнеуский район': 'Beineu',

    'Қарақия ауданы': 'Karakiyan',
    'Каракиянский район': 'Karakiyan',
    'Каракиянский район': 'Karakiyan',

    'Маңғыстау ауданы': 'Mangystau',
    'Мангистауский район': 'Mangystau',
    'Мангистауская область': 'Mangystau',
    'Мангистауский район': 'Mangystau',

    'Мұнайлы ауданы': 'Munaily',
    'Мунайлинский район': 'Munaily',
    'Мунайлинский район': 'Munaily',

    'Түпқараған ауданы': 'Tupkaragan',
    'Тупкараганский район': 'Tupkaragan',
    'Тупкараганский район': 'Tupkaragan',
}

In [385]:
# ----- ALL investments -----
mangystau_all_2014['rayon'] = mangystau_all_2014['rayon'].replace(rayon_map_mangystau)
mangystau_all_2015['rayon'] = mangystau_all_2015['rayon'].replace(rayon_map_mangystau)
mangystau_all_2016['rayon'] = mangystau_all_2016['rayon'].replace(rayon_map_mangystau)
mangystau_all_2017['rayon'] = mangystau_all_2017['rayon'].replace(rayon_map_mangystau)
mangystau_all_2018['rayon'] = mangystau_all_2018['rayon'].replace(rayon_map_mangystau)
mangystau_all_2019['rayon'] = mangystau_all_2019['rayon'].replace(rayon_map_mangystau)
mangystau_all_2020['rayon'] = mangystau_all_2020['rayon'].replace(rayon_map_mangystau)
mangystau_all_2021['rayon'] = mangystau_all_2021['rayon'].replace(rayon_map_mangystau)
mangystau_all_2022['rayon'] = mangystau_all_2022['rayon'].replace(rayon_map_mangystau)
mangystau_all_2023['rayon'] = mangystau_all_2023['rayon'].replace(rayon_map_mangystau)
mangystau_all_2024['rayon'] = mangystau_all_2024['rayon'].replace(rayon_map_mangystau)

# ----- NON-extractive investments -----
mangystau_non_2016['rayon'] = mangystau_non_2016['rayon'].replace(rayon_map_mangystau)
mangystau_non_2017['rayon'] = mangystau_non_2017['rayon'].replace(rayon_map_mangystau)
mangystau_non_2018['rayon'] = mangystau_non_2018['rayon'].replace(rayon_map_mangystau)
mangystau_non_2019['rayon'] = mangystau_non_2019['rayon'].replace(rayon_map_mangystau)
mangystau_non_2020['rayon'] = mangystau_non_2020['rayon'].replace(rayon_map_mangystau)
mangystau_non_2021['rayon'] = mangystau_non_2021['rayon'].replace(rayon_map_mangystau)
mangystau_non_2022['rayon'] = mangystau_non_2022['rayon'].replace(rayon_map_mangystau)
mangystau_non_2023['rayon'] = mangystau_non_2023['rayon'].replace(rayon_map_mangystau)
mangystau_non_2024['rayon'] = mangystau_non_2024['rayon'].replace(rayon_map_mangystau)

In [386]:
mangystau_2014 = mangystau_all_2014
mangystau_2015 = mangystau_all_2015
mangystau_2016 = mangystau_all_2016.merge(mangystau_non_2016, on='rayon', how='left')
mangystau_2017 = mangystau_all_2017.merge(mangystau_non_2017, on='rayon', how='left')
mangystau_2018 = mangystau_all_2018.merge(mangystau_non_2018, on='rayon', how='left')
mangystau_2019 = mangystau_all_2019.merge(mangystau_non_2019, on='rayon', how='left')
mangystau_2020 = mangystau_all_2020.merge(mangystau_non_2020, on='rayon', how='left')
mangystau_2021 = mangystau_all_2021.merge(mangystau_non_2021, on='rayon', how='left')
mangystau_2022 = mangystau_all_2022.merge(mangystau_non_2022, on='rayon', how='left')
mangystau_2023 = mangystau_all_2023.merge(mangystau_non_2023, on='rayon', how='left')
mangystau_2024 = mangystau_all_2024.merge(mangystau_non_2024, on='rayon', how='left')

dfs = [mangystau_2014, mangystau_2015, mangystau_2016, mangystau_2017, mangystau_2018, mangystau_2019, mangystau_2020, mangystau_2021, mangystau_2022, mangystau_2023, mangystau_2024]

for i in range(11):
    df = dfs[i]
    df['oblast'] = 'Mangystau'
    df['year'] = 2014 + i

mangystau_inv = pd.concat([mangystau_2014, mangystau_2015, mangystau_2016, mangystau_2017, mangystau_2018, mangystau_2019, mangystau_2020, mangystau_2021, mangystau_2022, mangystau_2023, mangystau_2024], ignore_index=True)
mangystau_inv['rayon'] = (
    mangystau_inv['rayon']
        .str.strip()          # remove hidden spaces
        .replace(rayon_map)   # enforce English names
)
mangystau_inv

,rayon,l_all_inv,f_all_inv,oblast,year,f_nonextr_inv,l_nonextr_inv
0,Aktau city,70722105,23099914.0,Mangystau,2014,NaN,NaN
1,Zhanaozen city,25748380,503747.0,Mangystau,2014,NaN,NaN
2,Beineu,54056184,646663.0,Mangystau,2014,NaN,NaN
3,Karakiyan,141781033,3201150.0,Mangystau,2014,NaN,NaN
4,Mangystau,46543595,20580195.0,Mangystau,2014,NaN,NaN
...,...,...,...,...,...,...,...
72,Beineu,52019002,9446725.0,Mangystau,2024,1989429.0,33033139.0
73,Karakiyan,333584851,13969368.0,Mangystau,2024,13760512.0,108960308.0
74,Mangystau,89894196,11494319.0,Mangystau,2024,3586508.0,17984227.0
75,Munaily,53716354,8675918.0,Mangystau,2024,6304729.0,22336378.0
76,Tupkaragan,27040664,90779383.0,Mangystau,2024,722115.0,12891733.0

In [387]:
mangystau_inv['rayon'].unique()

array(['Aktau city', 'Zhanaozen city', 'Beineu', 'Karakiyan', 'Mangystau',
       'Munaily', 'Tupkaragan'], dtype=object)

## Employment

In [388]:
mangystau_empl = pd.read_excel(Path("../Data/Employment/Mangystau.xls"), skiprows=18, nrows=7, header=None, usecols='A:L', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
mangystau_empl.columns = ['rayon', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
mangystau_empl['rayon'] = mangystau_empl['rayon'].replace(rayon_map_mangystau)
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    mangystau_empl[i] = mangystau_empl[i].astype(float)
    mangystau_employment = mangystau_empl.melt(id_vars='rayon', value_vars=[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024], var_name='year', value_name='employment')
mangystau_employment

             rayon  year  employment
0       Aktau city  2014       100.3
1   Zhanaozen city  2014        52.2
2           Beineu  2014        20.2
3        Karakiyan  2014        10.4
4        Mangystau  2014        12.8
..             ...   ...         ...
72          Beineu  2024        26.8
73       Karakiyan  2024        14.3
74       Mangystau  2024        15.5
75         Munaily  2024        74.8
76      Tupkaragan  2024        17.5

[77 rows x 3 columns]

In [389]:
mangystau_employment['rayon'].unique()

array(['Aktau city', 'Zhanaozen city', 'Beineu', 'Karakiyan', 'Mangystau',
       'Munaily', 'Tupkaragan'], dtype=object)

## Other Controls

In [390]:
aktau_city = pd.read_excel(Path("../Data/Controls/Mangystau_All.xlsx"), sheet_name="г.а.Актау", header=2, usecols='B, Z:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
aktau_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
aktau_city = aktau_city.loc[[74, 53, 109]].reset_index(drop=True)
aktau_city['Indicator'] = ['production', 'agriculture', 'retail']
aktau_city
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    aktau_city[i] = aktau_city[i].astype(str)
    aktau_city[i] = aktau_city[i].str.replace(',', '.')
    aktau_city[i] = aktau_city[i].str.replace(')', '')
    aktau_city[i] = aktau_city[i].str.replace(' ', '')
    aktau_city[i] = aktau_city[i].str.replace('\xa0', '')
    aktau_city[i] = aktau_city[i].str.replace('*', '')
    aktau_city[i] = aktau_city[i].astype(float)
aktau_city = pd.melt(aktau_city, id_vars=['Indicator'], var_name='year', value_name='value')
aktau_city = aktau_city.pivot(index='year', columns='Indicator', values='value').reset_index()
aktau_city.insert(0, 'rayon', 'Aktau city')
aktau_city.columns.name = None
aktau_city

        rayon  year  agriculture  production    retail
0  Aktau city  2014        302.0    137878.0  127922.6
1  Aktau city  2015        405.1    143037.0  123444.2
2  Aktau city  2016        311.2    184741.0  174583.0
3  Aktau city  2017       1729.8    209461.0  126268.9
4  Aktau city  2018        810.8    202937.0  153906.0
5  Aktau city  2019       1132.0    210815.0  180049.4
6  Aktau city  2020        642.0    214044.0  229000.0
7  Aktau city  2021        678.2    221383.1  254244.9
8  Aktau city  2022        730.3    250140.8  324421.8
9  Aktau city  2023        739.0    315056.5  419159.9

In [391]:
zhanaozen_city = pd.read_excel(Path("../Data/Controls/Mangystau_All.xlsx"), sheet_name="г.а. Жанаозен", header=2, usecols='B, Z:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
zhanaozen_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
zhanaozen_city = zhanaozen_city.loc[[74, 53, 109]].reset_index(drop=True)
zhanaozen_city['Indicator'] = ['production', 'agriculture', 'retail']
zhanaozen_city
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    zhanaozen_city[i] = zhanaozen_city[i].astype(str)
    zhanaozen_city[i] = zhanaozen_city[i].str.replace(',', '.')
    zhanaozen_city[i] = zhanaozen_city[i].str.replace(')', '')
    zhanaozen_city[i] = zhanaozen_city[i].str.replace(' ', '')
    zhanaozen_city[i] = zhanaozen_city[i].str.replace('\xa0', '')
    zhanaozen_city[i] = zhanaozen_city[i].str.replace('*', '')
    zhanaozen_city[i] = zhanaozen_city[i].astype(float)
zhanaozen_city = pd.melt(zhanaozen_city, id_vars=['Indicator'], var_name='year', value_name='value')
zhanaozen_city = zhanaozen_city.pivot(index='year', columns='Indicator', values='value').reset_index()
zhanaozen_city.insert(0, 'rayon', 'Zhanaozen city')
zhanaozen_city.columns.name = None
zhanaozen_city

            rayon  year  agriculture  production   retail
0  Zhanaozen city  2014        517.2    145837.0   2044.3
1  Zhanaozen city  2015        697.7    123019.0   4076.8
2  Zhanaozen city  2016        605.2    120258.0   3940.4
3  Zhanaozen city  2017        460.6    161566.0  47283.5
4  Zhanaozen city  2018        556.1    192277.0  14506.8
5  Zhanaozen city  2019        719.3    194891.0  15713.7
6  Zhanaozen city  2020        722.6    156092.0  18169.7
7  Zhanaozen city  2021        836.2    182060.0  46350.0
8  Zhanaozen city  2022       1105.5    222226.0  24439.9
9  Zhanaozen city  2023       1122.5    206740.0  30960.0

In [392]:
beineu = pd.read_excel(Path("../Data/Controls/Mangystau_All.xlsx"), sheet_name="Бейнеуский район", header=2, usecols='B, Z:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
beineu.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
beineu = beineu.loc[[74, 53, 109]].reset_index(drop=True)
beineu['Indicator'] = ['production', 'agriculture', 'retail']
beineu
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    beineu[i] = beineu[i].astype(str)
    beineu[i] = beineu[i].str.replace(',', '.')
    beineu[i] = beineu[i].str.replace(')', '')
    beineu[i] = beineu[i].str.replace(' ', '')
    beineu[i] = beineu[i].str.replace('\xa0', '')
    beineu[i] = beineu[i].str.replace('*', '')
    beineu[i] = beineu[i].astype(float)
beineu = pd.melt(beineu, id_vars=['Indicator'], var_name='year', value_name='value')
beineu = beineu.pivot(index='year', columns='Indicator', values='value').reset_index()
beineu.insert(0, 'rayon', 'Beineu')
beineu.columns.name = None
beineu

    rayon  year  agriculture  production   retail
0  Beineu  2014       1598.5     67224.0   3821.0
1  Beineu  2015       2167.7     47054.0  10145.3
2  Beineu  2016       2565.4     59053.0  13613.8
3  Beineu  2017       2838.9     51732.0  11016.0
4  Beineu  2018       3166.9     77676.0  17714.8
5  Beineu  2019       3911.9     81697.0  13930.9
6  Beineu  2020       3827.5    165809.0   8149.5
7  Beineu  2021       4014.1     85874.0  10894.7
8  Beineu  2022       4700.9     80176.0  14785.9
9  Beineu  2023       4741.8     71217.5  12692.6

In [393]:
karakiyan = pd.read_excel(Path("../Data/Controls/Mangystau_All.xlsx"), sheet_name="Каракиянский район", header=2, usecols='B, Z:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
karakiyan.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
karakiyan = karakiyan.loc[[74, 53, 109]].reset_index(drop=True)
karakiyan['Indicator'] = ['production', 'agriculture', 'retail']
karakiyan
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    karakiyan[i] = karakiyan[i].astype(str)
    karakiyan[i] = karakiyan[i].str.replace(',', '.')
    karakiyan[i] = karakiyan[i].str.replace(')', '')
    karakiyan[i] = karakiyan[i].str.replace(' ', '')
    karakiyan[i] = karakiyan[i].str.replace('\xa0', '')
    karakiyan[i] = karakiyan[i].str.replace('*', '')
    karakiyan[i] = karakiyan[i].astype(float)
karakiyan = pd.melt(karakiyan, id_vars=['Indicator'], var_name='year', value_name='value')
karakiyan = karakiyan.pivot(index='year', columns='Indicator', values='value').reset_index()
karakiyan.insert(0, 'rayon', 'Karakiyan')
karakiyan.columns.name = None
karakiyan

       rayon  year  agriculture  production  retail
0  Karakiyan  2014       1493.1    801851.0   324.7
1  Karakiyan  2015       1978.8    520988.0   544.8
2  Karakiyan  2016       1946.0    615141.0  1313.8
3  Karakiyan  2017       2201.6    837441.0  1325.0
4  Karakiyan  2018       2882.2   1071355.0  2177.8
5  Karakiyan  2019       3233.4   1085787.0  2483.8
6  Karakiyan  2020       3502.8    747426.0  1718.0
7  Karakiyan  2021       3487.4   1181322.0  1518.1
8  Karakiyan  2022       4399.0   1516169.6  3497.3
9  Karakiyan  2023       4994.7   1345407.0  5234.3

In [394]:
mangystau = pd.read_excel(Path("../Data/Controls/Mangystau_All.xlsx"), sheet_name="Мангистауский район", header=2, usecols='B, Z:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
mangystau.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
mangystau = mangystau.loc[[74, 53, 109]].reset_index(drop=True)
mangystau['Indicator'] = ['production', 'agriculture', 'retail']
mangystau
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    mangystau[i] = mangystau[i].astype(str)
    mangystau[i] = mangystau[i].str.replace(',', '.')
    mangystau[i] = mangystau[i].str.replace(')', '')
    mangystau[i] = mangystau[i].str.replace(' ', '')
    mangystau[i] = mangystau[i].str.replace('\xa0', '')
    mangystau[i] = mangystau[i].str.replace('*', '')
    mangystau[i] = mangystau[i].astype(float)
mangystau = pd.melt(mangystau, id_vars=['Indicator'], var_name='year', value_name='value')
mangystau = mangystau.pivot(index='year', columns='Indicator', values='value').reset_index()
mangystau.insert(0, 'rayon', 'Mangystau')
mangystau.columns.name = None
mangystau

       rayon  year  agriculture  production   retail
0  Mangystau  2014       2751.7    590549.0   4305.0
1  Mangystau  2015       3679.8    353115.0   2084.1
2  Mangystau  2016       4264.7    400209.0   2928.3
3  Mangystau  2017       4603.9    481209.0  16368.9
4  Mangystau  2018       5506.7    581077.0  14057.6
5  Mangystau  2019       6804.4    572046.0  11001.9
6  Mangystau  2020       6589.2    375780.0   1770.1
7  Mangystau  2021       6995.8    413282.0   3073.2
8  Mangystau  2022       8262.6    484135.4   3677.8
9  Mangystau  2023       8373.7    556321.5   5941.6

In [395]:
munaily = pd.read_excel(Path("../Data/Controls/Mangystau_All.xlsx"), sheet_name="Мунайлинский район", header=2, usecols='B, Q:Z', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
munaily.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
munaily = munaily.loc[[74, 53, 109]].reset_index(drop=True)
munaily['Indicator'] = ['production', 'agriculture', 'retail']
munaily
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    munaily[i] = munaily[i].astype(str)
    munaily[i] = munaily[i].str.replace(',', '.')
    munaily[i] = munaily[i].str.replace(')', '')
    munaily[i] = munaily[i].str.replace(' ', '')
    munaily[i] = munaily[i].str.replace('\xa0', '')
    munaily[i] = munaily[i].str.replace('*', '')
    munaily[i] = munaily[i].astype(float)
munaily = pd.melt(munaily, id_vars=['Indicator'], var_name='year', value_name='value')
munaily = munaily.pivot(index='year', columns='Indicator', values='value').reset_index()
munaily.insert(0, 'rayon', 'Munaily')
munaily.columns.name = None
munaily

     rayon  year  agriculture  production   retail
0  Munaily  2014        844.2     51763.0   6476.2
1  Munaily  2015       1272.7     51138.0   4718.6
2  Munaily  2016       1185.9     97933.0   3891.8
3  Munaily  2017       1039.3     53001.0  11980.3
4  Munaily  2018       1493.5     66530.0  23598.9
5  Munaily  2019       2212.7     57350.0  21544.6
6  Munaily  2020       2208.1     59072.0   5237.3
7  Munaily  2021       2516.5     65688.0  14611.1
8  Munaily  2022       4082.6     69536.0  17455.2
9  Munaily  2023       6338.8     69305.7  19923.2

In [396]:
tupkaragan = pd.read_excel(Path("../Data/Controls/Mangystau_All.xlsx"), sheet_name="Тупкараганский район", header=2, usecols='B, Z:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
tupkaragan.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
tupkaragan = tupkaragan.loc[[74, 53, 109]].reset_index(drop=True)
tupkaragan['Indicator'] = ['production', 'agriculture', 'retail']
tupkaragan
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    tupkaragan[i] = tupkaragan[i].astype(str)
    tupkaragan[i] = tupkaragan[i].str.replace(',', '.')
    tupkaragan[i] = tupkaragan[i].str.replace(')', '')
    tupkaragan[i] = tupkaragan[i].str.replace(' ', '')
    tupkaragan[i] = tupkaragan[i].str.replace('\xa0', '')
    tupkaragan[i] = tupkaragan[i].str.replace('*', '')
    tupkaragan[i] = tupkaragan[i].astype(float)
tupkaragan = pd.melt(tupkaragan, id_vars=['Indicator'], var_name='year', value_name='value')
tupkaragan = tupkaragan.pivot(index='year', columns='Indicator', values='value').reset_index()
tupkaragan.insert(0, 'rayon', 'Tupkaragan')
tupkaragan.columns.name = None
tupkaragan

        rayon  year  agriculture  production  retail
0  Tupkaragan  2014       1218.0    535047.0   345.3
1  Tupkaragan  2015       1532.5    330334.0  1663.4
2  Tupkaragan  2016       1587.7    440234.0  2080.8
3  Tupkaragan  2017       1555.7    521790.0  2923.6
4  Tupkaragan  2018       2211.4    700418.0  8704.6
5  Tupkaragan  2019       2622.6    706203.0  7894.9
6  Tupkaragan  2020       2700.8    438229.0  2911.7
7  Tupkaragan  2021       4264.0    577114.0  1891.6
8  Tupkaragan  2022       6658.1    559722.8  3101.2
9  Tupkaragan  2023       6404.9    501270.1  2861.2

In [397]:
mangystau_controls = pd.concat([aktau_city, zhanaozen_city, beineu, karakiyan, mangystau, munaily, tupkaragan], ignore_index=True)
mangystau_controls

         rayon  year  agriculture  production    retail
0   Aktau city  2014        302.0    137878.0  127922.6
1   Aktau city  2015        405.1    143037.0  123444.2
2   Aktau city  2016        311.2    184741.0  174583.0
3   Aktau city  2017       1729.8    209461.0  126268.9
4   Aktau city  2018        810.8    202937.0  153906.0
..         ...   ...          ...         ...       ...
65  Tupkaragan  2019       2622.6    706203.0    7894.9
66  Tupkaragan  2020       2700.8    438229.0    2911.7
67  Tupkaragan  2021       4264.0    577114.0    1891.6
68  Tupkaragan  2022       6658.1    559722.8    3101.2
69  Tupkaragan  2023       6404.9    501270.1    2861.2

[70 rows x 5 columns]

## PPI

In [398]:
mangystau_ppi = pd.read_excel(
    Path("../Data/PPI/Mangystau.xls"),
    header=2,
    usecols='Y:AH',
    nrows=65,
    na_values=['x', 'х', '-', '', ' ', '...']
)
mangystau_ppi.columns = [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
rayons = list(mangystau_inv['rayon'].unique())

dfs = []

for rayon in rayons:
    df_temp = pd.DataFrame({
        'rayon': [rayon] * len(range(2014, 2024)),
        'year': list(range(2014, 2024)),
        'ppi': mangystau_ppi.iloc[-1].values
    })
    dfs.append(df_temp)

mangystau_ppi = pd.concat(dfs, ignore_index=True)
mangystau_ppi['ppi'] = mangystau_ppi['ppi'].astype(str).str.replace(',', '.')
mangystau_ppi['ppi'] = mangystau_ppi['ppi'].astype(str).str.replace(')', '')
mangystau_ppi['ppi'] = mangystau_ppi['ppi'].astype(str).str.replace(' ', '')
mangystau_ppi['ppi'] = mangystau_ppi['ppi'].astype(str).str.replace('\xa0', '')
mangystau_ppi['ppi'] = mangystau_ppi['ppi'].astype(str).str.replace('*', '')
mangystau_ppi['ppi'] = mangystau_ppi['ppi'].astype(float)

mangystau_ppi

         rayon  year    ppi
0   Aktau city  2014   89.5
1   Aktau city  2015   89.1
2   Aktau city  2016  118.8
3   Aktau city  2017  125.6
4   Aktau city  2018  112.2
..         ...   ...    ...
65  Tupkaragan  2019  103.3
66  Tupkaragan  2020  111.8
67  Tupkaragan  2021  155.0
68  Tupkaragan  2022   95.8
69  Tupkaragan  2023  117.2

[70 rows x 3 columns]

## Combine

In [399]:
dfs_mangystau = [mangystau_inv, mangystau_employment, mangystau_controls, mangystau_ppi]
mangystau_merged = reduce(lambda left, right: pd.merge(left, right, on=['rayon', 'year'], how='outer'), dfs_mangystau)
mangystau_merged

,rayon,l_all_inv,f_all_inv,oblast,year,f_nonextr_inv,l_nonextr_inv,employment,agriculture,production,retail,ppi
0,Aktau city,70722105,23099914.0,Mangystau,2014,NaN,NaN,100.3,302.0,137878.0,127922.6,89.5
1,Aktau city,101670181,27233265.0,Mangystau,2015,NaN,NaN,98.0,405.1,143037.0,123444.2,89.1
2,Aktau city,77875569,17056060.0,Mangystau,2016,9779214.0,65099707.0,93.5,311.2,184741.0,174583.0,118.8
3,Aktau city,74691639,12030563.0,Mangystau,2017,8526094.0,65652411.0,87.0,1729.8,209461.0,126268.9,125.6
4,Aktau city,132102390,17454026.0,Mangystau,2018,14408729.0,114517207.0,89.4,810.8,202937.0,153906.0,112.2
...,...,...,...,...,...,...,...,...,...,...,...,...
72,Zhanaozen city,47012821,740.0,Mangystau,2020,740.0,15248839.0,78.7,722.6,156092.0,18169.7,111.8
73,Zhanaozen city,56381041,0.0,Mangystau,2021,0.0,27196988.0,79.6,836.2,182060.0,46350.0,155.0
74,Zhanaozen city,76717477,0.0,Mangystau,2022,0.0,35389806.0,70.8,1105.5,222226.0,24439.9,95.8
75,Zhanaozen city,231350685,0.0,Mangystau,2023,0.0,171637402.0,74.3,1122.5,206740.0,30960.0,117.2
76,Zhanaozen city,111688919,20580769.0,Mangystau,2024,20371225.0,30349463.0,74.2,NaN,NaN,NaN,NaN

# North-Kazakhstan

## Investments

In [400]:
# north_all_2015 
north_all_2015 = camelot.read_pdf(Path("../Data/Investments/North-Kazakhstan/2015_Investments.pdf"), pages='19', flavor='stream')[0].df
north_all_2015 = north_all_2015.iloc[6:, [0, 3, 5]].reset_index(drop=True)
for col in [3, 5]:
    north_all_2015[col] = (
        north_all_2015[col]
        .astype(str)
        .str.replace(' ', '', regex=False)
        .astype(int)
    )
# north_all_2016
north_all_2016 = camelot.read_pdf(Path("../Data/Investments/North-Kazakhstan/2016_Investments.pdf"), pages='20', flavor='stream')[0].df
north_all_2016 = north_all_2016.iloc[6:, [0, 3, 5]].reset_index(drop=True)
for col in [3, 5]:
    north_all_2016[col] = (
        north_all_2016[col]
        .astype(str)
        .str.replace(' ', '', regex=False)
        .astype(int)
    )
# north_all_2017
north_all_2017 = camelot.read_pdf(Path("../Data/Investments/North-Kazakhstan/2017_Investments.pdf"), pages='23', flavor='stream')[0].df
north_all_2017 = north_all_2017.iloc[6:, [0, 3, 5]].reset_index(drop=True)
for col in [3, 5]:
    north_all_2017[col] = (
        north_all_2017[col]
        .astype(str)
        .str.replace(' ', '', regex=False)
        .astype(int)
    )
# north_all_2018
north_all_2018 = camelot.read_pdf(Path("../Data/Investments/North-Kazakhstan/2018_Investments.pdf"), pages='29', flavor='stream', table_areas=['0,800,800,0']  # adjust if needed 
                                 )[0].df
df = north_all_2018.copy()
df['col_new_even'] = pd.NA
even_rows = df.index[df.index % 2 == 0]
shifted_indices = even_rows + 1
shifted_indices = shifted_indices[shifted_indices < len(df)]  # keep only valid indices
df.loc[shifted_indices, 'col_new_even'] = df.loc[even_rows[:len(shifted_indices)], 0].values
df = df[df.index % 2 == 1].reset_index(drop=True)
df = df[['col_new_even', df.columns[1], df.columns[4]]]
df = df.iloc[10:].reset_index(drop=True)
for col in [1, 4]:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(' ', '', regex=False)
        .astype(int)
    )
north_all_2018 = df

# EXCEL
north_all_2019 = pd.read_excel(Path("../Data/Investments/North-Kazakhstan/2019_Investments.xls"), sheet_name='14', header=3, nrows=15, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
north_all_2020 = pd.read_excel(Path("../Data/Investments/North-Kazakhstan/2020_Investments.xls"), sheet_name='13', header=3, nrows=15, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
north_all_2021 = pd.read_excel(Path("../Data/Investments/North-Kazakhstan/2021_Investments.xls"), sheet_name='13', header=3, nrows=15, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
north_all_2022 = pd.read_excel(Path("../Data/Investments/North-Kazakhstan/2022_Investments.xls"), sheet_name='13', header=3, nrows=15, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
north_all_2023 = pd.read_excel(Path("../Data/Investments/North-Kazakhstan/2023_Investments.xlsx"), sheet_name='20', header=3, nrows=15, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
north_all_2024 = pd.read_excel(Path("../Data/Investments/North-Kazakhstan/2024_Investments.xls"), sheet_name='14', header=3, nrows=15, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [401]:
# north_all_2016
north_non_2016 = camelot.read_pdf(Path("../Data/Investments/North-Kazakhstan/2016_Investments.pdf"), pages='21', flavor='stream')[0].df
north_non_2016 = north_non_2016.iloc[4:, [0, 2, 6]].reset_index(drop=True)
for col in [2, 6]:
    north_non_2016[col] = (
        north_non_2016[col]
        .astype(str)
        .str.replace(' ', '', regex=False)
        .astype(int)
    )
# north_all_2017
north_non_2017 = camelot.read_pdf(Path("../Data/Investments/North-Kazakhstan/2017_Investments.pdf"), pages='24', flavor='stream')[0].df
north_non_2017 = north_non_2017.iloc[4:, [0, 2, 6]].reset_index(drop=True)
for col in [2, 6]:
    north_non_2017[col] = (
        north_non_2017[col]
        .astype(str)
        .str.replace(' ', '', regex=False)
        .astype(int)
    )

# north_all_2018
north_non_2018 = camelot.read_pdf(Path("../Data/Investments/North-Kazakhstan/2018_Investments.pdf"), pages='30', flavor='stream')[0].df
dfs = north_non_2018.copy()
# Shift column 0 down by 1 row
dfs[0] = dfs[0].shift(1)
# Drop rows where column 0 is empty (NaN)
dfs = dfs.dropna(subset=[0]).reset_index(drop=True)
# Keep only odd rows
dfs = dfs[dfs.index % 2 == 1]
# Drop the first 2 rows
dfs = dfs.iloc[2:].reset_index(drop=True)
dfs = dfs[[dfs.columns[0], dfs.columns[1], dfs.columns[5]]]
north_non_2018 = dfs

north_non_2019 = pd.read_excel(Path("../Data/Investments/North-Kazakhstan/2019_Investments.xls"), sheet_name='15', header=3, nrows=15, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
north_non_2020 = pd.read_excel(Path("../Data/Investments/North-Kazakhstan/2020_Investments.xls"), sheet_name='14', header=3, nrows=15, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
north_non_2021 = pd.read_excel(Path("../Data/Investments/North-Kazakhstan/2021_Investments.xls"), sheet_name='14', header=3, nrows=15, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
north_non_2022 = pd.read_excel(Path("../Data/Investments/North-Kazakhstan/2022_Investments.xls"), sheet_name='14', header=3, nrows=15, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
north_non_2023 = pd.read_excel(Path("../Data/Investments/North-Kazakhstan/2023_Investments.xlsx"), sheet_name='21', header=3, nrows=15, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
north_non_2024 = pd.read_excel(Path("../Data/Investments/North-Kazakhstan/2024_Investments.xls"), sheet_name='15', header=3, nrows=15, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [402]:
dfs = [north_all_2015, north_all_2016, north_all_2017, north_all_2018, north_all_2019, north_all_2020,
       north_all_2021, north_all_2022, north_all_2023, north_all_2024,
       north_non_2016, north_non_2017, north_non_2018, north_non_2019, north_non_2020,
      north_non_2021, north_non_2022, north_non_2023, north_non_2024]

lists = []

for df in dfs:
    lists.extend(df.iloc[:, 0].unique())

unique_lists = pd.Series(lists).unique()
unique_lists

array(['Петропавл қ.', 'Айыртау ауданы', 'Ақжар ауданы',
       'Мағжан Жұмабаев ауданы', 'Есіл ауданы', 'Жамбыл ауданы',
       'Қызылжар ауданы', 'Мамлют ауданы', 'Шал ақын ауданы',
       'Аққайың ауданы', 'Тайынша ауданы', 'Тимирязев ауданы',
       'Уәлиханов ауданы', 'Ғабит Мүсірепов ауданы', 'Петропавл қаласы',
       'г.Петропавловск', 'Айыртауский район', 'Акжарский район',
       'район Магжана Жумабаева', 'Есильский район', 'Жамбылский район',
       'Кызылжарский район', 'Мамлютский район', 'район Шал акына',
       'Аккайынский район', 'Тайыншинский район', 'Тимирязевский район',
       'Уалихановский район', 'район им.Габита Мусрепова',
       'район им. Габита Мусрепова', 'Шал Ақын ауданы'], dtype=object)

In [403]:
rayon_map_north = {

    # ---- Cities ----
    'Петропавл қ.': 'Petropavl city',
    'Петропавл қаласы': 'Petropavl city',
    'г.Петропавловск': 'Petropavl city',
    'Петропавловск': 'Petropavl city',
    'г.Петропавловск': 'Petropavl city',

    # ---- Rayons ----
    'Айыртау ауданы': 'Aiyrtau',
    'Айыртауский район': 'Aiyrtau',
    'Айыртауский':	'Aiyrtau',

    'Ақжар ауданы': 'Akzhar',
    'Акжарский район': 'Akzhar',
    'Акжарский': 'Akzhar',

    'Мағжан Жұмабаев ауданы': 'Magzhan Zhumabayev',
    'район Магжана Жумабаева': 'Magzhan Zhumabayev',
    'М.Жумабаева': 'Magzhan Zhumabayev',

    'Есіл ауданы': 'Esil',
    'Есильский район': 'Esil',
    'Есильский': 'Esil',

    'Жамбыл ауданы': 'Zhambyl',
    'Жамбылский район': 'Zhambyl',
    'Жамбылский': 'Zhambyl',

    'Қызылжар ауданы': 'Kyzylzhar',
    'Кызылжарский район': 'Kyzylzhar',
    'Кызылжарский': 'Kyzylzhar',

    'Мамлют ауданы': 'Mamlyut',
    'Мамлютский район': 'Mamlyut',
    'Мамлютский': 'Mamlyut',

    'Шал ақын ауданы': 'Shal Akyn',
    'Шал Ақын ауданы': 'Shal Akyn',
    'район Шал акына': 'Shal Akyn',
    'Шал акына': 'Shal Akyn',

    'Аққайың ауданы': 'Akkayin',
    'Аккайынский район': 'Akkayin',
    'Аккайынский': 'Akkayin',

    'Тайынша ауданы': 'Taiynsha',
    'Тайыншинский район': 'Taiynsha',
    'Тайыншинский': 'Taiynsha',

    'Тимирязев ауданы': 'Timiryazev',
    'Тимирязевский район': 'Timiryazev',
    'Тимирязевский': 'Timiryazev',

    'Уәлиханов ауданы': 'Ualikhanov',
    'Уалихановский район': 'Ualikhanov',
    'Уалихановкий': 'Ualikhanov',

    'Ғабит Мүсірепов ауданы': 'Gabit Musrepov',
    'район им.Габита Мусрепова': 'Gabit Musrepov',
    'район им. Габита Мусрепова': 'Gabit Musrepov',
    'Г.Мусрепова': 'Gabit Musrepov',
}

In [404]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [north_all_2015, north_all_2016, north_all_2017,
          north_all_2018, north_all_2019, north_all_2020, north_all_2021,
          north_all_2022, north_all_2023, north_all_2024]:
    df.columns = all_columns

for df in [north_non_2016, north_non_2017,
          north_non_2018, north_non_2019, north_non_2020, north_non_2021,
          north_non_2022, north_non_2023, north_non_2024]:
    df.columns = non_columns

    df[['all_nonextr_inv', 'f_nonextr_inv']] = (
        df[['all_nonextr_inv', 'f_nonextr_inv']]
        .astype(str)
        .apply(lambda x: x.str.replace(' ', ''))
        .astype(float)
    )

    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

In [405]:
north_non_2016

                     rayon  f_nonextr_inv  l_nonextr_inv
0             Петропавл қ.      4188749.0     51063340.0
1           Айыртау ауданы         6147.0      2918648.0
2             Ақжар ауданы         2031.0      1004803.0
3   Мағжан Жұмабаев ауданы         8102.0      4117097.0
4              Есіл ауданы         2600.0       703411.0
5            Жамбыл ауданы         1152.0      1488373.0
6          Қызылжар ауданы        13017.0      7786860.0
7            Мамлют ауданы        25354.0       243339.0
8          Шал ақын ауданы         2119.0       105989.0
9           Аққайың ауданы       477031.0      6233971.0
10          Тайынша ауданы      2768875.0      8727874.0
11        Тимирязев ауданы        30095.0       303027.0
12        Уәлиханов ауданы        19710.0      1147928.0
13  Ғабит Мүсірепов ауданы       131374.0     12353394.0

In [406]:
# ----- ALL investments -----
north_all_2015['rayon'] = north_all_2015['rayon'].replace(rayon_map_north)
north_all_2016['rayon'] = north_all_2016['rayon'].replace(rayon_map_north)
north_all_2017['rayon'] = north_all_2017['rayon'].replace(rayon_map_north)
north_all_2018['rayon'] = north_all_2018['rayon'].replace(rayon_map_north)
north_all_2019['rayon'] = north_all_2019['rayon'].replace(rayon_map_north)
north_all_2020['rayon'] = north_all_2020['rayon'].replace(rayon_map_north)
north_all_2021['rayon'] = north_all_2021['rayon'].replace(rayon_map_north)
north_all_2022['rayon'] = north_all_2022['rayon'].replace(rayon_map_north)
north_all_2023['rayon'] = north_all_2023['rayon'].replace(rayon_map_north)
north_all_2024['rayon'] = north_all_2024['rayon'].replace(rayon_map_north)

# ----- NON-extractive investments -----
north_non_2016['rayon'] = north_non_2016['rayon'].replace(rayon_map_north)
north_non_2017['rayon'] = north_non_2017['rayon'].replace(rayon_map_north)
north_non_2018['rayon'] = north_non_2018['rayon'].replace(rayon_map_north)
north_non_2019['rayon'] = north_non_2019['rayon'].replace(rayon_map_north)
north_non_2020['rayon'] = north_non_2020['rayon'].replace(rayon_map_north)
north_non_2021['rayon'] = north_non_2021['rayon'].replace(rayon_map_north)
north_non_2022['rayon'] = north_non_2022['rayon'].replace(rayon_map_north)
north_non_2023['rayon'] = north_non_2023['rayon'].replace(rayon_map_north)
north_non_2024['rayon'] = north_non_2024['rayon'].replace(rayon_map_north)

In [407]:
north_2015 = north_all_2015
north_2016 = north_all_2016.merge(north_non_2016, on='rayon', how='left')
north_2017 = north_all_2017.merge(north_non_2017, on='rayon', how='left')
north_2018 = north_all_2018.merge(north_non_2018, on='rayon', how='left')
north_2019 = north_all_2019.merge(north_non_2019, on='rayon', how='left')
north_2020 = north_all_2020.merge(north_non_2020, on='rayon', how='left')
north_2021 = north_all_2021.merge(north_non_2021, on='rayon', how='left')
north_2022 = north_all_2022.merge(north_non_2022, on='rayon', how='left')
north_2023 = north_all_2023.merge(north_non_2023, on='rayon', how='left')
north_2024 = north_all_2024.merge(north_non_2024, on='rayon', how='left')

dfs = [north_2015, north_2016, north_2017, north_2018, north_2019, north_2020, north_2021, north_2022, north_2023, north_2024]

for i in range(10):
    df = dfs[i]
    df['oblast'] = 'North-Kazakhstan'
    df['year'] = 2015 + i

north_inv = pd.concat([north_2015, north_2016, north_2017, north_2018, north_2019, north_2020, north_2021, north_2022, north_2023, north_2024], ignore_index=True)
north_inv['rayon'] = (
    north_inv['rayon']
        .str.strip()          # remove hidden spaces
        .replace(rayon_map)   # enforce English names
)
north_inv

,rayon,l_all_inv,f_all_inv,oblast,year,f_nonextr_inv,l_nonextr_inv
0,Petropavl city,47762593,3425304.0,North-Kazakhstan,2015,NaN,NaN
1,Aiyrtau,4012334,90322.0,North-Kazakhstan,2015,NaN,NaN
2,Akzhar,1933270,15822.0,North-Kazakhstan,2015,NaN,NaN
3,Magzhan Zhumabayev,5259113,22496.0,North-Kazakhstan,2015,NaN,NaN
4,Esil,3585650,121259.0,North-Kazakhstan,2015,NaN,NaN
...,...,...,...,...,...,...,...
135,Akkayin,16699892,375215.0,North-Kazakhstan,2024,35445.0,2210157.0
136,Taiynsha,31109989,17122239.0,North-Kazakhstan,2024,17059666.0,6337395.0
137,Timiryazev,9623344,8495.0,North-Kazakhstan,2024,0.0,494725.0
138,Ualikhanov,12571783,0.0,North-Kazakhstan,2024,0.0,737268.0
139,Gabit Musrepov,37910202,425007.0,North-Kazakhstan,2024,255101.0,19931892.0

## Employment

In [408]:
north_empl = pd.read_excel(Path("../Data/Employment/North-Kazakhstan.xlsx"), skiprows=27, nrows=14, header=None, usecols='A:L', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
north_empl.columns = ['rayon', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
north_empl['rayon'] = north_empl['rayon'].replace(rayon_map_north)
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    north_empl[i] = north_empl[i].astype(float)
    north_employment = north_empl.melt(id_vars='rayon', value_vars=[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024], var_name='year', value_name='employment')
north_employment

                  rayon  year  employment
0        Petropavl city  2014     110.875
1               Aiyrtau  2014      22.109
2                Akzhar  2014       9.029
3    Magzhan Zhumabayev  2014      19.155
4                  Esil  2014      14.347
..                  ...   ...         ...
149             Akkayin  2024      10.561
150            Taiynsha  2024      20.434
151          Timiryazev  2024       5.748
152          Ualikhanov  2024       6.365
153      Gabit Musrepov  2024      18.031

[154 rows x 3 columns]

## Other controls

In [409]:
petropavl_city = pd.read_excel(Path("../Data/Controls/North-Kazakhstan_All.xlsx"), sheet_name="г.Петропавловск", header=2, usecols='B, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
petropavl_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
petropavl_city = petropavl_city.loc[[85, 113, 156]].reset_index(drop=True)
petropavl_city['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    petropavl_city[i] = petropavl_city[i].astype(str)
    petropavl_city[i] = petropavl_city[i].str.replace(',', '.')
    petropavl_city[i] = petropavl_city[i].str.replace(')', '')
    petropavl_city[i] = petropavl_city[i].str.replace(' ', '')
    petropavl_city[i] = petropavl_city[i].str.replace('\xa0', '')
    petropavl_city[i] = petropavl_city[i].str.replace('*', '')
    petropavl_city[i] = petropavl_city[i].astype(float)
petropavl_city = pd.melt(petropavl_city, id_vars=['Indicator'], var_name='year', value_name='value')
petropavl_city = petropavl_city.pivot(index='year', columns='Indicator', values='value').reset_index()
petropavl_city.insert(0, 'rayon', 'Petropavl city')
petropavl_city.columns.name = None
petropavl_city

             rayon  year  agriculture  production     retail
0   Petropavl city  2014  11972.10000  103921.500   98800.80
1   Petropavl city  2015  11238.50000  111835.500   98729.70
2   Petropavl city  2016  11245.80000  133451.100  121540.60
3   Petropavl city  2017  13375.40000  171020.700  143100.70
4   Petropavl city  2018  14443.80000  162359.000  169416.20
5   Petropavl city  2019  14464.60634  167807.500  178582.40
6   Petropavl city  2020  16163.00000  205504.000  154148.30
7   Petropavl city  2021  21371.40000  260287.400  202547.10
8   Petropavl city  2022  23057.50000  324673.700  232485.27
9   Petropavl city  2023  21433.20000  460133.079  255982.90
10  Petropavl city  2024  19817.60000  487067.100  273985.00

In [410]:
aiyrtau = pd.read_excel(Path("../Data/Controls/North-Kazakhstan_All.xlsx"), sheet_name="Айыртауский", header=2, usecols='B, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
aiyrtau.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
aiyrtau = aiyrtau.loc[[85, 113, 156]].reset_index(drop=True)
aiyrtau['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    aiyrtau[i] = aiyrtau[i].astype(str)
    aiyrtau[i] = aiyrtau[i].str.replace(',', '.')
    aiyrtau[i] = aiyrtau[i].str.replace(')', '')
    aiyrtau[i] = aiyrtau[i].str.replace(' ', '')
    aiyrtau[i] = aiyrtau[i].str.replace('\xa0', '')
    aiyrtau[i] = aiyrtau[i].str.replace('*', '')
    aiyrtau[i] = aiyrtau[i].astype(float)
aiyrtau = pd.melt(aiyrtau, id_vars=['Indicator'], var_name='year', value_name='value')
aiyrtau = aiyrtau.pivot(index='year', columns='Indicator', values='value').reset_index()
aiyrtau.insert(0, 'rayon', 'Aiyrtau')
aiyrtau.columns.name = None
aiyrtau

      rayon  year    agriculture  production   retail
0   Aiyrtau  2014   34267.500000    3801.900   3889.9
1   Aiyrtau  2015   36054.900000    4045.700   4030.5
2   Aiyrtau  2016   38050.300000    6400.300   6594.0
3   Aiyrtau  2017   49475.200000    4854.100   6122.7
4   Aiyrtau  2018   48492.800000    5698.700   7596.9
5   Aiyrtau  2019   55296.555605    5810.800   8553.2
6   Aiyrtau  2020   70727.500000    6031.100   7218.6
7   Aiyrtau  2021   76702.600000    7725.300  10690.3
8   Aiyrtau  2022  106350.700000    6886.300  11742.2
9   Aiyrtau  2023   63542.800000    7093.172  16775.9
10  Aiyrtau  2024   68959.500000    6073.400  13649.9

In [411]:
akzhar = pd.read_excel(Path("../Data/Controls/North-Kazakhstan_All.xlsx"), sheet_name="Акжарский", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
akzhar.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
akzhar = akzhar.loc[[85, 113, 156]].reset_index(drop=True)
akzhar['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    akzhar[i] = akzhar[i].astype(str)
    akzhar[i] = akzhar[i].str.replace(',', '.')
    akzhar[i] = akzhar[i].str.replace(')', '')
    akzhar[i] = akzhar[i].str.replace(' ', '')
    akzhar[i] = akzhar[i].str.replace('\xa0', '')
    akzhar[i] = akzhar[i].str.replace('*', '')
    akzhar[i] = akzhar[i].astype(float)
akzhar = pd.melt(akzhar, id_vars=['Indicator'], var_name='year', value_name='value')
akzhar = akzhar.pivot(index='year', columns='Indicator', values='value').reset_index()
akzhar.insert(0, 'rayon', 'Akzhar')
akzhar.columns.name = None
akzhar

     rayon  year   agriculture  production  retail
0   Akzhar  2014  16040.400000     973.700  1815.9
1   Akzhar  2015  18596.000000     680.500  1947.2
2   Akzhar  2016  19959.200000     548.300  2757.0
3   Akzhar  2017  23292.800000     745.300  2855.6
4   Akzhar  2018  27357.500000    2057.400  5177.5
5   Akzhar  2019  34822.780018    1925.500  3653.6
6   Akzhar  2020  46143.400000    1776.800  1212.0
7   Akzhar  2021  51048.900000    1837.300  1551.9
8   Akzhar  2022  53977.700000    2034.900  1778.3
9   Akzhar  2023  23934.000000    1784.713  2395.0
10  Akzhar  2024  48992.300000    2292.200  2080.8

In [412]:
magzhan_zhumabayev = pd.read_excel(Path("../Data/Controls/North-Kazakhstan_All.xlsx"), sheet_name="М.Жумабаева", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
magzhan_zhumabayev.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
magzhan_zhumabayev = magzhan_zhumabayev.loc[[85, 113, 156]].reset_index(drop=True)
magzhan_zhumabayev['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    magzhan_zhumabayev[i] = magzhan_zhumabayev[i].astype(str)
    magzhan_zhumabayev[i] = magzhan_zhumabayev[i].str.replace(',', '.')
    magzhan_zhumabayev[i] = magzhan_zhumabayev[i].str.replace(')', '')
    magzhan_zhumabayev[i] = magzhan_zhumabayev[i].str.replace(' ', '')
    magzhan_zhumabayev[i] = magzhan_zhumabayev[i].str.replace('\xa0', '')
    magzhan_zhumabayev[i] = magzhan_zhumabayev[i].str.replace('*', '')
    magzhan_zhumabayev[i] = magzhan_zhumabayev[i].astype(float)
magzhan_zhumabayev = pd.melt(magzhan_zhumabayev, id_vars=['Indicator'], var_name='year', value_name='value')
magzhan_zhumabayev = magzhan_zhumabayev.pivot(index='year', columns='Indicator', values='value').reset_index()
magzhan_zhumabayev.insert(0, 'rayon', 'Magzhan Zhumabayev')
magzhan_zhumabayev.columns.name = None
magzhan_zhumabayev

                 rayon  year   agriculture  production   retail
0   Magzhan Zhumabayev  2014  30281.700000    3342.585   4118.4
1   Magzhan Zhumabayev  2015  34138.900000    3185.285   4693.9
2   Magzhan Zhumabayev  2016  36787.400000    3401.524   5824.5
3   Magzhan Zhumabayev  2017  45087.800000    3439.529   4452.7
4   Magzhan Zhumabayev  2018  46500.900000    3890.769   5249.9
5   Magzhan Zhumabayev  2019  57065.156472    4583.197   5498.1
6   Magzhan Zhumabayev  2020  73989.000000    4496.888   5297.0
7   Magzhan Zhumabayev  2021  86606.800000    5465.832   6818.3
8   Magzhan Zhumabayev  2022  90423.500000    4782.973  10863.6
9   Magzhan Zhumabayev  2023  65203.000000    5766.319   4793.4
10  Magzhan Zhumabayev  2024  79381.900000    5636.100   5053.3

In [413]:
esil = pd.read_excel(Path("../Data/Controls/North-Kazakhstan_All.xlsx"), sheet_name="Есильский", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
esil.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
esil = esil.loc[[85, 113, 156]].reset_index(drop=True)
esil['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    esil[i] = esil[i].astype(str)
    esil[i] = esil[i].str.replace(',', '.')
    esil[i] = esil[i].str.replace(')', '')
    esil[i] = esil[i].str.replace(' ', '')
    esil[i] = esil[i].str.replace('\xa0', '')
    esil[i] = esil[i].str.replace('*', '')
    esil[i] = esil[i].astype(float)
esil = pd.melt(esil, id_vars=['Indicator'], var_name='year', value_name='value')
esil = esil.pivot(index='year', columns='Indicator', values='value').reset_index()
esil.insert(0, 'rayon', 'Esil')
esil.columns.name = None
esil

   rayon  year   agriculture  production  retail
0   Esil  2014  21152.700000    2443.077  2633.2
1   Esil  2015  24517.100000    2657.196  3442.7
2   Esil  2016  25801.500000    2533.302  4062.6
3   Esil  2017  31141.300000    3060.064  1958.4
4   Esil  2018  32493.100000    3673.707  4830.2
5   Esil  2019  40701.873311    5758.902  5031.4
6   Esil  2020  52514.800000    8874.539  5037.0
7   Esil  2021  61254.000000   11409.982  5268.8
8   Esil  2022  84003.400000   13067.094  6637.2
9   Esil  2023  62357.600000   10015.361  9896.6
10  Esil  2024  64683.800000    8173.300  7274.3

In [414]:
zhambyl = pd.read_excel(Path("../Data/Controls/North-Kazakhstan_All.xlsx"), sheet_name="Жамбылский", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
zhambyl.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
zhambyl = zhambyl.loc[[85, 113, 156]].reset_index(drop=True)
zhambyl['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    zhambyl[i] = zhambyl[i].astype(str)
    zhambyl[i] = zhambyl[i].str.replace(',', '.')
    zhambyl[i] = zhambyl[i].str.replace(')', '')
    zhambyl[i] = zhambyl[i].str.replace(' ', '')
    zhambyl[i] = zhambyl[i].str.replace('\xa0', '')
    zhambyl[i] = zhambyl[i].str.replace('*', '')
    zhambyl[i] = zhambyl[i].astype(float)
zhambyl = pd.melt(zhambyl, id_vars=['Indicator'], var_name='year', value_name='value')
zhambyl = zhambyl.pivot(index='year', columns='Indicator', values='value').reset_index()
zhambyl.insert(0, 'rayon', 'Zhambyl')
zhambyl.columns.name = None
zhambyl

      rayon  year   agriculture  production   retail
0   Zhambyl  2014  20727.200000    1360.300  2885.40
1   Zhambyl  2015  23382.400000    1461.800  3683.90
2   Zhambyl  2016  26274.000000    1694.600  3955.80
3   Zhambyl  2017  32735.600000    2216.500  4323.60
4   Zhambyl  2018  34023.200000    2554.100  4748.00
5   Zhambyl  2019  36965.220014    1951.800  5452.90
6   Zhambyl  2020  48357.200000    2344.900  3484.90
7   Zhambyl  2021  57159.400000    3162.100  4637.95
8   Zhambyl  2022  95186.200000    3028.900  6074.47
9   Zhambyl  2023  51027.000000    2754.088  7004.00
10  Zhambyl  2024  67268.300000    2396.300  6297.80

In [415]:
kyzylzhar = pd.read_excel(Path("../Data/Controls/North-Kazakhstan_All.xlsx"), sheet_name="Кызылжарский", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
kyzylzhar.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
kyzylzhar = kyzylzhar.loc[[85, 113, 156]].reset_index(drop=True)
kyzylzhar['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    kyzylzhar[i] = kyzylzhar[i].astype(str)
    kyzylzhar[i] = kyzylzhar[i].str.replace(',', '.')
    kyzylzhar[i] = kyzylzhar[i].str.replace(')', '')
    kyzylzhar[i] = kyzylzhar[i].str.replace(' ', '')
    kyzylzhar[i] = kyzylzhar[i].str.replace('\xa0', '')
    kyzylzhar[i] = kyzylzhar[i].str.replace('*', '')
    kyzylzhar[i] = kyzylzhar[i].astype(float)
kyzylzhar = pd.melt(kyzylzhar, id_vars=['Indicator'], var_name='year', value_name='value')
kyzylzhar = kyzylzhar.pivot(index='year', columns='Indicator', values='value').reset_index()
kyzylzhar.insert(0, 'rayon', 'Kyzylzhar')
kyzylzhar.columns.name = None
kyzylzhar

        rayon  year    agriculture  production   retail
0   Kyzylzhar  2014   32633.700000    8025.000   6682.4
1   Kyzylzhar  2015   35077.600000   11147.600   5556.9
2   Kyzylzhar  2016   38732.100000   14128.800   5500.3
3   Kyzylzhar  2017   47386.700000   14491.700   8883.9
4   Kyzylzhar  2018   50121.700000   15627.800  11256.5
5   Kyzylzhar  2019   57543.999749   17095.700  12233.0
6   Kyzylzhar  2020   66532.700000   20399.000   8716.8
7   Kyzylzhar  2021   86692.600000   25355.200  10879.0
8   Kyzylzhar  2022  106284.900000   32999.300  10739.8
9   Kyzylzhar  2023   84297.700000   36624.326  10336.4
10  Kyzylzhar  2024   88281.000000   35043.000  11632.5

In [416]:
mamlyut = pd.read_excel(Path("../Data/Controls/North-Kazakhstan_All.xlsx"), sheet_name="Мамлютский", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
mamlyut.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
mamlyut = mamlyut.loc[[85, 113, 156]].reset_index(drop=True)
mamlyut['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    mamlyut[i] = mamlyut[i].astype(str)
    mamlyut[i] = mamlyut[i].str.replace(',', '.')
    mamlyut[i] = mamlyut[i].str.replace(')', '')
    mamlyut[i] = mamlyut[i].str.replace(' ', '')
    mamlyut[i] = mamlyut[i].str.replace('\xa0', '')
    mamlyut[i] = mamlyut[i].str.replace('*', '')
    mamlyut[i] = mamlyut[i].astype(float)
mamlyut = pd.melt(mamlyut, id_vars=['Indicator'], var_name='year', value_name='value')
mamlyut = mamlyut.pivot(index='year', columns='Indicator', values='value').reset_index()
mamlyut.insert(0, 'rayon', 'Mamlyut')
mamlyut.columns.name = None
mamlyut

      rayon  year   agriculture  production  retail
0   Mamlyut  2014  12763.300000     1535.40  4564.5
1   Mamlyut  2015  14467.000000     1425.10  3863.9
2   Mamlyut  2016  15733.600000     1961.80  3779.2
3   Mamlyut  2017  19745.300000     1380.40  5173.6
4   Mamlyut  2018  20463.200000     1793.20  6836.4
5   Mamlyut  2019  27630.568234     2116.80  7233.3
6   Mamlyut  2020  33700.400000     2059.70  1983.5
7   Mamlyut  2021  40986.000000     1833.60  2799.0
8   Mamlyut  2022  63484.700000     2113.50  5893.4
9   Mamlyut  2023  38050.100000     2798.22  7267.7
10  Mamlyut  2024  42061.300000     1803.60  5734.6

In [417]:
shal_akyn = pd.read_excel(Path("../Data/Controls/North-Kazakhstan_All.xlsx"), sheet_name="Шал акына", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
shal_akyn.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
shal_akyn = shal_akyn.loc[[85, 113, 156]].reset_index(drop=True)
shal_akyn['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    shal_akyn[i] = shal_akyn[i].astype(str)
    shal_akyn[i] = shal_akyn[i].str.replace(',', '.')
    shal_akyn[i] = shal_akyn[i].str.replace(')', '')
    shal_akyn[i] = shal_akyn[i].str.replace(' ', '')
    shal_akyn[i] = shal_akyn[i].str.replace('\xa0', '')
    shal_akyn[i] = shal_akyn[i].str.replace('*', '')
    shal_akyn[i] = shal_akyn[i].astype(float)
shal_akyn = pd.melt(shal_akyn, id_vars=['Indicator'], var_name='year', value_name='value')
shal_akyn = shal_akyn.pivot(index='year', columns='Indicator', values='value').reset_index()
shal_akyn.insert(0, 'rayon', 'Shal Akyn')
shal_akyn.columns.name = None
shal_akyn

        rayon  year   agriculture  production   retail
0   Shal Akyn  2014  19361.800000    3420.100   2985.2
1   Shal Akyn  2015  20546.500000    3452.200   4065.1
2   Shal Akyn  2016  22496.900000    4097.100   4909.2
3   Shal Akyn  2017  23429.900000    4226.700   4826.2
4   Shal Akyn  2018  24926.100000    3355.900   5094.7
5   Shal Akyn  2019  30043.224634    3484.500   5755.2
6   Shal Akyn  2020  41872.100000    3385.700   5959.1
7   Shal Akyn  2021  51779.100000    4259.300   7553.7
8   Shal Akyn  2022  72941.500000    4801.400   9344.3
9   Shal Akyn  2023  38778.700000    5588.493  17148.4
10  Shal Akyn  2024  53211.000000    5489.600   9806.6

In [418]:
akkayin = pd.read_excel(Path("../Data/Controls/North-Kazakhstan_All.xlsx"), sheet_name="Аккайынский", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
akkayin.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
akkayin = akkayin.loc[[85, 113, 156]].reset_index(drop=True)
akkayin['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    akkayin[i] = akkayin[i].astype(str)
    akkayin[i] = akkayin[i].str.replace(',', '.')
    akkayin[i] = akkayin[i].str.replace(')', '')
    akkayin[i] = akkayin[i].str.replace(' ', '')
    akkayin[i] = akkayin[i].str.replace('\xa0', '')
    akkayin[i] = akkayin[i].str.replace('*', '')
    akkayin[i] = akkayin[i].astype(float)
akkayin = pd.melt(akkayin, id_vars=['Indicator'], var_name='year', value_name='value')
akkayin = akkayin.pivot(index='year', columns='Indicator', values='value').reset_index()
akkayin.insert(0, 'rayon', 'Akkayin')
akkayin.columns.name = None
akkayin

      rayon  year   agriculture  production  retail
0   Akkayin  2014  19537.400000    1902.600  2745.4
1   Akkayin  2015  21547.600000    3100.000  2580.8
2   Akkayin  2016  23279.100000    2943.900  3466.1
3   Akkayin  2017  28892.800000    2383.400  4133.8
4   Akkayin  2018  31116.200000    3616.100  5081.9
5   Akkayin  2019  34859.400000    3555.800  5576.9
6   Akkayin  2020  44359.400000    4458.400  5524.5
7   Akkayin  2021  59184.310085    5322.100  1615.6
8   Akkayin  2022  73117.300000    5007.900  2522.4
9   Akkayin  2023  53614.500000    8888.438  2790.9
10  Akkayin  2024  60659.300000   10046.300  2863.7

In [419]:
taiynsha = pd.read_excel(Path("../Data/Controls/North-Kazakhstan_All.xlsx"), sheet_name="Тайыншинский", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
taiynsha.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
taiynsha = taiynsha.loc[[85, 113, 156]].reset_index(drop=True)
taiynsha['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    taiynsha[i] = taiynsha[i].astype(str)
    taiynsha[i] = taiynsha[i].str.replace(',', '.')
    taiynsha[i] = taiynsha[i].str.replace(')', '')
    taiynsha[i] = taiynsha[i].str.replace(' ', '')
    taiynsha[i] = taiynsha[i].str.replace('\xa0', '')
    taiynsha[i] = taiynsha[i].str.replace('*', '')
    taiynsha[i] = taiynsha[i].astype(float)
taiynsha = pd.melt(taiynsha, id_vars=['Indicator'], var_name='year', value_name='value')
taiynsha = taiynsha.pivot(index='year', columns='Indicator', values='value').reset_index()
taiynsha.insert(0, 'rayon', 'Taiynsha')
taiynsha.columns.name = None
taiynsha

       rayon  year    agriculture  production   retail
0   Taiynsha  2014   52337.000000    8942.000   8331.4
1   Taiynsha  2015   54056.900000    6726.400  10226.2
2   Taiynsha  2016   56652.000000    8570.500  11088.5
3   Taiynsha  2017   69299.800000   14441.200   9866.3
4   Taiynsha  2018   66264.200000   17394.500  11726.0
5   Taiynsha  2019   83749.407003   25859.300  12340.4
6   Taiynsha  2020  104455.300000   28677.600  14363.6
7   Taiynsha  2021  122077.800000   32869.800  14929.1
8   Taiynsha  2022  139859.400000   56097.300  20659.4
9   Taiynsha  2023   97248.900000   66928.811  24324.3
10  Taiynsha  2024  139171.600000   57139.500  22417.1

In [420]:
timiryazev = pd.read_excel(Path("../Data/Controls/North-Kazakhstan_All.xlsx"), sheet_name="Тимирязевский", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
timiryazev.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
timiryazev = timiryazev.loc[[85, 113, 156]].reset_index(drop=True)
timiryazev['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    timiryazev[i] = timiryazev[i].astype(str)
    timiryazev[i] = timiryazev[i].str.replace(',', '.')
    timiryazev[i] = timiryazev[i].str.replace(')', '')
    timiryazev[i] = timiryazev[i].str.replace(' ', '')
    timiryazev[i] = timiryazev[i].str.replace('\xa0', '')
    timiryazev[i] = timiryazev[i].str.replace('*', '')
    timiryazev[i] = timiryazev[i].astype(float)
timiryazev = pd.melt(timiryazev, id_vars=['Indicator'], var_name='year', value_name='value')
timiryazev = timiryazev.pivot(index='year', columns='Indicator', values='value').reset_index()
timiryazev.insert(0, 'rayon', 'Timiryazev')
timiryazev.columns.name = None
timiryazev

         rayon  year   agriculture  production  retail
0   Timiryazev  2014  15233.100000    3915.700  1582.3
1   Timiryazev  2015  17610.400000    5102.200  2379.6
2   Timiryazev  2016  19026.600000    5875.700  3231.8
3   Timiryazev  2017  25284.000000    5360.500  2916.2
4   Timiryazev  2018  25462.700000    4050.500  3403.1
5   Timiryazev  2019  27612.945606    5011.100  3843.3
6   Timiryazev  2020  39918.400000    4526.600  3756.5
7   Timiryazev  2021  38504.600000    5099.500  4095.9
8   Timiryazev  2022  65053.700000    5729.800  5048.3
9   Timiryazev  2023  35020.100000    6512.954  5848.7
10  Timiryazev  2024  52942.000000    6039.000  5524.5

In [421]:
ualikhanov = pd.read_excel(Path("../Data/Controls/North-Kazakhstan_All.xlsx"), sheet_name="Уалихановский", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
ualikhanov.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
ualikhanov = ualikhanov.loc[[85, 113, 156]].reset_index(drop=True)
ualikhanov['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    ualikhanov[i] = ualikhanov[i].astype(str)
    ualikhanov[i] = ualikhanov[i].str.replace(',', '.')
    ualikhanov[i] = ualikhanov[i].str.replace(')', '')
    ualikhanov[i] = ualikhanov[i].str.replace(' ', '')
    ualikhanov[i] = ualikhanov[i].str.replace('\xa0', '')
    ualikhanov[i] = ualikhanov[i].str.replace('*', '')
    ualikhanov[i] = ualikhanov[i].astype(float)
ualikhanov = pd.melt(ualikhanov, id_vars=['Indicator'], var_name='year', value_name='value')
ualikhanov = ualikhanov.pivot(index='year', columns='Indicator', values='value').reset_index()
ualikhanov.insert(0, 'rayon', 'Ualikhanov')
ualikhanov.columns.name = None
ualikhanov

         rayon  year  agriculture  production  retail
0   Ualikhanov  2014  15144.10000     933.600  2642.3
1   Ualikhanov  2015  17598.00000     969.800  3215.5
2   Ualikhanov  2016  19379.00000    1028.400  3990.4
3   Ualikhanov  2017  22219.40000     637.800  5074.8
4   Ualikhanov  2018  22767.90000    1041.100  5200.1
5   Ualikhanov  2019  28051.86954    1184.000  5858.8
6   Ualikhanov  2020  29121.20000    1207.200  5665.8
7   Ualikhanov  2021  38072.60000    1425.800  4321.8
8   Ualikhanov  2022  45162.30000    1545.400  3476.0
9   Ualikhanov  2023  24057.40000    2034.616  3200.1
10  Ualikhanov  2024  34761.70000    1738.200  3241.5

In [422]:
gabit_musrepov = pd.read_excel(Path("../Data/Controls/North-Kazakhstan_All.xlsx"), sheet_name="Г.Мусрепова", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
gabit_musrepov.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
gabit_musrepov = gabit_musrepov.loc[[85, 113, 156]].reset_index(drop=True)
gabit_musrepov['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    gabit_musrepov[i] = gabit_musrepov[i].astype(str)
    gabit_musrepov[i] = gabit_musrepov[i].str.replace(',', '.')
    gabit_musrepov[i] = gabit_musrepov[i].str.replace(')', '')
    gabit_musrepov[i] = gabit_musrepov[i].str.replace(' ', '')
    gabit_musrepov[i] = gabit_musrepov[i].str.replace('\xa0', '')
    gabit_musrepov[i] = gabit_musrepov[i].str.replace('*', '')
    gabit_musrepov[i] = gabit_musrepov[i].astype(float)
gabit_musrepov = pd.melt(gabit_musrepov, id_vars=['Indicator'], var_name='year', value_name='value')
gabit_musrepov = gabit_musrepov.pivot(index='year', columns='Indicator', values='value').reset_index()
gabit_musrepov.insert(0, 'rayon', 'Gabit Musrepov')
gabit_musrepov.columns.name = None
gabit_musrepov

             rayon  year    agriculture  production   retail
0   Gabit Musrepov  2014   48817.200000   16683.900  14663.3
1   Gabit Musrepov  2015   51982.400000   10914.400  12883.0
2   Gabit Musrepov  2016   58068.100000   11396.600  14084.8
3   Gabit Musrepov  2017   67044.400000   12398.600  16435.0
4   Gabit Musrepov  2018   70253.500000   15926.200  15936.9
5   Gabit Musrepov  2019   81893.776111   17431.100  20193.0
6   Gabit Musrepov  2020  109280.300000   21773.700  19701.2
7   Gabit Musrepov  2021  108734.000000   28613.000  23816.3
8   Gabit Musrepov  2022  154700.000000   40818.300  30572.5
9   Gabit Musrepov  2023   98958.800000   39323.033  31122.5
10  Gabit Musrepov  2024  113423.800000   58136.800  31502.1

In [423]:
north_controls = pd.concat([petropavl_city, aiyrtau, akzhar, magzhan_zhumabayev, esil, zhambyl, kyzylzhar, mamlyut, shal_akyn, akkayin, taiynsha, timiryazev, ualikhanov, gabit_musrepov], ignore_index=True)
north_controls

              rayon  year  agriculture  production    retail
0    Petropavl city  2014      11972.1  103921.500   98800.8
1    Petropavl city  2015      11238.5  111835.500   98729.7
2    Petropavl city  2016      11245.8  133451.100  121540.6
3    Petropavl city  2017      13375.4  171020.700  143100.7
4    Petropavl city  2018      14443.8  162359.000  169416.2
..              ...   ...          ...         ...       ...
149  Gabit Musrepov  2020     109280.3   21773.700   19701.2
150  Gabit Musrepov  2021     108734.0   28613.000   23816.3
151  Gabit Musrepov  2022     154700.0   40818.300   30572.5
152  Gabit Musrepov  2023      98958.8   39323.033   31122.5
153  Gabit Musrepov  2024     113423.8   58136.800   31502.1

[154 rows x 5 columns]

## PPI

In [424]:
north_ppi = pd.read_excel(
    Path("../Data/PPI/North-Kazakhstan.xlsx"),
    header=2,
    usecols='Y:AI',
    nrows=199,
    na_values=['x', 'х', '-', '', ' ', '...']
)
north_ppi.columns = [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
years = north_ppi.columns.tolist()
rayons = list(north_inv['rayon'].unique())

dfs = []

for rayon in rayons:
    df_temp = pd.DataFrame({
        'rayon': [rayon] * len(years),
        'year': years,
        'ppi': north_ppi.iloc[-1].values
    })
    dfs.append(df_temp)
dfs
north_ppi_long = pd.concat(dfs, ignore_index=True)
north_ppi_long
north_ppi = north_ppi_long
north_ppi['ppi'] = north_ppi['ppi'].astype(str).str.replace(',', '.')
north_ppi['ppi'] = north_ppi['ppi'].astype(str).str.replace(')', '')
north_ppi['ppi'] = north_ppi['ppi'].astype(str).str.replace(' ', '')
north_ppi['ppi'] = north_ppi['ppi'].astype(str).str.replace('\xa0', '')
north_ppi['ppi'] = north_ppi['ppi'].astype(str).str.replace('*', '')
north_ppi['ppi'] = north_ppi['ppi'].astype(float)

north_ppi

              rayon  year    ppi
0    Petropavl city  2014  107.9
1    Petropavl city  2015  102.8
2    Petropavl city  2016  108.4
3    Petropavl city  2017  103.8
4    Petropavl city  2018  102.0
..              ...   ...    ...
149  Gabit Musrepov  2020  110.1
150  Gabit Musrepov  2021  114.1
151  Gabit Musrepov  2022  114.8
152  Gabit Musrepov  2023  103.7
153  Gabit Musrepov  2024  105.0

[154 rows x 3 columns]

## Combine

In [425]:
dfs_north = [north_inv, north_employment, north_controls, north_ppi]
north_merged = reduce(lambda left, right: pd.merge(left, right, on=['rayon', 'year'], how='outer'), dfs_north)
north_merged['oblast'] = north_merged['oblast'].fillna('North-Kazakhstan')
north_merged

,rayon,l_all_inv,f_all_inv,oblast,year,f_nonextr_inv,l_nonextr_inv,employment,agriculture,production,retail,ppi
0,Aiyrtau,NaN,NaN,North-Kazakhstan,2014,NaN,NaN,22.109,34267.5,3801.900,3889.90,107.9
1,Aiyrtau,4012334.0,90322.0,North-Kazakhstan,2015,NaN,NaN,22.937,36054.9,4045.700,4030.50,102.8
2,Aiyrtau,6850676.0,9972.0,North-Kazakhstan,2016,6147.0,2918648.0,21.928,38050.3,6400.300,6594.00,108.4
3,Aiyrtau,9717739.0,29603.0,North-Kazakhstan,2017,4188.0,5027309.0,21.644,49475.2,4854.100,6122.70,103.8
4,Aiyrtau,11468207.0,41387.0,North-Kazakhstan,2018,5862.0,7445438.0,22.618,48492.8,5698.700,7596.90,102.0
...,...,...,...,...,...,...,...,...,...,...,...,...
149,Zhambyl,8377027.0,204050.0,North-Kazakhstan,2020,202818.0,1101629.0,10.024,48357.2,2344.900,3484.90,110.1
150,Zhambyl,9994116.0,10107.0,North-Kazakhstan,2021,10107.0,908316.0,9.880,57159.4,3162.100,4637.95,114.1
151,Zhambyl,12185999.0,384803.0,North-Kazakhstan,2022,0.0,670247.0,9.700,95186.2,3028.900,6074.47,114.8
152,Zhambyl,13755817.0,9346.0,North-Kazakhstan,2023,0.0,943080.0,10.664,51027.0,2754.088,7004.00,103.7
153,Zhambyl,15028639.0,47056.0,North-Kazakhstan,2024,0.0,2645837.0,10.369,67268.3,2396.300,6297.80,105.0

# Pavlodar

## Investments all

In [426]:
# pavlodar_all_2014 
pavlodar_all_2014 = camelot.read_pdf(Path("../Data/Investments/Pavlodar/2014_Investments.pdf"), pages='29', flavor='stream')[0].df
pavlodar_all_2014 = pavlodar_all_2014.iloc[6:, [0, 2, 5]].reset_index(drop=True)
pavlodar_all_2014 = pavlodar_all_2014.drop(index=3).reset_index(drop=True)
pavlodar_all_2014[5] = (
    pavlodar_all_2014[5]
    .astype(str)
    .replace('–', '')
)
for col in [2, 5]:
    pavlodar_all_2014[col] = (
        pavlodar_all_2014[col]
        .astype(str)
        .str.replace(' ', '', regex=False)
        .replace('', pd.NA)
        .astype('Int64'))
pavlodar_all_2014 = pavlodar_all_2014.drop(index=13).reset_index(drop=True)
pavlodar_all_2014

# pavlodar_all_2015
pavlodar_all_2015 = camelot.read_pdf(Path("../Data/Investments/Pavlodar/2015_Investments.pdf"), pages='22', flavor='stream')[0].df
pavlodar_all_2015 = pavlodar_all_2015.iloc[7:, [0, 2, 5]].reset_index(drop=True)
pavlodar_all_2015 = pavlodar_all_2015.drop(index=3).reset_index(drop=True)
pavlodar_all_2015
pavlodar_all_2015[5] = (
    pavlodar_all_2015[5]
    .astype(str)
    .replace('–', '')
)
for col in [2, 5]:
    pavlodar_all_2015[col] = (
        pavlodar_all_2015[col]
        .astype(str)
        .str.replace(' ', '', regex=False)
        .replace('', pd.NA)
        .astype('Int64'))
pavlodar_all_2015 = pavlodar_all_2015.drop(index=13).reset_index(drop=True)
pavlodar_all_2015

# pavlodar_all_2016
pavlodar_all_2016 = camelot.read_pdf(Path("../Data/Investments/Pavlodar/2016_Investments.pdf"), pages='26', flavor='stream')[0].df
pavlodar_all_2016 = pavlodar_all_2016.iloc[7:, [0, 2, 4]].reset_index(drop=True)
pavlodar_all_2016 = pavlodar_all_2016.drop(index=3).reset_index(drop=True)
pavlodar_all_2016[4] = (
    pavlodar_all_2016[4]
    .astype(str)
    .replace('–', '')
)

for col in [2, 4]:
    pavlodar_all_2016[col] = (
        pavlodar_all_2016[col]
        .astype(str)
        .str.replace('\xa0', '', regex=False)  # <-- FIX
        .str.replace(' ', '', regex=False)
        .replace('', pd.NA)
        .astype('Int64')
    )
pavlodar_all_2016[4] = (
    pavlodar_all_2016[4]
    .astype(str)
    .replace("<NA>", '')
    .replace('', pd.NA)   # <-- REQUIRED
    .astype('Int64')      # <-- safe for missing values
)
pavlodar_all_2016 = pavlodar_all_2016.drop(index=13).reset_index(drop=True)
pavlodar_all_2016

# pavlodar_all_2017
pavlodar_all_2017 = camelot.read_pdf(Path("../Data/Investments/Pavlodar/2017_Investments.pdf"), pages='30', flavor='stream')[0].df
pavlodar_all_2017 = pavlodar_all_2017.iloc[7:, [0, 2, 4]].reset_index(drop=True)
pavlodar_all_2017 = pavlodar_all_2017.drop(index=3).reset_index(drop=True)
for col in [2, 4]:
    pavlodar_all_2017[col] = (
        pavlodar_all_2017[col]
        .astype(str)
        .str.replace(' ', '', regex=False)
        .str.replace('\xa0', '', regex=False)
        .astype(int)
    )
pavlodar_all_2017

# pavlodar_all_2018
pavlodar_all_2018 = camelot.read_pdf(Path("../Data/Investments/Pavlodar/2018_Investments.pdf"), pages='27', flavor='stream')[0].df
pavlodar_all_2018 = pavlodar_all_2018.iloc[7:, [0, 3, 6]].reset_index(drop=True)
pavlodar_all_2018 = pavlodar_all_2018.drop(index=3).reset_index(drop=True)
pavlodar_all_2018[6] = (
    pavlodar_all_2018[6]
    .astype(str)
    .replace('‐', '')
)
for col in [3, 6]:
    pavlodar_all_2018[col] = (
        pavlodar_all_2018[col]
        .astype(str)
        .str.replace('\xa0', '', regex=False)
        .replace('', pd.NA)
        .astype('Int64')
    )
pavlodar_all_2018

# EXCEL
pavlodar_all_2019 = pd.read_excel(Path("../Data/Investments/Pavlodar/2019_Investments.xls"), sheet_name='14.', header=4, nrows=16, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
pavlodar_all_2019 = pavlodar_all_2019.drop(index=3).reset_index(drop=True)
pavlodar_all_2019

pavlodar_all_2020 = pd.read_excel(Path("../Data/Investments/Pavlodar/2020_Investments.xls"), sheet_name='13.', header=3, nrows=16, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
pavlodar_all_2020 = pavlodar_all_2020.drop(index=3).reset_index(drop=True)
pavlodar_all_2020

pavlodar_all_2021 = pd.read_excel(Path("../Data/Investments/Pavlodar/2021_Investments.xls"), sheet_name='13.', header=3, nrows=16, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
pavlodar_all_2021 = pavlodar_all_2021.drop(index=3).reset_index(drop=True)
pavlodar_all_2021

pavlodar_all_2022 = pd.read_excel(Path("../Data/Investments/Pavlodar/2022_Investments.xlsx"), sheet_name='21', header=3, nrows=16, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
pavlodar_all_2022 = pavlodar_all_2022.drop(index=3).reset_index(drop=True)
pavlodar_all_2022

pavlodar_all_2023 = pd.read_excel(Path("../Data/Investments/Pavlodar/2023_Investments.xlsx"), sheet_name='21', header=3, nrows=16, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
pavlodar_all_2023 = pavlodar_all_2023.drop(index=3).reset_index(drop=True)
pavlodar_all_2023

pavlodar_all_2024 = pd.read_excel(Path("../Data/Investments/Pavlodar/2024_Investments.xlsx"), sheet_name='14', header=3, nrows=16, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
pavlodar_all_2024 = pavlodar_all_2024.drop(index=3).reset_index(drop=True)
pavlodar_all_2024

         Unnamed: 0   внутренние     внешние
0    Павлодар  г.а.  372966210.0  34266603.0
1        Аксу  г.а.  164585291.0     41428.0
2   Экибастуз  г.а.  277464461.0  69477307.0
3       Актогайский   17657421.0         0.0
4      Баянаульский   20952314.0   2186930.0
5       Железинский   13994296.0   2738400.0
6         Иртышский   22819024.0         0.0
7          Тереңкөл   20637236.0      5223.0
8            Аққулы   19703771.0         0.0
9           Майский   20586033.0         0.0
10     Павлодарский   20948396.0   1607374.0
11        Успенский   13167648.0         0.0
12    Щербактинский   17949832.0    136845.0

## Investments non

In [427]:
# pavlodar_non_2015
pavlodar_non_2015 = camelot.read_pdf(Path("../Data/Investments/Pavlodar/2015_Investments.pdf"), pages='23', flavor='stream')[0].df
pavlodar_non_2015 = pavlodar_non_2015.iloc[5:, [0, 2, 4]].reset_index(drop=True)
pavlodar_non_2015 = pavlodar_non_2015.drop(index=3).reset_index(drop=True)
pavlodar_non_2015[4] = (
    pavlodar_non_2015[4]
    .astype(str)
    .replace('–', '')
)
for col in [2, 4]:
    pavlodar_non_2015[col] = (
        pavlodar_non_2015[col]
        .astype(str)
        .str.replace(' ', '', regex=False)
        .replace('', pd.NA)
        .astype('Int64'))
pavlodar_non_2015 = pavlodar_non_2015.drop(index=13).reset_index(drop=True)
pavlodar_non_2015

# pavlodar_non_2016
pavlodar_non_2016 = camelot.read_pdf(Path("../Data/Investments/Pavlodar/2016_Investments.pdf"), pages='27', flavor='stream')[0].df
pavlodar_non_2016 = pavlodar_non_2016.iloc[4:, [0, 2, 6]].reset_index(drop=True)
pavlodar_non_2016 = pavlodar_non_2016.drop(index=3).reset_index(drop=True)
pavlodar_non_2016[6] = (
    pavlodar_non_2016[6]
    .astype(str)
    .replace('–', '')
)
for col in [2, 6]:
    pavlodar_non_2016[col] = (
        pavlodar_non_2016[col]
        .astype(str)
        .str.replace('\xa0', '', regex=False)
        .replace('', pd.NA)
        .astype('Int64'))
pavlodar_non_2016 = pavlodar_non_2016.drop(index=13).reset_index(drop=True)
pavlodar_non_2016

# pavlodar_non_2017
pavlodar_non_2017 = camelot.read_pdf(Path("../Data/Investments/Pavlodar/2017_Investments.pdf"), pages='31', flavor='stream')[0].df
pavlodar_non_2017 = pavlodar_non_2017.iloc[5:, [0, 2, 5]].reset_index(drop=True)
pavlodar_non_2017 = pavlodar_non_2017.drop(index=3).reset_index(drop=True)
pavlodar_non_2017[5] = (
    pavlodar_non_2017[5]
    .astype(str)
    .replace('‐', '')
)
for col in [2, 5]:
    pavlodar_non_2017[col] = (
        pavlodar_non_2017[col]
        .astype(str)
        .str.replace('\xa0', '', regex=False)
        .replace('', pd.NA)
        .astype('Int64'))
pavlodar_non_2017

# pavlodar_non_2018
pavlodar_non_2018 = camelot.read_pdf(Path("../Data/Investments/Pavlodar/2018_Investments.pdf"), pages='28', flavor='stream')[0].df
pavlodar_non_2018 = pavlodar_non_2018.iloc[4:, [0, 2, 5]].reset_index(drop=True)
pavlodar_non_2018 = pavlodar_non_2018.drop(index=3).reset_index(drop=True)
pavlodar_non_2018[5] = (
    pavlodar_non_2018[5]
    .astype(str)
    .replace('‐', '')
)
for col in [2, 5]:
    pavlodar_non_2018[col] = (
        pavlodar_non_2018[col]
        .astype(str)
        .str.replace('\xa0', '', regex=False)
        .replace('', pd.NA)
        .astype('Int64'))
pavlodar_non_2018

# EXCEL
pavlodar_non_2019 = pd.read_excel(Path("../Data/Investments/Pavlodar/2019_Investments.xls"), sheet_name='15.', header=5, nrows=16, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
pavlodar_non_2019 = pavlodar_non_2019.drop(index=3).reset_index(drop=True)
pavlodar_non_2019

pavlodar_non_2020 = pd.read_excel(Path("../Data/Investments/Pavlodar/2020_Investments.xls"), sheet_name='14.', header=3, nrows=16, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
pavlodar_non_2020 = pavlodar_non_2020.drop(index=3).reset_index(drop=True)
pavlodar_non_2020

pavlodar_non_2021 = pd.read_excel(Path("../Data/Investments/Pavlodar/2021_Investments.xls"), sheet_name='14.', header=3, nrows=16, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
pavlodar_non_2021 = pavlodar_non_2021.drop(index=3).reset_index(drop=True)
pavlodar_non_2021

pavlodar_non_2022 = pd.read_excel(Path("../Data/Investments/Pavlodar/2022_Investments.xlsx"), sheet_name='22', header=3, nrows=16, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
pavlodar_non_2022 = pavlodar_non_2022.drop(index=3).reset_index(drop=True)
pavlodar_non_2022

pavlodar_non_2023 = pd.read_excel(Path("../Data/Investments/Pavlodar/2023_Investments.xlsx"), sheet_name='22', header=3, nrows=16, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
pavlodar_non_2023 = pavlodar_non_2023.drop(index=3).reset_index(drop=True)
pavlodar_non_2023

pavlodar_non_2024 = pd.read_excel(Path("../Data/Investments/Pavlodar/2024_Investments.xlsx"), sheet_name='15', header=3, nrows=16, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
pavlodar_non_2024 = pavlodar_non_2024.drop(index=3).reset_index(drop=True)
pavlodar_non_2024

         Unnamed: 0   Unnamed: 1  внешние инвестиции
0    Павлодар  г.а.  302436773.0          34138197.0
1        Аксу  г.а.   71908929.0              4565.0
2   Экибастуз  г.а.  231665318.0          14966056.0
3       Актогайский    4606678.0                 0.0
4      Баянаульский   11656475.0            467705.0
5       Железинский    2824956.0                 0.0
6         Иртышский    2645583.0                 0.0
7          Тереңкөл    8641080.0                 0.0
8            Аққулы    7385206.0                 0.0
9           Майский    3889398.0                 0.0
10     Павлодарский   10737008.0                 0.0
11        Успенский    2016203.0                 0.0
12    Щербактинский    1673597.0                 0.0

In [428]:
dfs = [pavlodar_all_2014, pavlodar_all_2015, pavlodar_all_2016, pavlodar_all_2017, pavlodar_all_2018, pavlodar_all_2019, pavlodar_all_2020,
       pavlodar_all_2021, pavlodar_all_2022, pavlodar_all_2023, pavlodar_all_2024,
       pavlodar_non_2015, pavlodar_non_2016, pavlodar_non_2017, pavlodar_non_2018, pavlodar_non_2019, pavlodar_non_2020,
      pavlodar_non_2021, pavlodar_non_2022, pavlodar_non_2023, pavlodar_non_2024]

lists = []

for df in dfs:
    lists.extend(df.iloc[:, 0].unique())

unique_lists = pd.Series(lists).unique()
unique_lists

array(['Павлодар қ.ə.', 'Ақсу қ.ə.', 'Екібастұз қ.ə.', 'Ақтоғай',
       'Баянауыл', 'Железин', 'Ертіс', 'Качиры', 'Лебяжі', 'Май',
       'Павлодар', 'Успен', 'Шарбақты', 'Павлодар\xa0қ.ә.',
       'Ақсу\xa0қ.ә.', 'Екібастұз\xa0қ.ә.', 'Павлодар\xa0қ.ә',
       'Ақсу\xa0қ.ә', 'Екібастұз\xa0қ.ә', 'Тереңкөл', 'Аққулы',
       'Павлодар қ.ә', 'Ақсу қ.ә', 'Екібастұз қ.ә', 'Ақтоғай ',
       'Баянауыл ', 'Железин ', 'Май ', 'Павлодар ', 'Шарбақты ',
       'Павлодар қ.ә.', 'Ақсу қ.ә.', 'Екібастұз қ.ә.', 'Павлодар г.а.',
       'Аксу  г.а.', 'Екибастуз  г.а.', 'Актогайский', 'Баянаульский',
       'Железинский', 'Иртышский', 'Майский', 'Павлодарский', 'Успенский',
       'Щербактинский', 'Павлодар  г.а.', 'Экибастуз  г.а.',
       'Шарбақты ауданы', 'Ертіс ', 'Успен '], dtype=object)

In [429]:
rayon_map_pavlodar = {

    # ---- Cities ----
    'Павлодар қ.ə.': 'Pavlodar city',
    'Павлодар қ.ә.': 'Pavlodar city',
    'Павлодар қ.ә': 'Pavlodar city',
    'Павлодар\xa0қ.ә.': 'Pavlodar city',
    'Павлодар\xa0қ.ә': 'Pavlodar city',
    'Павлодар г.а.': 'Pavlodar city',
    'Павлодар  г.а.': 'Pavlodar city',
    'Павлодар': 'Pavlodar city',
    'Павлодар ': 'Pavlodar city',

    'Ақсу қ.ə.': 'Aksu city',
    'Ақсу қ.ә.': 'Aksu city',
    'Ақсу қ.ә': 'Aksu city',
    'Ақсу\xa0қ.ә.': 'Aksu city',
    'Ақсу\xa0қ.ә': 'Aksu city',
    'Аксу  г.а.': 'Aksu city',
    'Аксу г.а.': 'Aksu city',

    'Екібастұз қ.ə.': 'Ekibastuz city',
    'Екібастұз қ.ә.': 'Ekibastuz city',
    'Екібастұз қ.ә': 'Ekibastuz city',
    'Екібастұз\xa0қ.ә.': 'Ekibastuz city',
    'Екібастұз\xa0қ.ә': 'Ekibastuz city',
    'Екибастуз  г.а.': 'Ekibastuz city',
    'Экибастуз  г.а.': 'Ekibastuz city',
    'Экибастуз г.а.': 'Ekibastuz city',

    # ---- Districts (Kazakh) ----
    'Ақтоғай': 'Aqtogay',
    'Ақтоғай ': 'Aqtogay',
    'Актогайский ': 'Aqtogay',
    'Баянауыл': 'Bayanauyl',
    'Баянауыл ': 'Bayanauyl',
    'Баянаульский ': 'Bayanauyl',
    'Железин': 'Zhelezin',
    'Железин ': 'Zhelezin',
    'Железинский ': 'Zhelezin',
    'Ертіс': 'Ertis',
    'Ертіс ': 'Ertis',
    'Качиры': 'Kachiry',
    'Лебяжі': 'Lebiazhi',
    'Май': 'May',
    'Май ': 'May',
    'Майский ': 'May',
    'Успен': 'Uspen',
    'Успен ': 'Uspen',
    'Шарбақты': 'Sharbakty',
    'Шарбақты ': 'Sharbakty',
    'Тереңкөл': 'Terengkol',
    'Аққулы': 'Akkuly',
    'Шарбақты ауданы': 'Sharbakty',

    # ---- Districts (Russian) ----
    'Актогайский': 'Aqtogay',
    'Баянаульский': 'Bayanauyl',
    'Железинский': 'Zhelezin',
    'Иртышский': 'Ertis',
    'Иртышский ': 'Ertis',
    'Майский': 'May',
    'Павлодарский': 'Pavlodar district',
    'Павлодарский ': 'Pavlodar district',
    'Успенский': 'Uspen',
    'Успенский ': 'Uspen',
    'Щербактинский': 'Sharbakty',
    'Щербактинский ': 'Sharbakty',
}

In [430]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [pavlodar_all_2014, pavlodar_all_2015, pavlodar_all_2016, pavlodar_all_2017,
          pavlodar_all_2018, pavlodar_all_2019, pavlodar_all_2020, pavlodar_all_2021,
          pavlodar_all_2022, pavlodar_all_2023, pavlodar_all_2024]:
    df.columns = all_columns

for df in [pavlodar_non_2015, pavlodar_non_2016, pavlodar_non_2017,
          pavlodar_non_2018, pavlodar_non_2019, pavlodar_non_2020, pavlodar_non_2021,
          pavlodar_non_2022, pavlodar_non_2023, pavlodar_non_2024]:
    df.columns = non_columns

    df[['all_nonextr_inv', 'f_nonextr_inv']] = (
        df[['all_nonextr_inv', 'f_nonextr_inv']]
        .astype(str)
        .replace('<NA>', '')
        .apply(lambda x: x.str.replace(' ', ''))
        .replace('', 0)
        .astype(float)
    )
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

In [431]:
pavlodar_non_2016

             rayon  f_nonextr_inv  l_nonextr_inv
0    Павлодар қ.ә.     17204541.0    110955565.0
1        Ақсу қ.ә.      5131723.0     17708559.0
2   Екібастұз қ.ә.    140706905.0     51504621.0
3          Ақтоғай        15000.0       330979.0
4         Баянауыл        24286.0      1450474.0
5          Железин        14397.0       221282.0
6            Ертіс            0.0       218277.0
7           Качиры        83631.0       271097.0
8           Лебяжі            0.0       241672.0
9              Май         7161.0      3414940.0
10        Павлодар        49739.0       843963.0
11           Успен            0.0       226299.0
12        Шарбақты       123924.0       295558.0

In [432]:
# ----- ALL investments -----
pavlodar_all_2014['rayon'] = pavlodar_all_2014['rayon'].replace(rayon_map_pavlodar)
pavlodar_all_2015['rayon'] = pavlodar_all_2015['rayon'].replace(rayon_map_pavlodar)
pavlodar_all_2016['rayon'] = pavlodar_all_2016['rayon'].replace(rayon_map_pavlodar)
pavlodar_all_2017['rayon'] = pavlodar_all_2017['rayon'].replace(rayon_map_pavlodar)
pavlodar_all_2018['rayon'] = pavlodar_all_2018['rayon'].replace(rayon_map_pavlodar)
pavlodar_all_2019['rayon'] = pavlodar_all_2019['rayon'].replace(rayon_map_pavlodar)
pavlodar_all_2020['rayon'] = pavlodar_all_2020['rayon'].replace(rayon_map_pavlodar)
pavlodar_all_2021['rayon'] = pavlodar_all_2021['rayon'].replace(rayon_map_pavlodar)
pavlodar_all_2022['rayon'] = pavlodar_all_2022['rayon'].replace(rayon_map_pavlodar)
pavlodar_all_2023['rayon'] = pavlodar_all_2023['rayon'].replace(rayon_map_pavlodar)
pavlodar_all_2024['rayon'] = pavlodar_all_2024['rayon'].replace(rayon_map_pavlodar)

# ----- NON-extractive investments -----
pavlodar_non_2015['rayon'] = pavlodar_non_2015['rayon'].replace(rayon_map_pavlodar)
pavlodar_non_2016['rayon'] = pavlodar_non_2016['rayon'].replace(rayon_map_pavlodar)
pavlodar_non_2017['rayon'] = pavlodar_non_2017['rayon'].replace(rayon_map_pavlodar)
pavlodar_non_2018['rayon'] = pavlodar_non_2018['rayon'].replace(rayon_map_pavlodar)
pavlodar_non_2019['rayon'] = pavlodar_non_2019['rayon'].replace(rayon_map_pavlodar)
pavlodar_non_2020['rayon'] = pavlodar_non_2020['rayon'].replace(rayon_map_pavlodar)
pavlodar_non_2021['rayon'] = pavlodar_non_2021['rayon'].replace(rayon_map_pavlodar)
pavlodar_non_2022['rayon'] = pavlodar_non_2022['rayon'].replace(rayon_map_pavlodar)
pavlodar_non_2023['rayon'] = pavlodar_non_2023['rayon'].replace(rayon_map_pavlodar)
pavlodar_non_2024['rayon'] = pavlodar_non_2024['rayon'].replace(rayon_map_pavlodar)

In [433]:
pavlodar_2014 = pavlodar_all_2014
pavlodar_2015 = pavlodar_all_2015.merge(pavlodar_non_2015, on='rayon', how='left')
pavlodar_2016 = pavlodar_all_2016.merge(pavlodar_non_2016, on='rayon', how='left')
pavlodar_2017 = pavlodar_all_2017.merge(pavlodar_non_2017, on='rayon', how='left')
pavlodar_2018 = pavlodar_all_2018.merge(pavlodar_non_2018, on='rayon', how='left')
pavlodar_2019 = pavlodar_all_2019.merge(pavlodar_non_2019, on='rayon', how='left')
pavlodar_2020 = pavlodar_all_2020.merge(pavlodar_non_2020, on='rayon', how='left')
pavlodar_2021 = pavlodar_all_2021.merge(pavlodar_non_2021, on='rayon', how='left')
pavlodar_2022 = pavlodar_all_2022.merge(pavlodar_non_2022, on='rayon', how='left')
pavlodar_2023 = pavlodar_all_2023.merge(pavlodar_non_2023, on='rayon', how='left')
pavlodar_2024 = pavlodar_all_2024.merge(pavlodar_non_2024, on='rayon', how='left')

dfs = [pavlodar_2014, pavlodar_2015, pavlodar_2016, pavlodar_2017, pavlodar_2018, pavlodar_2019, pavlodar_2020, pavlodar_2021, pavlodar_2022, pavlodar_2023, pavlodar_2024]

for i in range(11):
    df = dfs[i]
    df['oblast'] = 'Pavlodar'
    df['year'] = 2014 + i

pavlodar_inv = pd.concat([pavlodar_2014, pavlodar_2015, pavlodar_2016, pavlodar_2017, pavlodar_2018, pavlodar_2019, pavlodar_2020, pavlodar_2021, pavlodar_2022, pavlodar_2023, pavlodar_2024], ignore_index=True)
pavlodar_inv['rayon'] = (
    pavlodar_inv['rayon']
        .str.strip()          # remove hidden spaces
        .replace(rayon_map)   # enforce English names
)
pavlodar_inv

,rayon,l_all_inv,f_all_inv,oblast,year,f_nonextr_inv,l_nonextr_inv
0,Pavlodar city,91479461.0,18631916.0,Pavlodar,2014,NaN,NaN
1,Aksu city,20253725.0,3669243.0,Pavlodar,2014,NaN,NaN
2,Ekibastuz city,90754172.0,93016579.0,Pavlodar,2014,NaN,NaN
3,Aqtogay,927747.0,6265.0,Pavlodar,2014,NaN,NaN
4,Bayanauyl,6065010.0,1339029.0,Pavlodar,2014,NaN,NaN
...,...,...,...,...,...,...,...
152,Akkuly,19703771.0,0.0,Pavlodar,2024,0.0,7385206.0
153,May,20586033.0,0.0,Pavlodar,2024,0.0,3889398.0
154,Pavlodar district,20948396.0,1607374.0,Pavlodar,2024,0.0,10737008.0
155,Uspen,13167648.0,0.0,Pavlodar,2024,0.0,2016203.0
156,Sharbakty,17949832.0,136845.0,Pavlodar,2024,0.0,1673597.0

In [434]:
pavlodar_inv['rayon'].unique()

array(['Pavlodar city', 'Aksu city', 'Ekibastuz city', 'Aqtogay',
       'Bayanauyl', 'Zhelezin', 'Ertis', 'Kachiry', 'Lebiazhi', 'May',
       'Uspen', 'Sharbakty', 'Terengkol', 'Akkuly', 'Pavlodar district'],
      dtype=object)

## Employment

In [435]:
pavlodar_empl = pd.read_excel(Path("../Data/Employment/Pavlodar.xlsx"), skiprows=25, nrows=14, header=None, usecols='A:L', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
pavlodar_empl = pavlodar_empl.drop(index=3).reset_index(drop=True)
pavlodar_empl.columns = ['rayon', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
pavlodar_empl['rayon'] = pavlodar_empl['rayon'].replace(rayon_map_pavlodar)
pavlodar_empl
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    pavlodar_empl[i] = pavlodar_empl[i].astype(float)
    pavlodar_employment = pavlodar_empl.melt(id_vars='rayon', value_vars=[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024], var_name='year', value_name='employment')
pavlodar_employment

                 rayon  year  employment
0        Pavlodar city  2014     187.023
1            Aksu city  2014      39.113
2       Ekibastuz city  2014      79.064
3              Aqtogay  2014       7.900
4            Bayanauyl  2014      16.474
..                 ...   ...         ...
138             Akkuly  2024       6.500
139                May  2024       5.400
140  Pavlodar district  2024      14.400
141              Uspen  2024       6.700
142          Sharbakty  2024      10.200

[143 rows x 3 columns]

In [436]:
pavlodar_employment['rayon'].unique()

array(['Pavlodar city', 'Aksu city', 'Ekibastuz city', 'Aqtogay',
       'Bayanauyl', 'Zhelezin', 'Ertis', 'Terengkol', 'Akkuly', 'May',
       'Pavlodar district', 'Uspen', 'Sharbakty'], dtype=object)

## Other Controls

In [437]:
pavlodar_city = pd.read_excel(Path("../Data/Controls/Pavlodar_All.xlsx"), sheet_name="Павлодар г.а. ", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
pavlodar_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
pavlodar_city = pavlodar_city.loc[[89, 118, 163]].reset_index(drop=True)
pavlodar_city['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    pavlodar_city[i] = pavlodar_city[i].astype(str)
    pavlodar_city[i] = pavlodar_city[i].str.replace(',', '.')
    pavlodar_city[i] = pavlodar_city[i].str.replace(')', '')
    pavlodar_city[i] = pavlodar_city[i].str.replace(' ', '')
    pavlodar_city[i] = pavlodar_city[i].str.replace('\xa0', '')
    pavlodar_city[i] = pavlodar_city[i].str.replace('*', '')
    pavlodar_city[i] = pavlodar_city[i].astype(float)
pavlodar_city = pd.melt(pavlodar_city, id_vars=['Indicator'], var_name='year', value_name='value')
pavlodar_city = pavlodar_city.pivot(index='year', columns='Indicator', values='value').reset_index()
pavlodar_city.insert(0, 'rayon', 'Pavlodar city')
pavlodar_city.columns.name = None
pavlodar_city

            rayon  year  agriculture  production  retail
0   Pavlodar city  2014      11980.0    447600.0   244.7
1   Pavlodar city  2015       8770.1    441639.0   205.5
2   Pavlodar city  2016       7874.0    587011.0   211.7
3   Pavlodar city  2017       9900.7    683282.0   233.1
4   Pavlodar city  2018      10528.2    786893.0   239.2
5   Pavlodar city  2019      11736.9    813581.0   255.3
6   Pavlodar city  2020      15553.2    849673.0   274.8
7   Pavlodar city  2021      19823.1   1083209.0   296.9
8   Pavlodar city  2022      22926.4   1269565.0   343.7
9   Pavlodar city  2023      22716.0   1206403.0   420.9
10  Pavlodar city  2024      22738.2   1330851.0   454.0

In [438]:
aksu_city = pd.read_excel(Path("../Data/Controls/Pavlodar_All.xlsx"), sheet_name="Аксу г.а. ", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
aksu_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
aksu_city = aksu_city.loc[[86, 112, 155]].reset_index(drop=True)
aksu_city['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    aksu_city[i] = aksu_city[i].astype(str)
    aksu_city[i] = aksu_city[i].str.replace(',', '.')
    aksu_city[i] = aksu_city[i].str.replace(')', '')
    aksu_city[i] = aksu_city[i].str.replace(' ', '')
    aksu_city[i] = aksu_city[i].str.replace('\xa0', '')
    aksu_city[i] = aksu_city[i].str.replace('*', '')
    aksu_city[i] = aksu_city[i].astype(float)
aksu_city = pd.melt(aksu_city, id_vars=['Indicator'], var_name='year', value_name='value')
aksu_city = aksu_city.pivot(index='year', columns='Indicator', values='value').reset_index()
aksu_city.insert(0, 'rayon', 'Aksu city')
aksu_city.columns.name = None
aksu_city

        rayon  year  agriculture  production  retail
0   Aksu city  2014      12814.4    284199.0     7.0
1   Aksu city  2015      12752.1    285336.0    14.6
2   Aksu city  2016      13385.2    387419.0    27.2
3   Aksu city  2017      17328.4    522505.0    23.4
4   Aksu city  2018      18513.3    535486.0    27.2
5   Aksu city  2019      19640.7    485305.0     NaN
6   Aksu city  2020      24660.8    438822.0    27.7
7   Aksu city  2021      32955.0    647711.0    31.1
8   Aksu city  2022      44236.8    792091.0    37.5
9   Aksu city  2023      42357.7    681187.0    42.3
10  Aksu city  2024      41657.0    721740.0    46.2

In [439]:
ekibastuz_city = pd.read_excel(Path("../Data/Controls/Pavlodar_All.xlsx"), sheet_name="Экибастуз г.а.", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
ekibastuz_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
ekibastuz_city = ekibastuz_city.loc[[88, 116, 160]].reset_index(drop=True)
ekibastuz_city['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    ekibastuz_city[i] = ekibastuz_city[i].astype(str)
    ekibastuz_city[i] = ekibastuz_city[i].str.replace(',', '.')
    ekibastuz_city[i] = ekibastuz_city[i].str.replace(')', '')
    ekibastuz_city[i] = ekibastuz_city[i].str.replace(' ', '')
    ekibastuz_city[i] = ekibastuz_city[i].str.replace('\xa0', '')
    ekibastuz_city[i] = ekibastuz_city[i].str.replace('*', '')
    ekibastuz_city[i] = ekibastuz_city[i].astype(float)
ekibastuz_city = pd.melt(ekibastuz_city, id_vars=['Indicator'], var_name='year', value_name='value')
ekibastuz_city = ekibastuz_city.pivot(index='year', columns='Indicator', values='value').reset_index()
ekibastuz_city.insert(0, 'rayon', 'Ekibastuz city')
ekibastuz_city.columns.name = None
ekibastuz_city

             rayon  year  agriculture  production  retail
0   Ekibastuz city  2014       8041.9    342402.0    24.7
1   Ekibastuz city  2015       8543.5    279468.0    34.7
2   Ekibastuz city  2016       9160.3    348168.0    51.8
3   Ekibastuz city  2017      11604.3    519761.0    55.0
4   Ekibastuz city  2018      12761.2    601740.0    61.6
5   Ekibastuz city  2019      13781.9    622933.0    66.5
6   Ekibastuz city  2020      18281.8    761417.0    71.1
7   Ekibastuz city  2021      19101.9    966850.0    78.6
8   Ekibastuz city  2022      28267.1   1054919.0    95.3
9   Ekibastuz city  2023      26328.8   1154601.0   137.9
10  Ekibastuz city  2024      27770.9   1271899.0   133.1

In [440]:
aqtogay = pd.read_excel(Path("../Data/Controls/Pavlodar_All.xlsx"), sheet_name="Актогайский район", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
aqtogay.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
aqtogay = aqtogay.loc[[65, 107, 151]].reset_index(drop=True)
aqtogay['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    aqtogay[i] = aqtogay[i].astype(str)
    aqtogay[i] = aqtogay[i].str.replace(',', '.')
    aqtogay[i] = aqtogay[i].str.replace(')', '')
    aqtogay[i] = aqtogay[i].str.replace(' ', '')
    aqtogay[i] = aqtogay[i].str.replace('\xa0', '')
    aqtogay[i] = aqtogay[i].str.replace('*', '')
    aqtogay[i] = aqtogay[i].astype(float)
aqtogay = pd.melt(aqtogay, id_vars=['Indicator'], var_name='year', value_name='value')
aqtogay = aqtogay.pivot(index='year', columns='Indicator', values='value').reset_index()
aqtogay.insert(0, 'rayon', 'Aqtogay')
aqtogay.columns.name = None
aqtogay

      rayon  year  agriculture  production  retail
0   Aqtogay  2014       7054.5       935.0     0.3
1   Aqtogay  2015       7950.8      1104.0     0.6
2   Aqtogay  2016       9423.8      1760.0     2.6
3   Aqtogay  2017      11742.2      4103.0     3.5
4   Aqtogay  2018      13231.7      5616.0     3.9
5   Aqtogay  2019      14192.6      6192.0     4.1
6   Aqtogay  2020      16941.4      8087.0     4.7
7   Aqtogay  2021      23360.6     10421.0     5.6
8   Aqtogay  2022      27516.5     12313.0     6.7
9   Aqtogay  2023      21957.1     15794.0     9.5
10  Aqtogay  2024      22219.3     17657.0     7.3

In [441]:
bayanauyl = pd.read_excel(Path("../Data/Controls/Pavlodar_All.xlsx"), sheet_name="Баянаульский район", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
bayanauyl.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
bayanauyl = bayanauyl.loc[[86, 108, 152]].reset_index(drop=True)
bayanauyl['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    bayanauyl[i] = bayanauyl[i].astype(str)
    bayanauyl[i] = bayanauyl[i].str.replace(',', '.')
    bayanauyl[i] = bayanauyl[i].str.replace(')', '')
    bayanauyl[i] = bayanauyl[i].str.replace(' ', '')
    bayanauyl[i] = bayanauyl[i].str.replace('\xa0', '')
    bayanauyl[i] = bayanauyl[i].str.replace('*', '')
    bayanauyl[i] = bayanauyl[i].astype(float)
bayanauyl = pd.melt(bayanauyl, id_vars=['Indicator'], var_name='year', value_name='value')
bayanauyl = bayanauyl.pivot(index='year', columns='Indicator', values='value').reset_index()
bayanauyl.insert(0, 'rayon', 'Bayanauyl')
bayanauyl.columns.name = None
bayanauyl

        rayon  year  agriculture  production  retail
0   Bayanauyl  2014       9301.7     16160.0     1.0
1   Bayanauyl  2015      10717.9     13363.0     1.2
2   Bayanauyl  2016      11262.9     20868.0     0.9
3   Bayanauyl  2017      12943.1     25629.0     2.9
4   Bayanauyl  2018      15712.9     32696.0     3.2
5   Bayanauyl  2019      17641.0     34422.0     6.0
6   Bayanauyl  2020      19181.7     34912.0     6.8
7   Bayanauyl  2021      22458.5     42747.0     7.3
8   Bayanauyl  2022      38903.1     45741.0     9.3
9   Bayanauyl  2023      22423.0     45477.0    10.4
10  Bayanauyl  2024      23229.1     48288.0     6.3

In [442]:
zhelezin = pd.read_excel(Path("../Data/Controls/Pavlodar_All.xlsx"), sheet_name="Железинский район", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
zhelezin.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
zhelezin = zhelezin.loc[[86, 107, 151]].reset_index(drop=True)
zhelezin['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    zhelezin[i] = zhelezin[i].astype(str)
    zhelezin[i] = zhelezin[i].str.replace(',', '.')
    zhelezin[i] = zhelezin[i].str.replace(')', '')
    zhelezin[i] = zhelezin[i].str.replace(' ', '')
    zhelezin[i] = zhelezin[i].str.replace('\xa0', '')
    zhelezin[i] = zhelezin[i].str.replace('*', '')
    zhelezin[i] = zhelezin[i].astype(float)
zhelezin = pd.melt(zhelezin, id_vars=['Indicator'], var_name='year', value_name='value')
zhelezin = zhelezin.pivot(index='year', columns='Indicator', values='value').reset_index()
zhelezin.insert(0, 'rayon', 'Zhelezin')
zhelezin.columns.name = None
zhelezin

       rayon  year  agriculture  production  retail
0   Zhelezin  2014      11080.2      2575.0     0.7
1   Zhelezin  2015      12620.9      3021.0     0.8
2   Zhelezin  2016      15203.6      3821.0     2.7
3   Zhelezin  2017      15462.1      2787.0     3.7
4   Zhelezin  2018      18889.4      2481.0     4.6
5   Zhelezin  2019      18443.5      3047.0     4.9
6   Zhelezin  2020      26109.9      2883.0     4.7
7   Zhelezin  2021      41363.0      3830.0     5.1
8   Zhelezin  2022      57499.9      2108.0    17.9
9   Zhelezin  2023      31114.4      1760.0     5.2
10  Zhelezin  2024      32158.7      1974.0     7.9

In [443]:
ertis = pd.read_excel(Path("../Data/Controls/Pavlodar_All.xlsx"), sheet_name="Иртышский район", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
ertis.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
ertis = ertis.loc[[86, 106, 150]].reset_index(drop=True)
ertis['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    ertis[i] = ertis[i].astype(str)
    ertis[i] = ertis[i].str.replace(',', '.')
    ertis[i] = ertis[i].str.replace(')', '')
    ertis[i] = ertis[i].str.replace(' ', '')
    ertis[i] = ertis[i].str.replace('\xa0', '')
    ertis[i] = ertis[i].str.replace('*', '')
    ertis[i] = ertis[i].astype(float)
ertis = pd.melt(ertis, id_vars=['Indicator'], var_name='year', value_name='value')
ertis = ertis.pivot(index='year', columns='Indicator', values='value').reset_index()
ertis.insert(0, 'rayon', 'Ertis')
ertis.columns.name = None
ertis

    rayon  year  agriculture  production  retail
0   Ertis  2014       8826.8      2038.0     0.4
1   Ertis  2015      12979.7      1717.0     0.7
2   Ertis  2016      14850.2      1628.0     5.9
3   Ertis  2017      18349.3      2354.0     4.9
4   Ertis  2018      17668.7      2674.0     5.6
5   Ertis  2019      18475.5      3289.0     6.0
6   Ertis  2020      30285.9      4121.0     6.2
7   Ertis  2021      42898.6      5204.0    11.9
8   Ertis  2022      44332.6      2539.0    14.0
9   Ertis  2023      26632.8      3207.0     5.4
10  Ertis  2024      43855.5      3087.0     9.9

In [444]:
terengkol = pd.read_excel(Path("../Data/Controls/Pavlodar_All.xlsx"), sheet_name="Теренкөл район", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
terengkol.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
terengkol = terengkol.loc[[87, 108, 152]].reset_index(drop=True)
terengkol['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    terengkol[i] = terengkol[i].astype(str)
    terengkol[i] = terengkol[i].str.replace(',', '.')
    terengkol[i] = terengkol[i].str.replace(')', '')
    terengkol[i] = terengkol[i].str.replace(' ', '')
    terengkol[i] = terengkol[i].str.replace('\xa0', '')
    terengkol[i] = terengkol[i].str.replace('*', '')
    terengkol[i] = terengkol[i].astype(float)
terengkol = pd.melt(terengkol, id_vars=['Indicator'], var_name='year', value_name='value')
terengkol = terengkol.pivot(index='year', columns='Indicator', values='value').reset_index()
terengkol.insert(0, 'rayon', 'Terengkol')
terengkol.columns.name = None
terengkol

        rayon  year  agriculture  production  retail
0   Terengkol  2014       9172.1      1749.0     1.4
1   Terengkol  2015      13972.1      2240.0     2.8
2   Terengkol  2016      17102.1      2264.0     5.4
3   Terengkol  2017      21907.6      2927.0     5.5
4   Terengkol  2018      22675.5      3619.0     9.8
5   Terengkol  2019      23294.8      4614.0    10.3
6   Terengkol  2020      34023.8      5321.0    11.0
7   Terengkol  2021      50594.0      5690.0    10.8
8   Terengkol  2022      44963.2      3041.0    13.2
9   Terengkol  2023      31341.0      3520.0    14.8
10  Terengkol  2024      41269.7      2828.0    12.5

In [445]:
akkuly = pd.read_excel(Path("../Data/Controls/Pavlodar_All.xlsx"), sheet_name="Аққулы район", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
akkuly.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
akkuly = akkuly.loc[[86, 108, 151]].reset_index(drop=True)
akkuly['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    akkuly[i] = akkuly[i].astype(str)
    akkuly[i] = akkuly[i].str.replace(',', '.')
    akkuly[i] = akkuly[i].str.replace(')', '')
    akkuly[i] = akkuly[i].str.replace(' ', '')
    akkuly[i] = akkuly[i].str.replace('\xa0', '')
    akkuly[i] = akkuly[i].str.replace('*', '')
    akkuly[i] = akkuly[i].astype(float)
akkuly = pd.melt(akkuly, id_vars=['Indicator'], var_name='year', value_name='value')
akkuly = akkuly.pivot(index='year', columns='Indicator', values='value').reset_index()
akkuly.insert(0, 'rayon', 'Akkuly')
akkuly.columns.name = None
akkuly

     rayon  year  agriculture  production  retail
0   Akkuly  2014      10170.5      1416.0     0.1
1   Akkuly  2015      11825.7      1242.0     0.3
2   Akkuly  2016      11522.0      1169.0     1.1
3   Akkuly  2017      14332.3      1276.0     2.5
4   Akkuly  2018      15704.4      1328.0     2.9
5   Akkuly  2019      17799.5      1463.0     NaN
6   Akkuly  2020      19420.1      1488.0     3.1
7   Akkuly  2021      30254.3      1663.0     3.3
8   Akkuly  2022      37514.7       336.0     0.9
9   Akkuly  2023      32741.2       242.0     3.5
10  Akkuly  2024      31782.8       277.0     5.5

In [446]:
may = pd.read_excel(Path("../Data/Controls/Pavlodar_All.xlsx"), sheet_name="Майский район", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
may.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
may = may.loc[[86, 108, 152]].reset_index(drop=True)
may['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    may[i] = may[i].astype(str)
    may[i] = may[i].str.replace(',', '.')
    may[i] = may[i].str.replace(')', '')
    may[i] = may[i].str.replace(' ', '')
    may[i] = may[i].str.replace('\xa0', '')
    may[i] = may[i].str.replace('*', '')
    may[i] = may[i].astype(float)
may = pd.melt(may, id_vars=['Indicator'], var_name='year', value_name='value')
may = may.pivot(index='year', columns='Indicator', values='value').reset_index()
may.insert(0, 'rayon', 'May')
may.columns.name = None
may

   rayon  year  agriculture  production  retail
0    May  2014       5824.7      1845.0     0.3
1    May  2015       6655.2      3112.0     0.5
2    May  2016       6944.4      4344.0     0.6
3    May  2017       8096.4      4550.0     4.1
4    May  2018       9931.3      3610.0     4.3
5    May  2019      11977.1      3323.0     4.1
6    May  2020      14465.2      3151.0     4.9
7    May  2021      16673.1      4882.0     5.3
8    May  2022      33502.9      4903.0     6.2
9    May  2023      17678.3      2202.0     6.9
10   May  2024      22137.4      1893.0     8.4

In [447]:
pavlodar_district = pd.read_excel(Path("../Data/Controls/Pavlodar_All.xlsx"), sheet_name="Павлодарский район", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
pavlodar_district.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
pavlodar_district = pavlodar_district.loc[[85, 109, 152]].reset_index(drop=True)
pavlodar_district['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    pavlodar_district[i] = pavlodar_district[i].astype(str)
    pavlodar_district[i] = pavlodar_district[i].str.replace(',', '.')
    pavlodar_district[i] = pavlodar_district[i].str.replace(')', '')
    pavlodar_district[i] = pavlodar_district[i].str.replace(' ', '')
    pavlodar_district[i] = pavlodar_district[i].str.replace('\xa0', '')
    pavlodar_district[i] = pavlodar_district[i].str.replace('*', '')
    pavlodar_district[i] = pavlodar_district[i].astype(float)
pavlodar_district = pd.melt(pavlodar_district, id_vars=['Indicator'], var_name='year', value_name='value')
pavlodar_district = pavlodar_district.pivot(index='year', columns='Indicator', values='value').reset_index()
pavlodar_district.insert(0, 'rayon', 'Pavlodar district')
pavlodar_district.columns.name = None
pavlodar_district

                rayon  year  agriculture  production  retail
0   Pavlodar district  2014      20952.6      3615.0     1.7
1   Pavlodar district  2015      21151.8      4632.0     6.4
2   Pavlodar district  2016      24552.1      4574.0     0.9
3   Pavlodar district  2017      28370.0      4354.0     3.7
4   Pavlodar district  2018      37328.8      4286.0     4.1
5   Pavlodar district  2019      30880.2      5017.0     4.9
6   Pavlodar district  2020      37073.0      3776.0     5.3
7   Pavlodar district  2021      53416.1      6070.0     5.7
8   Pavlodar district  2022      75076.6      5238.0     8.2
9   Pavlodar district  2023      62953.5      4874.0    10.8
10  Pavlodar district  2024      70055.8      4680.0     6.8

In [448]:
uspen = pd.read_excel(Path("../Data/Controls/Pavlodar_All.xlsx"), sheet_name="Успенский район", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
uspen.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
uspen = uspen.loc[[87, 109, 153]].reset_index(drop=True)
uspen['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    uspen[i] = uspen[i].astype(str)
    uspen[i] = uspen[i].str.replace(',', '.')
    uspen[i] = uspen[i].str.replace(')', '')
    uspen[i] = uspen[i].str.replace(' ', '')
    uspen[i] = uspen[i].str.replace('\xa0', '')
    uspen[i] = uspen[i].str.replace('*', '')
    uspen[i] = uspen[i].astype(float)
uspen = pd.melt(uspen, id_vars=['Indicator'], var_name='year', value_name='value')
uspen = uspen.pivot(index='year', columns='Indicator', values='value').reset_index()
uspen.insert(0, 'rayon', 'Uspen')
uspen.columns.name = None
uspen

    rayon  year  agriculture  production  retail
0   Uspen  2014       8086.3      1708.0     1.1
1   Uspen  2015      11245.3      2222.0     2.1
2   Uspen  2016      13978.5      2137.0     4.5
3   Uspen  2017      14961.3      2333.0     4.3
4   Uspen  2018      15626.9      1960.0     4.6
5   Uspen  2019      15550.4      2191.0     4.8
6   Uspen  2020      20932.4      2397.0     5.1
7   Uspen  2021      37740.5      2753.0     5.7
8   Uspen  2022      28181.5      1084.0     6.8
9   Uspen  2023      20054.4      1130.0     5.1
10  Uspen  2024      33277.3      1200.0     7.3

In [449]:
sharbakty = pd.read_excel(Path("../Data/Controls/Pavlodar_All.xlsx"), sheet_name="Щербактинский район", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
sharbakty.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
sharbakty = sharbakty.loc[[86, 109, 152]].reset_index(drop=True)
sharbakty['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    sharbakty[i] = sharbakty[i].astype(str)
    sharbakty[i] = sharbakty[i].str.replace(',', '.')
    sharbakty[i] = sharbakty[i].str.replace(')', '')
    sharbakty[i] = sharbakty[i].str.replace(' ', '')
    sharbakty[i] = sharbakty[i].str.replace('\xa0', '')
    sharbakty[i] = sharbakty[i].str.replace('*', '')
    sharbakty[i] = sharbakty[i].astype(float)
sharbakty = pd.melt(sharbakty, id_vars=['Indicator'], var_name='year', value_name='value')
sharbakty = sharbakty.pivot(index='year', columns='Indicator', values='value').reset_index()
sharbakty.insert(0, 'rayon', 'Sharbakty')
sharbakty.columns.name = None
sharbakty

        rayon  year  agriculture  production  retail
0   Sharbakty  2014      11687.6      4381.0     6.8
1   Sharbakty  2015      13222.8      5297.0     8.1
2   Sharbakty  2016      16283.0      6739.0     7.0
3   Sharbakty  2017      19424.3      6220.0     7.8
4   Sharbakty  2018      19920.6      6434.0     8.4
5   Sharbakty  2019      23007.9      7615.0     8.8
6   Sharbakty  2020      25215.1      6829.0     9.5
7   Sharbakty  2021      37555.3     10511.0    10.3
8   Sharbakty  2022      34545.0      7196.0    12.5
9   Sharbakty  2023      32022.0      6571.0    16.3
10  Sharbakty  2024      39755.7      6810.0    13.4

In [450]:
pavlodar_controls = pd.concat([aksu_city, pavlodar_city, ekibastuz_city, aqtogay, bayanauyl, zhelezin, ertis, terengkol, akkuly, may, pavlodar_district, uspen, sharbakty], ignore_index=True)
pavlodar_controls

         rayon  year  agriculture  production  retail
0    Aksu city  2014      12814.4    284199.0     7.0
1    Aksu city  2015      12752.1    285336.0    14.6
2    Aksu city  2016      13385.2    387419.0    27.2
3    Aksu city  2017      17328.4    522505.0    23.4
4    Aksu city  2018      18513.3    535486.0    27.2
..         ...   ...          ...         ...     ...
138  Sharbakty  2020      25215.1      6829.0     9.5
139  Sharbakty  2021      37555.3     10511.0    10.3
140  Sharbakty  2022      34545.0      7196.0    12.5
141  Sharbakty  2023      32022.0      6571.0    16.3
142  Sharbakty  2024      39755.7      6810.0    13.4

[143 rows x 5 columns]

## PPI

In [451]:
pavlodar_ppi = pd.read_excel(
    Path("../Data/PPI/Pavlodar.xlsx"),
    header=2,
    usecols='Y:AI',
    nrows=83,
    na_values=['x', 'х', '-', '', ' ', '...']
)
pavlodar_ppi.columns = [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
rayons = list(pavlodar_inv['rayon'].unique())

dfs = []

for rayon in rayons:
    df_temp = pd.DataFrame({
        'rayon': [rayon] * len(range(2014, 2025)),
        'year': list(range(2014, 2025)),
        'ppi': pavlodar_ppi.iloc[-1].values
    })
    dfs.append(df_temp)

pavlodar_ppi = pd.concat(dfs, ignore_index=True)
pavlodar_ppi['ppi'] = pavlodar_ppi['ppi'].astype(str).str.replace(',', '.')
pavlodar_ppi['ppi'] = pavlodar_ppi['ppi'].astype(str).str.replace(')', '')
pavlodar_ppi['ppi'] = pavlodar_ppi['ppi'].astype(str).str.replace(' ', '')
pavlodar_ppi['ppi'] = pavlodar_ppi['ppi'].astype(str).str.replace('\xa0', '')
pavlodar_ppi['ppi'] = pavlodar_ppi['ppi'].astype(str).str.replace('*', '')
pavlodar_ppi['ppi'] = pavlodar_ppi['ppi'].astype(float)

pavlodar_ppi

                 rayon  year    ppi
0        Pavlodar city  2014  111.9
1        Pavlodar city  2015  106.3
2        Pavlodar city  2016  127.4
3        Pavlodar city  2017  109.7
4        Pavlodar city  2018  114.2
..                 ...   ...    ...
160  Pavlodar district  2020  107.6
161  Pavlodar district  2021  125.9
162  Pavlodar district  2022  102.5
163  Pavlodar district  2023   95.0
164  Pavlodar district  2024  115.5

[165 rows x 3 columns]

In [452]:
pavlodar_ppi['rayon'].unique()

array(['Pavlodar city', 'Aksu city', 'Ekibastuz city', 'Aqtogay',
       'Bayanauyl', 'Zhelezin', 'Ertis', 'Kachiry', 'Lebiazhi', 'May',
       'Uspen', 'Sharbakty', 'Terengkol', 'Akkuly', 'Pavlodar district'],
      dtype=object)

## Combine

In [453]:
dfs_pavlodar = [pavlodar_inv, pavlodar_employment, pavlodar_controls, pavlodar_ppi]
pavlodar_merged = reduce(lambda left, right: pd.merge(left, right, on=['rayon', 'year'], how='outer'), dfs_pavlodar)
pavlodar_merged['oblast'] = pavlodar_merged['oblast'].fillna('Pavlodar')
pavlodar_merged

,rayon,l_all_inv,f_all_inv,oblast,year,f_nonextr_inv,l_nonextr_inv,employment,agriculture,production,retail,ppi
0,Akkuly,<NA>,<NA>,Pavlodar,2014,NaN,NaN,8.216,10170.5,1416.0,0.1,111.9
1,Akkuly,<NA>,<NA>,Pavlodar,2015,NaN,NaN,6.876,11825.7,1242.0,0.3,106.3
2,Akkuly,<NA>,<NA>,Pavlodar,2016,NaN,NaN,6.739,11522.0,1169.0,1.1,127.4
3,Akkuly,<NA>,<NA>,Pavlodar,2017,NaN,NaN,6.568,14332.3,1276.0,2.5,109.7
4,Akkuly,20929641.0,<NA>,Pavlodar,2018,0.0,700732.0,6.591,15704.4,1328.0,2.9,114.2
...,...,...,...,...,...,...,...,...,...,...,...,...
182,Zhelezin,6535942.0,470946.0,Pavlodar,2020,285739.0,2045243.0,8.562,26109.9,2883.0,4.7,107.6
183,Zhelezin,7991939.0,544134.0,Pavlodar,2021,235110.0,2048911.0,8.503,41363.0,3830.0,5.1,125.9
184,Zhelezin,11974373.0,250000.0,Pavlodar,2022,250000.0,2351431.0,8.503,57499.9,2108.0,17.9,102.5
185,Zhelezin,13067639.0,2422520.0,Pavlodar,2023,370200.0,3676540.0,8.872,31114.4,1760.0,5.2,95.0
186,Zhelezin,13994296.0,2738400.0,Pavlodar,2024,0.0,2824956.0,8.700,32158.7,1974.0,7.9,115.5

# Shymkent-city

## Investments

In [454]:
# EXCEL
shymkent_city_all_2020 = pd.read_excel(Path("../Data/Investments/Shymkent-city/2020_Investments.xls"), sheet_name='12', header=3, nrows=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
shymkent_city_all_2021 = pd.read_excel(Path("../Data/Investments/Shymkent-city/2021_Investments.xls"), sheet_name='12', header=3, nrows=15, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
shymkent_city_all_2022 = pd.read_excel(Path("../Data/Investments/Shymkent-city/2022_Investments.xlsx"), sheet_name='20', header=2, nrows=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
shymkent_city_all_2023 = pd.read_excel(Path("../Data/Investments/Shymkent-city/2023_Investments.xlsx"), sheet_name='20', header=2, nrows=8, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
shymkent_city_all_2024 = pd.read_excel(Path("../Data/Investments/Shymkent-city/2024_Investments.xlsx"), sheet_name='12', header=2, nrows=7, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
shymkent_city_all_2024

# EXCEL
shymkent_city_non_2020 = pd.read_excel(Path("../Data/Investments/Shymkent-city/2020_Investments.xls"), sheet_name='13', header=3, nrows=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
shymkent_city_non_2021 = pd.read_excel(Path("../Data/Investments/Shymkent-city/2021_Investments.xls"), sheet_name='13', header=3, nrows=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
shymkent_city_non_2022 = pd.read_excel(Path("../Data/Investments/Shymkent-city/2022_Investments.xlsx"), sheet_name='21', header=2, nrows=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
shymkent_city_non_2023 = pd.read_excel(Path("../Data/Investments/Shymkent-city/2023_Investments.xlsx"), sheet_name='21', header=2, nrows=7, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
shymkent_city_non_2024 = pd.read_excel(Path("../Data/Investments/Shymkent-city/2024_Investments.xlsx"), sheet_name='13', header=2, nrows=7, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [455]:
dfs = [shymkent_city_all_2020, shymkent_city_all_2021, shymkent_city_all_2022, shymkent_city_all_2023, shymkent_city_all_2024,
      shymkent_city_non_2020, shymkent_city_non_2021, shymkent_city_non_2022, shymkent_city_non_2023, shymkent_city_non_2024]

lists = []

for df in dfs:
    lists.extend(df.iloc[:, 0].unique())

unique_lists = pd.Series(lists).unique()
unique_lists

array(['Шымкент қаласы', 'Абай ауданы', 'Әл  Фараби ', 'Еңбекші ',
       'Қаратау ', 'Әл-Фараби ', 'г. Шымкент', 'Абайский район',
       'Аль-Фарабийский ', 'Енбекшинский', 'Каратауский', 'Тұран',
       'Әл -Фараби '], dtype=object)

In [456]:
rayon_map_shymkent = {

    # ---- City-level ----
    'Шымкент қаласы': 'Shymkent city',
    'г. Шымкент': 'Shymkent city',
    'город Шымкент': 'Shymkent city',

    # ---- Abay district ----
    'Абай ауданы': 'Abay',
    'Абайский район': 'Abay',
    'Абайский район': 'Abay',

    # ---- Al-Farabi district ----
    'Әл  Фараби ': 'Al-Farabi',
    'Әл-Фараби ': 'Al-Farabi',
    'Әл -Фараби ': 'Al-Farabi',
    'Аль-Фарабийский ': 'Al-Farabi',
    'Аль-Фарабийский ': 'Al-Farabi',

    # ---- Enbekshi district ----
    'Еңбекші ': 'Enbekshi',
    'Енбекшинский': 'Enbekshi',
    'Енбекшинский ': 'Enbekshi',

    # ---- Karatau district ----
    'Қаратау ': 'Karatau',
    'Каратауский': 'Karatau',
    'Каратауский ': 'Karatau',

    # ---- Turan district ----
    'Тұран': 'Turan'
}

In [457]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [shymkent_city_all_2020, shymkent_city_all_2021,
          shymkent_city_all_2022, shymkent_city_all_2023, shymkent_city_all_2024]:
    df.columns = all_columns

for df in [shymkent_city_non_2020, shymkent_city_non_2021,
          shymkent_city_non_2022, shymkent_city_non_2023, shymkent_city_non_2024]:
    df.columns = non_columns

    df[['all_nonextr_inv', 'f_nonextr_inv']] = (
        df[['all_nonextr_inv', 'f_nonextr_inv']]
        .astype(str)
        .apply(lambda x: x.str.replace(' ', ''))
        .astype(float)
    )

    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

In [458]:
# ----- ALL investments -----
shymkent_city_all_2020['rayon'] = shymkent_city_all_2020['rayon'].replace(rayon_map_shymkent)
shymkent_city_all_2021['rayon'] = shymkent_city_all_2021['rayon'].replace(rayon_map_shymkent)
shymkent_city_all_2022['rayon'] = shymkent_city_all_2022['rayon'].replace(rayon_map_shymkent)
shymkent_city_all_2023['rayon'] = shymkent_city_all_2023['rayon'].replace(rayon_map_shymkent)
shymkent_city_all_2024['rayon'] = shymkent_city_all_2024['rayon'].replace(rayon_map_shymkent)

# ----- NON-extractive investments -----
shymkent_city_non_2020['rayon'] = shymkent_city_non_2020['rayon'].replace(rayon_map_shymkent)
shymkent_city_non_2021['rayon'] = shymkent_city_non_2021['rayon'].replace(rayon_map_shymkent)
shymkent_city_non_2022['rayon'] = shymkent_city_non_2022['rayon'].replace(rayon_map_shymkent)
shymkent_city_non_2023['rayon'] = shymkent_city_non_2023['rayon'].replace(rayon_map_shymkent)
shymkent_city_non_2024['rayon'] = shymkent_city_non_2024['rayon'].replace(rayon_map_shymkent)

In [459]:
shymkent_city_2020 = shymkent_city_all_2020.merge(shymkent_city_non_2020, on='rayon', how='left')
shymkent_city_2021 = shymkent_city_all_2021.merge(shymkent_city_non_2021, on='rayon', how='left')
shymkent_city_2022 = shymkent_city_all_2022.merge(shymkent_city_non_2022, on='rayon', how='left')
shymkent_city_2023 = shymkent_city_all_2023.merge(shymkent_city_non_2023, on='rayon', how='left')
shymkent_city_2024 = shymkent_city_all_2024.merge(shymkent_city_non_2024, on='rayon', how='left')

dfs = [shymkent_city_2020, shymkent_city_2021, shymkent_city_2022, shymkent_city_2023, shymkent_city_2024]

for i in range(5):
    df = dfs[i]
    df['oblast'] = 'Shymkent-city'
    df['year'] = 2020 + i

shymkent_city_inv = pd.concat([shymkent_city_2020, shymkent_city_2021, shymkent_city_2022, shymkent_city_2023, shymkent_city_2024], ignore_index=True)
shymkent_city_inv['rayon'] = (
    shymkent_city_inv['rayon']
        .str.strip()          # remove hidden spaces
        .replace(rayon_map)   # enforce English names
)
shymkent_city_inv

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year
0,Shymkent city,265611052,12896229,12834967.0,152589296.0,Shymkent-city,2020
1,Abay,52845300,1839874,1778842.0,33210392.0,Shymkent-city,2020
2,Al-Farabi,21259575,5216243,5216243.0,14793294.0,Shymkent-city,2020
3,Enbekshi,36718167,5702964,5702734.0,30886929.0,Shymkent-city,2020
4,Karatau,154788011,137149,137149.0,73698680.0,Shymkent-city,2020
5,Shymkent city,435756547,26296401,26295831.0,309513954.0,Shymkent-city,2021
6,Abay,85849484,7438504,7438504.0,54808163.0,Shymkent-city,2021
7,Al-Farabi,65539007,5373116,5373116.0,46793904.0,Shymkent-city,2021
8,Enbekshi,115191941,12161715,12161145.0,103341760.0,Shymkent-city,2021
9,Karatau,169176115,1323066,1323066.0,104570126.0,Shymkent-city,2021
10,Shymkent city,529711363,19906460,19656460.0,382965675.0,Shymkent-city,2022
11,Abay,92594589,9001322,9001322.0,70565782.0,Shymkent-city,2022
12,Al-Farabi,88601724,4204018,4204018.0,73571354.0,Shymkent-city,2022
13,Enbekshi,106910209,4246338,3996338.0,90457533.0,Shymkent-city,2022
14,Karatau,241604841,2454782,2454782.0,148371006.0,Shymkent-city,2022
15,Shymkent city,632024858,29715411,29715411.0,497388176.0,Shymkent-city,2023
16,Abay,183358677,7446606,7446606.0,158356204.0,Shymkent-city,2023
17,Al-Farabi,54877060,11935455,11935455.0,42692836.0,Shymkent-city,2023
18,Enbekshi,82780458,8695525,8695525.0,69359916.0,Shymkent-city,2023
19,Karatau,292159435,498148,498148.0,209671045.0,Shymkent-city,2023
20,Turan,18849230,1139679,1139679.0,17308173.0,Shymkent-city,2023
21,Shymkent city,721659516,44412825,36668166.0,517534148.0,Shymkent-city,2024
22,Abay,228255557,21466031,21466031.0,172558643.0,Shymkent-city,2024
23,Al-Farabi,66548779,15603392,7858733.0,50758424.0,Shymkent-city,2024
24,Enbekshi,95071936,6155085,6155085.0,77437949.0,Shymkent-city,2024
25,Karatau,285798116,526361,526361.0,178333700.0,Shymkent-city,2024
26,Turan,45985127,661958,661958.0,38445429.0,Shymkent-city,2024

## Employment

In [460]:
shymkent_city_empl = pd.read_excel(Path("../Data/Employment/Shymkent-city.xlsx"), skiprows=14, nrows=5, header=None, usecols='A:F, R', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
shymkent_city_empl.columns = ['rayon', 2018, 2019, 2020, 2021, 2022, 2023]
shymkent_city_empl['rayon'] = shymkent_city_empl['rayon'].replace(rayon_map_shymkent)
shymkent_city_empl
for i in [2018, 2019, 2020, 2021, 2022, 2023]:
    shymkent_city_empl[i] = shymkent_city_empl[i].astype(float)
    shymkent_city_employment = shymkent_city_empl.melt(id_vars='rayon', value_vars=[2018, 2019, 2020, 2021, 2022, 2023], var_name='year', value_name='employment')
shymkent_city_employment

            rayon  year  employment
0   Shymkent city  2018       385.4
1            Abay  2018        98.8
2       Al-Farabi  2018        73.6
3        Enbekshi  2018       123.0
4         Karatau  2018        90.0
5   Shymkent city  2019       409.8
6            Abay  2019       103.0
7       Al-Farabi  2019        85.3
8        Enbekshi  2019       127.3
9         Karatau  2019        94.2
10  Shymkent city  2020       410.3
11           Abay  2020       102.7
12      Al-Farabi  2020        83.9
13       Enbekshi  2020       127.7
14        Karatau  2020        96.0
15  Shymkent city  2021       414.3
16           Abay  2021       104.1
17      Al-Farabi  2021        85.1
18       Enbekshi  2021       128.0
19        Karatau  2021        97.1
20  Shymkent city  2022       426.1
21           Abay  2022       118.6
22      Al-Farabi  2022        79.9
23       Enbekshi  2022       104.0
24        Karatau  2022       123.5
25  Shymkent city  2023       433.5
26           Abay  2023       122.5
27      Al-Farabi  2023        79.6
28       Enbekshi  2023       106.5
29        Karatau  2023       124.8

## Other controls

In [461]:
abay = pd.read_excel(Path("../Data/Controls/Shymkent-city_All.xls"), sheet_name="Абайский район", header=2, usecols='B:I', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
abay.columns = ['Indicator', 2017, 2018, 2019, 2020, 2021, 2022, 2023]
abay = abay.loc[[65, 79, 106]].reset_index(drop=True)
abay['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    abay[i] = abay[i].astype(str)
    abay[i] = abay[i].str.replace(',', '.')
    abay[i] = abay[i].str.replace(')', '')
    abay[i] = abay[i].str.replace(' ', '')
    abay[i] = abay[i].str.replace('\xa0', '')
    abay[i] = abay[i].str.replace('*', '')
    abay[i] = abay[i].astype(float)
abay = pd.melt(abay, id_vars=['Indicator'], var_name='year', value_name='value')
abay = abay.pivot(index='year', columns='Indicator', values='value').reset_index()
abay.insert(0, 'rayon', 'Abay')
abay.columns.name = None
abay

  rayon  year  agriculture  production    retail
0  Abay  2017       8950.9     62475.8   92642.9
1  Abay  2018       8929.9     65812.2  102466.1
2  Abay  2019      11899.8     81365.0  149997.4
3  Abay  2020      12799.5     82024.0  158474.0
4  Abay  2021      15485.4     99039.4  188600.5
5  Abay  2022      15259.0    128292.2  230193.4
6  Abay  2023      18235.4     80890.0  274594.1

In [462]:
al_farabi = pd.read_excel(Path("../Data/Controls/Shymkent-city_All.xls"), sheet_name="Аль-Фарабийский район", header=2, usecols='B:I', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
al_farabi.columns = ['Indicator', 2017, 2018, 2019, 2020, 2021, 2022, 2023]
al_farabi = al_farabi.loc[[65, 79, 106]].reset_index(drop=True)
al_farabi['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    al_farabi[i] = al_farabi[i].astype(str)
    al_farabi[i] = al_farabi[i].str.replace(',', '.')
    al_farabi[i] = al_farabi[i].str.replace(')', '')
    al_farabi[i] = al_farabi[i].str.replace(' ', '')
    al_farabi[i] = al_farabi[i].str.replace('\xa0', '')
    al_farabi[i] = al_farabi[i].str.replace('*', '')
    al_farabi[i] = al_farabi[i].astype(float)
al_farabi = pd.melt(al_farabi, id_vars=['Indicator'], var_name='year', value_name='value')
al_farabi = al_farabi.pivot(index='year', columns='Indicator', values='value').reset_index()
al_farabi.insert(0, 'rayon', 'Al-Farabi')
al_farabi.columns.name = None
al_farabi

       rayon  year  agriculture  production    retail
0  Al-Farabi  2017        946.9     81903.9  129281.7
1  Al-Farabi  2018       1461.6     82337.2  151051.2
2  Al-Farabi  2019       1383.4     84283.8  141013.5
3  Al-Farabi  2020       2096.5    116446.0  146275.5
4  Al-Farabi  2021       2536.4    134337.2  177990.7
5  Al-Farabi  2022       2499.3    152011.6  232109.6
6  Al-Farabi  2023       2986.8    130283.3  273263.7

In [463]:
enbekshi = pd.read_excel(Path("../Data/Controls/Shymkent-city_All.xls"), sheet_name="Енбекшинский район", header=2, usecols='B:I', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
enbekshi.columns = ['Indicator', 2017, 2018, 2019, 2020, 2021, 2022, 2023]
enbekshi = enbekshi.loc[[65, 79, 106]].reset_index(drop=True)
enbekshi['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    enbekshi[i] = enbekshi[i].astype(str)
    enbekshi[i] = enbekshi[i].str.replace(',', '.')
    enbekshi[i] = enbekshi[i].str.replace(')', '')
    enbekshi[i] = enbekshi[i].str.replace(' ', '')
    enbekshi[i] = enbekshi[i].str.replace('\xa0', '')
    enbekshi[i] = enbekshi[i].str.replace('*', '')
    enbekshi[i] = enbekshi[i].astype(float)
enbekshi = pd.melt(enbekshi, id_vars=['Indicator'], var_name='year', value_name='value')
enbekshi = enbekshi.pivot(index='year', columns='Indicator', values='value').reset_index()
enbekshi.insert(0, 'rayon', 'Enbekshi')
enbekshi.columns.name = None
enbekshi

      rayon  year  agriculture  production    retail
0  Enbekshi  2017       4718.0    213681.9   65349.1
1  Enbekshi  2018       6082.0    272184.7   71178.8
2  Enbekshi  2019       6399.3    322838.4   91937.8
3  Enbekshi  2020       8716.9    360711.0  130994.2
4  Enbekshi  2021      10546.0    450238.3  130488.8
5  Enbekshi  2022      10391.8    542328.9  171945.4
6  Enbekshi  2023      12418.8    658681.8  226717.3

In [464]:
karatau = pd.read_excel(Path("../Data/Controls/Shymkent-city_All.xls"), sheet_name="Каратауский район", header=2, usecols='B:I', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
karatau.columns = ['Indicator', 2017, 2018, 2019, 2020, 2021, 2022, 2023]
karatau = karatau.loc[[65, 79, 106]].reset_index(drop=True)
karatau['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    karatau[i] = karatau[i].astype(str)
    karatau[i] = karatau[i].str.replace(',', '.')
    karatau[i] = karatau[i].str.replace(')', '')
    karatau[i] = karatau[i].str.replace(' ', '')
    karatau[i] = karatau[i].str.replace('\xa0', '')
    karatau[i] = karatau[i].str.replace('*', '')
    karatau[i] = karatau[i].astype(float)
karatau = pd.melt(karatau, id_vars=['Indicator'], var_name='year', value_name='value')
karatau = karatau.pivot(index='year', columns='Indicator', values='value').reset_index()
karatau.insert(0, 'rayon', 'Karatau')
karatau.columns.name = None
karatau

     rayon  year  agriculture  production    retail
0  Karatau  2017      10019.9     53722.5   22108.0
1  Karatau  2018       9214.5     71858.9   35343.7
2  Karatau  2019       9773.0     85069.8   49769.2
3  Karatau  2020      13167.2    111349.0   60170.7
4  Karatau  2021      15930.4    129258.8   97973.7
5  Karatau  2022      15697.5    143474.8  119418.4
6  Karatau  2023      18759.4    174040.0  101257.9

In [465]:
turan = pd.read_excel(Path("../Data/Controls/Shymkent-city_All.xls"), sheet_name="Тұран", header=2, usecols='B:C', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
turan.columns = ['Indicator', 2023]
turan = turan.loc[[65, 79, 106]].reset_index(drop=True)
turan['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2023]:
    turan[i] = turan[i].astype(str)
    turan[i] = turan[i].str.replace(',', '.')
    turan[i] = turan[i].str.replace(')', '')
    turan[i] = turan[i].str.replace(' ', '')
    turan[i] = turan[i].str.replace('\xa0', '')
    turan[i] = turan[i].str.replace('*', '')
    turan[i] = turan[i].astype(float)
turan = pd.melt(turan, id_vars=['Indicator'], var_name='year', value_name='value')
turan = turan.pivot(index='year', columns='Indicator', values='value').reset_index()
turan.insert(0, 'rayon', 'Turan')
turan.columns.name = None
turan

   rayon  year  agriculture  production   retail
0  Turan  2023          NaN     45998.0  78109.0

In [466]:
shymkent_city_controls = pd.concat([abay, al_farabi, enbekshi, karatau, turan], ignore_index=True)
shymkent_city_controls

        rayon  year  agriculture  production    retail
0        Abay  2017       8950.9     62475.8   92642.9
1        Abay  2018       8929.9     65812.2  102466.1
2        Abay  2019      11899.8     81365.0  149997.4
3        Abay  2020      12799.5     82024.0  158474.0
4        Abay  2021      15485.4     99039.4  188600.5
5        Abay  2022      15259.0    128292.2  230193.4
6        Abay  2023      18235.4     80890.0  274594.1
7   Al-Farabi  2017        946.9     81903.9  129281.7
8   Al-Farabi  2018       1461.6     82337.2  151051.2
9   Al-Farabi  2019       1383.4     84283.8  141013.5
10  Al-Farabi  2020       2096.5    116446.0  146275.5
11  Al-Farabi  2021       2536.4    134337.2  177990.7
12  Al-Farabi  2022       2499.3    152011.6  232109.6
13  Al-Farabi  2023       2986.8    130283.3  273263.7
14   Enbekshi  2017       4718.0    213681.9   65349.1
15   Enbekshi  2018       6082.0    272184.7   71178.8
16   Enbekshi  2019       6399.3    322838.4   91937.8
17   Enbekshi  2020       8716.9    360711.0  130994.2
18   Enbekshi  2021      10546.0    450238.3  130488.8
19   Enbekshi  2022      10391.8    542328.9  171945.4
20   Enbekshi  2023      12418.8    658681.8  226717.3
21    Karatau  2017      10019.9     53722.5   22108.0
22    Karatau  2018       9214.5     71858.9   35343.7
23    Karatau  2019       9773.0     85069.8   49769.2
24    Karatau  2020      13167.2    111349.0   60170.7
25    Karatau  2021      15930.4    129258.8   97973.7
26    Karatau  2022      15697.5    143474.8  119418.4
27    Karatau  2023      18759.4    174040.0  101257.9
28      Turan  2023          NaN     45998.0   78109.0

## PPI

In [467]:
shymkent_city_ppi = pd.read_excel(
    Path("../Data/PPI/Shymkent-city.xls"),
    header=2,
    usecols='Y:AH',
    nrows=54,
    na_values=['x', 'х', '-', '', ' ', '...']
)
shymkent_city_ppi.columns = [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
rayons = list(shymkent_city_inv['rayon'].unique())

dfs = []

for rayon in rayons:
    df_temp = pd.DataFrame({
        'rayon': [rayon] * len(range(2014, 2024)),
        'year': list(range(2014, 2024)),
        'ppi': shymkent_city_ppi.iloc[-1].values
    })
    dfs.append(df_temp)
shymkent_city_ppi = pd.concat(dfs, ignore_index=True)
shymkent_city_ppi['ppi'] = shymkent_city_ppi['ppi'].astype(str).str.replace(',', '.')
shymkent_city_ppi['ppi'] = shymkent_city_ppi['ppi'].astype(str).str.replace(')', '')
shymkent_city_ppi['ppi'] = shymkent_city_ppi['ppi'].astype(str).str.replace(' ', '')
shymkent_city_ppi['ppi'] = shymkent_city_ppi['ppi'].astype(str).str.replace('\xa0', '')
shymkent_city_ppi['ppi'] = shymkent_city_ppi['ppi'].astype(str).str.replace('*', '')
shymkent_city_ppi['ppi'] = shymkent_city_ppi['ppi'].astype(float)

shymkent_city_ppi.loc[
    shymkent_city_ppi['year'].isin([2014, 2015, 2016, 2017]),
    'ppi'
] = ''

shymkent_city_ppi

/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_21020/3545733056.py:28: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  shymkent_city_ppi.loc[

            rayon  year    ppi
0   Shymkent city  2014
1   Shymkent city  2015
2   Shymkent city  2016
3   Shymkent city  2017
4   Shymkent city  2018  110.3
5   Shymkent city  2019  102.6
6   Shymkent city  2020  105.2
7   Shymkent city  2021  115.9
8   Shymkent city  2022  103.2
9   Shymkent city  2023  105.0
10           Abay  2014
11           Abay  2015
12           Abay  2016
13           Abay  2017
14           Abay  2018  110.3
15           Abay  2019  102.6
16           Abay  2020  105.2
17           Abay  2021  115.9
18           Abay  2022  103.2
19           Abay  2023  105.0
20      Al-Farabi  2014
21      Al-Farabi  2015
22      Al-Farabi  2016
23      Al-Farabi  2017
24      Al-Farabi  2018  110.3
25      Al-Farabi  2019  102.6
26      Al-Farabi  2020  105.2
27      Al-Farabi  2021  115.9
28      Al-Farabi  2022  103.2
29      Al-Farabi  2023  105.0
30       Enbekshi  2014
31       Enbekshi  2015
32       Enbekshi  2016
33       Enbekshi  2017
34       Enbekshi  2018  110.3
35       Enbekshi  2019  102.6
36       Enbekshi  2020  105.2
37       Enbekshi  2021  115.9
38       Enbekshi  2022  103.2
39       Enbekshi  2023  105.0
40        Karatau  2014
41        Karatau  2015
42        Karatau  2016
43        Karatau  2017
44        Karatau  2018  110.3
45        Karatau  2019  102.6
46        Karatau  2020  105.2
47        Karatau  2021  115.9
48        Karatau  2022  103.2
49        Karatau  2023  105.0
50          Turan  2014
51          Turan  2015
52          Turan  2016
53          Turan  2017
54          Turan  2018  110.3
55          Turan  2019  102.6
56          Turan  2020  105.2
57          Turan  2021  115.9
58          Turan  2022  103.2
59          Turan  2023  105.0

## Combine

In [468]:
dfs_shymkent_city = [shymkent_city_inv, shymkent_city_employment, shymkent_city_controls, shymkent_city_ppi]
shymkent_city_merged = reduce(lambda left, right: pd.merge(left, right, on=['rayon', 'year'], how='outer'), dfs_shymkent_city)
shymkent_city_merged['oblast'] = shymkent_city_merged['oblast'].fillna('Shymkent-city')
shymkent_city_merged

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year,employment,agriculture,production,retail,ppi
0,Abay,NaN,NaN,NaN,NaN,Shymkent-city,2014,NaN,NaN,NaN,NaN,
1,Abay,NaN,NaN,NaN,NaN,Shymkent-city,2015,NaN,NaN,NaN,NaN,
2,Abay,NaN,NaN,NaN,NaN,Shymkent-city,2016,NaN,NaN,NaN,NaN,
3,Abay,NaN,NaN,NaN,NaN,Shymkent-city,2017,NaN,8950.9,62475.8,92642.9,
4,Abay,NaN,NaN,NaN,NaN,Shymkent-city,2018,98.8,8929.9,65812.2,102466.1,110.3
...,...,...,...,...,...,...,...,...,...,...,...,...
61,Turan,NaN,NaN,NaN,NaN,Shymkent-city,2020,NaN,NaN,NaN,NaN,105.2
62,Turan,NaN,NaN,NaN,NaN,Shymkent-city,2021,NaN,NaN,NaN,NaN,115.9
63,Turan,NaN,NaN,NaN,NaN,Shymkent-city,2022,NaN,NaN,NaN,NaN,103.2
64,Turan,18849230,1139679,1139679.0,17308173.0,Shymkent-city,2023,NaN,NaN,45998.0,78109.0,105.0
65,Turan,45985127,661958,661958.0,38445429.0,Shymkent-city,2024,NaN,NaN,NaN,NaN,NaN

# Turkestan

## Investments

In [469]:
# turkestan_all_2014 
turkestan_all_2014 = camelot.read_pdf(Path("../Data/Investments/Turkistan/2014_Investments.pdf"), pages='44', flavor='stream')[0].df
turkestan_all_2014 = turkestan_all_2014.iloc[6:, [0, 2, 5]].reset_index(drop=True)
for col in [2, 5]:
    turkestan_all_2014[col] = (
        turkestan_all_2014[col]
        .astype(str)
        .str.replace(' ', '', regex=False)
        .replace('', pd.NA)
        .astype('Int64'))
turkestan_all_2014

# turkestan_all_2015
turkestan_all_2015 = camelot.read_pdf(Path("../Data/Investments/Turkistan/2015_Investments.pdf"), pages='54', flavor='stream')[0].df
turkestan_all_2015 = turkestan_all_2015.iloc[6:, [0, 2, 4]].reset_index(drop=True)
for col in [2, 4]:
    turkestan_all_2015[col] = (
        turkestan_all_2015[col]
        .astype(str)
        .str.replace(' ', '', regex=False)
        .replace('', pd.NA)
        .astype('Int64'))
turkestan_all_2015

# EXCEL
turkestan_all_2016 = pd.read_excel(Path("../Data/Investments/Turkistan/2016_Investments/Internal_vs_external.xls"), header=6, nrows=16, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
turkestan_all_2017 = pd.read_excel(Path("../Data/Investments/Turkistan/2017_Investments/Internal_vs_external.xls"), header=6, nrows=16, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
turkestan_all_2018 = pd.read_excel(Path("../Data/Investments/Turkistan/2018_Investments/Internal_vs_external.xls"), header=6, nrows=17, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
turkestan_all_2019 = pd.read_excel(Path("../Data/Investments/Turkistan/2019_Investments.xls"), sheet_name = "14",header=4, nrows=17, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
turkestan_all_2020 = pd.read_excel(Path("../Data/Investments/Turkistan/2020_Investments.xls"), sheet_name = "13",header=4, nrows=17, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
turkestan_all_2021 = pd.read_excel(Path("../Data/Investments/Turkistan/2021_Investments.xls"), sheet_name = "13",header=4, nrows=18, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
turkestan_all_2022 = pd.read_excel(Path("../Data/Investments/Turkistan/2022_Investments.xls"), sheet_name = "13",header=4, nrows=18, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
turkestan_all_2023 = pd.read_excel(Path("../Data/Investments/Turkistan/2023_Investments.xlsx"), sheet_name = "19",header=3, nrows=18, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
turkestan_all_2024 = pd.read_excel(Path("../Data/Investments/Turkistan/2024_Investments.xls"), sheet_name = "14",header=4, nrows=18, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

Ignoring wrong pointing object 7 0 (offset 0)
Ignoring wrong pointing object 9 0 (offset 0)
Ignoring wrong pointing object 11 0 (offset 0)
Ignoring wrong pointing object 13 0 (offset 0)
Ignoring wrong pointing object 15 0 (offset 0)
Ignoring wrong pointing object 17 0 (offset 0)
Ignoring wrong pointing object 19 0 (offset 0)
Ignoring wrong pointing object 21 0 (offset 0)
Ignoring wrong pointing object 23 0 (offset 0)
Ignoring wrong pointing object 25 0 (offset 0)
Ignoring wrong pointing object 33 0 (offset 0)
Ignoring wrong pointing object 35 0 (offset 0)
Ignoring wrong pointing object 37 0 (offset 0)
Ignoring wrong pointing object 39 0 (offset 0)
Ignoring wrong pointing object 47 0 (offset 0)
Ignoring wrong pointing object 49 0 (offset 0)
Ignoring wrong pointing object 51 0 (offset 0)
Ignoring wrong pointing object 56 0 (offset 0)
Ignoring wrong pointing object 58 0 (offset 0)
Ignoring wrong pointing object 66 0 (offset 0)
Ignoring wrong pointing object 68 0 (offset 0)
Ignoring wrong pointing object 70 0 (offset 0)
Ignoring wrong pointing object 72 0 (offset 0)
Ignoring wrong pointing object 77 0 (offset 0)
Ignoring wrong pointing object 79 0 (offset 0)
Ignoring wrong pointing object 103 0 (offset 0)
Ignoring wrong pointing object 115 0 (offset 0)
Ignoring wrong pointing object 126 0 (offset 0)
Ignoring wrong pointing object 206 0 (offset 0)
Ignoring wrong pointing object 7 0 (offset 0)
Ignoring wrong pointing object 9 0 (offset 0)
Ignoring wrong pointing object 11 0 (offset 0)
Ignoring wrong pointing object 13 0 (offset 0)
Ignoring wrong pointing object 15 0 (offset 0)
Ignoring wrong pointing object 17 0 (offset 0)
Ignoring wrong pointing object 19 0 (offset 0)
Ignoring wrong pointing object 21 0 (offset 0)
Ignoring wrong pointing object 23 0 (offset 0)
Ignoring wrong pointing object 25 0 (offset 0)
Ignoring wrong pointing object 33 0 (offset 0)
Ignoring wrong pointing object 35 0 (offset 0)
Ignoring wrong pointing object 37 0 (offset 0)
Ignoring wrong pointing object 39 0 (offset 0)
Ignoring wrong pointing object 47 0 (offset 0)
Ignoring wrong pointing object 49 0 (offset 0)
Ignoring wrong pointing object 51 0 (offset 0)
Ignoring wrong pointing object 56 0 (offset 0)
Ignoring wrong pointing object 58 0 (offset 0)
Ignoring wrong pointing object 66 0 (offset 0)
Ignoring wrong pointing object 68 0 (offset 0)
Ignoring wrong pointing object 70 0 (offset 0)
Ignoring wrong pointing object 72 0 (offset 0)
Ignoring wrong pointing object 77 0 (offset 0)
Ignoring wrong pointing object 79 0 (offset 0)
Ignoring wrong pointing object 103 0 (offset 0)
Ignoring wrong pointing object 115 0 (offset 0)
Ignoring wrong pointing object 126 0 (offset 0)
Ignoring wrong pointing object 206 0 (offset 0)
Ignoring wrong pointing object 7 0 (offset 0)
Ignoring wrong pointing object 9 0 (offset 0)
Ignoring wrong pointing object 11 0 (offset 0)
Ignoring wrong pointing object 13 0 (offset 0)
Ignoring wrong pointing object 15 0 (offset 0)
Ignoring wrong pointing object 17 0 (offset 0)
Ignoring wrong pointing object 19 0 (offset 0)
Ignoring wrong pointing object 21 0 (offset 0)
Ignoring wrong pointing object 28 0 (offset 0)
Ignoring wrong pointing object 30 0 (offset 0)
Ignoring wrong pointing object 32 0 (offset 0)
Ignoring wrong pointing object 34 0 (offset 0)
Ignoring wrong pointing object 39 0 (offset 0)
Ignoring wrong pointing object 44 0 (offset 0)
Ignoring wrong pointing object 52 0 (offset 0)
Ignoring wrong pointing object 57 0 (offset 0)
Ignoring wrong pointing object 59 0 (offset 0)
Ignoring wrong pointing object 64 0 (offset 0)
Ignoring wrong pointing object 66 0 (offset 0)
Ignoring wrong pointing object 68 0 (offset 0)
Ignoring wrong pointing object 70 0 (offset 0)
Ignoring wrong pointing object 72 0 (offset 0)
Ignoring wrong pointing object 78 0 (offset 0)
Ignoring wrong pointing object 80 0 (offset 0)
Ignoring wrong pointing object 113 0 (offset 0)
Ignoring wrong pointing object 118 0 (offset 0)
Ignoring wrong pointing object 239 0 (offset 0)
Ignoring wrong pointing object 7 0 (offset 0)
Ignoring wrong pointing object 9 0 (offset 0)
Ignoring wrong pointing object 11 0 (offset 0)
Ignoring wrong pointing object 13 0 (offset 0)
Ignoring wrong pointing object 15 0 (offset 0)
Ignoring wrong pointing object 17 0 (offset 0)
Ignoring wrong pointing object 19 0 (offset 0)
Ignoring wrong pointing object 21 0 (offset 0)
Ignoring wrong pointing object 28 0 (offset 0)
Ignoring wrong pointing object 30 0 (offset 0)
Ignoring wrong pointing object 32 0 (offset 0)
Ignoring wrong pointing object 34 0 (offset 0)
Ignoring wrong pointing object 39 0 (offset 0)
Ignoring wrong pointing object 44 0 (offset 0)
Ignoring wrong pointing object 52 0 (offset 0)
Ignoring wrong pointing object 57 0 (offset 0)
Ignoring wrong pointing object 59 0 (offset 0)
Ignoring wrong pointing object 64 0 (offset 0)
Ignoring wrong pointing object 66 0 (offset 0)
Ignoring wrong pointing object 68 0 (offset 0)
Ignoring wrong pointing object 70 0 (offset 0)
Ignoring wrong pointing object 72 0 (offset 0)
Ignoring wrong pointing object 78 0 (offset 0)
Ignoring wrong pointing object 80 0 (offset 0)
Ignoring wrong pointing object 113 0 (offset 0)
Ignoring wrong pointing object 118 0 (offset 0)
Ignoring wrong pointing object 239 0 (offset 0)

In [470]:
# turkestan_all_2014 
turkestan_non_2014 = camelot.read_pdf(Path("../Data/Investments/Turkistan/2014_Investments.pdf"), pages='45', flavor='stream')[0].df
turkestan_non_2014 = turkestan_non_2014.iloc[8:, [0, 2, 6]].reset_index(drop=True)
for col in [2, 6]:
    turkestan_non_2014[col] = (
        turkestan_non_2014[col]
        .astype(str)
        .str.replace(' ', '', regex=False)
        .replace('', pd.NA)
        .astype('Int64'))
turkestan_non_2014

# turkestan_all_2015 
tables = camelot.read_pdf(
    Path("../Data/Investments/Turkistan/2015_Investments.pdf"),
    pages='55',
    flavor='stream',
    table_areas=['0,0,1000,1000']
)
turkestan_non_2015 = tables[0].df
turkestan_non_2015 = turkestan_non_2015.iloc[27:, [0, 2, 6]].reset_index(drop=True)
turkestan_non_2015 = turkestan_non_2015.drop(index=15).reset_index(drop=True)
turkestan_non_2015
for col in [2, 6]:
    turkestan_non_2015[col] = (
        turkestan_non_2015[col]
        .astype(str)
        .str.replace(' ', '', regex=False)
        .replace('', pd.NA)
        .astype('Int64'))
turkestan_non_2015

# EXCEL
turkestan_non_2016 = pd.read_excel(Path("../Data/Investments/Turkistan/2016_Investments/Greenfield_investments.xls"), header=7, nrows=16, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
turkestan_non_2017 = pd.read_excel(Path("../Data/Investments/Turkistan/2017_Investments/Greenfield_investments.xls"), header=7, nrows=16, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
turkestan_non_2018 = pd.read_excel(Path("../Data/Investments/Turkistan/2018_Investments/Greenfield_investments.xls"), header=7, nrows=17, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
turkestan_non_2019 = pd.read_excel(Path("../Data/Investments/Turkistan/2019_Investments.xls"), sheet_name='15', header=4, nrows=17, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
turkestan_non_2020 = pd.read_excel(Path("../Data/Investments/Turkistan/2020_Investments.xls"), sheet_name='14', header=4, nrows=17, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
turkestan_non_2021 = pd.read_excel(Path("../Data/Investments/Turkistan/2021_Investments.xls"), sheet_name='14', header=4, nrows=18, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
turkestan_non_2022 = pd.read_excel(Path("../Data/Investments/Turkistan/2022_Investments.xls"), sheet_name='14', header=4, nrows=18, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
turkestan_non_2023 = pd.read_excel(Path("../Data/Investments/Turkistan/2023_Investments.xlsx"), sheet_name='20', header=3, nrows=18, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
turkestan_non_2024 = pd.read_excel(Path("../Data/Investments/Turkistan/2024_Investments.xls"), sheet_name='15', header=4, nrows=18, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

Ignoring wrong pointing object 7 0 (offset 0)
Ignoring wrong pointing object 9 0 (offset 0)
Ignoring wrong pointing object 11 0 (offset 0)
Ignoring wrong pointing object 13 0 (offset 0)
Ignoring wrong pointing object 15 0 (offset 0)
Ignoring wrong pointing object 17 0 (offset 0)
Ignoring wrong pointing object 19 0 (offset 0)
Ignoring wrong pointing object 21 0 (offset 0)
Ignoring wrong pointing object 23 0 (offset 0)
Ignoring wrong pointing object 25 0 (offset 0)
Ignoring wrong pointing object 33 0 (offset 0)
Ignoring wrong pointing object 35 0 (offset 0)
Ignoring wrong pointing object 37 0 (offset 0)
Ignoring wrong pointing object 39 0 (offset 0)
Ignoring wrong pointing object 47 0 (offset 0)
Ignoring wrong pointing object 49 0 (offset 0)
Ignoring wrong pointing object 51 0 (offset 0)
Ignoring wrong pointing object 56 0 (offset 0)
Ignoring wrong pointing object 58 0 (offset 0)
Ignoring wrong pointing object 66 0 (offset 0)
Ignoring wrong pointing object 68 0 (offset 0)
Ignoring wrong pointing object 70 0 (offset 0)
Ignoring wrong pointing object 72 0 (offset 0)
Ignoring wrong pointing object 77 0 (offset 0)
Ignoring wrong pointing object 79 0 (offset 0)
Ignoring wrong pointing object 103 0 (offset 0)
Ignoring wrong pointing object 115 0 (offset 0)
Ignoring wrong pointing object 126 0 (offset 0)
Ignoring wrong pointing object 206 0 (offset 0)
Ignoring wrong pointing object 7 0 (offset 0)
Ignoring wrong pointing object 9 0 (offset 0)
Ignoring wrong pointing object 11 0 (offset 0)
Ignoring wrong pointing object 13 0 (offset 0)
Ignoring wrong pointing object 15 0 (offset 0)
Ignoring wrong pointing object 17 0 (offset 0)
Ignoring wrong pointing object 19 0 (offset 0)
Ignoring wrong pointing object 21 0 (offset 0)
Ignoring wrong pointing object 23 0 (offset 0)
Ignoring wrong pointing object 25 0 (offset 0)
Ignoring wrong pointing object 33 0 (offset 0)
Ignoring wrong pointing object 35 0 (offset 0)
Ignoring wrong pointing object 37 0 (offset 0)
Ignoring wrong pointing object 39 0 (offset 0)
Ignoring wrong pointing object 47 0 (offset 0)
Ignoring wrong pointing object 49 0 (offset 0)
Ignoring wrong pointing object 51 0 (offset 0)
Ignoring wrong pointing object 56 0 (offset 0)
Ignoring wrong pointing object 58 0 (offset 0)
Ignoring wrong pointing object 66 0 (offset 0)
Ignoring wrong pointing object 68 0 (offset 0)
Ignoring wrong pointing object 70 0 (offset 0)
Ignoring wrong pointing object 72 0 (offset 0)
Ignoring wrong pointing object 77 0 (offset 0)
Ignoring wrong pointing object 79 0 (offset 0)
Ignoring wrong pointing object 103 0 (offset 0)
Ignoring wrong pointing object 115 0 (offset 0)
Ignoring wrong pointing object 126 0 (offset 0)
Ignoring wrong pointing object 206 0 (offset 0)
Ignoring wrong pointing object 7 0 (offset 0)
Ignoring wrong pointing object 9 0 (offset 0)
Ignoring wrong pointing object 11 0 (offset 0)
Ignoring wrong pointing object 13 0 (offset 0)
Ignoring wrong pointing object 15 0 (offset 0)
Ignoring wrong pointing object 17 0 (offset 0)
Ignoring wrong pointing object 19 0 (offset 0)
Ignoring wrong pointing object 21 0 (offset 0)
Ignoring wrong pointing object 28 0 (offset 0)
Ignoring wrong pointing object 30 0 (offset 0)
Ignoring wrong pointing object 32 0 (offset 0)
Ignoring wrong pointing object 34 0 (offset 0)
Ignoring wrong pointing object 39 0 (offset 0)
Ignoring wrong pointing object 44 0 (offset 0)
Ignoring wrong pointing object 52 0 (offset 0)
Ignoring wrong pointing object 57 0 (offset 0)
Ignoring wrong pointing object 59 0 (offset 0)
Ignoring wrong pointing object 64 0 (offset 0)
Ignoring wrong pointing object 66 0 (offset 0)
Ignoring wrong pointing object 68 0 (offset 0)
Ignoring wrong pointing object 70 0 (offset 0)
Ignoring wrong pointing object 72 0 (offset 0)
Ignoring wrong pointing object 78 0 (offset 0)
Ignoring wrong pointing object 80 0 (offset 0)
Ignoring wrong pointing object 113 0 (offset 0)
Ignoring wrong pointing object 118 0 (offset 0)
Ignoring wrong pointing object 239 0 (offset 0)
Ignoring wrong pointing object 7 0 (offset 0)
Ignoring wrong pointing object 9 0 (offset 0)
Ignoring wrong pointing object 11 0 (offset 0)
Ignoring wrong pointing object 13 0 (offset 0)
Ignoring wrong pointing object 15 0 (offset 0)
Ignoring wrong pointing object 17 0 (offset 0)
Ignoring wrong pointing object 19 0 (offset 0)
Ignoring wrong pointing object 21 0 (offset 0)
Ignoring wrong pointing object 28 0 (offset 0)
Ignoring wrong pointing object 30 0 (offset 0)
Ignoring wrong pointing object 32 0 (offset 0)
Ignoring wrong pointing object 34 0 (offset 0)
Ignoring wrong pointing object 39 0 (offset 0)
Ignoring wrong pointing object 44 0 (offset 0)
Ignoring wrong pointing object 52 0 (offset 0)
Ignoring wrong pointing object 57 0 (offset 0)
Ignoring wrong pointing object 59 0 (offset 0)
Ignoring wrong pointing object 64 0 (offset 0)
Ignoring wrong pointing object 66 0 (offset 0)
Ignoring wrong pointing object 68 0 (offset 0)
Ignoring wrong pointing object 70 0 (offset 0)
Ignoring wrong pointing object 72 0 (offset 0)
Ignoring wrong pointing object 78 0 (offset 0)
Ignoring wrong pointing object 80 0 (offset 0)
Ignoring wrong pointing object 113 0 (offset 0)
Ignoring wrong pointing object 118 0 (offset 0)
Ignoring wrong pointing object 239 0 (offset 0)

In [471]:
dfs = [turkestan_all_2014, turkestan_all_2015, turkestan_all_2016, turkestan_all_2017,
      turkestan_all_2018, turkestan_all_2019, turkestan_all_2020, turkestan_all_2021,
      turkestan_all_2022, turkestan_all_2023, turkestan_all_2024, turkestan_non_2014,
      turkestan_non_2015, turkestan_non_2016, turkestan_non_2017, turkestan_non_2018,
      turkestan_non_2019, turkestan_non_2020, turkestan_non_2021, turkestan_non_2022,
      turkestan_non_2023, turkestan_non_2024]

lists = []

for df in dfs:
    lists.extend(df.iloc[:, 0].unique())

unique_lists = pd.Series(lists).unique()
unique_lists

array(['Шымкент қ.', 'Арыс қ.ə.', 'Кентау қ.ə.', 'Түркістан қ.ə.',
       'Бəйдібек ауданы', 'Қазығұрт', 'Мақтаарал', 'Ордабасы', 'Отырар',
       'Сайрам', 'Сарыағаш', 'Созақ', 'Төлеби', 'Түлкібас', 'Шардара',
       'Арыс қ.ә.', 'Кентау қ.ә.', 'Түркістан қ.ә.', 'Бәйдібек ауданы',
       'Арыс қ.', 'Кентау қ.', 'Түркістан қ.', 'Қазығұрт ауданы',
       'Мақтаарал ауданы', 'Ордабасы ауданы', 'Отырар ауданы',
       'Сайрам ауданы', 'Сарыағаш ауданы', 'Созақ ауданы',
       'Төле би ауданы', 'Түлкібас ауданы', 'Шардара ауданы',
       'Жетісай ауданы', 'Келес ауданы', 'Сауран ауданы', 'г.Туркестан',
       'г.а.Арысь', 'г.а.Кентау', 'район Байдибека', 'Жетысайский',
       'Келесский', 'Казыгуртский', 'Махтааральский', 'Ордабасинский',
       'Отырарский', 'Сайрамский', 'Сарыагашский', 'Сауранский',
       'Сузакский', 'Толебийский', 'Тулькубасский', 'Шардаринский',
       'Ордабасынский', 'Отрарский'], dtype=object)

In [472]:
rayon_map_turkestan = {

    # ---- Cities (қ. / қ.ә. / г.а.) ----
    'Шымкент қ.': 'Shymkent city',
    'г. Шымкент': 'Shymkent city',
    'г.Шымкент ': 'Shymkent city',

    'Арыс қ.': 'Arys city',
    'Арыс қ.ə.': 'Arys city',
    'г.а.Арысь': 'Arys city',
    'г.а.Арысь': 'Arys city',
    'Арыс қ.ә.': 'Arys city',

    'Кентау қ.': 'Kentau city',
    'Кентау қ.ə.': 'Kentau city',
    'г.а.Кентау': 'Kentau city',
    'г.а.Кентау': 'Kentau city',
    'Кентау қ.ә.': 'Kentau city',

    'Түркістан қ.': 'Turkestan city',
    'Түркістан қ.ə.': 'Turkestan city',
    'г.Туркестан': 'Turkestan city',
    'г.Туркестан': 'Turkestan city',
    'Түркістан қ.ә.': 'Turkestan city',

    # ---- Districts (Kazakh) ----
    'Бəйдібек ауданы': 'Baidibek',
    'Бәйдібек ауданы': 'Baidibek',
    'район Байдибека': 'Baidibek',
    'Район Байдибека': 'Baidibek',

    'Қазығұрт': 'Kazygurt',
    'Қазығұрт ауданы': 'Kazygurt',
    'Казыгуртский': 'Kazygurt',
    'Казыгуртский район': 'Kazygurt',

    'Мақтаарал': 'Maktaaral',
    'Мақтаарал ауданы': 'Maktaaral',
    'Махтааральский': 'Maktaaral',
    'Мактааральский район': 'Maktaaral',

    'Ордабасы': 'Ordabasy',
    'Ордабасы ауданы': 'Ordabasy',
    'Ордабасинский': 'Ordabasy',
    'Ордабасынский': 'Ordabasy',
    'Ордабасынский район': 'Ordabasy',

    'Отырар': 'Otyrar',
    'Отырар ауданы': 'Otyrar',
    'Отырарский': 'Otyrar',
    'Отрарский': 'Otyrar',
    'Отрарский район': 'Otyrar',

    'Сайрам': 'Sairam',
    'Сайрам ауданы': 'Sairam',
    'Сайрамский': 'Sairam',
    'Сайрамский район': 'Sairam',

    'Сарыағаш': 'Saryagash',
    'Сарыағаш ауданы': 'Saryagash',
    'Сарыагашский': 'Saryagash',
    'Сарыагашский район': 'Saryagash',

    'Созақ': 'Sozak',
    'Созақ ауданы': 'Sozak',
    'Сузакский': 'Sozak',
    'Сузакский район': 'Sozak',

    'Төлеби': 'Tolebi',
    'Төле би ауданы': 'Tolebi',
    'Толебийский': 'Tolebi',
    'Толебийский район': 'Tolebi',

    'Түлкібас': 'Tulkibas',
    'Түлкібас ауданы': 'Tulkibas',
    'Тулькубасский': 'Tulkibas',
    'Тюлькубасский район': 'Tulkibas',

    'Шардара': 'Shardara',
    'Шардара ауданы': 'Shardara',
    'Шардаринский': 'Shardara',
    'Шардаринский район': 'Shardara',

    'Жетісай ауданы': 'Zhetysay',
    'Жетысайский': 'Zhetysay',
    'Жетысайский район': 'Zhetysay',

    'Келес ауданы': 'Keles',
    'Келесский': 'Keles',
    'Келесский район': 'Keles',

    'Сауран ауданы': 'Sauran',
    'Сауранский': 'Sauran',
    'Район Сауран': 'Sauran'
}

In [473]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [turkestan_all_2014, turkestan_all_2015, turkestan_all_2016,
          turkestan_all_2017, turkestan_all_2018, turkestan_all_2019,
          turkestan_all_2020, turkestan_all_2021, turkestan_all_2022,
          turkestan_all_2023, turkestan_all_2024]:
    df.columns = all_columns

for df in [turkestan_non_2014, turkestan_non_2015, turkestan_non_2016,
          turkestan_non_2017, turkestan_non_2018, turkestan_non_2019,
          turkestan_non_2020, turkestan_non_2021, turkestan_non_2022,
          turkestan_non_2023, turkestan_non_2024]:
    df.columns = non_columns

    df[['all_nonextr_inv', 'f_nonextr_inv']] = (
        df[['all_nonextr_inv', 'f_nonextr_inv']]
        .astype(str)
        .apply(lambda x: x.str.replace(' ', ''))
        .astype(float)
    )

    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

In [474]:
# ----- ALL investments -----
turkestan_all_2014['rayon'] = turkestan_all_2014['rayon'].replace(rayon_map_turkestan)
turkestan_all_2015['rayon'] = turkestan_all_2015['rayon'].replace(rayon_map_turkestan)
turkestan_all_2016['rayon'] = turkestan_all_2016['rayon'].replace(rayon_map_turkestan)
turkestan_all_2017['rayon'] = turkestan_all_2017['rayon'].replace(rayon_map_turkestan)
turkestan_all_2018['rayon'] = turkestan_all_2018['rayon'].replace(rayon_map_turkestan)
turkestan_all_2019['rayon'] = turkestan_all_2019['rayon'].replace(rayon_map_turkestan)
turkestan_all_2020['rayon'] = turkestan_all_2020['rayon'].replace(rayon_map_turkestan)
turkestan_all_2021['rayon'] = turkestan_all_2021['rayon'].replace(rayon_map_turkestan)
turkestan_all_2022['rayon'] = turkestan_all_2022['rayon'].replace(rayon_map_turkestan)
turkestan_all_2023['rayon'] = turkestan_all_2023['rayon'].replace(rayon_map_turkestan)
turkestan_all_2024['rayon'] = turkestan_all_2024['rayon'].replace(rayon_map_turkestan)

# ----- NON-extractive investments -----
turkestan_non_2014['rayon'] = turkestan_non_2014['rayon'].replace(rayon_map_turkestan)
turkestan_non_2015['rayon'] = turkestan_non_2015['rayon'].replace(rayon_map_turkestan)
turkestan_non_2016['rayon'] = turkestan_non_2016['rayon'].replace(rayon_map_turkestan)
turkestan_non_2017['rayon'] = turkestan_non_2017['rayon'].replace(rayon_map_turkestan)
turkestan_non_2018['rayon'] = turkestan_non_2018['rayon'].replace(rayon_map_turkestan)
turkestan_non_2019['rayon'] = turkestan_non_2019['rayon'].replace(rayon_map_turkestan)
turkestan_non_2020['rayon'] = turkestan_non_2020['rayon'].replace(rayon_map_turkestan)
turkestan_non_2021['rayon'] = turkestan_non_2021['rayon'].replace(rayon_map_turkestan)
turkestan_non_2022['rayon'] = turkestan_non_2022['rayon'].replace(rayon_map_turkestan)
turkestan_non_2023['rayon'] = turkestan_non_2023['rayon'].replace(rayon_map_turkestan)
turkestan_non_2024['rayon'] = turkestan_non_2024['rayon'].replace(rayon_map_turkestan)

In [475]:
turkestan_2014 = turkestan_all_2014.merge(turkestan_non_2014, on='rayon', how='left')
turkestan_2015 = turkestan_all_2015.merge(turkestan_non_2015, on='rayon', how='left')
turkestan_2016 = turkestan_all_2016.merge(turkestan_non_2016, on='rayon', how='left')
turkestan_2017 = turkestan_all_2017.merge(turkestan_non_2017, on='rayon', how='left')
turkestan_2018 = turkestan_all_2018.merge(turkestan_non_2018, on='rayon', how='left')
turkestan_2019 = turkestan_all_2019.merge(turkestan_non_2019, on='rayon', how='left')
turkestan_2020 = turkestan_all_2020.merge(turkestan_non_2020, on='rayon', how='left')
turkestan_2021 = turkestan_all_2021.merge(turkestan_non_2021, on='rayon', how='left')
turkestan_2022 = turkestan_all_2022.merge(turkestan_non_2022, on='rayon', how='left')
turkestan_2023 = turkestan_all_2023.merge(turkestan_non_2023, on='rayon', how='left')
turkestan_2024 = turkestan_all_2024.merge(turkestan_non_2024, on='rayon', how='left')

dfs = [turkestan_2014, turkestan_2015, turkestan_2016, turkestan_2017, turkestan_2018, turkestan_2019, turkestan_2020, turkestan_2021, turkestan_2022, turkestan_2023, turkestan_2024]

for i in range(11):
    df = dfs[i]
    df['oblast'] = 'Turkestan'
    df['year'] = 2014 + i

turkestan_inv = pd.concat([turkestan_2014, turkestan_2015, turkestan_2016, turkestan_2017, turkestan_2018, turkestan_2019, turkestan_2020, turkestan_2021, turkestan_2022, turkestan_2023, turkestan_2024], ignore_index=True)
turkestan_inv['rayon'] = (
    turkestan_inv['rayon']
        .str.strip()          # remove hidden spaces
        .replace(rayon_map)   # enforce English names
)
turkestan_inv

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year
0,Shymkent city,154790266,17861645.0,17289353.0,95983918.0,Turkestan,2014
1,Arys city,8244208,434050.0,434050.0,2270985.0,Turkestan,2014
2,Kentau city,5657478,27960.0,27960.0,1858103.0,Turkestan,2014
3,Turkestan city,19779288,831526.0,831526.0,8989299.0,Turkestan,2014
4,Baidibek,3963324,305626.0,283554.0,2335461.0,Turkestan,2014
...,...,...,...,...,...,...,...
171,Sauran,66182097,194677.0,194677.0,21030365.0,Turkestan,2024
172,Sozak,165803999,74691459.0,1443106.0,13976183.0,Turkestan,2024
173,Tolebi,43086768,155876.0,155876.0,23980570.0,Turkestan,2024
174,Tulkibas,32669962,1728262.0,1728262.0,18934008.0,Turkestan,2024
175,Shardara,36000875,6146158.0,6146158.0,11193037.0,Turkestan,2024

In [476]:
turkestan_inv['rayon'].unique()

array(['Shymkent city', 'Arys city', 'Kentau city', 'Turkestan city',
       'Baidibek', 'Kazygurt', 'Maktaaral', 'Ordabasy', 'Otyrar',
       'Sairam', 'Saryagash', 'Sozak', 'Tolebi', 'Tulkibas', 'Shardara',
       'Zhetysay', 'Keles', 'Sauran'], dtype=object)

## Employment

In [477]:
turkestan_empl = pd.read_excel(Path("../Data/Employment/Turkistan.xls"), skiprows=28, nrows=18, header=None, usecols='A:K', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
turkestan_empl.columns = ['rayon', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
turkestan_empl['rayon'] = turkestan_empl['rayon'].replace(rayon_map_turkestan)
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    turkestan_empl[i] = turkestan_empl[i].astype(float)
    turkestan_employment = turkestan_empl.melt(id_vars='rayon', value_vars=[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023], var_name='year', value_name='employment')
turkestan_employment

              rayon  year  employment
0     Shymkent city  2014    286313.0
1    Turkestan city  2014     88671.0
2         Arys city  2014     29053.0
3       Kentau city  2014     40075.0
4          Baidibek  2014     25459.0
..              ...   ...         ...
175          Sauran  2023     37929.0
176           Sozak  2023     24571.0
177          Tolebi  2023     47235.0
178        Tulkibas  2023     40660.0
179        Shardara  2023     31825.0

[180 rows x 3 columns]

In [478]:
turkestan_employment['rayon'].unique()

array(['Shymkent city', 'Turkestan city', 'Arys city', 'Kentau city',
       'Baidibek', 'Zhetysay', 'Keles', 'Kazygurt', 'Maktaaral',
       'Ordabasy', 'Otyrar', 'Sairam', 'Saryagash', 'Sauran', 'Sozak',
       'Tolebi', 'Tulkibas', 'Shardara'], dtype=object)

## Other Controls

In [479]:
shymkent_city = pd.read_excel(Path("../Data/Controls/Turkistan_All.xls"), sheet_name="г.Шымкент", header=2, usecols='A, X:AB', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
shymkent_city.columns = ['Indicator', 2013, 2014, 2015, 2016, 2017]
shymkent_city = shymkent_city.loc[[99, 128, 172]].reset_index(drop=True)
shymkent_city['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2013, 2014, 2015, 2016, 2017]:
    shymkent_city[i] = shymkent_city[i].astype(str)
    shymkent_city[i] = shymkent_city[i].str.replace(',', '.')
    shymkent_city[i] = shymkent_city[i].str.replace(')', '')
    shymkent_city[i] = shymkent_city[i].str.replace(' ', '')
    shymkent_city[i] = shymkent_city[i].str.replace('\xa0', '')
    shymkent_city[i] = shymkent_city[i].str.replace('*', '')
    shymkent_city[i] = shymkent_city[i].astype(float)
shymkent_city = pd.melt(shymkent_city, id_vars=['Indicator'], var_name='year', value_name='value')
shymkent_city = shymkent_city.pivot(index='year', columns='Indicator', values='value').reset_index()
shymkent_city.insert(0, 'rayon', 'Shymkent city')
shymkent_city.columns.name = None
shymkent_city

           rayon  year  agriculture  production    retail
0  Shymkent city  2013      13086.9  202579.900  204788.7
1  Shymkent city  2014      16590.8  244268.600  241549.4
2  Shymkent city  2015      20755.8  281531.600  227256.3
3  Shymkent city  2016      22548.6  335761.700  270276.7
4  Shymkent city  2017      24357.3  247761.546  202281.2

In [480]:
turkestan_city = pd.read_excel(Path("../Data/Controls/Turkistan_All.xls"), sheet_name="г.Туркестан", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
turkestan_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
turkestan_city = turkestan_city.loc[[100, 129, 173]].reset_index(drop=True)
turkestan_city['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    turkestan_city[i] = turkestan_city[i].astype(str)
    turkestan_city[i] = turkestan_city[i].str.replace(',', '.')
    turkestan_city[i] = turkestan_city[i].str.replace(')', '')
    turkestan_city[i] = turkestan_city[i].str.replace(' ', '')
    turkestan_city[i] = turkestan_city[i].str.replace('\xa0', '')
    turkestan_city[i] = turkestan_city[i].str.replace('*', '')
    turkestan_city[i] = turkestan_city[i].astype(float)
turkestan_city = pd.melt(turkestan_city, id_vars=['Indicator'], var_name='year', value_name='value')
turkestan_city = turkestan_city.pivot(index='year', columns='Indicator', values='value').reset_index()
turkestan_city.insert(0, 'rayon', 'Turkestan city')
turkestan_city.columns.name = None
turkestan_city

             rayon  year  agriculture  production   retail
0   Turkestan city  2014     36269.10     11745.6  18770.9
1   Turkestan city  2015     37013.10     11701.7  19910.4
2   Turkestan city  2016     39738.20     13634.0  24469.6
3   Turkestan city  2017     43086.20     12870.0  27731.4
4   Turkestan city  2018      5503.40      9757.0  37404.9
5   Turkestan city  2019      2923.90     11289.0  41567.5
6   Turkestan city  2020      6903.00     16451.0  43463.9
7   Turkestan city  2021      7954.00     20045.0  55734.2
8   Turkestan city  2022      7707.71     22284.0  66398.3
9   Turkestan city  2023      9010.50     29340.0  79469.4
10  Turkestan city  2024     10678.40     34794.0  92310.9

In [481]:
arys_city = pd.read_excel(Path("../Data/Controls/Turkistan_All.xls"), sheet_name="г.а.Арысь", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
arys_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
arys_city = arys_city.loc[[100, 129, 173]].reset_index(drop=True)
arys_city['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    arys_city[i] = arys_city[i].astype(str)
    arys_city[i] = arys_city[i].str.replace(',', '.')
    arys_city[i] = arys_city[i].str.replace(')', '')
    arys_city[i] = arys_city[i].str.replace(' ', '')
    arys_city[i] = arys_city[i].str.replace('\xa0', '')
    arys_city[i] = arys_city[i].str.replace('*', '')
    arys_city[i] = arys_city[i].astype(float)
arys_city = pd.melt(arys_city, id_vars=['Indicator'], var_name='year', value_name='value')
arys_city = arys_city.pivot(index='year', columns='Indicator', values='value').reset_index()
arys_city.insert(0, 'rayon', 'Arys city')
arys_city.columns.name = None
arys_city

        rayon  year  agriculture  production   retail
0   Arys city  2014      9727.90      6086.0   4313.0
1   Arys city  2015     10649.00      7335.3   4574.5
2   Arys city  2016     11192.20      7402.6   5372.3
3   Arys city  2017     13138.90      8813.0   5810.2
4   Arys city  2018     13219.70      4865.0   6453.9
5   Arys city  2019     15572.40      3749.0   6978.5
6   Arys city  2020     19206.80      4731.0   7367.9
7   Arys city  2021     19779.80      5985.0   8391.0
8   Arys city  2022     20951.49      7524.0   9772.8
9   Arys city  2023     19877.40     10843.0  11213.3
10  Arys city  2024     21458.30     10317.0   9893.8

In [482]:
kentau_city = pd.read_excel(Path("../Data/Controls/Turkistan_All.xls"), sheet_name="г.а.Кентау", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
kentau_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
kentau_city = kentau_city.loc[[100, 129, 173]].reset_index(drop=True)
kentau_city['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    kentau_city[i] = kentau_city[i].astype(str)
    kentau_city[i] = kentau_city[i].str.replace(',', '.')
    kentau_city[i] = kentau_city[i].str.replace(')', '')
    kentau_city[i] = kentau_city[i].str.replace(' ', '')
    kentau_city[i] = kentau_city[i].str.replace('\xa0', '')
    kentau_city[i] = kentau_city[i].str.replace('*', '')
    kentau_city[i] = kentau_city[i].astype(float)
kentau_city = pd.melt(kentau_city, id_vars=['Indicator'], var_name='year', value_name='value')
kentau_city = kentau_city.pivot(index='year', columns='Indicator', values='value').reset_index()
kentau_city.insert(0, 'rayon', 'Kentau city')
kentau_city.columns.name = None
kentau_city

          rayon  year  agriculture  production   retail
0   Kentau city  2014      2542.10     21449.8   4622.9
1   Kentau city  2015      2740.50     21166.8   4919.9
2   Kentau city  2016      2813.50     23827.6   5841.3
3   Kentau city  2017      3242.10     26368.0   6718.6
4   Kentau city  2018     51336.50     29772.0   8816.8
5   Kentau city  2019     60835.50     32797.0   9565.2
6   Kentau city  2020      7911.00     38373.0   9524.6
7   Kentau city  2021     10353.40     32811.0  10979.6
8   Kentau city  2022     10393.91     41188.0  12770.0
9   Kentau city  2023     11531.20     43747.0  14859.8
10  Kentau city  2024     12350.10     51209.0  13262.0

In [483]:
baidibek = pd.read_excel(Path("../Data/Controls/Turkistan_All.xls"), sheet_name="Байдибек", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
baidibek.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
baidibek = baidibek.loc[[100, 129, 173]].reset_index(drop=True)
baidibek['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    baidibek[i] = baidibek[i].astype(str)
    baidibek[i] = baidibek[i].str.replace(',', '.')
    baidibek[i] = baidibek[i].str.replace(')', '')
    baidibek[i] = baidibek[i].str.replace(' ', '')
    baidibek[i] = baidibek[i].str.replace('\xa0', '')
    baidibek[i] = baidibek[i].str.replace('*', '')
    baidibek[i] = baidibek[i].astype(float)
baidibek = pd.melt(baidibek, id_vars=['Indicator'], var_name='year', value_name='value')
baidibek = baidibek.pivot(index='year', columns='Indicator', values='value').reset_index()
baidibek.insert(0, 'rayon', 'Baidibek')
baidibek.columns.name = None
baidibek

       rayon  year  agriculture  production  retail
0   Baidibek  2014      14919.3      2498.0  2195.7
1   Baidibek  2015      14774.9      2337.0  2332.9
2   Baidibek  2016      15589.6      2567.0  2828.0
3   Baidibek  2017      17785.9      3128.0  3142.8
4   Baidibek  2018      19090.3      2064.0  2493.6
5   Baidibek  2019      21945.7      1825.0  2725.3
6   Baidibek  2020      26903.8      1118.0  2754.9
7   Baidibek  2021      28254.8      1321.0  4206.5
8   Baidibek  2022     326069.0       566.0  4896.0
9   Baidibek  2023      31447.2       997.0  6814.8
10  Baidibek  2024      36501.7       923.0  8135.1

In [484]:
zhetysay = pd.read_excel(Path("../Data/Controls/Turkistan_All.xls"), sheet_name="Жетысай", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
zhetysay.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
zhetysay = zhetysay.loc[[100, 129, 173]].reset_index(drop=True)
zhetysay['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    zhetysay[i] = zhetysay[i].astype(str)
    zhetysay[i] = zhetysay[i].str.replace(',', '.')
    zhetysay[i] = zhetysay[i].str.replace(')', '')
    zhetysay[i] = zhetysay[i].str.replace(' ', '')
    zhetysay[i] = zhetysay[i].str.replace('\xa0', '')
    zhetysay[i] = zhetysay[i].str.replace('*', '')
    zhetysay[i] = zhetysay[i].astype(float)
zhetysay = pd.melt(zhetysay, id_vars=['Indicator'], var_name='year', value_name='value')
zhetysay = zhetysay.pivot(index='year', columns='Indicator', values='value').reset_index()
zhetysay.insert(0, 'rayon', 'Zhetysay')
zhetysay.columns.name = None
zhetysay

       rayon  year  agriculture  production   retail
0   Zhetysay  2014          NaN         NaN      NaN
1   Zhetysay  2015          NaN         NaN      NaN
2   Zhetysay  2016          NaN         NaN      NaN
3   Zhetysay  2017          NaN         NaN      NaN
4   Zhetysay  2018     56228.00      8131.0  15952.9
5   Zhetysay  2019     58722.10      7608.0  17910.0
6   Zhetysay  2020     66707.70      7797.0  18344.4
7   Zhetysay  2021     98466.80      8236.0  21453.3
8   Zhetysay  2022     99198.79     18394.0  25164.7
9   Zhetysay  2023     93656.70     18297.0  29770.7
10  Zhetysay  2024    107915.50     18490.0  28360.6

In [485]:
keles = pd.read_excel(Path("../Data/Controls/Turkistan_All.xls"), sheet_name="Келес", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
keles.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
keles = keles.loc[[100, 129, 173]].reset_index(drop=True)
keles['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    keles[i] = keles[i].astype(str)
    keles[i] = keles[i].str.replace(',', '.')
    keles[i] = keles[i].str.replace(')', '')
    keles[i] = keles[i].str.replace(' ', '')
    keles[i] = keles[i].str.replace('\xa0', '')
    keles[i] = keles[i].str.replace('*', '')
    keles[i] = keles[i].astype(float)
keles = pd.melt(keles, id_vars=['Indicator'], var_name='year', value_name='value')
keles = keles.pivot(index='year', columns='Indicator', values='value').reset_index()
keles.insert(0, 'rayon', 'Keles')
keles.columns.name = None
keles

    rayon  year  agriculture  production   retail
0   Keles  2014          NaN         NaN      NaN
1   Keles  2015          NaN         NaN      NaN
2   Keles  2016          NaN         NaN      NaN
3   Keles  2017          NaN         NaN      NaN
4   Keles  2018     35310.70      3177.0   4575.2
5   Keles  2019     39267.40      4047.0   4872.1
6   Keles  2020     48972.90      4076.0   4900.3
7   Keles  2021     60538.20      5060.0   7380.2
8   Keles  2022     63621.89      3695.0  10178.2
9   Keles  2023     66501.40      5014.0  15124.4
10  Keles  2024     69444.00      5392.0  13486.2

In [486]:
Maktaaral = pd.read_excel(Path("../Data/Controls/Turkistan_All.xls"), sheet_name="Мактаарал", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Maktaaral.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Maktaaral = Maktaaral.loc[[100, 129, 173]].reset_index(drop=True)
Maktaaral['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Maktaaral[i] = Maktaaral[i].astype(str)
    Maktaaral[i] = Maktaaral[i].str.replace(',', '.')
    Maktaaral[i] = Maktaaral[i].str.replace(')', '')
    Maktaaral[i] = Maktaaral[i].str.replace(' ', '')
    Maktaaral[i] = Maktaaral[i].str.replace('\xa0', '')
    Maktaaral[i] = Maktaaral[i].str.replace('*', '')
    Maktaaral[i] = Maktaaral[i].astype(float)
Maktaaral = pd.melt(Maktaaral, id_vars=['Indicator'], var_name='year', value_name='value')
Maktaaral = Maktaaral.pivot(index='year', columns='Indicator', values='value').reset_index()
Maktaaral.insert(0, 'rayon', 'Maktaaral')
Maktaaral.columns.name = None
Maktaaral

        rayon  year  agriculture  production   retail
0   Maktaaral  2014     72649.40      9997.0   8071.1
1   Maktaaral  2015     74952.40      9335.0   8461.8
2   Maktaaral  2016     79917.60     10096.0  10262.5
3   Maktaaral  2017     83126.60     12113.0  11577.1
4   Maktaaral  2018     42373.10      8248.0   4227.1
5   Maktaaral  2019     42467.70     10668.0   4471.9
6   Maktaaral  2020     48263.40     16719.0   4608.3
7   Maktaaral  2021     72623.40     15851.0   5800.1
8   Maktaaral  2022     72854.51     13214.0   6727.7
9   Maktaaral  2023     68797.80     26540.0   7713.9
10  Maktaaral  2024     80620.80     20152.0   8067.2

In [487]:
Ordabasy = pd.read_excel(Path("../Data/Controls/Turkistan_All.xls"), sheet_name="Ордабасы", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Ordabasy.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Ordabasy = Ordabasy.loc[[100, 129, 173]].reset_index(drop=True)
Ordabasy['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Ordabasy[i] = Ordabasy[i].astype(str)
    Ordabasy[i] = Ordabasy[i].str.replace(',', '.')
    Ordabasy[i] = Ordabasy[i].str.replace(')', '')
    Ordabasy[i] = Ordabasy[i].str.replace(' ', '')
    Ordabasy[i] = Ordabasy[i].str.replace('\xa0', '')
    Ordabasy[i] = Ordabasy[i].str.replace('*', '')
    Ordabasy[i] = Ordabasy[i].astype(float)
Ordabasy = pd.melt(Ordabasy, id_vars=['Indicator'], var_name='year', value_name='value')
Ordabasy = Ordabasy.pivot(index='year', columns='Indicator', values='value').reset_index()
Ordabasy.insert(0, 'rayon', 'Ordabasy')
Ordabasy.columns.name = None
Ordabasy

       rayon  year  agriculture  production   retail
0   Ordabasy  2014     29688.20     12158.0   3940.5
1   Ordabasy  2015     28898.60     11858.0   4183.4
2   Ordabasy  2016     31998.50     16177.0   5058.5
3   Ordabasy  2017     32144.70     13967.0   5648.4
4   Ordabasy  2018     35356.40     18020.0   6007.8
5   Ordabasy  2019     42624.60     20955.0   6352.3
6   Ordabasy  2020     52553.80     22853.0   6485.2
7   Ordabasy  2021     65393.50     27749.0   7826.8
8   Ordabasy  2022     61730.49     30500.0   9074.6
9   Ordabasy  2023     61889.40     34579.0  10427.2
10  Ordabasy  2024     71172.80     45273.0  14229.2

In [488]:
Otyrar = pd.read_excel(Path("../Data/Controls/Turkistan_All.xls"), sheet_name="Отрар", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Otyrar.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Otyrar = Otyrar.loc[[100, 129, 173]].reset_index(drop=True)
Otyrar['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Otyrar[i] = Otyrar[i].astype(str)
    Otyrar[i] = Otyrar[i].str.replace(',', '.')
    Otyrar[i] = Otyrar[i].str.replace(')', '')
    Otyrar[i] = Otyrar[i].str.replace(' ', '')
    Otyrar[i] = Otyrar[i].str.replace('\xa0', '')
    Otyrar[i] = Otyrar[i].str.replace('*', '')
    Otyrar[i] = Otyrar[i].astype(float)
Otyrar = pd.melt(Otyrar, id_vars=['Indicator'], var_name='year', value_name='value')
Otyrar = Otyrar.pivot(index='year', columns='Indicator', values='value').reset_index()
Otyrar.insert(0, 'rayon', 'Otyrar')
Otyrar.columns.name = None
Otyrar

     rayon  year  agriculture  production  retail
0   Otyrar  2014      10754.4     15623.0  1986.0
1   Otyrar  2015      12359.9     14409.0  2036.9
2   Otyrar  2016      13339.2     15014.0  2345.7
3   Otyrar  2017      15384.4     15027.0  2834.9
4   Otyrar  2018      19215.2     12791.0  3370.8
5   Otyrar  2019      22102.9     13529.0  3767.7
6   Otyrar  2020      27208.1     12072.0  3784.0
7   Otyrar  2021      32620.0     14873.0  4119.3
8   Otyrar  2022     351959.0     18220.0  4773.4
9   Otyrar  2023      35125.1     20290.0  5450.5
10  Otyrar  2024      37382.6     29173.0  3954.4

In [489]:
Sairam = pd.read_excel(Path("../Data/Controls/Turkistan_All.xls"), sheet_name="Сайрам", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Sairam.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Sairam = Sairam.loc[[100, 129, 173]].reset_index(drop=True)
Sairam['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Sairam[i] = Sairam[i].astype(str)
    Sairam[i] = Sairam[i].str.replace(',', '.')
    Sairam[i] = Sairam[i].str.replace(')', '')
    Sairam[i] = Sairam[i].str.replace(' ', '')
    Sairam[i] = Sairam[i].str.replace('\xa0', '')
    Sairam[i] = Sairam[i].str.replace('*', '')
    Sairam[i] = Sairam[i].astype(float)
Sairam = pd.melt(Sairam, id_vars=['Indicator'], var_name='year', value_name='value')
Sairam = Sairam.pivot(index='year', columns='Indicator', values='value').reset_index()
Sairam.insert(0, 'rayon', 'Sairam')
Sairam.columns.name = None
Sairam

     rayon  year  agriculture  production   retail
0   Sairam  2014     48666.60     22348.0  18348.5
1   Sairam  2015     44625.80     18257.0  19472.0
2   Sairam  2016     51476.80     28955.0  24027.3
3   Sairam  2017     54258.90     37919.0  24285.1
4   Sairam  2018     63903.60     27910.0  26688.3
5   Sairam  2019     74106.80     27752.0  33664.0
6   Sairam  2020     87041.30     33882.0  33494.2
7   Sairam  2021    107253.90     38085.0  37623.2
8   Sairam  2022    104797.69     55043.0  49667.2
9   Sairam  2023    116787.40     53501.0  58542.3
10  Sairam  2024    145145.30     58385.0  49277.7

In [490]:
Saryagash = pd.read_excel(Path("../Data/Controls/Turkistan_All.xls"), sheet_name="Сарыагаш", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Saryagash.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Saryagash = Saryagash.loc[[100, 129, 173]].reset_index(drop=True)
Saryagash['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Saryagash[i] = Saryagash[i].astype(str)
    Saryagash[i] = Saryagash[i].str.replace(',', '.')
    Saryagash[i] = Saryagash[i].str.replace(')', '')
    Saryagash[i] = Saryagash[i].str.replace(' ', '')
    Saryagash[i] = Saryagash[i].str.replace('\xa0', '')
    Saryagash[i] = Saryagash[i].str.replace('*', '')
    Saryagash[i] = Saryagash[i].astype(float)
Saryagash = pd.melt(Saryagash, id_vars=['Indicator'], var_name='year', value_name='value')
Saryagash = Saryagash.pivot(index='year', columns='Indicator', values='value').reset_index()
Saryagash.insert(0, 'rayon', 'Saryagash')
Saryagash.columns.name = None
Saryagash

        rayon  year  agriculture  production   retail
0   Saryagash  2014     73297.20     21993.0  16580.5
1   Saryagash  2015     69089.20     22858.0  17642.1
2   Saryagash  2016     91787.20     27873.0  21130.2
3   Saryagash  2017     86547.20     27223.0  24016.3
4   Saryagash  2018     58652.60     22659.0  27221.2
5   Saryagash  2019     70303.10     28015.0  29032.5
6   Saryagash  2020     92768.60     25988.0  30534.8
7   Saryagash  2021    104867.00     25585.0  34656.1
8   Saryagash  2022    100525.81     30100.0  45089.8
9   Saryagash  2023    123654.60     26508.0  54452.8
10  Saryagash  2024    133559.80     27855.0  71962.3

In [491]:
Sauran = pd.read_excel(Path("../Data/Controls/Turkistan_All.xls"), sheet_name="Сауран", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Sauran.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Sauran = Sauran.loc[[100, 129, 173]].reset_index(drop=True)
Sauran['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Sauran[i] = Sauran[i].astype(str)
    Sauran[i] = Sauran[i].str.replace(',', '.')
    Sauran[i] = Sauran[i].str.replace(')', '')
    Sauran[i] = Sauran[i].str.replace(' ', '')
    Sauran[i] = Sauran[i].str.replace('\xa0', '')
    Sauran[i] = Sauran[i].str.replace('*', '')
    Sauran[i] = Sauran[i].astype(float)
Sauran = pd.melt(Sauran, id_vars=['Indicator'], var_name='year', value_name='value')
Sauran = Sauran.pivot(index='year', columns='Indicator', values='value').reset_index()
Sauran.insert(0, 'rayon', 'Sauran')
Sauran.columns.name = None
Sauran

     rayon  year  agriculture  production  retail
0   Sauran  2014          NaN         NaN     NaN
1   Sauran  2015          NaN         NaN     NaN
2   Sauran  2016          NaN         NaN     NaN
3   Sauran  2017          NaN         NaN     NaN
4   Sauran  2018          NaN         NaN     NaN
5   Sauran  2019          NaN         NaN     NaN
6   Sauran  2020     65567.30         NaN     NaN
7   Sauran  2021     82487.40      9047.0  1044.4
8   Sauran  2022     79479.59      7633.0  1220.6
9   Sauran  2023     86259.80     12386.0  1596.9
10  Sauran  2024     89015.30     15816.0  4249.6

In [492]:
Sozak = pd.read_excel(Path("../Data/Controls/Turkistan_All.xls"), sheet_name="Сузак", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Sozak.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Sozak = Sozak.loc[[100, 129, 173]].reset_index(drop=True)
Sozak['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Sozak[i] = Sozak[i].astype(str)
    Sozak[i] = Sozak[i].str.replace(',', '.')
    Sozak[i] = Sozak[i].str.replace(')', '')
    Sozak[i] = Sozak[i].str.replace(' ', '')
    Sozak[i] = Sozak[i].str.replace('\xa0', '')
    Sozak[i] = Sozak[i].str.replace('*', '')
    Sozak[i] = Sozak[i].astype(float)
Sozak = pd.melt(Sozak, id_vars=['Indicator'], var_name='year', value_name='value')
Sozak = Sozak.pivot(index='year', columns='Indicator', values='value').reset_index()
Sozak.insert(0, 'rayon', 'Sozak')
Sozak.columns.name = None
Sozak

    rayon  year  agriculture  production   retail
0   Sozak  2014      9539.60    186242.0   3338.1
1   Sozak  2015      9927.70    219216.0   3440.8
2   Sozak  2016      9866.80    255018.0   3784.7
3   Sozak  2017     11242.00    194111.0   4451.7
4   Sozak  2018     12824.30    228868.0   5505.5
5   Sozak  2019     13273.40    282474.0   6233.0
6   Sozak  2020     14609.10    289499.0   6289.7
7   Sozak  2021     17884.10    419677.0   7575.8
8   Sozak  2022     17330.59    547457.0   8852.5
9   Sozak  2023     19002.20    647833.0  10126.8
10  Sozak  2024     19635.60    749791.0   6939.8

In [493]:
Tolebi = pd.read_excel(Path("../Data/Controls/Turkistan_All.xls"), sheet_name="Толеби", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Tolebi.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Tolebi = Tolebi.loc[[100, 129, 173]].reset_index(drop=True)
Tolebi['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Tolebi[i] = Tolebi[i].astype(str)
    Tolebi[i] = Tolebi[i].str.replace(',', '.')
    Tolebi[i] = Tolebi[i].str.replace(')', '')
    Tolebi[i] = Tolebi[i].str.replace(' ', '')
    Tolebi[i] = Tolebi[i].str.replace('\xa0', '')
    Tolebi[i] = Tolebi[i].str.replace('*', '')
    Tolebi[i] = Tolebi[i].astype(float)
Tolebi = pd.melt(Tolebi, id_vars=['Indicator'], var_name='year', value_name='value')
Tolebi = Tolebi.pivot(index='year', columns='Indicator', values='value').reset_index()
Tolebi.insert(0, 'rayon', 'Tolebi')
Tolebi.columns.name = None
Tolebi

     rayon  year  agriculture  production   retail
0   Tolebi  2014     25845.20     20433.0   8542.9
1   Tolebi  2015     26517.60     21624.0   9430.9
2   Tolebi  2016     29265.90     21577.0  11126.5
3   Tolebi  2017     31660.00     24694.0  11048.5
4   Tolebi  2018     35107.40     31740.0   7869.9
5   Tolebi  2019     39055.80     32410.0   8516.3
6   Tolebi  2020     48168.90     34825.0   8484.7
7   Tolebi  2021     57344.70     45448.0   9986.3
8   Tolebi  2022     51602.89     40747.0  12569.5
9   Tolebi  2023     54169.70     46562.0  14531.2
10  Tolebi  2024     54869.60     64967.0  23530.8

In [494]:
Tulkibas = pd.read_excel(Path("../Data/Controls/Turkistan_All.xls"), sheet_name="Тюлькубас", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Tulkibas.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Tulkibas = Tulkibas.loc[[100, 129, 173]].reset_index(drop=True)
Tulkibas['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Tulkibas[i] = Tulkibas[i].astype(str)
    Tulkibas[i] = Tulkibas[i].str.replace(',', '.')
    Tulkibas[i] = Tulkibas[i].str.replace(')', '')
    Tulkibas[i] = Tulkibas[i].str.replace(' ', '')
    Tulkibas[i] = Tulkibas[i].str.replace('\xa0', '')
    Tulkibas[i] = Tulkibas[i].str.replace('*', '')
    Tulkibas[i] = Tulkibas[i].astype(float)
Tulkibas = pd.melt(Tulkibas, id_vars=['Indicator'], var_name='year', value_name='value')
Tulkibas = Tulkibas.pivot(index='year', columns='Indicator', values='value').reset_index()
Tulkibas.insert(0, 'rayon', 'Tulkibas')
Tulkibas.columns.name = None
Tulkibas

       rayon  year  agriculture  production   retail
0   Tulkibas  2014     24387.10     17410.0   7054.5
1   Tulkibas  2015     25300.00     17009.0   7383.1
2   Tulkibas  2016     28548.50     17977.0   8923.2
3   Tulkibas  2017     31298.80     22031.0   9876.6
4   Tulkibas  2018     34624.20     17258.0  10388.6
5   Tulkibas  2019     38441.30     13539.0  11145.3
6   Tulkibas  2020     44818.40     12980.0  11309.3
7   Tulkibas  2021     53140.40     13251.0  12358.1
8   Tulkibas  2022     48801.59     15678.0  14320.6
9   Tulkibas  2023     51045.20     16993.0  16499.0
10  Tulkibas  2024     52766.20     18191.0  10920.7

In [495]:
Shardara = pd.read_excel(Path("../Data/Controls/Turkistan_All.xls"), sheet_name="Шардара", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Shardara.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Shardara = Shardara.loc[[100, 129, 173]].reset_index(drop=True)
Shardara['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Shardara[i] = Shardara[i].astype(str)
    Shardara[i] = Shardara[i].str.replace(',', '.')
    Shardara[i] = Shardara[i].str.replace(')', '')
    Shardara[i] = Shardara[i].str.replace(' ', '')
    Shardara[i] = Shardara[i].str.replace('\xa0', '')
    Shardara[i] = Shardara[i].str.replace('*', '')
    Shardara[i] = Shardara[i].astype(float)
Shardara = pd.melt(Shardara, id_vars=['Indicator'], var_name='year', value_name='value')
Shardara = Shardara.pivot(index='year', columns='Indicator', values='value').reset_index()
Shardara.insert(0, 'rayon', 'Shardara')
Shardara.columns.name = None
Shardara

       rayon  year  agriculture  production  retail
0   Shardara  2014      16707.9      6119.0  7001.8
1   Shardara  2015      21144.9      7009.0  7232.6
2   Shardara  2016      21770.4      7252.0  7979.2
3   Shardara  2017      25260.5      7500.0  7997.1
4   Shardara  2018      29781.6      6533.0  5735.0
5   Shardara  2019      32784.0      7686.0  6067.8
6   Shardara  2020      36339.7     12395.0  5994.4
7   Shardara  2021      53857.0     12177.0  6520.6
8   Shardara  2022     615089.0     17569.0  7622.9
9   Shardara  2023      55265.1     22386.0  8604.2
10  Shardara  2024      60777.6     21626.0  6437.8

In [496]:
Kazygurt = pd.read_excel(Path("../Data/Controls/Turkistan_All.xls"), sheet_name="Казыгурт", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Kazygurt.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Kazygurt = Kazygurt.loc[[100, 129, 173]].reset_index(drop=True)
Kazygurt['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Kazygurt[i] = Kazygurt[i].astype(str)
    Kazygurt[i] = Kazygurt[i].str.replace(',', '.')
    Kazygurt[i] = Kazygurt[i].str.replace(')', '')
    Kazygurt[i] = Kazygurt[i].str.replace(' ', '')
    Kazygurt[i] = Kazygurt[i].str.replace('\xa0', '')
    Kazygurt[i] = Kazygurt[i].str.replace('*', '')
    Kazygurt[i] = Kazygurt[i].astype(float)
Kazygurt = pd.melt(Kazygurt, id_vars=['Indicator'], var_name='year', value_name='value')
Kazygurt = Kazygurt.pivot(index='year', columns='Indicator', values='value').reset_index()
Kazygurt.insert(0, 'rayon', 'Kazygurt')
Kazygurt.columns.name = None
Kazygurt

       rayon  year  agriculture  production   retail
0   Kazygurt  2014     28102.40      5632.0   4907.5
1   Kazygurt  2015     28145.00      4762.0   5229.8
2   Kazygurt  2016     30546.30      5919.0   6331.8
3   Kazygurt  2017     32759.90      7254.0   6284.7
4   Kazygurt  2018     36179.70      6850.0   4850.3
5   Kazygurt  2019     39579.80      6611.0   5132.6
6   Kazygurt  2020     49936.80      9424.0   4998.4
7   Kazygurt  2021     58224.50     12601.0   6199.1
8   Kazygurt  2022     57895.69     11886.0   7322.1
9   Kazygurt  2023     59595.90     12653.0   8348.8
10  Kazygurt  2024     71981.10     15412.0  17502.5

In [497]:
turkestan_controls = pd.concat([shymkent_city, turkestan_city, arys_city, kentau_city, baidibek, zhetysay, keles, Kazygurt, Maktaaral, Ordabasy, Otyrar, Sairam, Saryagash, Sauran, Sozak, Tolebi, Tulkibas, Shardara], ignore_index=True)
turkestan_controls

             rayon  year  agriculture  production    retail
0    Shymkent city  2013      13086.9  202579.900  204788.7
1    Shymkent city  2014      16590.8  244268.600  241549.4
2    Shymkent city  2015      20755.8  281531.600  227256.3
3    Shymkent city  2016      22548.6  335761.700  270276.7
4    Shymkent city  2017      24357.3  247761.546  202281.2
..             ...   ...          ...         ...       ...
187       Shardara  2020      36339.7   12395.000    5994.4
188       Shardara  2021      53857.0   12177.000    6520.6
189       Shardara  2022     615089.0   17569.000    7622.9
190       Shardara  2023      55265.1   22386.000    8604.2
191       Shardara  2024      60777.6   21626.000    6437.8

[192 rows x 5 columns]

In [498]:
turkestan_controls['rayon'].unique()

array(['Shymkent city', 'Turkestan city', 'Arys city', 'Kentau city',
       'Baidibek', 'Zhetysay', 'Keles', 'Kazygurt', 'Maktaaral',
       'Ordabasy', 'Otyrar', 'Sairam', 'Saryagash', 'Sauran', 'Sozak',
       'Tolebi', 'Tulkibas', 'Shardara'], dtype=object)

## PPI

In [499]:
turkestan_ppi = pd.read_excel(
    Path("../Data/PPI/Turkistan.xls"),
    header=2,
    usecols='Y:AI',
    nrows=64,
    na_values=['x', 'х', '-', '', ' ', '...']
)
turkestan_ppi.columns = [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
rayons = list(turkestan_inv['rayon'].unique())

dfs = []

for rayon in rayons:
    df_temp = pd.DataFrame({
        'rayon': [rayon] * len(range(2014, 2025)),
        'year': list(range(2014, 2025)),
        'ppi': turkestan_ppi.iloc[-1].values
    })
    dfs.append(df_temp)

turkestan_ppi = pd.concat(dfs, ignore_index=True)
turkestan_ppi['ppi'] = turkestan_ppi['ppi'].astype(str).str.replace(',', '.')
turkestan_ppi['ppi'] = turkestan_ppi['ppi'].astype(str).str.replace(')', '')
turkestan_ppi['ppi'] = turkestan_ppi['ppi'].astype(str).str.replace(' ', '')
turkestan_ppi['ppi'] = turkestan_ppi['ppi'].astype(str).str.replace('\xa0', '')
turkestan_ppi['ppi'] = turkestan_ppi['ppi'].astype(str).str.replace('*', '')
turkestan_ppi['ppi'] = turkestan_ppi['ppi'].astype(float)

turkestan_ppi

             rayon  year    ppi
0    Shymkent city  2014  105.4
1    Shymkent city  2015  101.8
2    Shymkent city  2016  110.3
3    Shymkent city  2017  108.6
4    Shymkent city  2018   98.6
..             ...   ...    ...
193         Sauran  2020  105.1
194         Sauran  2021  106.0
195         Sauran  2022  112.4
196         Sauran  2023  107.2
197         Sauran  2024  101.5

[198 rows x 3 columns]

In [500]:
turkestan_inv['rayon'].unique()

array(['Shymkent city', 'Arys city', 'Kentau city', 'Turkestan city',
       'Baidibek', 'Kazygurt', 'Maktaaral', 'Ordabasy', 'Otyrar',
       'Sairam', 'Saryagash', 'Sozak', 'Tolebi', 'Tulkibas', 'Shardara',
       'Zhetysay', 'Keles', 'Sauran'], dtype=object)

## Combine

In [501]:
dfs_turkestan = [turkestan_inv, turkestan_employment, turkestan_controls, turkestan_ppi]
turkestan_merged = reduce(lambda left, right: pd.merge(left, right, on=['rayon', 'year'], how='outer'), dfs_turkestan)
turkestan_merged['oblast'] = turkestan_merged['oblast'].fillna('Turkestan')
turkestan_merged

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year,employment,agriculture,production,retail,ppi
0,Arys city,8244208,434050.0,434050.0,2270985.0,Turkestan,2014,29053.0,9727.90,6086.0,4313.0,105.4
1,Arys city,6024011,42748.0,42748.0,1601384.0,Turkestan,2015,30638.0,10649.00,7335.3,4574.5,101.8
2,Arys city,9801380,89480.0,89480.0,8758883.0,Turkestan,2016,29573.0,11192.20,7402.6,5372.3,110.3
3,Arys city,5829919,1288.0,1288.0,1849635.0,Turkestan,2017,31137.0,13138.90,8813.0,5810.2,108.6
4,Arys city,7634123,92510.0,92510.0,2754515.0,Turkestan,2018,30188.0,13219.70,4865.0,6453.9,98.6
...,...,...,...,...,...,...,...,...,...,...,...,...
194,Zhetysay,10944444,7826.0,7826.0,2915803.0,Turkestan,2020,60216.0,66707.70,7797.0,18344.4,105.1
195,Zhetysay,28687170,392968.0,92968.0,23088271.0,Turkestan,2021,63109.0,98466.80,8236.0,21453.3,106.0
196,Zhetysay,14907457,146485.0,146485.0,2314467.0,Turkestan,2022,67301.0,99198.79,18394.0,25164.7,112.4
197,Zhetysay,19942162,3100.0,3100.0,3619627.0,Turkestan,2023,72809.0,93656.70,18297.0,29770.7,107.2
198,Zhetysay,39409037,4344866.0,4344866.0,7252512.0,Turkestan,2024,NaN,107915.50,18490.0,28360.6,101.5

# West-Kazakhstan

## Investments

In [502]:
west_all_2014 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2014_Investments.xls"), header=6, nrows=14, usecols='A, C, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
west_all_2015 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2015_Investments/Internal_vs_external.xls"), header=6, nrows=14, usecols='A, C, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
west_all_2016 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2016_Investments/Internal_vs_external.xls"), header=5, nrows=14, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
west_all_2017 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2017_Investments/Internal_vs_external.xls"), header=5, nrows=14, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
west_all_2017['внутренние'] = (
    west_all_2017['внутренние']
    .astype(str)
    .str.replace(' ', '', regex=False)
    .astype(float)
)
west_all_2017['внешние'] = (
    west_all_2017['внешние']
    .astype(str)
    .str.replace(' ', '', regex=False)
    .astype(float)
)
west_all_2018 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2018_Investments/Internal_vs_external.xls"), header=5, nrows=14, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
west_all_2019 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2019_Investments.xls"), sheet_name="14", header=7, nrows=14, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
west_all_2020 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2020_Investments.xls"), sheet_name="14", header=7, nrows=14, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
west_all_2021 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2021_Investments.xls"), sheet_name="13", header=7, nrows=14, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
west_all_2022 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2022_Investments.xls"), sheet_name="12.", header=5, nrows=14, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
west_all_2023 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2023_Investments.xls"), sheet_name="18", header=3, nrows=14, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
west_all_2024 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2024_Investments.xls"), sheet_name="14.", header=5, nrows=14, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [503]:
west_non_2015 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2015_Investments/Greenfield_investments.xls"), header=7, nrows=14, usecols='A, B, C', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
west_non_2016 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2016_Investments/Greenfield_investments.xls"), header=5, nrows=14, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
west_non_2017 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2017_Investments/Greenfield_investments.xls"), header=5, nrows=14, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
west_non_2017['Unnamed: 1'] = (
    west_non_2017['Unnamed: 1']
    .astype(str)
    .str.replace(' ', '', regex=False)
    .astype(float)
)
west_non_2017['внешние инвестиции'] = (
    west_non_2017['внешние инвестиции']
    .astype(str)
    .str.replace(' ', '', regex=False)
    .astype(float)
)
west_non_2017
west_non_2018 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2018_Investments/Greenfield_investments.xls"), header=5, nrows=14, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
west_non_2019 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2019_Investments.xls"), sheet_name="15", header=7, nrows=14, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
west_non_2020 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2020_Investments.xls"), sheet_name="15", header=7, nrows=14, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
west_non_2021 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2021_Investments.xls"), sheet_name="14", header=5, nrows=14, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
west_non_2022 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2022_Investments.xls"), sheet_name="13.", header=5, nrows=14, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
west_non_2023 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2023_Investments.xls"), sheet_name="19", header=3, nrows=14, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
west_non_2024 = pd.read_excel(Path("../Data/Investments/West-Kazakhstan/2024_Investments.xls"), sheet_name="15.", header=5, nrows=14, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [504]:
dfs = [west_all_2014, west_all_2015, west_all_2016, west_all_2017,
      west_all_2018, west_all_2019, west_all_2020, west_all_2021,
      west_all_2022, west_all_2023, west_all_2024,
      west_non_2015, west_non_2016, west_non_2017, west_non_2018,
      west_non_2019, west_non_2020, west_non_2021, west_non_2022,
      west_non_2023, west_non_2024]

lists = []

for df in dfs:
    lists.extend(df.iloc[:, 0].unique())

unique_lists = pd.Series(lists).unique()
unique_lists

array(['Ақжайық ', 'Бөкей ордасы', 'Бөрлі ', 'Жаңғала', 'Жәнібек',
       'Зеленов ', 'Казталов ', 'Қаратөбе', 'Сырым ', 'Тасқала ',
       'Теректі ', 'Шыңғырлау', 'Орал қ.', 'Казталов', 'Сырым',
       'Орал қ.ә', 'Ақжайық ауданы', 'Бөкейордасы  ауданы',
       'Бөрлі ауданы', 'Жаңақала ауданы', 'Жәнібек ауданы',
       'Зеленов ауданы', 'Казталовка ауданы', 'Қаратөбе ауданы',
       'Сырым ауданы', 'Тасқала ауданы', 'Теректі ауданы',
       'Шыңғырлау ауданы', 'Бөкей ордасы  ', 'Жаңақала ', 'Жәнібек ',
       'Қаратөбе ', 'Шыңғырлау ', 'Бәйтерек', 'Орал қ.ә.', 'Акжаикский',
       'Бокейординский', 'Бурлинский', 'Жангалинский', 'Жанибекский',
       'Казталовский ', 'Каратобинский', 'Сырымский', 'Таскалинский',
       'Теректинский', 'Чингирлауский', 'г.Уральск', 'Уральск г.а.',
       'Бөкейордасы ауданы', 'Бөкей ордасы '], dtype=object)

In [505]:
rayon_map_west = {

    # ---- City ----
    'Орал қ.': 'Oral city',
    'Орал қ.ә': 'Oral city',
    'Орал қ.ә.': 'Oral city',
    'г.Уральск': 'Oral city',
    'Уральск г.а.': 'Oral city',
    'г.Уральск ': 'Oral city',

    # ---- Akzhaiyk ----
    'Ақжайық ': 'Akzhaiyk',
    'Ақжайық ауданы': 'Akzhaiyk',
    'Акжаикский': 'Akzhaiyk',
    'Акжаик': 'Akzhaiyk',

    # ---- Bokey Orda ----
    'Бөкей ордасы': 'Bokey Orda',
    'Бөкей ордасы  ': 'Bokey Orda',
    'Бөкейордасы  ауданы': 'Bokey Orda',
    'Бөкейордасы ауданы': 'Bokey Orda',
    'Бокейординский': 'Bokey Orda',
    'Бокей орда': 'Bokey Orda',

    # ---- Borili ----
    'Бөрлі ': 'Borili',
    'Бөрлі ауданы': 'Borili',
    'Бурлинский': 'Borili',
    'Бурлин': 'Borili',

    # ---- Zhangala ----
    'Жаңғала': 'Zhangala',
    'Жаңақала ': 'Zhangala',
    'Жаңақала ауданы': 'Zhangala',
    'Жангалинский': 'Zhangala',
    'Жангала': 'Zhangala',

    # ---- Zhanibek ----
    'Жәнібек': 'Zhanibek',
    'Жәнібек ': 'Zhanibek',
    'Жәнібек ауданы': 'Zhanibek',
    'Жанибекский': 'Zhanibek',
    'Жанибек': 'Zhanibek',

    # ---- Baiterek (ex-Zelenov) ----
    'Зеленов ': 'Baiterek',
    'Зеленов ауданы': 'Baiterek',
    'Бәйтерек': 'Baiterek',
    'Бәйтерек ': 'Baiterek',

    # ---- Kaztalov ----
    'Казталов ': 'Kaztalov',
    'Казталов': 'Kaztalov',
    'Казталовка ауданы': 'Kaztalov',
    'Казталовский ': 'Kaztalov',
    'Казталов ': 'Kaztalov',

    # ---- Karatobe ----
    'Қаратөбе': 'Karatobe',
    'Қаратөбе ': 'Karatobe',
    'Қаратөбе ауданы': 'Karatobe',
    'Каратобинский': 'Karatobe',
    'Каратобе': 'Karatobe',

    # ---- Syrym ----
    'Сырым ': 'Syrym',
    'Сырым': 'Syrym',
    'Сырым ауданы': 'Syrym',
    'Сырымский': 'Syrym',
    'Сырым ': 'Syrym',

    # ---- Taskala ----
    'Тасқала ': 'Taskala',
    'Тасқала ауданы': 'Taskala',
    'Таскалинский': 'Taskala',
    'Таскала ': 'Taskala',

    # ---- Terekti ----
    'Теректі ': 'Terekti',
    'Теректі ауданы': 'Terekti',
    'Теректинский': 'Terekti',
    'Теректа': 'Terekti',

    # ---- Shyngyrlau ----
    'Шыңғырлау': 'Shyngyrlau',
    'Шыңғырлау ': 'Shyngyrlau',
    'Шыңғырлау ауданы': 'Shyngyrlau',
    'Чингирлауский': 'Shyngyrlau',
    'Чингирлау': 'Shyngyrlau',
}

In [506]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [west_all_2014, west_all_2015, west_all_2016,
          west_all_2017, west_all_2018, west_all_2019,
          west_all_2020, west_all_2021, west_all_2022,
          west_all_2023, west_all_2024]:
    df.columns = all_columns

for df in [west_non_2015, west_non_2016,
          west_non_2017, west_non_2018, west_non_2019,
          west_non_2020, west_non_2021, west_non_2022,
          west_non_2023, west_non_2024]:
    df.columns = non_columns

    df[['all_nonextr_inv', 'f_nonextr_inv']] = (
        df[['all_nonextr_inv', 'f_nonextr_inv']]
        .astype(str)
        .apply(lambda x: x.str.replace(' ', ''))
        .astype(float)
    )

    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

In [507]:
# ----- ALL investments -----
west_all_2014['rayon'] = west_all_2014['rayon'].replace(rayon_map_west)
west_all_2015['rayon'] = west_all_2015['rayon'].replace(rayon_map_west)
west_all_2016['rayon'] = west_all_2016['rayon'].replace(rayon_map_west)
west_all_2017['rayon'] = west_all_2017['rayon'].replace(rayon_map_west)
west_all_2018['rayon'] = west_all_2018['rayon'].replace(rayon_map_west)
west_all_2019['rayon'] = west_all_2019['rayon'].replace(rayon_map_west)
west_all_2020['rayon'] = west_all_2020['rayon'].replace(rayon_map_west)
west_all_2021['rayon'] = west_all_2021['rayon'].replace(rayon_map_west)
west_all_2022['rayon'] = west_all_2022['rayon'].replace(rayon_map_west)
west_all_2023['rayon'] = west_all_2023['rayon'].replace(rayon_map_west)
west_all_2024['rayon'] = west_all_2024['rayon'].replace(rayon_map_west)

# ----- NON-extractive investments -----
west_non_2015['rayon'] = west_non_2015['rayon'].replace(rayon_map_west)
west_non_2016['rayon'] = west_non_2016['rayon'].replace(rayon_map_west)
west_non_2017['rayon'] = west_non_2017['rayon'].replace(rayon_map_west)
west_non_2018['rayon'] = west_non_2018['rayon'].replace(rayon_map_west)
west_non_2019['rayon'] = west_non_2019['rayon'].replace(rayon_map_west)
west_non_2020['rayon'] = west_non_2020['rayon'].replace(rayon_map_west)
west_non_2021['rayon'] = west_non_2021['rayon'].replace(rayon_map_west)
west_non_2022['rayon'] = west_non_2022['rayon'].replace(rayon_map_west)
west_non_2023['rayon'] = west_non_2023['rayon'].replace(rayon_map_west)
west_non_2024['rayon'] = west_non_2024['rayon'].replace(rayon_map_west)

In [508]:
west_2014 = west_all_2014
west_2015 = west_all_2015.merge(west_non_2015, on='rayon', how='left')
west_2016 = west_all_2016.merge(west_non_2016, on='rayon', how='left')
west_2017 = west_all_2017.merge(west_non_2017, on='rayon', how='left')
west_2018 = west_all_2018.merge(west_non_2018, on='rayon', how='left')
west_2019 = west_all_2019.merge(west_non_2019, on='rayon', how='left')
west_2020 = west_all_2020.merge(west_non_2020, on='rayon', how='left')
west_2021 = west_all_2021.merge(west_non_2021, on='rayon', how='left')
west_2022 = west_all_2022.merge(west_non_2022, on='rayon', how='left')
west_2023 = west_all_2023.merge(west_non_2023, on='rayon', how='left')
west_2024 = west_all_2024.merge(west_non_2024, on='rayon', how='left')

dfs = [west_2014, west_2015, west_2016, west_2017, west_2018, west_2019, west_2020, west_2021, west_2022, west_2023, west_2024]

for i in range(11):
    df = dfs[i]
    df['oblast'] = 'West-Kazakhstan'
    df['year'] = 2014 + i

west_inv = pd.concat([west_2014, west_2015, west_2016, west_2017, west_2018, west_2019, west_2020, west_2021, west_2022, west_2023, west_2024], ignore_index=True)
west_inv['rayon'] = (
    west_inv['rayon']
        .str.strip()          # remove hidden spaces
        .replace(rayon_map)   # enforce English names
)
west_inv

,rayon,l_all_inv,f_all_inv,oblast,year,f_nonextr_inv,l_nonextr_inv
0,Akzhaiyk,2057680.0,123909.0,West-Kazakhstan,2014,NaN,NaN
1,Bokey Orda,375069.0,63.0,West-Kazakhstan,2014,NaN,NaN
2,Borili,9580632.0,122053832.0,West-Kazakhstan,2014,NaN,NaN
3,Zhangala,2869120.0,583.0,West-Kazakhstan,2014,NaN,NaN
4,Zhanibek,248291.0,299357.0,West-Kazakhstan,2014,NaN,NaN
...,...,...,...,...,...,...,...
138,Syrym,11491353.0,0.0,West-Kazakhstan,2024,0.0,6153640.0
139,Taskala,4855461.0,355061.0,West-Kazakhstan,2024,355061.0,1363162.0
140,Terekti,45334267.0,0.0,West-Kazakhstan,2024,0.0,9060580.0
141,Shyngyrlau,5403357.0,0.0,West-Kazakhstan,2024,0.0,1143580.0
142,Oral city,169271036.0,10674786.0,West-Kazakhstan,2024,9531042.0,103831417.0

## Employment

In [509]:
west_empl = pd.read_excel(Path("../Data/Employment/West-Kazakhstan.xlsx"), skiprows=25, nrows=13, header=None, usecols='A:K', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
west_empl.columns = ['rayon', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
west_empl['rayon'] = west_empl['rayon'].replace(rayon_map_west)
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    west_empl[i] = west_empl[i].astype(float)
    west_employment = west_empl.melt(id_vars='rayon', value_vars=[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023], var_name='year', value_name='employment')
west_employment

          rayon  year  employment
0      Akzhaiyk  2014      22.726
1    Bokey Orda  2014       8.874
2        Borili  2014      32.250
3      Zhangala  2014      12.829
4      Zhanibek  2014       9.812
..          ...   ...         ...
125       Syrym  2023       8.776
126     Taskala  2023       8.677
127     Terekti  2023      19.986
128  Shyngyrlau  2023       6.767
129   Oral city  2023     161.645

[130 rows x 3 columns]

## Other controls

In [510]:
Akzhaiyk = pd.read_excel(Path("../Data/Controls/West-Kazakhstan_All.xls"), sheet_name="Акжаик", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Akzhaiyk.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
Akzhaiyk = Akzhaiyk.loc[[68, 86, 130]].reset_index(drop=True)
Akzhaiyk['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    Akzhaiyk[i] = Akzhaiyk[i].astype(str)
    Akzhaiyk[i] = Akzhaiyk[i].str.replace(',', '.')
    Akzhaiyk[i] = Akzhaiyk[i].str.replace(')', '')
    Akzhaiyk[i] = Akzhaiyk[i].str.replace(' ', '')
    Akzhaiyk[i] = Akzhaiyk[i].str.replace('\xa0', '')
    Akzhaiyk[i] = Akzhaiyk[i].str.replace('*', '')
    Akzhaiyk[i] = Akzhaiyk[i].astype(float)
Akzhaiyk = pd.melt(Akzhaiyk, id_vars=['Indicator'], var_name='year', value_name='value')
Akzhaiyk = Akzhaiyk.pivot(index='year', columns='Indicator', values='value').reset_index()
Akzhaiyk.insert(0, 'rayon', 'Akzhaiyk')
Akzhaiyk.columns.name = None
Akzhaiyk

      rayon  year   agriculture  production   retail
0  Akzhaiyk  2014  11421.200000      1616.4   5083.5
1  Akzhaiyk  2015  11959.700000      1818.9   6505.3
2  Akzhaiyk  2016  13439.200000      1783.6   8080.0
3  Akzhaiyk  2017  14809.300000      3122.0  14532.0
4  Akzhaiyk  2018  16105.500000      2898.3   5725.0
5  Akzhaiyk  2019  19158.900000      1671.2   7030.0
6  Akzhaiyk  2020  21857.700000      1535.9   4612.3
7  Akzhaiyk  2021  28821.200000      1826.9   9859.5
8  Akzhaiyk  2022  31439.000000      1395.9   6138.1
9  Akzhaiyk  2023  34622.826094      1610.1   3167.7

In [511]:
bokey_orda = pd.read_excel(Path("../Data/Controls/West-Kazakhstan_All.xls"), sheet_name="Бокейорда", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
bokey_orda.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
bokey_orda = bokey_orda.loc[[68, 86, 130]].reset_index(drop=True)
bokey_orda['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    bokey_orda[i] = bokey_orda[i].astype(str)
    bokey_orda[i] = bokey_orda[i].str.replace(',', '.')
    bokey_orda[i] = bokey_orda[i].str.replace(')', '')
    bokey_orda[i] = bokey_orda[i].str.replace(' ', '')
    bokey_orda[i] = bokey_orda[i].str.replace('\xa0', '')
    bokey_orda[i] = bokey_orda[i].str.replace('*', '')
    bokey_orda[i] = bokey_orda[i].astype(float)
bokey_orda = pd.melt(bokey_orda, id_vars=['Indicator'], var_name='year', value_name='value')
bokey_orda = bokey_orda.pivot(index='year', columns='Indicator', values='value').reset_index()
bokey_orda.insert(0, 'rayon', 'Bokey Orda')
bokey_orda.columns.name = None
bokey_orda

        rayon  year  agriculture  production  retail
0  Bokey Orda  2014   5607.20000      1071.1  2031.6
1  Bokey Orda  2015   6002.50000       991.3  2256.7
2  Bokey Orda  2016   6454.60000       560.6  2906.3
3  Bokey Orda  2017   7117.20000      1160.2  3768.5
4  Bokey Orda  2018   7562.20000       752.2  4044.1
5  Bokey Orda  2019   9074.10000       394.8   508.1
6  Bokey Orda  2020   9870.30000       520.5   503.1
7  Bokey Orda  2021  12335.80000       474.0   658.5
8  Bokey Orda  2022  14152.10000       141.0   633.4
9  Bokey Orda  2023  13183.59997       353.9   797.8

In [512]:
Borili = pd.read_excel(Path("../Data/Controls/West-Kazakhstan_All.xls"), sheet_name="Бурлин", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Borili.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
Borili = Borili.loc[[68, 86, 130]].reset_index(drop=True)
Borili['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    Borili[i] = Borili[i].astype(str)
    Borili[i] = Borili[i].str.replace(',', '.')
    Borili[i] = Borili[i].str.replace(')', '')
    Borili[i] = Borili[i].str.replace(' ', '')
    Borili[i] = Borili[i].str.replace('\xa0', '')
    Borili[i] = Borili[i].str.replace('*', '')
    Borili[i] = Borili[i].astype(float)
Borili = pd.melt(Borili, id_vars=['Indicator'], var_name='year', value_name='value')
Borili = Borili.pivot(index='year', columns='Indicator', values='value').reset_index()
Borili.insert(0, 'rayon', 'Borili')
Borili.columns.name = None
Borili

    rayon  year   agriculture  production   retail
0  Borili  2014   6743.700000   1557569.4  12466.7
1  Borili  2015   6235.500000   1084839.6  16668.0
2  Borili  2016   7313.000000   1301437.6  21839.7
3  Borili  2017   7850.200000   1613884.0  20352.2
4  Borili  2018   6771.600000   2131783.6  22549.3
5  Borili  2019   7905.400000   2015630.4  17195.6
6  Borili  2020   8586.700000   1503235.9  16148.7
7  Borili  2021  10801.700000   2467430.5  21681.5
8  Borili  2022  11975.500000   3521325.6  36653.9
9  Borili  2023  11708.186155   3122281.4  23090.0

In [513]:
Zhangala = pd.read_excel(Path("../Data/Controls/West-Kazakhstan_All.xls"), sheet_name="Жанакала", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Zhangala.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
Zhangala = Zhangala.loc[[68, 86, 130]].reset_index(drop=True)
Zhangala['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    Zhangala[i] = Zhangala[i].astype(str)
    Zhangala[i] = Zhangala[i].str.replace(',', '.')
    Zhangala[i] = Zhangala[i].str.replace(')', '')
    Zhangala[i] = Zhangala[i].str.replace(' ', '')
    Zhangala[i] = Zhangala[i].str.replace('\xa0', '')
    Zhangala[i] = Zhangala[i].str.replace('*', '')
    Zhangala[i] = Zhangala[i].astype(float)
Zhangala = pd.melt(Zhangala, id_vars=['Indicator'], var_name='year', value_name='value')
Zhangala = Zhangala.pivot(index='year', columns='Indicator', values='value').reset_index()
Zhangala.insert(0, 'rayon', 'Zhangala')
Zhangala.columns.name = None
Zhangala

      rayon  year   agriculture  production  retail
0  Zhangala  2014   6276.300000       199.2  2866.3
1  Zhangala  2015   6949.000000       191.2  3218.2
2  Zhangala  2016   8148.700000        69.5  3779.8
3  Zhangala  2017   8209.400000       189.1  5627.9
4  Zhangala  2018   8170.900000       663.3  7474.3
5  Zhangala  2019   9913.000000       567.3  3282.4
6  Zhangala  2020  11038.000000       626.9  2053.4
7  Zhangala  2021  13073.900000       759.6  2262.3
8  Zhangala  2022  14749.100000       281.6  1306.0
9  Zhangala  2023  13949.846602       110.6  2496.2

In [514]:
Zhanibek = pd.read_excel(Path("../Data/Controls/West-Kazakhstan_All.xls"), sheet_name="Жанибек", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Zhanibek.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
Zhanibek = Zhanibek.loc[[68, 86, 130]].reset_index(drop=True)
Zhanibek['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    Zhanibek[i] = Zhanibek[i].astype(str)
    Zhanibek[i] = Zhanibek[i].str.replace(',', '.')
    Zhanibek[i] = Zhanibek[i].str.replace(')', '')
    Zhanibek[i] = Zhanibek[i].str.replace(' ', '')
    Zhanibek[i] = Zhanibek[i].str.replace('\xa0', '')
    Zhanibek[i] = Zhanibek[i].str.replace('*', '')
    Zhanibek[i] = Zhanibek[i].astype(float)
Zhanibek = pd.melt(Zhanibek, id_vars=['Indicator'], var_name='year', value_name='value')
Zhanibek = Zhanibek.pivot(index='year', columns='Indicator', values='value').reset_index()
Zhanibek.insert(0, 'rayon', 'Zhanibek')
Zhanibek.columns.name = None
Zhanibek

      rayon  year   agriculture  production  retail
0  Zhanibek  2014   4213.700000       432.5  2334.1
1  Zhanibek  2015   4829.500000       371.7  2663.4
2  Zhanibek  2016   6321.000000       362.0  3339.4
3  Zhanibek  2017   5964.100000       553.9   538.0
4  Zhanibek  2018   6323.400000       475.3  3463.9
5  Zhanibek  2019   7358.700000       414.5  1133.6
6  Zhanibek  2020   7800.900000       409.7  1365.5
7  Zhanibek  2021   9499.200000       450.7   903.4
8  Zhanibek  2022  10978.600000        63.2  1331.4
9  Zhanibek  2023  13216.492472       136.8  2785.2

In [515]:
Baiterek = pd.read_excel(Path("../Data/Controls/West-Kazakhstan_All.xls"), sheet_name="Бәйтерек", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Baiterek.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
Baiterek = Baiterek.loc[[68, 86, 130]].reset_index(drop=True)
Baiterek['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    Baiterek[i] = Baiterek[i].astype(str)
    Baiterek[i] = Baiterek[i].str.replace(',', '.')
    Baiterek[i] = Baiterek[i].str.replace(')', '')
    Baiterek[i] = Baiterek[i].str.replace(' ', '')
    Baiterek[i] = Baiterek[i].str.replace('\xa0', '')
    Baiterek[i] = Baiterek[i].str.replace('*', '')
    Baiterek[i] = Baiterek[i].astype(float)
Baiterek = pd.melt(Baiterek, id_vars=['Indicator'], var_name='year', value_name='value')
Baiterek = Baiterek.pivot(index='year', columns='Indicator', values='value').reset_index()
Baiterek.insert(0, 'rayon', 'Baiterek')
Baiterek.columns.name = None
Baiterek

      rayon  year   agriculture  production   retail
0  Baiterek  2014  21410.600000    160460.0   5510.9
1  Baiterek  2015  21344.200000     98393.0   5204.3
2  Baiterek  2016  27977.900000    128772.2   8518.0
3  Baiterek  2017  29426.800000    141618.8  10403.0
4  Baiterek  2018  28871.700000    169062.1   9279.2
5  Baiterek  2019  39062.200000    175429.3   6613.0
6  Baiterek  2020  47031.500000    115642.5   8571.2
7  Baiterek  2021  52541.000000    141076.0  10118.0
8  Baiterek  2022  79051.000000    125946.3  11933.2
9  Baiterek  2023  73477.278439    113990.2  14317.4

In [516]:
Kaztalov = pd.read_excel(Path("../Data/Controls/West-Kazakhstan_All.xls"), sheet_name="Казталов", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Kaztalov.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
Kaztalov = Kaztalov.loc[[68, 86, 130]].reset_index(drop=True)
Kaztalov['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    Kaztalov[i] = Kaztalov[i].astype(str)
    Kaztalov[i] = Kaztalov[i].str.replace(',', '.')
    Kaztalov[i] = Kaztalov[i].str.replace(')', '')
    Kaztalov[i] = Kaztalov[i].str.replace(' ', '')
    Kaztalov[i] = Kaztalov[i].str.replace('\xa0', '')
    Kaztalov[i] = Kaztalov[i].str.replace('*', '')
    Kaztalov[i] = Kaztalov[i].astype(float)
Kaztalov = pd.melt(Kaztalov, id_vars=['Indicator'], var_name='year', value_name='value')
Kaztalov = Kaztalov.pivot(index='year', columns='Indicator', values='value').reset_index()
Kaztalov.insert(0, 'rayon', 'Kaztalov')
Kaztalov.columns.name = None
Kaztalov

      rayon  year   agriculture  production   retail
0  Kaztalov  2014   9545.800000       423.0   3093.5
1  Kaztalov  2015   9863.600000       474.8   3427.3
2  Kaztalov  2016  12323.200000       577.7   4515.5
3  Kaztalov  2017  13120.800000      1006.1   4925.3
4  Kaztalov  2018  14148.000000      1243.4  16986.0
5  Kaztalov  2019  16290.100000       742.9   4302.7
6  Kaztalov  2020  15593.700000       714.2   6177.3
7  Kaztalov  2021  21650.700000      1119.4   6620.8
8  Kaztalov  2022  24628.500000       374.5   9284.5
9  Kaztalov  2023  22984.312899       288.8   5152.6

In [517]:
Syrym = pd.read_excel(Path("../Data/Controls/West-Kazakhstan_All.xls"), sheet_name="Сырым", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Syrym.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
Syrym = Syrym.loc[[68, 86, 130]].reset_index(drop=True)
Syrym['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    Syrym[i] = Syrym[i].astype(str)
    Syrym[i] = Syrym[i].str.replace(',', '.')
    Syrym[i] = Syrym[i].str.replace(')', '')
    Syrym[i] = Syrym[i].str.replace(' ', '')
    Syrym[i] = Syrym[i].str.replace('\xa0', '')
    Syrym[i] = Syrym[i].str.replace('*', '')
    Syrym[i] = Syrym[i].astype(float)
Syrym = pd.melt(Syrym, id_vars=['Indicator'], var_name='year', value_name='value')
Syrym = Syrym.pivot(index='year', columns='Indicator', values='value').reset_index()
Syrym.insert(0, 'rayon', 'Syrym')
Syrym.columns.name = None
Syrym

   rayon  year   agriculture  production  retail
0  Syrym  2014   6005.200000       223.1  2457.2
1  Syrym  2015   6962.400000       223.4  3158.2
2  Syrym  2016   8704.200000       254.8  4039.8
3  Syrym  2017   9387.000000       323.1  6138.1
4  Syrym  2018   8990.800000       748.4  4157.9
5  Syrym  2019  10607.400000       657.9  2610.2
6  Syrym  2020  12825.600000       628.6   575.1
7  Syrym  2021  15881.700000       758.9   419.2
8  Syrym  2022  18704.100000       525.5  1140.9
9  Syrym  2023  18464.935214       344.1  2204.7

In [518]:
Karatobe = pd.read_excel(Path("../Data/Controls/West-Kazakhstan_All.xls"), sheet_name="Каратобе", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Karatobe.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
Karatobe = Karatobe.loc[[68, 86, 130]].reset_index(drop=True)
Karatobe['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    Karatobe[i] = Karatobe[i].astype(str)
    Karatobe[i] = Karatobe[i].str.replace(',', '.')
    Karatobe[i] = Karatobe[i].str.replace(')', '')
    Karatobe[i] = Karatobe[i].str.replace(' ', '')
    Karatobe[i] = Karatobe[i].str.replace('\xa0', '')
    Karatobe[i] = Karatobe[i].str.replace('*', '')
    Karatobe[i] = Karatobe[i].astype(float)
Karatobe = pd.melt(Karatobe, id_vars=['Indicator'], var_name='year', value_name='value')
Karatobe = Karatobe.pivot(index='year', columns='Indicator', values='value').reset_index()
Karatobe.insert(0, 'rayon', 'Karatobe')
Karatobe.columns.name = None
Karatobe

      rayon  year   agriculture  production  retail
0  Karatobe  2014   3912.500000       839.5  1632.8
1  Karatobe  2015   4200.200000       891.0  1976.3
2  Karatobe  2016   5359.900000       826.4  2714.0
3  Karatobe  2017   5174.700000       983.6  2996.7
4  Karatobe  2018   5257.400000       461.3  5644.2
5  Karatobe  2019   6245.100000       373.8  1896.4
6  Karatobe  2020   8178.800000       392.8   532.0
7  Karatobe  2021   9686.400000       406.4   266.3
8  Karatobe  2022  10874.600000        99.1   725.2
9  Karatobe  2023  11575.957891       132.6   617.0

In [519]:
Taskala = pd.read_excel(Path("../Data/Controls/West-Kazakhstan_All.xls"), sheet_name="Таскала", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Taskala.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
Taskala = Taskala.loc[[68, 86, 130]].reset_index(drop=True)
Taskala['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    Taskala[i] = Taskala[i].astype(str)
    Taskala[i] = Taskala[i].str.replace(',', '.')
    Taskala[i] = Taskala[i].str.replace(')', '')
    Taskala[i] = Taskala[i].str.replace(' ', '')
    Taskala[i] = Taskala[i].str.replace('\xa0', '')
    Taskala[i] = Taskala[i].str.replace('*', '')
    Taskala[i] = Taskala[i].astype(float)
Taskala = pd.melt(Taskala, id_vars=['Indicator'], var_name='year', value_name='value')
Taskala = Taskala.pivot(index='year', columns='Indicator', values='value').reset_index()
Taskala.insert(0, 'rayon', 'Taskala')
Taskala.columns.name = None
Taskala

     rayon  year   agriculture  production  retail
0  Taskala  2014   5408.800000       548.0  2391.7
1  Taskala  2015   5646.500000       560.2  2678.8
2  Taskala  2016   7156.600000       430.8  3163.0
3  Taskala  2017   7711.800000       960.4  3818.8
4  Taskala  2018   7304.800000       637.1  1716.2
5  Taskala  2019   9493.300000       714.5   600.4
6  Taskala  2020  10838.500000       593.8   312.1
7  Taskala  2021  11889.400000       850.3   396.8
8  Taskala  2022  16970.100000       573.3   716.0
9  Taskala  2023  16377.800483       225.3   775.6

In [520]:
Terekti = pd.read_excel(Path("../Data/Controls/West-Kazakhstan_All.xls"), sheet_name="Теректа", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Terekti.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
Terekti = Terekti.loc[[68, 86, 130]].reset_index(drop=True)
Terekti['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    Terekti[i] = Terekti[i].astype(str)
    Terekti[i] = Terekti[i].str.replace(',', '.')
    Terekti[i] = Terekti[i].str.replace(')', '')
    Terekti[i] = Terekti[i].str.replace(' ', '')
    Terekti[i] = Terekti[i].str.replace('\xa0', '')
    Terekti[i] = Terekti[i].str.replace('*', '')
    Terekti[i] = Terekti[i].astype(float)
Terekti = pd.melt(Terekti, id_vars=['Indicator'], var_name='year', value_name='value')
Terekti = Terekti.pivot(index='year', columns='Indicator', values='value').reset_index()
Terekti.insert(0, 'rayon', 'Terekti')
Terekti.columns.name = None
Terekti

     rayon  year   agriculture  production  retail
0  Terekti  2014  10405.700000      2979.2  3021.8
1  Terekti  2015   9674.900000      2984.6  2915.8
2  Terekti  2016  13502.900000      2610.2  3328.3
3  Terekti  2017  14681.600000      1556.9  1712.8
4  Terekti  2018  14356.700000      5077.1  1829.5
5  Terekti  2019  17829.600000      3092.6  2347.1
6  Terekti  2020  21290.700000      4772.9  1297.0
7  Terekti  2021  24110.800000      5814.6   743.1
8  Terekti  2022  31898.500000      7343.4  2718.3
9  Terekti  2023  28171.451392      7379.3  6513.0

In [521]:
Shyngyrlau = pd.read_excel(Path("../Data/Controls/West-Kazakhstan_All.xls"), sheet_name="Чингирлау", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Shyngyrlau.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
Shyngyrlau = Shyngyrlau.loc[[68, 86, 130]].reset_index(drop=True)
Shyngyrlau['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    Shyngyrlau[i] = Shyngyrlau[i].astype(str)
    Shyngyrlau[i] = Shyngyrlau[i].str.replace(',', '.')
    Shyngyrlau[i] = Shyngyrlau[i].str.replace(')', '')
    Shyngyrlau[i] = Shyngyrlau[i].str.replace(' ', '')
    Shyngyrlau[i] = Shyngyrlau[i].str.replace('\xa0', '')
    Shyngyrlau[i] = Shyngyrlau[i].str.replace('*', '')
    Shyngyrlau[i] = Shyngyrlau[i].astype(float)
Shyngyrlau = pd.melt(Shyngyrlau, id_vars=['Indicator'], var_name='year', value_name='value')
Shyngyrlau = Shyngyrlau.pivot(index='year', columns='Indicator', values='value').reset_index()
Shyngyrlau.insert(0, 'rayon', 'Shyngyrlau')
Shyngyrlau.columns.name = None
Shyngyrlau

        rayon  year   agriculture  production  retail
0  Shyngyrlau  2014   4920.800000       748.2  3041.4
1  Shyngyrlau  2015   5571.200000       999.9  3926.4
2  Shyngyrlau  2016   6762.400000      1159.2  4919.6
3  Shyngyrlau  2017   7480.800000       835.2  5382.6
4  Shyngyrlau  2018   7718.600000       410.0  2831.8
5  Shyngyrlau  2019   9084.000000       422.3  3439.9
6  Shyngyrlau  2020  11395.000000       679.2   413.3
7  Shyngyrlau  2021  18581.600000       691.8  1236.4
8  Shyngyrlau  2022  16737.900000       335.2  1421.0
9  Shyngyrlau  2023  17747.624464      1190.6  2007.3

In [522]:
oral_city = pd.read_excel(Path("../Data/Controls/West-Kazakhstan_All.xls"), sheet_name="г.а Уральск", header=2, usecols='A, Y:AH', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
oral_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
oral_city = oral_city.loc[[68, 86, 130]].reset_index(drop=True)
oral_city['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    oral_city[i] = oral_city[i].astype(str)
    oral_city[i] = oral_city[i].str.replace(',', '.')
    oral_city[i] = oral_city[i].str.replace(')', '')
    oral_city[i] = oral_city[i].str.replace(' ', '')
    oral_city[i] = oral_city[i].str.replace('\xa0', '')
    oral_city[i] = oral_city[i].str.replace('*', '')
    oral_city[i] = oral_city[i].astype(float)
oral_city = pd.melt(oral_city, id_vars=['Indicator'], var_name='year', value_name='value')
oral_city = oral_city.pivot(index='year', columns='Indicator', values='value').reset_index()
oral_city.insert(0, 'rayon', 'Oral city')
oral_city.columns.name = None
oral_city

       rayon  year   agriculture  production    retail
0  Oral city  2014   7668.400000    112712.3  155852.5
1  Oral city  2015   7305.200000    109328.5  140754.3
2  Oral city  2016   7552.200000    128115.0  170637.3
3  Oral city  2017   9110.200000    148308.4  185138.5
4  Oral city  2018   8259.400000    166312.5  207137.4
5  Oral city  2019   9123.300000    191997.5  262850.9
6  Oral city  2020  11094.300000    193113.6  269895.6
7  Oral city  2021  13133.600000    221471.4  325015.0
8  Oral city  2022  18155.400000    257456.9  384713.2
9  Oral city  2023  14857.035598    269234.1  427599.6

In [523]:
west_controls = pd.concat([Akzhaiyk, bokey_orda, Borili,Zhangala, Zhanibek, Baiterek, Kaztalov, Syrym, Karatobe, Taskala, Terekti, Shyngyrlau, oral_city], ignore_index=True)
west_controls

         rayon  year   agriculture  production    retail
0     Akzhaiyk  2014  11421.200000      1616.4    5083.5
1     Akzhaiyk  2015  11959.700000      1818.9    6505.3
2     Akzhaiyk  2016  13439.200000      1783.6    8080.0
3     Akzhaiyk  2017  14809.300000      3122.0   14532.0
4     Akzhaiyk  2018  16105.500000      2898.3    5725.0
..         ...   ...           ...         ...       ...
125  Oral city  2019   9123.300000    191997.5  262850.9
126  Oral city  2020  11094.300000    193113.6  269895.6
127  Oral city  2021  13133.600000    221471.4  325015.0
128  Oral city  2022  18155.400000    257456.9  384713.2
129  Oral city  2023  14857.035598    269234.1  427599.6

[130 rows x 5 columns]

## PPI

In [524]:
west_ppi = pd.read_excel(
    Path("../Data/PPI/West-Kazakhstan.xls"),
    header=2,
    usecols='Y:AH',
    nrows=86,
    na_values=['x', 'х', '-', '', ' ', '...']
)
west_ppi.columns = [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
rayons = list(west_inv['rayon'].unique())
west_ppi
dfs = []

for rayon in rayons:
    df_temp = pd.DataFrame({
        'rayon': [rayon] * len(range(2014, 2024)),
        'year': list(range(2014, 2024)),
        'ppi': west_ppi.iloc[-1].values
    })
    dfs.append(df_temp)

west_ppi = pd.concat(dfs, ignore_index=True)
west_ppi['ppi'] = west_ppi['ppi'].astype(str).str.replace(',', '.')
west_ppi['ppi'] = west_ppi['ppi'].astype(str).str.replace(')', '')
west_ppi['ppi'] = west_ppi['ppi'].astype(str).str.replace(' ', '')
west_ppi['ppi'] = west_ppi['ppi'].astype(str).str.replace('\xa0', '')
west_ppi['ppi'] = west_ppi['ppi'].astype(str).str.replace('*', '')
west_ppi['ppi'] = west_ppi['ppi'].astype(float)

west_ppi

         rayon  year    ppi
0     Akzhaiyk  2014   90.8
1     Akzhaiyk  2015   75.1
2     Akzhaiyk  2016  109.5
3     Akzhaiyk  2017  143.7
4     Akzhaiyk  2018  116.5
..         ...   ...    ...
125  Oral city  2019  102.6
126  Oral city  2020   75.0
127  Oral city  2021  123.9
128  Oral city  2022   93.1
129  Oral city  2023  105.6

[130 rows x 3 columns]

## Combine

In [525]:
dfs_west = [west_inv, west_employment, west_controls, west_ppi]
west_merged = reduce(lambda left, right: pd.merge(left, right, on=['rayon', 'year'], how='outer'), dfs_west)
west_merged['oblast'] = west_merged['oblast'].fillna('West-Kazakhstan')
west_merged

,rayon,l_all_inv,f_all_inv,oblast,year,f_nonextr_inv,l_nonextr_inv,employment,agriculture,production,retail,ppi
0,Akzhaiyk,2057680.0,123909.0,West-Kazakhstan,2014,NaN,NaN,22.726,11421.200000,1616.4,5083.5,90.8
1,Akzhaiyk,2678248.0,93097.0,West-Kazakhstan,2015,52.0,2666748.0,22.086,11959.700000,1818.9,6505.3,75.1
2,Akzhaiyk,1266422.0,120180.0,West-Kazakhstan,2016,0.0,656276.0,22.794,13439.200000,1783.6,8080.0,109.5
3,Akzhaiyk,2438136.0,597357.0,West-Kazakhstan,2017,519044.0,310457.0,22.275,14809.300000,3122.0,14532.0,143.7
4,Akzhaiyk,3197514.0,335036.0,West-Kazakhstan,2018,286644.0,727590.0,21.796,16105.500000,2898.3,5725.0,116.5
...,...,...,...,...,...,...,...,...,...,...,...,...
138,Zhanibek,3764194.0,164019.0,West-Kazakhstan,2020,160129.0,258423.0,8.621,7800.900000,409.7,1365.5,75.0
139,Zhanibek,4500455.0,263969.0,West-Kazakhstan,2021,263969.0,271753.0,8.814,9499.200000,450.7,903.4,123.9
140,Zhanibek,8679409.0,9205.0,West-Kazakhstan,2022,9205.0,171266.0,7.782,10978.600000,63.2,1331.4,93.1
141,Zhanibek,8812195.0,0.0,West-Kazakhstan,2023,0.0,1679626.0,7.684,13216.492472,136.8,2785.2,105.6
142,Zhanibek,10747884.0,0.0,West-Kazakhstan,2024,0.0,1408371.0,NaN,NaN,NaN,NaN,NaN

# Zhambyl

## Investments

In [526]:
#zhambyl_all_2015 
zhambyl_all_2015 = camelot.read_pdf(Path("../Data/Investments/Zhambyl/2015_Investments.pdf"), pages='13', flavor='stream')[0].df
zhambyl_all_2015 = zhambyl_all_2015.iloc[4:, [0, 2, 5]].reset_index(drop=True)
for col in [2, 5]:
   zhambyl_all_2015[col] = (
        zhambyl_all_2015[col]
        .astype(str)
        .str.replace(' ', '', regex=False)
        .replace('', pd.NA)
        .astype('Int64'))
zhambyl_all_2015

zhambyl_all_2016 = pd.read_excel(Path("../Data/Investments/Zhambyl/2016_Investments/Internal_vs_external.xls"), header=6, nrows=14, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhambyl_all_2017 = pd.read_excel(Path("../Data/Investments/Zhambyl/2017_Investments/Internal_vs_external.xls"), header=6, nrows=14, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhambyl_all_2018 = pd.read_excel(Path("../Data/Investments/Zhambyl/2018_Investments/Internal_vs_external.xls"), header=6, nrows=14, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhambyl_all_2019 = pd.read_excel(Path("../Data/Investments/Zhambyl/2019_Investments.xlsx"), sheet_name='14', header=6, nrows=14, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhambyl_all_2020 = pd.read_excel(Path("../Data/Investments/Zhambyl/2020_Investments.xls"), sheet_name='13', header=6, nrows=14, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhambyl_all_2021 = pd.read_excel(Path("../Data/Investments/Zhambyl/2021_Investments.xls"), sheet_name='13', header=6, nrows=14, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhambyl_all_2022 = pd.read_excel(Path("../Data/Investments/Zhambyl/2022_Investments.xls"), sheet_name='14', header=6, nrows=14, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhambyl_all_2023 = pd.read_excel(Path("../Data/Investments/Zhambyl/2023_Investments.xlsx"), sheet_name='19', header=4, nrows=14, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhambyl_all_2024 = pd.read_excel(Path("../Data/Investments/Zhambyl/2024_Investments.xlsx"), sheet_name='14', header=4, nrows=14, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 13 0 (offset 0)
Ignoring wrong pointing object 15 0 (offset 0)
Ignoring wrong pointing object 17 0 (offset 0)
Ignoring wrong pointing object 19 0 (offset 0)
Ignoring wrong pointing object 21 0 (offset 0)
Ignoring wrong pointing object 23 0 (offset 0)
Ignoring wrong pointing object 25 0 (offset 0)
Ignoring wrong pointing object 27 0 (offset 0)
Ignoring wrong pointing object 35 0 (offset 0)
Ignoring wrong pointing object 40 0 (offset 0)
Ignoring wrong pointing object 48 0 (offset 0)
Ignoring wrong pointing object 50 0 (offset 0)
Ignoring wrong pointing object 55 0 (offset 0)
Ignoring wrong pointing object 57 0 (offset 0)
Ignoring wrong pointing object 59 0 (offset 0)
Ignoring wrong pointing object 61 0 (offset 0)
Ignoring wrong pointing object 73 0 (offset 0)
Ignoring wrong pointing object 76 0 (offset 0)
Ignoring wrong pointing object 84 0 (offset 0)
Ignoring wrong pointing object 89 0 (offset 0)
Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 13 0 (offset 0)
Ignoring wrong pointing object 15 0 (offset 0)
Ignoring wrong pointing object 17 0 (offset 0)
Ignoring wrong pointing object 19 0 (offset 0)
Ignoring wrong pointing object 21 0 (offset 0)
Ignoring wrong pointing object 23 0 (offset 0)
Ignoring wrong pointing object 25 0 (offset 0)
Ignoring wrong pointing object 27 0 (offset 0)
Ignoring wrong pointing object 35 0 (offset 0)
Ignoring wrong pointing object 40 0 (offset 0)
Ignoring wrong pointing object 48 0 (offset 0)
Ignoring wrong pointing object 50 0 (offset 0)
Ignoring wrong pointing object 55 0 (offset 0)
Ignoring wrong pointing object 57 0 (offset 0)
Ignoring wrong pointing object 59 0 (offset 0)
Ignoring wrong pointing object 61 0 (offset 0)
Ignoring wrong pointing object 73 0 (offset 0)
Ignoring wrong pointing object 76 0 (offset 0)
Ignoring wrong pointing object 84 0 (offset 0)
Ignoring wrong pointing object 89 0 (offset 0)

In [527]:
zhambyl_non_2016 = pd.read_excel(Path("../Data/Investments/Zhambyl/2016_Investments/Greenfield_investments.xls"), header=7, nrows=12, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhambyl_non_2017 = pd.read_excel(Path("../Data/Investments/Zhambyl/2017_Investments/Greenfield_investments.xls"), header=7, nrows=12, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhambyl_non_2018 = pd.read_excel(Path("../Data/Investments/Zhambyl/2018_Investments/Greenfield_investments.xls"), header=7, nrows=12, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhambyl_non_2019 = pd.read_excel(Path("../Data/Investments/Zhambyl/2019_Investments.xlsx"), sheet_name="14", header=6, nrows=12, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhambyl_non_2020 = pd.read_excel(Path("../Data/Investments/Zhambyl/2020_Investments.xls"), sheet_name="13", header=6, nrows=12, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhambyl_non_2021 = pd.read_excel(Path("../Data/Investments/Zhambyl/2021_Investments.xls"), sheet_name="14", header=7, nrows=12, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhambyl_non_2022 = pd.read_excel(Path("../Data/Investments/Zhambyl/2022_Investments.xls"), sheet_name="15", header=7, nrows=12, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhambyl_non_2023 = pd.read_excel(Path("../Data/Investments/Zhambyl/2023_Investments.xlsx"), sheet_name="20", header=4, nrows=12, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhambyl_non_2024 = pd.read_excel(Path("../Data/Investments/Zhambyl/2024_Investments.xlsx"), sheet_name="15", header=4, nrows=12, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [528]:
dfs = [zhambyl_all_2015, zhambyl_all_2016, zhambyl_all_2017, zhambyl_all_2018, zhambyl_all_2019,
      zhambyl_all_2020, zhambyl_all_2021, zhambyl_all_2022, zhambyl_all_2023, zhambyl_all_2024,
      zhambyl_non_2016, zhambyl_non_2017, zhambyl_non_2018, zhambyl_non_2019, zhambyl_non_2020,
      zhambyl_non_2021, zhambyl_non_2022, zhambyl_non_2023, zhambyl_non_2024]

lists = []

for df in dfs:
    lists.extend(df.iloc[:, 0].unique())

unique_lists = pd.Series(lists).unique()
unique_lists

array(['Тараз қ.', 'Байзақ', 'Жамбыл', 'Жуалы', 'Қордай', 'Т.Рысқұлов',
       'Меркі', 'Мойынқұм', 'Сарысу', 'Талас', 'Шу', 'Тараз қаласы',
       'Тұрар Рысқұлов', 'Мойынқұм ', 'Сарысу ', 'г. Тараз',
       'Байзакский ', 'Жамбылский ', 'Жуалынский ', 'Кордайский ',
       'Турара Рыскулова', 'Меркенский ', 'Мойынкумский ', 'Сарысуский ',
       'Таласский ', 'Шуский ', 'г.Тараз', 'Жуалы ', 'Қордай ', 'Талас ',
       'Шу '], dtype=object)

In [529]:
rayon_map_zhambyl = {

    # ---- City ----
    'Тараз қ.': 'Taraz city',
    'Тараз қаласы': 'Taraz city',
    'г. Тараз': 'Taraz city',
    'г.Тараз': 'Taraz city',

    # ---- Bayzak ----
    'Байзақ': 'Baizak',
    'Байзакский ': 'Baizak',
    'Байзакский район': 'Baizak',

    # ---- Zhambyl ----
    'Жамбыл': 'Zhambyl',
    'Жамбылский ': 'Zhambyl',
    'Жамбылский район': 'Zhambyl',

    # ---- Zhualy ----
    'Жуалы': 'Zhualy',
    'Жуалы ': 'Zhualy',
    'Жуалынский ': 'Zhualy',
    'Жуалынский район': 'Zhualy',

    # ---- Korday ----
    'Қордай': 'Korday',
    'Қордай ': 'Korday',
    'Кордайский ': 'Korday',
    'Кордайский район': 'Korday',

    # ---- T. Ryskulov ----
    'Т.Рысқұлов': 'Ryskulov',
    'Тұрар Рысқұлов': 'Ryskulov',
    'Турара Рыскулова': 'Ryskulov',
    'район Т.Рыскулова': 'Ryskulov',

    # ---- Merke ----
    'Меркі': 'Merke',
    'Меркенский ': 'Merke',
    'Меркенский район': 'Merke',

    # ---- Moyynkum ----
    'Мойынқұм': 'Moyynkum',
    'Мойынқұм ': 'Moyynkum',
    'Мойынкумский ': 'Moyynkum',
    'Мойынкумский район': 'Moyynkum',

    # ---- Sarysu ----
    'Сарысу': 'Sarysu',
    'Сарысу ': 'Sarysu',
    'Сарысуский ': 'Sarysu',
    'Сарысуский район': 'Sarysu',

    # ---- Talas ----
    'Талас': 'Talas',
    'Талас ': 'Talas',
    'Таласский ': 'Talas',
    'Таласский район': 'Talas',

    # ---- Shu ----
    'Шу': 'Shu',
    'Шу ': 'Shu',
    'Шуский ': 'Shu',
    'Шуский район': 'Shu'
}

In [530]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [zhambyl_all_2015, zhambyl_all_2016, zhambyl_all_2017, zhambyl_all_2018, zhambyl_all_2019,
      zhambyl_all_2020, zhambyl_all_2021, zhambyl_all_2022, zhambyl_all_2023, zhambyl_all_2024]:
    df.columns = all_columns

for df in [zhambyl_non_2016, zhambyl_non_2017, zhambyl_non_2018, zhambyl_non_2019, zhambyl_non_2020,
      zhambyl_non_2021, zhambyl_non_2022, zhambyl_non_2023, zhambyl_non_2024]:
    df.columns = non_columns

    df[['all_nonextr_inv', 'f_nonextr_inv']] = (
        df[['all_nonextr_inv', 'f_nonextr_inv']]
        .astype(str)
        .apply(lambda x: x.str.replace(' ', ''))
        .astype(float)
    )

    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

In [531]:
# ----- ALL investments -----
zhambyl_all_2015['rayon'] = zhambyl_all_2015['rayon'].replace(rayon_map_zhambyl)
zhambyl_all_2016['rayon'] = zhambyl_all_2016['rayon'].replace(rayon_map_zhambyl)
zhambyl_all_2017['rayon'] = zhambyl_all_2017['rayon'].replace(rayon_map_zhambyl)
zhambyl_all_2018['rayon'] = zhambyl_all_2018['rayon'].replace(rayon_map_zhambyl)
zhambyl_all_2019['rayon'] = zhambyl_all_2019['rayon'].replace(rayon_map_zhambyl)
zhambyl_all_2020['rayon'] = zhambyl_all_2020['rayon'].replace(rayon_map_zhambyl)
zhambyl_all_2021['rayon'] = zhambyl_all_2021['rayon'].replace(rayon_map_zhambyl)
zhambyl_all_2022['rayon'] = zhambyl_all_2022['rayon'].replace(rayon_map_zhambyl)
zhambyl_all_2023['rayon'] = zhambyl_all_2023['rayon'].replace(rayon_map_zhambyl)
zhambyl_all_2024['rayon'] = zhambyl_all_2024['rayon'].replace(rayon_map_zhambyl)

# ----- NON-extractive investments -----
zhambyl_non_2016['rayon'] = zhambyl_non_2016['rayon'].replace(rayon_map_zhambyl)
zhambyl_non_2017['rayon'] = zhambyl_non_2017['rayon'].replace(rayon_map_zhambyl)
zhambyl_non_2018['rayon'] = zhambyl_non_2018['rayon'].replace(rayon_map_zhambyl)
zhambyl_non_2019['rayon'] = zhambyl_non_2019['rayon'].replace(rayon_map_zhambyl)
zhambyl_non_2020['rayon'] = zhambyl_non_2020['rayon'].replace(rayon_map_zhambyl)
zhambyl_non_2021['rayon'] = zhambyl_non_2021['rayon'].replace(rayon_map_zhambyl)
zhambyl_non_2022['rayon'] = zhambyl_non_2022['rayon'].replace(rayon_map_zhambyl)
zhambyl_non_2023['rayon'] = zhambyl_non_2023['rayon'].replace(rayon_map_zhambyl)
zhambyl_non_2024['rayon'] = zhambyl_non_2024['rayon'].replace(rayon_map_zhambyl)

In [532]:
zhambyl_2015 = zhambyl_all_2015
zhambyl_2016 = zhambyl_all_2016.merge(zhambyl_non_2016, on='rayon', how='left')
zhambyl_2017 = zhambyl_all_2017.merge(zhambyl_non_2017, on='rayon', how='left')
zhambyl_2018 = zhambyl_all_2018.merge(zhambyl_non_2018, on='rayon', how='left')
zhambyl_2019 = zhambyl_all_2019.merge(zhambyl_non_2019, on='rayon', how='left')
zhambyl_2020 = zhambyl_all_2020.merge(zhambyl_non_2020, on='rayon', how='left')
zhambyl_2021 = zhambyl_all_2021.merge(zhambyl_non_2021, on='rayon', how='left')
zhambyl_2022 = zhambyl_all_2022.merge(zhambyl_non_2022, on='rayon', how='left')
zhambyl_2023 = zhambyl_all_2023.merge(zhambyl_non_2023, on='rayon', how='left')
zhambyl_2024 = zhambyl_all_2024.merge(zhambyl_non_2024, on='rayon', how='left')

dfs = [zhambyl_2015, zhambyl_2016, zhambyl_2017, zhambyl_2018, zhambyl_2019, zhambyl_2020, zhambyl_2021, zhambyl_2022, zhambyl_2023, zhambyl_2024]

for i in range(10):
    df = dfs[i]
    df['oblast'] = 'Zhambyl'
    df['year'] = 2015 + i

zhambyl_inv = pd.concat([zhambyl_2015, zhambyl_2016, zhambyl_2017, zhambyl_2018, zhambyl_2019, zhambyl_2020, zhambyl_2021, zhambyl_2022, zhambyl_2023, zhambyl_2024], ignore_index=True)
zhambyl_inv['rayon'] = (
    zhambyl_inv['rayon']
        .str.strip()          # remove hidden spaces
        .replace(rayon_map)   # enforce English names
)
zhambyl_inv

,rayon,l_all_inv,f_all_inv,oblast,year,f_nonextr_inv,l_nonextr_inv
0,Taraz city,44649956,4847136.0,Zhambyl,2015,NaN,NaN
1,Baizak,10963490,379001.0,Zhambyl,2015,NaN,NaN
2,Zhambyl,9126537,14929916.0,Zhambyl,2015,NaN,NaN
3,Zhualy,19028537,353024.0,Zhambyl,2015,NaN,NaN
4,Korday,24551088,2360791.0,Zhambyl,2015,NaN,NaN
...,...,...,...,...,...,...,...
105,Merke,19147524,15148652.0,Zhambyl,2024,15148652.0,6164102.0
106,Moyynkum,12550507,12088544.0,Zhambyl,2024,11144457.0,3426227.0
107,Sarysu,12250346,29625107.0,Zhambyl,2024,22143669.0,3524405.0
108,Talas,21864981,161153.0,Zhambyl,2024,161153.0,15094694.0
109,Shu,61184446,4950279.0,Zhambyl,2024,4107190.0,33570634.0

## Employment

In [533]:
zhambyl_empl = pd.read_excel(Path("../Data/Employment/Zhambyl.xlsx"), skiprows=21, nrows=11, header=None, usecols='A:L', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
zhambyl_empl
zhambyl_empl.columns = ['rayon', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
zhambyl_empl['rayon'] = zhambyl_empl['rayon'].replace(rayon_map_zhambyl)
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    zhambyl_empl[i] = zhambyl_empl[i].astype(float)
    zhambyl_employment = zhambyl_empl.melt(id_vars='rayon', value_vars=[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024], var_name='year', value_name='employment')
zhambyl_employment

          rayon  year  employment
0    Taraz city  2014    202.6127
1        Baizak  2014     54.2000
2       Zhambyl  2014     30.9000
3        Zhualy  2014     17.8000
4        Korday  2014     55.5000
..          ...   ...         ...
116       Merke  2024     42.3000
117    Moyynkum  2024     14.7000
118      Sarysu  2024     18.1000
119       Talas  2024     20.0000
120         Shu  2024     47.9000

[121 rows x 3 columns]

## Other controls

In [534]:
taraz_city = pd.read_excel(Path("../Data/Controls/Zhambyl_All.xls"), sheet_name="г.Тараз", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
taraz_city.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
taraz_city = taraz_city.loc[[89, 112, 158]].reset_index(drop=True)
taraz_city['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    taraz_city[i] = taraz_city[i].astype(str)
    taraz_city[i] = taraz_city[i].str.replace(',', '.')
    taraz_city[i] = taraz_city[i].str.replace(')', '')
    taraz_city[i] = taraz_city[i].str.replace(' ', '')
    taraz_city[i] = taraz_city[i].str.replace('\xa0', '')
    taraz_city[i] = taraz_city[i].str.replace('*', '')
    taraz_city[i] = taraz_city[i].astype(float)
taraz_city = pd.melt(taraz_city, id_vars=['Indicator'], var_name='year', value_name='value')
taraz_city = taraz_city.pivot(index='year', columns='Indicator', values='value').reset_index()
taraz_city.insert(0, 'rayon', 'Taraz city')
taraz_city.columns.name = None
taraz_city

         rayon  year   agriculture  production     retail
0   Taraz city  2014   8951.800000   184693.10  140338.60
1   Taraz city  2015   7508.200000   185766.60  138177.10
2   Taraz city  2016   8506.100000   207938.90  182751.00
3   Taraz city  2017   7954.300000   230430.70  205427.90
4   Taraz city  2018   7901.800000   240144.40  221984.00
5   Taraz city  2019  10457.500000   280803.00  238454.90
6   Taraz city  2020  11686.000000   288837.90  246758.10
7   Taraz city  2021  13184.506109   372781.70  272086.40
8   Taraz city  2022  15184.949065   522467.70  306654.90
9   Taraz city  2023  13346.791890   463208.10  332073.50
10  Taraz city  2024  13653.610000   491668.81  389815.51

In [535]:
Baizak = pd.read_excel(Path("../Data/Controls/Zhambyl_All.xls"), sheet_name="Байзакский район", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Baizak.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Baizak = Baizak.loc[[71, 90, 136]].reset_index(drop=True)
Baizak['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Baizak[i] = Baizak[i].astype(str)
    Baizak[i] = Baizak[i].str.replace(',', '.')
    Baizak[i] = Baizak[i].str.replace(')', '')
    Baizak[i] = Baizak[i].str.replace(' ', '')
    Baizak[i] = Baizak[i].str.replace('\xa0', '')
    Baizak[i] = Baizak[i].str.replace('*', '')
    Baizak[i] = Baizak[i].astype(float)
Baizak = pd.melt(Baizak, id_vars=['Indicator'], var_name='year', value_name='value')
Baizak = Baizak.pivot(index='year', columns='Indicator', values='value').reset_index()
Baizak.insert(0, 'rayon', 'Baizak')
Baizak.columns.name = None
Baizak

     rayon  year   agriculture  production    retail
0   Baizak  2014  28111.400000     2382.70   1655.70
1   Baizak  2015  26117.600000     2356.50   2417.90
2   Baizak  2016  29208.900000      948.30   4207.20
3   Baizak  2017  30218.800000     2805.90   4531.90
4   Baizak  2018  31264.100000     3906.50  10915.80
5   Baizak  2019  39966.900000     4871.50  12123.00
6   Baizak  2020  46251.200000     6408.80  13347.70
7   Baizak  2021  54348.600000     6815.40  15834.30
8   Baizak  2022  64789.882102     6581.90  21367.50
9   Baizak  2023  64159.688028     8373.30  22001.10
10  Baizak  2024  69879.010000     9422.31  24138.31

In [536]:
Zhambyl = pd.read_excel(Path("../Data/Controls/Zhambyl_All.xls"), sheet_name="Жамбылский район", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Zhambyl.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Zhambyl = Zhambyl.loc[[71, 90, 136]].reset_index(drop=True)
Zhambyl['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Zhambyl[i] = Zhambyl[i].astype(str)
    Zhambyl[i] = Zhambyl[i].str.replace(',', '.')
    Zhambyl[i] = Zhambyl[i].str.replace(')', '')
    Zhambyl[i] = Zhambyl[i].str.replace(' ', '')
    Zhambyl[i] = Zhambyl[i].str.replace('\xa0', '')
    Zhambyl[i] = Zhambyl[i].str.replace('*', '')
    Zhambyl[i] = Zhambyl[i].astype(float)
Zhambyl = pd.melt(Zhambyl, id_vars=['Indicator'], var_name='year', value_name='value')
Zhambyl = Zhambyl.pivot(index='year', columns='Indicator', values='value').reset_index()
Zhambyl.insert(0, 'rayon', 'Zhambyl')
Zhambyl.columns.name = None
Zhambyl

      rayon  year   agriculture  production    retail
0   Zhambyl  2014  24761.100000    10132.50   2187.70
1   Zhambyl  2015  24534.900000     5725.20   2702.30
2   Zhambyl  2016  25116.200000     6379.40   2884.60
3   Zhambyl  2017  26945.600000     8708.60   3131.50
4   Zhambyl  2018  29799.600000    19941.00   7430.60
5   Zhambyl  2019  38192.700000    16303.10   6706.60
6   Zhambyl  2020  46930.700000    21961.70   6817.20
7   Zhambyl  2021  59737.800000    18972.30   8797.70
8   Zhambyl  2022  70502.373170    28743.60  13459.80
9   Zhambyl  2023  65351.928225    37932.40  17776.70
10  Zhambyl  2024  67744.510000    50227.81  19950.31

In [537]:
Zhualy = pd.read_excel(Path("../Data/Controls/Zhambyl_All.xls"), sheet_name="Жуалынский район", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Zhualy.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Zhualy = Zhualy.loc[[71, 90, 136]].reset_index(drop=True)
Zhualy['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Zhualy[i] = Zhualy[i].astype(str)
    Zhualy[i] = Zhualy[i].str.replace(',', '.')
    Zhualy[i] = Zhualy[i].str.replace(')', '')
    Zhualy[i] = Zhualy[i].str.replace(' ', '')
    Zhualy[i] = Zhualy[i].str.replace('\xa0', '')
    Zhualy[i] = Zhualy[i].str.replace('*', '')
    Zhualy[i] = Zhualy[i].astype(float)
Zhualy = pd.melt(Zhualy, id_vars=['Indicator'], var_name='year', value_name='value')
Zhualy = Zhualy.pivot(index='year', columns='Indicator', values='value').reset_index()
Zhualy.insert(0, 'rayon', 'Zhualy')
Zhualy.columns.name = None
Zhualy

     rayon  year   agriculture  production   retail
0   Zhualy  2014  20129.300000     2276.20  2810.00
1   Zhualy  2015  21141.000000     4070.10  1026.10
2   Zhualy  2016  21333.300000     5253.40  1315.30
3   Zhualy  2017  23189.000000     6566.80  2498.10
4   Zhualy  2018  25463.400000     8361.90  2463.30
5   Zhualy  2019  30273.200000    10898.80  3330.50
6   Zhualy  2020  35121.100000    11818.70  2889.50
7   Zhualy  2021  42701.500000    13816.00  3577.60
8   Zhualy  2022  53566.132484    14770.80  4188.50
9   Zhualy  2023  49294.530751    17301.30  2738.30
10  Zhualy  2024  46260.710000    16722.01  4834.61

In [538]:
Korday = pd.read_excel(Path("../Data/Controls/Zhambyl_All.xls"), sheet_name="Кордайский район", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Korday.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Korday = Korday.loc[[71, 91, 137]].reset_index(drop=True)
Korday['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Korday[i] = Korday[i].astype(str)
    Korday[i] = Korday[i].str.replace(',', '.')
    Korday[i] = Korday[i].str.replace(')', '')
    Korday[i] = Korday[i].str.replace(' ', '')
    Korday[i] = Korday[i].str.replace('\xa0', '')
    Korday[i] = Korday[i].str.replace('*', '')
    Korday[i] = Korday[i].astype(float)
Korday = pd.melt(Korday, id_vars=['Indicator'], var_name='year', value_name='value')
Korday = Korday.pivot(index='year', columns='Indicator', values='value').reset_index()
Korday.insert(0, 'rayon', 'Korday')
Korday.columns.name = None
Korday

     rayon  year   agriculture  production    retail
0   Korday  2014  36435.200000     7717.10   9028.00
1   Korday  2015  37687.600000     9414.80  16579.10
2   Korday  2016  44647.600000    13078.90  21180.90
3   Korday  2017  44932.600000    16374.10  23209.70
4   Korday  2018  47176.300000    14829.50  23220.80
5   Korday  2019  56713.800000    15559.10  36360.90
6   Korday  2020  68465.700000    18319.60  26395.80
7   Korday  2021  83562.500000    25781.20  28699.40
8   Korday  2022  95269.103968    21396.30  34334.60
9   Korday  2023  80382.288681    19161.00  42947.40
10  Korday  2024  83587.710000    21658.11  41936.11

In [539]:
Ryskulov = pd.read_excel(Path("../Data/Controls/Zhambyl_All.xls"), sheet_name="район Т.Рыскулова", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Ryskulov.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Ryskulov = Ryskulov.loc[[71, 90, 136]].reset_index(drop=True)
Ryskulov['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Ryskulov[i] = Ryskulov[i].astype(str)
    Ryskulov[i] = Ryskulov[i].str.replace(',', '.')
    Ryskulov[i] = Ryskulov[i].str.replace(')', '')
    Ryskulov[i] = Ryskulov[i].str.replace(' ', '')
    Ryskulov[i] = Ryskulov[i].str.replace('\xa0', '')
    Ryskulov[i] = Ryskulov[i].str.replace('*', '')
    Ryskulov[i] = Ryskulov[i].astype(float)
Ryskulov = pd.melt(Ryskulov, id_vars=['Indicator'], var_name='year', value_name='value')
Ryskulov = Ryskulov.pivot(index='year', columns='Indicator', values='value').reset_index()
Ryskulov.insert(0, 'rayon', 'Ryskulov')
Ryskulov.columns.name = None
Ryskulov

       rayon  year   agriculture  production   retail
0   Ryskulov  2014  18959.900000     4230.20  3268.30
1   Ryskulov  2015  21029.300000     6456.70  3071.60
2   Ryskulov  2016  23047.000000     7898.20  3757.00
3   Ryskulov  2017  25351.500000     8106.80  3889.60
4   Ryskulov  2018  27224.400000     7531.70  3254.30
5   Ryskulov  2019  32366.500000    11518.90  2898.80
6   Ryskulov  2020  41110.400000    17521.70  3828.00
7   Ryskulov  2021  45016.000000    14734.00  4697.90
8   Ryskulov  2022  58745.042037    17547.60  6238.10
9   Ryskulov  2023  49119.194801    12274.30  6548.50
10  Ryskulov  2024  53261.810000    15323.51  7359.61

In [540]:
Merke = pd.read_excel(Path("../Data/Controls/Zhambyl_All.xls"), sheet_name="Меркенский район", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Merke.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Merke = Merke.loc[[71, 91, 137]].reset_index(drop=True)
Merke['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Merke[i] = Merke[i].astype(str)
    Merke[i] = Merke[i].str.replace(',', '.')
    Merke[i] = Merke[i].str.replace(')', '')
    Merke[i] = Merke[i].str.replace(' ', '')
    Merke[i] = Merke[i].str.replace('\xa0', '')
    Merke[i] = Merke[i].str.replace('*', '')
    Merke[i] = Merke[i].astype(float)
Merke = pd.melt(Merke, id_vars=['Indicator'], var_name='year', value_name='value')
Merke = Merke.pivot(index='year', columns='Indicator', values='value').reset_index()
Merke.insert(0, 'rayon', 'Merke')
Merke.columns.name = None
Merke

    rayon  year   agriculture  production    retail
0   Merke  2014  15998.100000    13029.70   6372.10
1   Merke  2015  17618.800000    15843.10   5634.80
2   Merke  2016  21234.400000    33279.60   5228.20
3   Merke  2017  23990.700000    17347.70   5598.00
4   Merke  2018  24893.300000    14511.10   7797.40
5   Merke  2019  29122.100000     5865.30   7933.20
6   Merke  2020  37382.200000     6461.30  10938.90
7   Merke  2021  45878.000000     6894.80  11916.30
8   Merke  2022  53719.249136    18871.20  16840.00
9   Merke  2023  44740.891926    20140.10  17162.60
10  Merke  2024  41052.610000    17782.11  19338.11

In [541]:
Moyynkum = pd.read_excel(Path("../Data/Controls/Zhambyl_All.xls"), sheet_name="Мойынкумский район", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Moyynkum.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Moyynkum = Moyynkum.loc[[71, 89, 135]].reset_index(drop=True)
Moyynkum['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Moyynkum[i] = Moyynkum[i].astype(str)
    Moyynkum[i] = Moyynkum[i].str.replace(',', '.')
    Moyynkum[i] = Moyynkum[i].str.replace(')', '')
    Moyynkum[i] = Moyynkum[i].str.replace(' ', '')
    Moyynkum[i] = Moyynkum[i].str.replace('\xa0', '')
    Moyynkum[i] = Moyynkum[i].str.replace('*', '')
    Moyynkum[i] = Moyynkum[i].astype(float)
Moyynkum = pd.melt(Moyynkum, id_vars=['Indicator'], var_name='year', value_name='value')
Moyynkum = Moyynkum.pivot(index='year', columns='Indicator', values='value').reset_index()
Moyynkum.insert(0, 'rayon', 'Moyynkum')
Moyynkum.columns.name = None
Moyynkum

       rayon  year  agriculture  production   retail
0   Moyynkum  2014  4385.800000    28326.40   597.40
1   Moyynkum  2015  4174.900000    31002.10  1005.60
2   Moyynkum  2016  4136.900000    33757.30  1389.00
3   Moyynkum  2017  4398.400000    45101.70   876.40
4   Moyynkum  2018  4524.800000    66277.00  2375.00
5   Moyynkum  2019  5432.700000    71721.60  1465.00
6   Moyynkum  2020  6671.800000    84169.00  2172.20
7   Moyynkum  2021  6640.900000    88416.90  2456.70
8   Moyynkum  2022  8389.357459    98746.90  3166.40
9   Moyynkum  2023  6330.253559    89107.80  2884.00
10  Moyynkum  2024  5789.710000   117041.21  4420.41

In [542]:
Sarysu = pd.read_excel(Path("../Data/Controls/Zhambyl_All.xls"), sheet_name="Сарысуский район", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Sarysu.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Sarysu = Sarysu.loc[[85, 104, 150]].reset_index(drop=True)
Sarysu['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Sarysu[i] = Sarysu[i].astype(str)
    Sarysu[i] = Sarysu[i].str.replace(',', '.')
    Sarysu[i] = Sarysu[i].str.replace(')', '')
    Sarysu[i] = Sarysu[i].str.replace(' ', '')
    Sarysu[i] = Sarysu[i].str.replace('\xa0', '')
    Sarysu[i] = Sarysu[i].str.replace('*', '')
    Sarysu[i] = Sarysu[i].astype(float)
Sarysu = pd.melt(Sarysu, id_vars=['Indicator'], var_name='year', value_name='value')
Sarysu = Sarysu.pivot(index='year', columns='Indicator', values='value').reset_index()
Sarysu.insert(0, 'rayon', 'Sarysu')
Sarysu.columns.name = None
Sarysu

     rayon  year   agriculture  production   retail
0   Sarysu  2014   8374.300000     1295.80  2431.60
1   Sarysu  2015   9264.000000     3514.00  3998.70
2   Sarysu  2016   9878.600000    15621.40  2441.10
3   Sarysu  2017  10165.200000    19115.20  2753.30
4   Sarysu  2018  11177.000000    20564.70  1924.80
5   Sarysu  2019  12998.000000    23317.60  2023.40
6   Sarysu  2020  16594.200000    25782.30  2804.00
7   Sarysu  2021  23647.300000    41913.00  3032.00
8   Sarysu  2022  26335.540076    76456.80  4127.90
9   Sarysu  2023  19073.687136   103434.90  4522.00
10  Sarysu  2024  18319.610000    88680.11  4410.81

In [543]:
Talas = pd.read_excel(Path("../Data/Controls/Zhambyl_All.xls"), sheet_name="Таласский район", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Talas.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Talas = Talas.loc[[73, 93, 139]].reset_index(drop=True)
Talas['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Talas[i] = Talas[i].astype(str)
    Talas[i] = Talas[i].str.replace(',', '.')
    Talas[i] = Talas[i].str.replace(')', '')
    Talas[i] = Talas[i].str.replace(' ', '')
    Talas[i] = Talas[i].str.replace('\xa0', '')
    Talas[i] = Talas[i].str.replace('*', '')
    Talas[i] = Talas[i].astype(float)
Talas = pd.melt(Talas, id_vars=['Indicator'], var_name='year', value_name='value')
Talas = Talas.pivot(index='year', columns='Indicator', values='value').reset_index()
Talas.insert(0, 'rayon', 'Talas')
Talas.columns.name = None
Talas

    rayon  year   agriculture  production   retail
0   Talas  2014   9757.000000     6546.70  1826.20
1   Talas  2015  10246.900000     7079.50  1996.10
2   Talas  2016  10281.200000    10454.80  1817.10
3   Talas  2017  10555.200000    14286.80  1844.10
4   Talas  2018  10989.000000    17069.30  2096.20
5   Talas  2019  12896.600000    22594.90  2193.50
6   Talas  2020  15858.600000    22376.60  2438.30
7   Talas  2021  18027.800000    25704.20  2753.80
8   Talas  2022  21601.341253    45810.20  4475.50
9   Talas  2023  18288.681387    47910.10  5161.20
10  Talas  2024  18743.210000    38696.01  5042.31

In [544]:
Shu = pd.read_excel(Path("../Data/Controls/Zhambyl_All.xls"), sheet_name="Шуский район", header=2, usecols='A, Y:AI', nrows=180, na_values=['x', 'х', '-', '', ' ', '...'])
Shu.columns = ['Indicator', 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Shu = Shu.loc[[71, 91, 137]].reset_index(drop=True)
Shu['Indicator'] = ['production', 'agriculture', 'retail']
for i in [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    Shu[i] = Shu[i].astype(str)
    Shu[i] = Shu[i].str.replace(',', '.')
    Shu[i] = Shu[i].str.replace(')', '')
    Shu[i] = Shu[i].str.replace(' ', '')
    Shu[i] = Shu[i].str.replace('\xa0', '')
    Shu[i] = Shu[i].str.replace('*', '')
    Shu[i] = Shu[i].astype(float)
Shu = pd.melt(Shu, id_vars=['Indicator'], var_name='year', value_name='value')
Shu = Shu.pivot(index='year', columns='Indicator', values='value').reset_index()
Shu.insert(0, 'rayon', 'Shu')
Shu.columns.name = None
Shu

   rayon  year    agriculture  production    retail
0    Shu  2014   28923.500000    18714.10  12251.10
1    Shu  2015   39403.300000    12721.60  13261.80
2    Shu  2016   39675.800000     6727.90  16633.80
3    Shu  2017   43615.600000     5184.80  18139.50
4    Shu  2018   47810.200000     8009.30  19180.80
5    Shu  2019   57328.000000    13517.50  10163.50
6    Shu  2020   65298.900000    14585.80  13686.20
7    Shu  2021   85389.800000    23281.40  16829.50
8    Shu  2022  110924.657685    21239.80  19966.70
9    Shu  2023  111389.080532    28460.80  24714.00
10   Shu  2024   70272.010000    36978.91  26514.31

In [545]:
zhambyl_controls = pd.concat([taraz_city, Baizak, Zhambyl, Zhualy, Korday, Ryskulov, Merke, Moyynkum, Sarysu, Talas, Shu], ignore_index=True)
zhambyl_controls

          rayon  year    agriculture  production     retail
0    Taraz city  2014    8951.800000   184693.10  140338.60
1    Taraz city  2015    7508.200000   185766.60  138177.10
2    Taraz city  2016    8506.100000   207938.90  182751.00
3    Taraz city  2017    7954.300000   230430.70  205427.90
4    Taraz city  2018    7901.800000   240144.40  221984.00
..          ...   ...            ...         ...        ...
116         Shu  2020   65298.900000    14585.80   13686.20
117         Shu  2021   85389.800000    23281.40   16829.50
118         Shu  2022  110924.657685    21239.80   19966.70
119         Shu  2023  111389.080532    28460.80   24714.00
120         Shu  2024   70272.010000    36978.91   26514.31

[121 rows x 5 columns]

## PPI

In [546]:
zhambyl_ppi = pd.read_excel(
    Path("../Data/PPI/Zhambyl.xls"),
    header=2,
    usecols='Y:AI',
    nrows=78,
    na_values=['x', 'х', '-', '', ' ', '...']
)
zhambyl_ppi.columns = [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
rayons = list(zhambyl_inv['rayon'].unique())
zhambyl_ppi
dfs = []

for rayon in rayons:
    df_temp = pd.DataFrame({
        'rayon': [rayon] * len(range(2014, 2025)),
        'year': list(range(2014, 2025)),
        'ppi': zhambyl_ppi.iloc[-1].values
    })
    dfs.append(df_temp)

zhambyl_ppi = pd.concat(dfs, ignore_index=True)
zhambyl_ppi['ppi'] = zhambyl_ppi['ppi'].astype(str).str.replace(',', '.')
zhambyl_ppi['ppi'] = zhambyl_ppi['ppi'].astype(str).str.replace(')', '')
zhambyl_ppi['ppi'] = zhambyl_ppi['ppi'].astype(str).str.replace(' ', '')
zhambyl_ppi['ppi'] = zhambyl_ppi['ppi'].astype(str).str.replace('\xa0', '')
zhambyl_ppi['ppi'] = zhambyl_ppi['ppi'].astype(str).str.replace('*', '')
zhambyl_ppi['ppi'] = zhambyl_ppi['ppi'].astype(float)

zhambyl_ppi

          rayon  year    ppi
0    Taraz city  2014  106.9
1    Taraz city  2015  105.6
2    Taraz city  2016  110.4
3    Taraz city  2017  100.0
4    Taraz city  2018  103.4
..          ...   ...    ...
116         Shu  2020  109.5
117         Shu  2021  111.1
118         Shu  2022  117.9
119         Shu  2023   97.0
120         Shu  2024  114.4

[121 rows x 3 columns]

## Combine

In [547]:
dfs_zhambyl = [zhambyl_inv, zhambyl_employment, zhambyl_controls, zhambyl_ppi]
zhambyl_merged = reduce(lambda left, right: pd.merge(left, right, on=['rayon', 'year'], how='outer'), dfs_zhambyl)
zhambyl_merged['oblast'] = zhambyl_merged['oblast'].fillna('Zhambyl')
zhambyl_merged

,rayon,l_all_inv,f_all_inv,oblast,year,f_nonextr_inv,l_nonextr_inv,employment,agriculture,production,retail,ppi
0,Baizak,<NA>,<NA>,Zhambyl,2014,NaN,NaN,54.2,28111.400000,2382.70,1655.70,106.9
1,Baizak,10963490,379001.0,Zhambyl,2015,NaN,NaN,47.7,26117.600000,2356.50,2417.90,105.6
2,Baizak,8494653,141478.0,Zhambyl,2016,141478.0,4187992.0,46.5,29208.900000,948.30,4207.20,110.4
3,Baizak,9347858,85622.0,Zhambyl,2017,85622.0,1469777.0,51.6,30218.800000,2805.90,4531.90,100.0
4,Baizak,14034365,63505.0,Zhambyl,2018,27082.0,3452544.0,51.9,31264.100000,3906.50,10915.80,103.4
...,...,...,...,...,...,...,...,...,...,...,...,...
116,Zhualy,7708860,16271.0,Zhambyl,2020,16271.0,7692589.0,25.7,35121.100000,11818.70,2889.50,109.5
117,Zhualy,7978661,88255.0,Zhambyl,2021,88255.0,2732845.0,24.9,42701.500000,13816.00,3577.60,111.1
118,Zhualy,8641522,753967.0,Zhambyl,2022,753967.0,2601442.0,25.8,53566.132484,14770.80,4188.50,117.9
119,Zhualy,10489137,253820.0,Zhambyl,2023,253820.0,6759616.0,24.6,49294.530751,17301.30,2738.30,97.0
120,Zhualy,13727461,16809.0,Zhambyl,2024,16809.0,6083575.0,24.5,46260.710000,16722.01,4834.61,114.4

# Combine all oblast

In [548]:
all_merged = pd.concat([east_merged, akmola_merged, aktobe_merged, alm_city_merged, almaty_merged, astana_city_merged, atyrau_merged,
                       karagandy_merged, kostanay_merged, kyzylorda_merged, mangystau_merged, north_merged, pavlodar_merged,
                       shymkent_city_merged, turkestan_merged, west_merged, zhambyl_merged, almaty_merged], ignore_index=True)
all_merged

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year,employment,agriculture,production,retail,ppi
0,Abay,2868180,3092.0,3092.0,981955.0,East-Kazakhstan,2018,6.8,22795.4,1593.9,1869.4,100.7
1,Abay,2514048,405350.0,67923.0,529073.0,East-Kazakhstan,2019,6.8,25865.6,2352.1,2470.9,103.4
2,Abay,7040473,5593.0,5593.0,784053.0,East-Kazakhstan,2020,6.7,29614.9,3201.9,2720.2,121.1
3,Abay,3671620,1643.0,1643.0,1125547.0,East-Kazakhstan,2021,6.8,34162.9,5753.1,3228.1,116.6
4,Abay,6258213,0.0,0.0,1723622.0,East-Kazakhstan,2022,7.0,40779.1,7437.8,4868.6,101.9
...,...,...,...,...,...,...,...,...,...,...,...,...
2536,Zhambyl,20079790.0,4594545.0,1294715,9991101.0,Almaty,2020,81.3,63252.2,20051.6,15585.7,105.4
2537,Zhambyl,21363798.0,5167718.0,4683327,12520896,Almaty,2021,81.1,65931.7,22136.3,16729.2,107.5
2538,Zhambyl,31782899.0,5970398.0,5970398.0,10750287.0,Almaty,2022,78.1,80803.2,23505.1,16163.1,115.0
2539,Zhambyl,30223976.0,15128599.0,15128599.0,15104859.0,Almaty,2023,78.4,80627.025943,21456.4,23717.5,NaN
2540,Zhambyl,53175462.0,59797102.0,59797102.0,23714834.0,Almaty,2024,NaN,NaN,NaN,NaN,NaN

In [549]:
 #all_merged.to_excel("/Users/darhanmashirapov/Downloads/all_merged.xlsx", index=False)